const contributorsDb = [
  {
    id: 1,
    name: 'Nguyễn Tấn Đạt',
    nickname: '',
    relatedOrganization: '',
    totalDonation: '******',
    moneySource: 'Bank',
    description: '',
    place: '',
    time: '',
    avatar: '',
  },
  {
    id: 2,
    name: 'Nguyễn Cao Thục Đoan',
    nickname: 'Cheryx',
    relatedOrganization: '',
    totalDonation: '******',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '',
    avatar: './images/contributors/cheryx',
  },
  {
    id: 3,
    name: 'Huỳnh Thị Thanh Ngân',
    nickname: 'Hanna',
    relatedOrganization: '',
    totalDonation: '******',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '',
    avatar: './images/contributors/hanna',
  },
  {
    id: 4,
    name: 'Tô Thị Thảo My',
    nickname: 'ToMy',
    relatedOrganization: '',
    totalDonation: '******',
    moneySource: 'Bank',
    description: '',
    place: '',
    time: '',
    avatar: './images/contributors/',
  },
  {
    id: 5,
    name: 'Phùng Thị Nhật Thương',
    nickname: 'Tessa',
    relatedOrganization: '',
    totalDonation: '******',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '',
    avatar: './images/contributors/lou',
  },
  {
    id: 6,
    name: 'Huỳnh Minh Cường',
    nickname: 'Bevis',
    relatedOrganization: '',
    totalDonation: '******',
    moneySource: 'Bank',
    description: '',
    place: '',
    time: '',
    avatar: './images/contributors/bevis',
  },
  {
    id: 7,
    name: 'Võ Yến Nhi',
    nickname: 'Millie',
    relatedOrganization: '',
    totalDonation: '******',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '',
    avatar: '',
  },
  {
    id: 8,
    name: 'Phùng Văn Ý',
    nickname: 'Zany',
    relatedOrganization: '',
    totalDonation: '******',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '',
    avatar: '',
  },
  {
    id: 9,
    name: 'Dương Văn Thảo',
    nickname: 'Roy',
    relatedOrganization: '',
    totalDonation: '******',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '',
    avatar: '',
  },
  {
    id: 10,
    name: 'Đặng Quang Dinh',
    nickname: 'Kevin De Bruyne',
    relatedOrganization: '',
    totalDonation: '******',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '',
    avatar: '',
  },
  {
    id: 11,
    name: 'Nguyễn Chí Bảo',
    nickname: 'Shino',
    relatedOrganization: '',
    totalDonation: '******',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '',
    avatar: '',
  },
  {
    id: 12,
    name: 'Trần Thị Ngọc Huyền',
    nickname: 'Selena',
    relatedOrganization: '',
    totalDonation: '******',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '',
    avatar: '',
  },
  {
    id: 13,
    name: 'Nguyễn Mạnh Hùng',
    nickname: 'Poppy',
    relatedOrganization: '',
    totalDonation: '******',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '',
    avatar: '',
  },
  {
    id: 14,
    name: 'Phan Thị Kim Hoàng',
    nickname: '',
    relatedOrganization: '',
    totalDonation: '******',
    moneySource: 'MoMo',
    description: '???',
    place: '',
    time: '',
    avatar: '',
  },
  {
    id: 15,
    name: 'Nguyễn Thị Hồng Ngọc',
    nickname: 'Ruby',
    relatedOrganization: '',
    totalDonation: '******',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '',
    avatar: '',
  },
  {
    id: 16,
    name: 'Lê Thị Anh Thư',
    nickname: 'Zina',
    relatedOrganization: '',
    totalDonation: '******',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '',
    avatar: '',
  },
  {
    id: 17,
    name: 'Nguyễn Lê Minh Phương',
    nickname: 'Philis',
    relatedOrganization: '',
    totalDonation: '******',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '',
    avatar: '',
  },
  {
    id: 18,
    name: ' Nguyễn Thanh Hải',
    nickname: 'HaiB',
    relatedOrganization: '',
    totalDonation: '******',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '',
    avatar: '',
  },
  {
    id: 19,
    name: 'Nguyễn Thị Diễm Ái',
    nickname: '',
    relatedOrganization: '',
    totalDonation: '******',
    moneySource: 'Bank',
    description: '',
    place: '',
    time: '',
    avatar: '',
  },
  {
    id: 20,
    name: 'Nguyễn Thị Kim Thoa',
    nickname: 'Kita',
    relatedOrganization: '',
    totalDonation: '******',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '',
    avatar: '',
  },
  {
    id: 21,
    name: 'Nguyễn Đoàn Phương Anh',
    nickname: '',
    relatedOrganization: '',
    totalDonation: '******',
    moneySource: 'Bank',
    description: '',
    place: '',
    time: '',
    avatar: '',
  },
  {
    id: 22,
    name: 'Lê Ngọc Quý',
    nickname: 'Wilson',
    relatedOrganization: '',
    totalDonation: '******',
    moneySource: 'Cash 💵',
    description: '',
    place: '',
    time: '',
    avatar: '',
  },
  {
    id: 23,
    name: 'Nguyễn Hữu Nghĩa',
    nickname: 'Andy',
    relatedOrganization: '',
    totalDonation: '******',
    moneySource: 'Cash 💵',
    description: '',
    place: '',
    time: '',
    avatar: '',
  },
  {
    id: 24,
    name: 'Ngô Huỳnh Công Trứ',
    nickname: 'Lou',
    relatedOrganization: '',
    totalDonation: '******',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '',
    avatar: '',
  },
  {
    id: 25,
    name: 'Lê Nguyễn Hoàng Huy',
    nickname: 'Victor',
    relatedOrganization: '',
    totalDonation: '******',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '',
    avatar: '',
  },
  {
    id: 26,
    name: 'Nguyễn Anh Thư',
    nickname: 'Daisy',
    relatedOrganization: '',
    totalDonation: '******',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '',
    avatar: '',
  },
  {
    id: 27,
    name: 'Ngô Thị Thúy Vi',
    nickname: 'Sarah',
    relatedOrganization: '',
    totalDonation: '******',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '',
    avatar: '',
  },
  {
    id: 28,
    name: 'Hồ Quốc Cường',
    nickname: 'Tony',
    relatedOrganization: '',
    totalDonation: '******',
    moneySource: 'Bank',
    description: '',
    place: '',
    time: '',
    avatar: '',
  },
  {
    id: 29,
    name: 'Nguyễn Bá Thông',
    nickname: 'Max',
    relatedOrganization: '',
    totalDonation: '******',
    moneySource: 'Bank',
    description: '',
    place: '',
    time: '',
    avatar: '',
  },
  {
    id: 30,
    name: 'Nguyễn Trọng Nghĩa',
    nickname: 'June',
    relatedOrganization: '',
    totalDonation: '******',
    moneySource: 'Bank',
    description: '',
    place: '',
    time: '',
    avatar: '',
  },
  {
    id: 31,
    name: 'Đinh Hiền Sĩ',
    nickname: 'Hiroshi',
    relatedOrganization: '',
    totalDonation: '******',
    moneySource: 'Bank',
    description: '',
    place: '',
    time: '',
    avatar: '',
  },
  {
    id: 32,
    name: 'Nguyễn Hoàng Thủy Trúc',
    nickname: 'Tina',
    relatedOrganization: '',
    totalDonation: '******',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '',
    avatar: '',
  },
  {
    id: 33,
    name: 'Lâm Huỳnh Như',
    nickname: 'Janina',
    relatedOrganization: '',
    totalDonation: '******',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '',
    avatar: '',
  },

]
export default contributorsDb
