const contributorsDb = [
  {
    id: 1,
    name: 'Nguyễn Tấn Đạt',
    nickname: '',
    relatedOrganization: 'former Open University',
    totalDonation: '******',
    hiddenDonation: '200000',
    moneySource: 'Bank',
    description: '',
    place: '',
    time: '2025/04/10 17:08',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 2,
    name: 'Nguyễn Cao Thục Đoan',
    nickname: 'Cheryx',
    relatedOrganization: 'Glodival',
    totalDonation: '******',
    hiddenDonation: '100000',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '2025/04/09 14:25',
    avatar: './images/contributors/cheryx',
    status: 'Đã ghi nhận',
  },
  {
    id: 3,
    name: 'Huỳnh Thị Thanh Ngân',
    nickname: 'Hanna',
    relatedOrganization: 'Glodival',
    totalDonation: '******',
    hiddenDonation: '50000',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '2025/04/09 14:47',
    avatar: './images/contributors/hanna',
    status: 'Đã ghi nhận',
  },
  {
    id: 4,
    name: 'Tô Thị Thảo My',
    nickname: 'ToMy',
    relatedOrganization: 'Glodival',
    totalDonation: '******',
    hiddenDonation: '100000',
    moneySource: 'Bank',
    description: '',
    place: '',
    time: '2025/04/09 22:03',
    avatar: './images/contributors/tomy',
    status: 'Đã ghi nhận',
  },
  {
    id: 5,
    name: 'Phùng Thị Nhật Thương',
    nickname: 'Tessa',
    relatedOrganization: 'Glodival',
    totalDonation: '******',
    hiddenDonation: '50000',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '2025/04/09 15:22',
    avatar: './images/contributors/lou',
    status: 'Đã ghi nhận',
  },
  {
    id: 6,
    name: 'Huỳnh Minh Cường',
    nickname: 'Bevis',
    relatedOrganization: 'Glodival',
    totalDonation: '******',
    hiddenDonation: '50000',
    moneySource: 'Bank',
    description: '',
    place: '',
    time: '2025/04/09 15:53',
    avatar: './images/contributors/bevis',
    status: 'Đã ghi nhận',
  },
  {
    id: 7,
    name: 'Võ Yến Nhi',
    nickname: 'Millie',
    relatedOrganization: 'Glodival',
    totalDonation: '******',
    hiddenDonation: '5000',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '2025/04/09 14:10',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 8,
    name: 'Phùng Văn Ý',
    relatedOrganization: 'Glodival',
    totalDonation: '******',
    hiddenDonation: '5000',
    moneySource: 'MoMo',
    description: 'Glodival',
    place: '',
    time: '2025/04/09 14:10',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 9,
    name: 'Dương Văn Thảo',
    nickname: 'Roy',
    relatedOrganization: 'Glodival',
    totalDonation: '******',
    hiddenDonation: '5000',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '2025/04/09 14:11',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 10,
    name: 'Đặng Quang Dinh',
    nickname: 'Kevin De Bruyne',
    relatedOrganization: 'Glodival',
    totalDonation: '******',
    hiddenDonation: '5000',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '2025/04/09 14:12',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 11,
    name: 'Nguyễn Chí Bảo',
    nickname: 'Shino',
    relatedOrganization: 'Glodival',
    totalDonation: '******',
    hiddenDonation: '3000',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '2025/04/09 14:22',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 12,
    name: 'Trần Thị Ngọc Huyền',
    nickname: 'Selena',
    relatedOrganization: 'Glodival',
    totalDonation: '******',
    hiddenDonation: '5000',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '2025/04/09 14:24',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 13,
    name: 'Nguyễn Mạnh Hùng',
    nickname: 'Poppy',
    relatedOrganization: 'Glodival',
    totalDonation: '******',
    hiddenDonation: '8000',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '2025/04/09 14:55',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 14,
    name: 'Nhóm bạn Tom & Jerry',
    nickname: '',
    relatedOrganization: 'former Open University',
    totalDonation: '******',
    hiddenDonation: '5000',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '2025/04/09 22:15',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 15,
    name: 'Nguyễn Thị Hồng Ngọc',
    nickname: 'Ruby',
    relatedOrganization: 'Glodival',
    totalDonation: '******',
    hiddenDonation: '10000',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '2025/04/10 07:14',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 16,
    name: 'Lê Thị Anh Thư',
    nickname: 'Zina',
    relatedOrganization: 'Glodival',
    totalDonation: '******',
    hiddenDonation: '10000',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '2025/04/10 15:18',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 17,
    name: 'Minh Phương & Thanh Hải',
    nickname: 'Philis & HaiB',
    relatedOrganization: 'Glodival',
    totalDonation: '******',
    hiddenDonation: '20000',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '2025/04/10 11:35',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 19,
    name: 'Nguyễn Thị Diễm Ái',
    nickname: '',
    relatedOrganization: 'former TNH high school',
    totalDonation: '******',
    hiddenDonation: '5000',
    moneySource: 'Bank',
    description: '',
    place: '',
    time: '2025/04/10 10:01',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 20,
    name: 'Nguyễn Thị Kim Thoa',
    nickname: 'Kita',
    relatedOrganization: 'former Glodival',
    totalDonation: '******',
    hiddenDonation: '5000',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '2025/04/10 10:27',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 21,
    name: 'Nguyễn Đoàn Phương Anh',
    nickname: '',
    relatedOrganization: 'former Open University',
    totalDonation: '******',
    hiddenDonation: '50000',
    moneySource: 'Bank',
    description: '',
    place: '',
    time: '2025/04/10 10:56',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 22,
    name: 'Lê Ngọc Quý',
    nickname: 'Wilson',
    relatedOrganization: 'Glodival',
    totalDonation: '******',
    hiddenDonation: '45000',
    moneySource: 'Cash',
    description: '',
    place: '',
    time: '2025/04/11 13:30',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 23,
    name: 'Nguyễn Hữu Nghĩa',
    nickname: 'Andy',
    relatedOrganization: 'Glodival',
    totalDonation: '******',
    hiddenDonation: '5000',
    moneySource: 'Cash',
    description: '',
    place: '',
    time: '2025/04/09 14:53',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 24,
    name: 'Ngô Huỳnh Công Trứ',
    nickname: 'Lou',
    relatedOrganization: 'Glodival',
    totalDonation: '******',
    hiddenDonation: '5000',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '2025/04/09 14:39',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 25,
    name: 'Lê Nguyễn Hoàng Huy',
    nickname: 'Victor',
    relatedOrganization: 'Glodival',
    totalDonation: '******',
    hiddenDonation: '5000',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '2025/04/10 08:03',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 26,
    name: 'Nguyễn Anh Thư',
    nickname: 'Daisy',
    relatedOrganization: 'Glodival',
    totalDonation: '******',
    hiddenDonation: '5000',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '2025/04/09 14:12',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 27,
    name: 'Ngô Thị Thúy Vi',
    nickname: 'Sarah',
    relatedOrganization: 'Glodival',
    totalDonation: '******',
    hiddenDonation: '10000',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '2025/04/09 16:15',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 28,
    name: 'Hồ Quốc Cường',
    nickname: 'Tony',
    relatedOrganization: 'Glodival Open University',
    totalDonation: '******',
    hiddenDonation: '5000',
    moneySource: 'Bank',
    description: '',
    place: '',
    time: '2025/04/09 15:28',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 29,
    name: 'Nguyễn Bá Thông',
    nickname: 'Max',
    relatedOrganization: 'Glodival',
    totalDonation: '******',
    hiddenDonation: '10000',
    moneySource: 'Bank',
    description: '',
    place: '',
    time: '2025/04/09 16:22',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 30,
    name: 'Nguyễn Trọng Nghĩa',
    nickname: 'June',
    relatedOrganization: 'former Glodival',
    totalDonation: '******',
    hiddenDonation: '5000',
    moneySource: 'Bank',
    description: '',
    place: '',
    time: '2025/04/09 16:44',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 31,
    name: 'Đinh Hiền Sĩ',
    nickname: 'Hiroshi',
    relatedOrganization: 'former Glodival',
    totalDonation: '******',
    hiddenDonation: '5555',
    moneySource: 'Momo',
    description: '',
    place: '',
    time: '2025/04/09 19:21',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 32,
    name: 'Nguyễn Hoàng Thủy Trúc',
    nickname: 'Tina',
    relatedOrganization: 'Glodival',
    totalDonation: '******',
    hiddenDonation: '5000',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '2025/04/09 20:01',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 33,
    name: 'Lâm Huỳnh Như',
    nickname: 'Janina',
    relatedOrganization: 'Glodival',
    totalDonation: '******',
    hiddenDonation: '5000',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '2025/04/09 22:33',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 34,
    name: 'Trần Lê Gia Linh',
    nickname: 'Gloria',
    relatedOrganization: 'Glodival',
    totalDonation: '******',
    hiddenDonation: '10000',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '2025/04/12 08:42',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 35,
    name: 'Nguyễn Ngọc Vinh',
    nickname: 'Leo',
    relatedOrganization: 'Glodival',
    totalDonation: '******',
    hiddenDonation: '50000',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '2025/04/12 09:00',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 36,
    name: 'Dương Gia Bảo',
    nickname: 'Fubao',
    relatedOrganization: 'Glodival',
    totalDonation: '******',
    hiddenDonation: '10000',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '2025/04/12 09:25',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 37,
    name: 'Trần Kim Hương',
    nickname: 'Jade',
    relatedOrganization: 'Glodival',
    totalDonation: '******',
    hiddenDonation: '10000',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '2025/04/12 10:20',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 38,
    name: 'Võ Thị Mỹ Duyên',
    nickname: 'Flora',
    relatedOrganization: 'former Glodival',
    totalDonation: '******',
    hiddenDonation: '20000',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '2025/04/12 11:07',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 39,
    name: 'Lê Thị Dung',
    nickname: 'Andrean',
    relatedOrganization: 'Glodival',
    totalDonation: '******',
    hiddenDonation: '50000',
    moneySource: 'MoMo',
    description: '',
    place: '',
    time: '2025/04/12 11:36',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 40,
    name: 'Nguyễn Thị Quỳnh Nga',
    nickname: 'Coca',
    relatedOrganization: 'former Open University',
    totalDonation: '******',
    hiddenDonation: '100000',
    moneySource: 'Bank',
    description: '',
    place: '',
    time: '2025/04/12 13:25',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 41,
    name: 'Nguyễn Văn Tâm',
    nickname: 'Guy',
    relatedOrganization: 'Glodival',
    totalDonation: '******',
    hiddenDonation: '15000',
    moneySource: 'Momo',
    description: '',
    place: '',
    time: '2025/04/12 08:47',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 42,
    name: 'Trần Phương Nga',
    nickname: 'Navy',
    relatedOrganization: 'Glodival',
    totalDonation: '******',
    hiddenDonation: '5000',
    moneySource: 'Momo',
    description: '',
    place: '',
    time: '2025/04/12 12:15',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 43,
    name: 'Vòng Quang Chắn',
    nickname: 'Nấm',
    relatedOrganization: 'former Open University',
    totalDonation: '******',
    hiddenDonation: '10000',
    moneySource: 'Momo',
    description: '',
    place: '',
    time: '2025/04/12 20:58',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 44,
    name: 'Đường Lệ Hoa',
    nickname: '',
    relatedOrganization: 'former Open University',
    totalDonation: '******',
    hiddenDonation: '50000',
    moneySource: 'Momo',
    description: '',
    place: '',
    time: '2025/04/12 20:59',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 45,
    name: 'Vy Thu Thủy Tiên',
    nickname: 'Cụt',
    relatedOrganization: 'former Open University',
    totalDonation: '******',
    hiddenDonation: '10000',
    moneySource: 'Momo',
    description: '',
    place: '',
    time: '2025/04/12 21:30',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 46,
    name: 'Võ Thị Ái Nhi',
    nickname: 'Beli',
    relatedOrganization: 'former Open University',
    totalDonation: '******',
    hiddenDonation: '50000',
    moneySource: 'Momo',
    description: '',
    place: '',
    time: '2025/04/12 21:38',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 47,
    name: 'Trần Hoàng Trọng',
    nickname: '',
    relatedOrganization: 'former Open University',
    totalDonation: '******',
    hiddenDonation: '200000',
    moneySource: 'Bank',
    description: '',
    place: '',
    time: '2025/04/12 21:41',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 48,
    name: 'Phạm Thị Ngọc Yến',
    nickname: 'Babibird',
    relatedOrganization: 'former IYC',
    totalDonation: '******',
    hiddenDonation: '50000',
    moneySource: 'Bank',
    description: '',
    place: '',
    time: '2025/04/12 21:46',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 49,
    name: '(Giấu tên)',
    nickname: 'Dylan Lucasemwazi',
    relatedOrganization: 'former Glodival',
    totalDonation: '******',
    hiddenDonation: '100000',
    moneySource: 'Momo',
    description: '',
    place: '',
    time: '2025/04/13 11:36',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 50,
    name: 'Nguyễn Anh Thư',
    nickname: 'Scarlett',
    relatedOrganization: 'former Glodival',
    totalDonation: '******',
    hiddenDonation: '86000',
    moneySource: 'Momo',
    description: '',
    place: '',
    time: '2025/04/14 09:30',
    avatar: '',
    status: 'Đã ghi nhận',
  },
  {
    id: 51,
    name: 'Lâm Thị Huyền Trân',
    nickname: 'Tamy',
    relatedOrganization: 'former Glodival',
    totalDonation: '******',
    hiddenDonation: '10000',
    moneySource: 'Momo',
    description: '',
    place: '',
    time: '2025/04/14 09:57',
    avatar: '',
    status: 'Đã ghi nhận',
  },
]
export default contributorsDb
