import type { KoanTitle, Koan } from "@/types.ts";

export const TiedijiTitles: KoanTitle[] = [
    { title: "VĂN THÙ VÀO CỬA", slug: "if001-Van-Thu-vao-cua" },
    { title: "LA SƠN KHAI ĐƯỜNG", slug: "if002-La-Son-khai-duong" },
    { title: "NAM TUYỀN PHẬT ĐÁ", slug: "if003-Nam-Tuyen-Phat-da" },
    { title: "BÁCH LINH CHỨNG ĐẮC", slug: "if004-Bach-Linh-chung-dac" },
    { title: "THIỀU SƠN MỘT CÂU", slug: "if005-Thieu-Son-mot-cau" },
    { title: "ĐẦU TỬ THỌ TRAI", slug: "if006-Dau-Tu-tho-trai" },
    { title: "VÂN MÔN TIỆC Ở MIẾU THẦN", slug: "if007-Van-Mon-tiec-o-mieu-than" },
    { title: "VÂN CƯ CHỈ DẠY", slug: "if008-Van-Cu-chi-day" },
    { title: "TỪ MINH ĐẠI Ý", slug: "if009-Tu-Minh-dai-y" },
    { title: "DƯỢC SƠN NẮM GIỮ", slug: "if010-Duoc-Son-nam-giu" },
    { title: "TRIỆU CHÂU TRÙM ĐẦU", slug: "if011-Trieu-Chau-trum-dau" },
    { title: "TAM THÁNH GẶP HỌC NHÂN", slug: "if012-Tam-Thanh-gap-hoc-nhan" },
    { title: "TIỆM NGUYÊN RÈM GIẤY", slug: "if013-Tiem-Nguyen-rem-giay" },
    { title: "BẠCH VÂN TRẮNG VÀ ĐEN", slug: "if014-Bach-Van-trang-va-den" },
    { title: "ĐẠI TÙY TU BÊN TRONG", slug: "if015-Dai-Tuy-tu-ben-trong" },
    { title: "QUY SƠN THỜI GIAN", slug: "if016-Quy-Son-thoi-gian" },
    { title: "ĐẠI TÙY CON RÙA", slug: "if017-Dai-Tuy-con-rua" },
    { title: "LÂM TẾ TRỒNG TÙNG", slug: "if018-Lam-Te-trong-tung" },
    { title: "TRIỆU CHÂU VIẾNG CHÙA", slug: "if019-Trieu-Chau-vieng-chua" },
    { title: "ĐỨC SƠN HIỀN ĐỨC NGÀY XƯA", slug: "if020-Duc-Son-hien-duc-ngay-xua" },
    { title: "PHẦN DƯƠNG CÂY GẬY", slug: "if021-Phan-Duong-cay-gay" },
    { title: "BA LĂNG MẬT TRUYỀN", slug: "if022-Ba-Lang-mat-truyen" },
    { title: "TUYẾT PHONG CHẶT CÂY", slug: "if023-Tuyet-Phong-chat-cay" },
    { title: "NAM TUYỀN TUỔI PHẬT", slug: "if024-Nam-Tuyen-tuoi-Phat" },
    { title: "NHAM ĐẦU THÙNG NƯỚC", slug: "if025-Nham-Dau-thung-nuoc" },
    { title: "TUYẾT PHONG CHÍNH XÁC", slug: "if026-Tuyet-Phong-chinh-xac" },
    { title: "NGƯỠNG SƠN NGÀN MUÔN CẢNH", slug: "if027-Nguong-Son-ngan-muon-canh" },
    { title: "LONG NHA CẢNH GIỚI VÔ THƯỢNG", slug: "if028-Long-Nha-canh-gioi-vo-thuong" },
    { title: "NGƯỠNG SƠN CHÀO THẦY", slug: "if029-Nguong-Son-chao-thay" },
    { title: "THÁI TÔNG NẰM MỘNG", slug: "if030-Thai-Tong-nam-mong" },
    { title: "QUY SƠN GỌI HAI TĂNG CHỨC", slug: "if031-Quy-Son-goi-hai-tang-chuc" },
    { title: "PHẦN DƯƠNG TRỪNG PHẠT HƯ KHÔNG", slug: "if032-Phan-Duong-trung-Phat-hu-khong" },
    { title: "DƯỢC SƠN VẤN ĐỀ", slug: "if033-Duoc-Son-van-de" },
    { title: "TUYẾT PHONG THẤY PHẬT TÁNH", slug: "if034-Tuyet-Phong-thay-Phat-tanh" },
    { title: "LỢI TUNG BÀI THƠ", slug: "if035-Loi-Tung-bai-tho" },
    { title: "SAU KHI CHẾT GẶP NHAU Ở ĐÂU", slug: "if036-sau-khi-chet-gap-nhau-o-dau" },
    { title: "TUYẾT PHONG THÁNH TÍNH", slug: "if037-Tuyet-Phong-thanh-tinh" },
    { title: "RA ĐI VÀ TRỞ LẠI", slug: "if038-ra-di-va-tro-lai" },
    { title: "BA LẦN GỌI", slug: "if039-ba-lan-goi" },
    { title: "KHE SUỐI KHÔ", slug: "if040-khe-suoi-kho" },
    { title: "ĐỘNG SƠN BA TẠNG", slug: "if041-Dong-Son-ba-tang" },
    { title: "NÚI NAM", slug: "if042-nui-nam" },
    { title: "ĐẠO LÝ TỐI HẬU CỦA THIỀN", slug: "if043-Dao-ly-toi-hau-cua-thien" },
    { title: "NAM TUYỀN CHẲNG NHẬN CẢ TĂNG LẪN TỤC", slug: "if044-Nam-Tuyen-chang-nhan-ca-tang-lan-tuc" },
    { title: "VU ĐỊCH HỎI PHẬT", slug: "if045-Vu-Dich-hoi-Phat" },
    { title: "CHỮ TÂM", slug: "if046-Chu-tam" },
    { title: "TRIỆU CHÂU ĐO NƯỚC", slug: "if047-Trieu-Chau-do-nuoc" },
    { title: "ĐỊA TẠNG PHẬT PHÁP", slug: "if048-Dia-Tang-Phat-phap" },
    { title: "HUYỀN SA GIẤY TRẮNG", slug: "if049-Huyen-Sa-giay-trang" },
    { title: "NGHĨA TRUNG THUYẾT PHÁP", slug: "if050-Nghia-Trung-thuyet-phap" },
    { title: "BẢO PHÚC CÁI CHÙA", slug: "if051-Bao-Phuc-cai-chua" },
    { title: "HOA NGHIÊM TRỞ LẠI THẾ GIAN MÊ HOẶC", slug: "if052-Hoa-Nghiem-tro-lai-the-gian-me-hoac" },
    { title: "HUỆ TRUNG ĐÁNH ĐUỔI ĐỆ TỬ", slug: "if053-Hue-Trung-danh-duoi-de-tu" },
    { title: "NHAM ĐẦU HAI BỮA ĂN", slug: "if054-Nham-Dau-hai-bua-an" },
    { title: "MỤC CHÂU KẺ ĐỘN CĂN", slug: "if055-Muc-Chau-ke-don-can" },
    { title: "LỖ TỔ QUAY MẶT VÀO TƯỜNG", slug: "if056-Lo-To-quay-mat-vao-tuong" },
    { title: "LÂM TẾ NGƯỜI KHÔNG NGÔI VỊ", slug: "if057-Lam-Te-nguoi-khong-ngoi-vi" },
    { title: "PHO TƯỢNG QUAN THẾ ÂM", slug: "if058-pho-tuong-Quan-The-Am" },
    { title: "VÔ NGHIỆP VỌNG TƯỞNG", slug: "if059-Vo-Nghiep-vong-tuong" },
    { title: "CÁI GỐI GỖ", slug: "if060-cai-goi-go" },
    { title: "VÂN MÔN QUẢ THÁNH", slug: "if061-Van-Mon-qua-thanh" },
    { title: "NAM TUYỀN AM NHỎ", slug: "if062-Nam-Tuyen-am-nho" },
    { title: "DƯỢC SƠN THUYẾT PHÁP", slug: "if063-Duoc-Son-thuyet-phap" },
    { title: "CẢNH THANH GẬY TO", slug: "if064-Canh-Thanh-gay-to" },
    { title: "VẬT KỲ DIỆU NHẤT", slug: "if065-vat-ky-dieu-nhat" },
    { title: "ĐẠO NGÔ ĐẠO LÝ THÂM SÂU", slug: "if066-Dao-Ngo-dao-ly-tham-sau" },
    { title: "CÀN PHONG LUÂN HỒI", slug: "if067-Can-Phong-luan-hoi" },
    { title: "VÂN MÔN BA NGÀY", slug: "if068-Van-Mon-ba-ngay" },
    { title: "QUAN THƯỢNG THƯ", slug: "if069-Quan-Thuong-thu" },
    { title: "TRIỆU CHÂU TRỤ CHỖ NÀO", slug: "if070-Trieu-Chau-tru-cho-nao" },
    { title: "VÂN MÔN NẾP NHÀ", slug: "if071-Van-Mon-nep-nha" },
    { title: "BẢO THỌ QUAY LƯNG", slug: "if072-Bao-Tho-quay-lung" },
    { title: "TUYẾT PHONG TỪ CHỐI ÔNG TĂNG", slug: "if073-Tuyet-Phong-tu-choi-ong-Tang" },
    { title: "CHỌN NGƯỜI KHAI SÁNG MỘT NGÔI CHÙA", slug: "if074-chon-nguoi-khai-sang-mot-ngoi-chua" },
    { title: "ÔNG TĂNG NGỒI THIỀN", slug: "if075-ong-tang-ngoi-thien" },
    { title: "ĐỊA TẠNG HOA MẪU ĐƠN", slug: "if076-Dia-Tang-hoa-mau-don" },
    { title: "ĐỘNG SƠN KHUYÊN TĂNG", slug: "if077-Dong-Son-khuyen-tang" },
    { title: "VÂN CƯ TẶNG Y", slug: "if078-Van-Cu-tang-y" },
    { title: "ĐỨC SƠN GIÁO PHÁP TỘT CÙNG", slug: "if079-Duc-Son-giao-phap-tot-cung" },
    { title: "BA TIÊU KHÔNG DẠY", slug: "if080-Ba-Tieu-khong-day" },
    { title: "CAO ĐÌNH ĐÁNH TĂNG", slug: "if081-Cao-Dinh-danh-tang" },
    { title: "NHAM ĐẦU CÁI BÚA", slug: "if082-Nham-Dau-cai-bua" },
    { title: "NGƯỠNG SƠN VẼ MỘT ĐƯỜNG", slug: "if083-Nguong-Son-ve-mot-duong" },
    { title: "CÀN PHONG MỘT ĐƯỜNG", slug: "if084-Can-Phong-mot-duong" },
    { title: "HUYỀN SA THUYỀN SẮT", slug: "if085-Huyen-Sa-thuyen-sat" },
    { title: "NGƯỠNG SƠN NGỒI THIỀN", slug: "if086-Nguong-Son-ngoi-thien" },
    { title: "THIỀN NGUYỆT KHẢY MÓNG TAY", slug: "if087-Thien-Nguyet-khay-mong-tay" },
    { title: "DƯỢC SƠN CÁI HỒ", slug: "if088-Duoc-Son-cai-ho" },
    { title: "TUYẾT PHONG QUẢ CẦU GỖ", slug: "if089-Tuyet-Phong-qua-cau-go" },
    { title: "CÁI MÂM VỠ", slug: "if090-cai-mam-vo" },
    { title: "PHÁP NHÃN GIỌT NƯỚC", slug: "if091-Phap-Nhan-giot-nuoc" },
    { title: "TÀO SƠN BỐN KHÔNG", slug: "if092-Tao-Son-bon-khong" },
    { title: "ĐỨC SƠN SƯ TỬ", slug: "if093-Duc-Son-su-tu" },
    { title: "SỐNG MỘT MÌNH", slug: "if094-song-mot-minh" },
    { title: "LÂM TẾ MẮT CHÁNH", slug: "if095-Lam-Te-mat-chanh" },
    { title: "NHAM ĐẦU BA GIỚI", slug: "if096-Nham-Dau-ba-gioi" },
    { title: "THÂN PHẬT", slug: "if097-than-Phat" },
    { title: "HƯU TỊNH DÙNG TRÒ CHƠI", slug: "if098-Huu-Tinh-dung-tro-choi" },
    { title: "ĐẠI ĐIÊN BAO NHIÊU TUỔI", slug: "if099-Dai-Dien-bao-nhieu-tuoi" },
    { title: "QUY SƠN PHƯƠNG TRƯỢNG", slug: "if100-Quy-Son-phuong-truong" }
];

const Tiediji: Koan[] = [

];

export default Tiediji;
