const bookViDb = [
  {
    id: 1,
    cover: 'https://i.ytimg.com/vi/RFhGmMxOP6I/maxresdefault.jpg',
    title: 'BÁ TRƯỢNG NGỮ LỤC',
    author: 'Thiền Sư Bá Trượng Hoài Hải',
    description: 'Việt Dịch @ HT. Thích Duy Lực',
    info: '',
    link: 'http://tosuthien.info/kinh_sach_storage/ba%20truong%20ngu%20luc.pdf',
    youtube: '',
    saveAudio: '/ftp/MP3/- T Duy Luc/Góp Nhặt Lời Phật Tổ/11 Bá Trượng Ngữ Lục.mp3',
  },
  {
    id: 2,
    cover: 'https://i.ytimg.com/vi/oGGGn259CfI/maxresdefault.jpg',
    title: 'ĐƯỜNG LỐI THỰC HÀNH THAM TỒ SƯ THIỀN',
    author: 'HT. Thích Duy Lực',
    description: '',
    info: '',
    link: 'http://tosuthien.info/kinh_sach_storage/duong%20loi%20thuc%20hanh%20tham%20to%20su%20thien.pdf',
    youtube: '',
    saveAudio: '',
  },
  {
    id: 3,
    cover: 'https://i.ex-cdn.com/phatgiao.org.vn/files/f1/Contents/levanthong/20170301/Phatgiao-org-vn-buu-tang-luan-2123.jpg',
    title: 'BỬU TẠNG LUẬN',
    author: 'Đại Sư Tăng Triệu',
    description: 'Việt Dịch @ HT. Thích Duy Lực',
    info: '',
    link: 'http://tosuthien.info/kinh_sach_storage/buu%20tang%20luan.pdf',
    linkAudio: 'https://ph.tinhtong.vn/Home/MP3?p=MP3*-+T+Duy+Luc*B%E1%BA%A3o+T%E1%BA%A1ng+Lu%E1%BA%ADn+-+T%C4%83ng+Tri%E1%BB%87u',
    youtube: '',
    saveAudio: 'https://ph.tinhtong.vn/ftp/MP3/-%20T%20Duy%20Luc/B%E1%BA%A3o%20T%E1%BA%A1ng%20Lu%E1%BA%ADn%20-%20T%C4%83ng%20Tri%E1%BB%87u/Bao-Tang-Luan.mp3',
  },
  {
    id: 4,
    cover: 'https://i.ytimg.com/vi/-lm3_HoaANM/maxresdefault.jpg',
    title: 'CỘI NGUỒN TRUYỀN THỪA',
    author: 'Nguyệt Khê Thiền Sư',
    description: 'Việt Dịch @ HT. Thích Duy Lực',
    info: '',
    link: 'http://tosuthien.info/kinh_sach_storage/coi%20nguon%20truyen%20thua.pdf',
    linkAudio: 'https://ph.tinhtong.vn/Home/MP3?p=MP3*-+T+Duy+Luc*C%E1%BB%99i+Ngu%E1%BB%93n+Truy%E1%BB%81n+Th%E1%BB%ABa',
    youtube: '',
    saveAudio: 'https://ph.tinhtong.vn/ftp2/ZIP%20MP3/MP3/-%20T%20Duy%20Luc/C%E1%BB%99i%20Ngu%E1%BB%93n%20Truy%E1%BB%81n%20Th%E1%BB%ABa/C%E1%BB%99i%20Ngu%E1%BB%93n%20Truy%E1%BB%81n%20Th%E1%BB%ABa.zip',
  },
  {
    id: 5,
    cover: 'https://i.ytimg.com/vi/jUrguAriWhs/maxresdefault.jpg',
    title: 'CÔNG ÁN CỦA PHẬT THÍCH CA VÀ TỔ ĐẠT MA',
    author: '',
    description: 'Việt Dịch @ HT. Thích Duy Lực',
    info: '',
    link: 'http://tosuthien.info/kinh_sach_storage/cong%20an%20cua%20phat%20thich%20ca%20va%20to%20dat%20ma.pdf',
    youtube: '',
    saveAudio: '',
  },
  {
    id: 6,
    cover: 'https://i.ytimg.com/vi/73Tf24W5F30/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLCEyIsu0xC8LB0VFNEnM596Ru61nw',
    title: 'ĐẠI HUỆ NGỮ LỤC',
    author: '',
    description: 'Việt Dịch @ HT. Thích Duy Lực',
    info: '',
    link: 'http://tosuthien.info/kinh_sach_storage/dai%20hue%20ngu%20luc.pdf',
    linkAudio: 'https://ph.tinhtong.vn/Home/MP3?p=MP3*-+T+Duy+Luc*%C4%90%E1%BA%A1i+Hu%E1%BB%87+Ng%E1%BB%AF+L%E1%BB%A5c',
    youtube: '',
    saveAudio: 'https://ph.tinhtong.vn/ftp2/ZIP%20MP3/MP3/-%20T%20Duy%20Luc/%C4%90%E1%BA%A1i%20Hu%E1%BB%87%20Ng%E1%BB%AF%20L%E1%BB%A5c/%C4%90%E1%BA%A1i%20Hu%E1%BB%87%20Ng%E1%BB%AF%20L%E1%BB%A5c.zip',
  },
  {
    id: 7,
    cover: 'https://i.ytimg.com/vi/9FnueTmIIE0/maxresdefault.jpg',
    title: 'ĐẠI THỪA TUYỆT ĐỐI LUẬN',
    author: 'Nguyệt Khê Thiền Sư',
    description: 'Việt Dịch @ HT. Thích Duy Lực',
    info: '',
    link: 'http://tosuthien.info/kinh_sach_storage/dai%20thua%20tuyet%20doi%20luan.pdf',
    youtube: '',
    saveAudio: '',
  },
  {
    id: 8,
    cover: 'https://i.ex-cdn.com/phatgiao.org.vn/files/f1/Contents/levanthong/20171222/Phatgiao-org-vn-yeu-chi-phat-phap-thich-duy-luc-01.jpg',
    title: 'DUY LỰC NGỮ LỤC',
    author: 'HT. Thích Duy Lực',
    description: 'Tập hợp từ những lời thị chúng của Thiền Sư trong những kỳ thiền thất tại Việt Nam kể từ năm 1983 cho đến những năm tháng cuối đời',
    info: 'QUYỂN THƯỢNG - P1 & QUYỂN HẠ - P2',
    link1: 'http://tosuthien.info/kinh_sach_storage/duy%20luc%20ngu%20luc%20quyen%20thuong.pdf',
    link2: 'http://tosuthien.info/kinh_sach_storage/duy%20luc%20ngu%20luc%20quyen%20ha.pdf',
    linkAudio1: 'https://ph.tinhtong.vn/Home/MP3?p=MP3*-+T+Duy+Luc*Duy+L%E1%BB%B1c+Ng%E1%BB%AF+L%E1%BB%A5c+-+Quy%E1%BB%83n+Th%C6%B0%E1%BB%A3ng',
    linkAudio2: 'https://ph.tinhtong.vn/Home/MP3?p=MP3*-+T+Duy+Luc*Duy+L%E1%BB%B1c+Ng%E1%BB%AF+L%E1%BB%A5c+-+Quy%E1%BB%83n+H%E1%BA%A1',
    youtube: '',
    saveAudio: '',
  },
  {
    id: 9,
    cover: 'https://i.ytimg.com/vi/rT3wLhMSa4Q/maxresdefault.jpg',
    title: 'GIẢNG GIẢI TÍN TÂM MINH TỊCH NGHĨA GIẢI',
    author: '',
    description: 'TS. Trung Phong Minh Bổn @ Tịch Nghĩa giải --- Việt Dịch & Giảng Tịch Nghĩa @ HT. Thích Duy Lực',
    info: 'TÍN TÂM MINH là bài thơ của Tam tổ Tăng Xán',
    link: 'http://tosuthien.info/kinh_sach_storage/giang%20tin%20tam%20minh%20tich%20nghia%20giai.pdf',
    linkAudio: 'https://ph.tinhtong.vn/Home/MP3?p=MP3*-+T+Duy+Luc*T%C3%ADn+T%C3%A2m+Minh+T%E1%BB%8Bch+Ngh%C4%A9a+Gi%E1%BA%A3i+-+T%E1%BB%95+Trung+Phong',
    youtube: '',
    saveAudio: 'https://ph.tinhtong.vn/ftp2/ZIP%20MP3/MP3/-%20T%20Duy%20Luc/T%C3%ADn%20T%C3%A2m%20Minh%20T%E1%BB%8Bch%20Ngh%C4%A9a%20Gi%E1%BA%A3i%20-%20T%E1%BB%95%20Trung%20Phong/T%C3%ADn%20T%C3%A2m%20Minh%20T%E1%BB%8Bch%20Ngh%C4%A9a%20Gi%E1%BA%A3i%20-%20T%E1%BB%95%20Trung%20Phong.zip',
  },
  {
    id: 10,
    cover: 'https://t.ex-cdn.com/phatgiao.org.vn/560w/files/news/2023/06/06/to-de-da-ca--to-su-thien-tong-doi-thu-nam-091833.jpg',
    title: 'GÓP NHẶT LỜI PHẬT TỔ VÀ THÁNH HIÊN',
    author: 'HT. Thích Duy Lực',
    description: 'Phật pháp là pháp bất nhị, tâm trí không thể đến được, nhưng người đời nay ưa thích đem tâm trí suy lường lời Phật Tổ, nên không đến được chỗ rốt ráo giải thoát',
    info: 'Chúng tôi góp nhặt những lời chân thật của Phật Tổ và Thánh Hiền để chứng tỏ “tâm ngôn lộ tuyệt”',
    link: 'http://tosuthien.info/kinh_sach_storage/got%20nhat%20loi%20to%20va%20thanh%20hien.pdf',
    youtube: '',
    saveAudio: '',
  },
  {
    id: 11,
    cover: 'https://i.ytimg.com/vi/v4a6yGQvYwo/hq720.jpg?sqp=-oaymwE7CK4FEIIDSFryq4qpAy0IARUAAAAAGAElAADIQj0AgKJD8AEB-AH-CYAC0AWKAgwIABABGGUgYyhFMA8=&rs=AOn4CLBAcgIiPZyQWEIZRnI50Q8Bk51Tlg',
    title: 'VẤN ĐÁP THIỀN VÀ PHẬT PHÁP',
    author: 'HT. Thích Duy Lực',
    description: '',
    info: '',
    link: 'http://tosuthien.info/kinh_sach_storage/van%20dap%20thien.pdf',
    youtube: '',
    saveAudio: '',
  },
  {
    id: 12,
    cover: 'https://i.ytimg.com/vi/Uy0GL1-G5Gc/maxresdefault.jpg',
    title: 'TRIỆU LUẬN LƯỢC GIẢI',
    author: 'Tăng Triệu Ðại Sư - Lược Giải: Hám Sơn Ðại Sư',
    description: 'Việt Dịch @ HT. Thích Duy Lực',
    info: '',
    link: 'http://tosuthien.info/kinh_sach_storage/trieu%20luan%20luoc%20giai.pdf',
    youtube: '',
    saveAudio: '',
  },
  {
    id: 13,
    cover: 'https://i.ytimg.com/vi/Z-CjEqrgCa8/hq720.jpg?sqp=-oaymwE7CK4FEIIDSFryq4qpAy0IARUAAAAAGAElAADIQj0AgKJD8AEB-AH-CYAC0AWKAgwIABABGFQgYChlMA8=&rs=AOn4CLBHFQ5D4yckjHWswaeMo65zqo03Vg',
    title: 'THAM THIỀN CẢNH NGỮ',
    author: 'Thiền Sư Bác Sơn',
    description: 'Việt Dịch @ HT. Thích Duy Lực',
    info: '',
    link: 'http://tosuthien.info/kinh_sach_storage/tham%20thien%20canh%20ngu.pdf',
    linkAudio: 'https://ph.tinhtong.vn/Home/MP3?p=MP3*-+T+Duy+Luc*Tham+Thi%E1%BB%81n+C%E1%BA%A3nh+Ng%E1%BB%AF+-+Thi%E1%BB%81n+S%C6%B0+B%C3%A1c+S%C6%A1n',
    youtube: 'RFhGmMxOP6I',
    saveAudio: 'https://ph.tinhtong.vn/ftp2/ZIP%20MP3/MP3/-%20T%20Duy%20Luc/Tham%20Thi%E1%BB%81n%20C%E1%BA%A3nh%20Ng%E1%BB%AF%20-%20Thi%E1%BB%81n%20S%C6%B0%20B%C3%A1c%20S%C6%A1n/Tham%20Thi%E1%BB%81n%20C%E1%BA%A3nh%20Ng%E1%BB%AF%20-%20Thi%E1%BB%81n%20S%C6%B0%20B%C3%A1c%20S%C6%A1n.zip',
  },
  {
    id: 14,
    cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVlIgD9Qd1_U-GT3YyicIfaBi_M-WeY3wfZA&s',
    title: 'THIỀN THẤT KHAI THỊ LỤC',
    author: 'TS. Lai Quả',
    description: 'Việt Dịch @ HT. Thích Duy Lực',
    info: 'QUYỂN THƯỢNG - P1 & QUYỂN HẠ - P2',
    link: 'http://tosuthien.info/kinh_sach_storage/duy%20luc%20ngu%20luc%20quyen%20thuong.pdf',
    linkAudio1: 'https://ph.tinhtong.vn/Home/MP3?p=MP3*-+T+Duy+Luc*Tham+Thi%E1%BB%81n+Ph%E1%BB%95+Thuy%E1%BA%BFt+-+Quy%E1%BB%83n+Th%C6%B0%E1%BB%A3ng+-+TS+Lai+Qu%E1%BA%A3',
    linkAudio2: 'https://ph.tinhtong.vn/Home/MP3?p=MP3*-+T+Duy+Luc*Tham+Thi%E1%BB%81n+Ph%E1%BB%95+Thuy%E1%BA%BFt+-+Quy%E1%BB%83n+H%E1%BA%A1+-+TS+Lai+Qu%E1%BA%A3',
    youtube: '',
    saveAudio: 'https://ph.tinhtong.vn/ftp2/ZIP%20MP3/MP3/-%20T%20Duy%20Luc/Thi%E1%BB%81n%20Th%E1%BA%A5t%20Khai%20Th%E1%BB%8B%20L%E1%BB%A5c%20-%20TS%20Lai%20Qu%E1%BA%A3/Thi%E1%BB%81n%20Th%E1%BA%A5t%20Khai%20Th%E1%BB%8B%20L%E1%BB%A5c%20-%20TS%20Lai%20Qu%E1%BA%A3.zip',
  },
  {
    id: 15,
    cover: 'https://i.ytimg.com/vi/Od56X9rUCIg/hq720.jpg?sqp=-oaymwE7CK4FEIIDSFryq4qpAy0IARUAAAAAGAElAADIQj0AgKJD8AEB-AH-CYAC0AWKAgwIABABGEAgWihlMA8=&rs=AOn4CLDJ_9diYZJugj9coj17DbJrCkd8yA',
    title: 'TRUNG PHONG PHÁP NGỮ',
    author: 'TS. TRUNG PHONG',
    description: 'Việt Dịch @ Nguyên Chánh',
    info: 'Trích trong Chỉ Nguyệt Lục của bộ Tục Tạng Kinh',
    link: 'http://tosuthien.info/kinh_sach_storage/trung%20phong%20phap%20ngu.pdf',
    linkAudio: 'https://ph.tinhtong.vn/Home/MP3?p=MP3*-+T+Duy+Luc*Trung+Phong+Ph%C3%A1p+Ng%E1%BB%AF',
    youtube: '',
    saveAudio: 'https://ph.tinhtong.vn/ftp2/ZIP%20MP3/MP3/-%20T%20Duy%20Luc/Trung%20Phong%20Ph%C3%A1p%20Ng%E1%BB%AF/Trung%20Phong%20Ph%C3%A1p%20Ng%E1%BB%AF.zip',
  },
  {
    id: 16,
    cover: 'https://i.ytimg.com/vi/-zMyMq9KePE/maxresdefault.jpg',
    title: 'LÂM TẾ NGỮ LỤC',
    author: 'TS. LÂM TẾ',
    description: 'Việt Dịch @ HT. Thích Duy Lực',
    info: '',
    link: 'http://tosuthien.info/kinh_sach_storage/lam%20te%20ngu%20luc.pdf',
    youtube: '',
    saveAudio: '',
  },
  {
    id: 17,
    cover: 'https://quangduc.com/images/file/vxlpaTXc0wgBALkr/nam-tuyen-chem-meo.jpg',
    title: 'NAM TUYỀN NGỮ LỤC',
    author: '',
    description: 'Việt Dịch: HT. Thích Duy Lực',
    info: 'Trích dịch trong Chỉ Nguyệt Lục',
    link: 'http://tosuthien.info/kinh_sach_storage/nam%20tuyen%20ngu%20luc.pdf',
    linkAudio: 'https://ph.tinhtong.vn/Home/MP3?p=MP3*-+T+Duy+Luc*Nam+Tuy%E1%BB%81n+Ng%E1%BB%AF+L%E1%BB%A5c',
    youtube: '',
    saveAudio: 'https://ph.tinhtong.vn/ftp/MP3/-%20T%20Duy%20Luc/Nam%20Tuy%E1%BB%81n%20Ng%E1%BB%AF%20L%E1%BB%A5c/Nam%20tuyen%20ngu%20luc.mp3',
  },
  {
    id: 18,
    cover: 'https://chuatutam.net/wp-content/uploads/2021/10/TS-LAI-QUA.jpg',
    title: 'THAM THIỀN PHỔ THUYẾT',
    author: 'TS. Lai Quả',
    description: 'Việt Dịch: HT. Thích Duy Lực',
    info: '',
    link1: 'http://tosuthien.info/kinh_sach_storage/tham%20thien%20pho%20thuyet%20-%20quyen%20thuong.pdf',
    link2: 'http://tosuthien.info/kinh_sach_storage/tham%20thien%20pho%20thuyet%20-%20quyen%20ha.pdf',
    linkAudio1: 'https://ph.tinhtong.vn/Home/MP3?p=MP3*-+T+Duy+Luc*Tham+Thi%E1%BB%81n+Ph%E1%BB%95+Thuy%E1%BA%BFt+-+Quy%E1%BB%83n+Th%C6%B0%E1%BB%A3ng+-+TS+Lai+Qu%E1%BA%A3',
    linkAudio2: 'https://ph.tinhtong.vn/Home/MP3?p=MP3*-+T+Duy+Luc*Tham+Thi%E1%BB%81n+Ph%E1%BB%95+Thuy%E1%BA%BFt+-+Quy%E1%BB%83n+H%E1%BA%A1+-+TS+Lai+Qu%E1%BA%A3',
    youtube: '',
    saveAudio: '',
  },
]
export default bookViDb;
