const bookEnDb = [
  {
    id: 1,
    cover: 'https://i.ex-cdn.com/phatgiao.org.vn/files/f1/Contents/levanthong/20171222/Phatgiao-org-vn-yeu-chi-phat-phap-thich-duy-luc-01.jpg',
    title: 'THE ZEN TEACHINGS OF MASTER DUY LUC',
    author: 'Venerable Thich Duy Luc',
    description: 'Translated into English by Nguyen Giac',
    info: 'An approach of direct meditation that Gautama Buddha taught',
    link: 'https://nigioikhatsi.net/kinhsach-pdf/thezenteachingofmasterthichduyluc.pdf',
    youtube: 'vAfUrK9vGk4',
    mp3: '',
  },
  {
    id: 2,
    cover: 'https://p1-tt.byteimg.com/origin/pgc-image/f8d4f1653f014ce198e6d1f31d228338.jpg',
    title: 'THE RECORD OF TRANSMITTING THE LIGHT',
    author: 'Keizan Zenji',
    description: 'Denkōroku - A kōan collection written in 1300',
    info: 'Including 53 enlightenment stories',
    link: 'https://terebess.hu/zen/mesterek/tra.pdf',
    youtube: '',
    mp3: '',
  },
  {
    id: 3,
    cover: 'https://static1.squarespace.com/static/58e565bb440243f7e4488283/62c21e715afcae5eb9ac7549/63cf3710a5619d54d34943d6/1674869308208/THE+GATELESS+GATE.2000PX.jpg',
    title: 'WÚ MÉN GUĀN - THE BARRIER THAT HAS NO GATE',
    author: 'Chán Master Wúmén Huìkāi',
    description: 'Questions and Additional Comments by Sŏn Master Sǔngan',
    info: 'Compiled and Edited by Paul Dōch’ŏng Lynch, JDPSN',
    link: 'https://terebess.hu/zen/Wumenguan.pdf',
    youtube: '',
    mp3: '',
  },
  {
    id: 4,
    cover: 'https://www.lionsroar.com/wp-content/uploads/2024/06/bluecliff.jpg',
    title: 'THE BLUE CLIFF RECORD',
    author: 'Selected by Hsueh Tou Chʾung-hsien - annotated and commented by Yuanwu Keqin',
    description: 'Translated by Thomas Cleary and J. C. Cleary - Foreword by Taizan Maezumi Roshi',
    info: 'A collection of Chan Buddhist kōans originally compiled in 1125 and expanded into its present form',
    link: 'https://terebess.hu/zen/Blue-Cliff.pdf',
    youtube: '',
    mp3: '',
  },
  {
    id: 5,
    cover: 'https://m.media-amazon.com/images/I/41dmHOCKBvL._SR600%2C315_PIWhiteStrip%2CBottomLeft%2C0%2C35_PIStarRatingFOURANDHALF%2CBottomLeft%2C360%2C-6_SR600%2C315_ZA13%2C445%2C290%2C400%2C400%2CAmazonEmberBold%2C12%2C4%2C0%2C0%2C5_SCLZZZZZZZ_FMpng_BG255%2C255%2C255.jpg',
    title: 'IRON FLUTE',
    author: '',
    description: 'Translated by Ruth Strout McCandless, Genro Oryu, Fugai, Steve Hagen, Nyogen Senzaki',
    info: '',
    link: 'https://terebess.hu/zen/iron-flute.pdf',
    youtube: '',
    mp3: '',
  },
  {
    id: 6,
    cover: 'https://m.media-amazon.com/images/I/41irljmY73L._SR600%2C315_PIWhiteStrip%2CBottomLeft%2C0%2C35_PIStarRatingTHREEANDHALF%2CBottomLeft%2C360%2C-6_SR600%2C315_ZA10%2C445%2C290%2C400%2C400%2CAmazonEmberBold%2C12%2C4%2C0%2C0%2C5_SCLZZZZZZZ_FMpng_BG255%2C255%2C255.jpg',
    title: 'THE SOUND OF THE ONE HAND',
    author: '',
    description: 'Translated by Yoel Hoffmann',
    info: '281 Zen Koans with Answers',
    link: 'https://terebess.hu/zen/sound-one-hand.pdf',
    youtube: '',
    mp3: '',
  },
]
export default bookEnDb;
