const bookViDb = [
  {
    id: 1,
    cover: 'https://i.ytimg.com/vi/RFhGmMxOP6I/maxresdefault.jpg',
    title: 'BÁ TRƯỢNG NGỮ LỤC',
    author: 'Thiền Sư Bá Trượng Hoài Hải',
    description: 'Việt Dịch: HT. Thích Duy Lực',
    info: '',
    link: 'http://tosuthien.info/kinh_sach_storage/ba%20truong%20ngu%20luc.pdf',
    youtube: 'RFhGmMxOP6I',
    mp3: '/ftp/MP3/- T Duy Luc/Góp Nhặt Lời Phật Tổ/11 Bá Trượng Ngữ Lục.mp3',
  },
  {
    id: 2,
    cover: 'https://vanthaphienminh.org/wp-content/uploads/2017/07/Bat-Nha-Tam-Kinh.jpg',
    title: 'BÁT NHÃ BA LA MẬT ĐA TÂM KINH LƯỢC GIẢI',
    author: 'HT. Thích Duy Lực',
    description: '',
    info: '',
    link: 'http://tosuthien.info/kinh_sach_storage/bat%20nha%20ba%20la%20mat%20da%20tam%20kinh%20luoc%20giai.pdf',
    youtube: '',
    mp3: '',
  },
  {
    id: 3,
    cover: '/images/book-covers/buu-tang-luan.jpg',
    title: 'BỬU TẠNG LUẬN',
    author: 'Đại Sư Tăng Triệu',
    description: 'Việt Dịch: HT. Thích Duy Lực',
    info: '',
    link: 'http://tosuthien.info/kinh_sach_storage/buu%20tang%20luan.pdf',
    youtube: '',
    mp3: '',
  },
  {
    id: 4,
    cover: 'https://i.ytimg.com/vi/-lm3_HoaANM/maxresdefault.jpg',
    title: 'CỘI NGUỒN TRUYỀN THỪA',
    author: 'Nguyệt Khê Thiền Sư',
    description: 'Việt Dịch: HT. Thích Duy Lực',
    info: '',
    link: 'http://tosuthien.info/kinh_sach_storage/coi%20nguon%20truyen%20thua.pdf',
    youtube: '',
    mp3: '',
  },
  {
    id: 5,
    cover: 'https://i.ytimg.com/vi/jUrguAriWhs/maxresdefault.jpg',
    title: 'CÔNG ÁN CỦA PHẬT THÍCH CA VÀ TỔ ĐẠT MA',
    author: '',
    description: 'Việt Dịch: HT. Thích Duy Lực',
    info: '',
    link: 'http://tosuthien.info/kinh_sach_storage/cong%20an%20cua%20phat%20thich%20ca%20va%20to%20dat%20ma.pdf',
    youtube: '',
    mp3: '',
  },
  {
    id: 6,
    cover: 'https://i.ytimg.com/vi/73Tf24W5F30/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLCEyIsu0xC8LB0VFNEnM596Ru61nw',
    title: 'ĐẠI HUỆ NGỮ LỤC',
    author: '',
    description: 'Việt Dịch: HT. Thích Duy Lực',
    info: '',
    link: 'http://tosuthien.info/kinh_sach_storage/dai%20hue%20ngu%20luc.pdf',
    youtube: '',
    mp3: '',
  },
]
export default bookViDb;
