const masterDb = [
  {
    id: 1,
    name_en: 'Gaofeng Yuanmiao',
    name_es: 'Gaofeng Yuanmiao',
    name_de: 'Gaofeng Yuanmiao',
    name_fr: 'Gaofeng Yuanmiao',
    name_vi: 'Cao Phong Nguyên Diệu',
    name_ru: 'Gaofeng Yuanmiao',
    name_zh: '高峰原妙',
    name_ja: 'Kōhō Genmyō',
    name_ko: 'Kobong Wŏnmyo',
    name_ar: 'Gaofeng Yuanmiao',
    country: 'China',
    teacher: '',
    disciples: ['Zhongfeng Mingben'],
    image: 'https://terebess.hu/zen/mesterek/woodcut/55.jpg'
  },
  {
    id: 2,
    name_en: 'Zhongfeng Mingben',
    name_es: 'Zhongfeng Mingben',
    name_de: 'Zhongfeng Mingben',
    name_fr: 'Zhongfeng Mingben',
    name_vi: 'Trung Phong Minh Bản',
    name_ru: 'Zhongfeng Mingben',
    name_zh: '中峰明本',
    name_ja: 'Zhongfeng Mingben',
    name_ko: 'Zhongfeng Mingben',
    name_ar: 'Zhongfeng Mingben',
    country: 'China',
    teacher: 'Gaofeng Yuanmiao',
    disciples: [''],
    image: 'https://terebess.hu/zen/mesterek/Zhongfeng_Mingben.jpg'
  },  {
    id: 3,
    name_en: 'Peter 1',
    name_es: 'Peter 1',
    name_de: 'Peter 1',
    name_fr: 'Peter 1',
    name_vi: 'Peter 1',
    name_ru: 'Peter 1',
    name_zh: 'Peter 1',
    name_ja: 'Peter 1',
    name_ko: 'Peter 1',
    name_ar: 'Peter 1',
    country: 'China',
    teacher: 'Peter 0',
    disciples: ['John 2, Peter 2'],
    dimage: 'https://terebess.hu/zen/mesterek/Zhongfeng_Mingben.jpg'
  },
  {
    id: 4,
    name_en: 'Peter 1',
    name_es: 'Peter 1',
    name_de: 'Peter 1',
    name_fr: 'Peter 1',
    name_vi: 'Peter 1',
    name_ru: 'Peter 1',
    name_zh: 'Peter 1',
    name_ja: 'Peter 1',
    name_ko: 'Peter 1',
    name_ar: 'Peter 1',
    country: 'China',
    teacher: 'Peter 0',
    disciples: ['John 2, Peter 2'],
    image: 'https://terebess.hu/zen/mesterek/Zhongfeng_Mingben.jpg'
  },
  {
    id: 5,
    name_en: '5 1',
    name_es: 'Peter 1',
    name_de: 'Peter 1',
    name_fr: 'Peter 1',
    name_vi: 'Peter 1',
    name_ru: 'Peter 1',
    name_zh: 'Peter 1',
    name_ja: 'Peter 1',
    name_ko: 'Peter 1',
    name_ar: 'Peter 1',
    country: 'China',
    teacher: 'Peter 0',
    disciples: ['John 2, Peter 2'],
    image: 'https://terebess.hu/zen/mesterek/Zhongfeng_Mingben.jpg',
  },
  {
    id: 6,
    name_en: '6 1',
    name_es: 'Peter 1',
    name_de: 'Peter 1',
    name_fr: 'Peter 1',
    name_vi: 'Peter 1',
    name_ru: 'Peter 1',
    name_zh: 'Peter 1',
    name_ja: 'Peter 1',
    name_ko: 'Peter 1',
    name_ar: 'Peter 1',
    country: 'China',
    teacher: 'Peter 0',
    disciples: ['John 2, Peter 2'],
    image: 'https://terebess.hu/zen/mesterek/Zhongfeng_Mingben.jpg',
  },
  {
    id: 7,
    name_en: '7 1',
    name_es: 'Peter 1',
    name_de: 'Peter 1',
    name_fr: 'Peter 1',
    name_vi: 'Peter 1',
    name_ru: 'Peter 1',
    name_zh: 'Peter 1',
    name_ja: 'Peter 1',
    name_ko: 'Peter 1',
    name_ar: 'Peter 1',
    country: 'China',
    teacher: 'Peter 0',
    disciples: ['John 2, Peter 2'],
    image: 'https://terebess.hu/zen/mesterek/Zhongfeng_Mingben.jpg',
  },
  {
    id: 8,
    name_en: '8 1',
    name_es: 'Peter 1',
    name_de: 'Peter 1',
    name_fr: 'Peter 1',
    name_vi: 'Peter 1',
    name_ru: 'Peter 1',
    name_zh: 'Peter 1',
    name_ja: 'Peter 1',
    name_ko: 'Peter 1',
    name_ar: 'Peter 1',
    country: 'China',
    teacher: 'Peter 0',
    disciples: ['John 2, Peter 2'],
    image: 'https://terebess.hu/zen/mesterek/Zhongfeng_Mingben.jpg',
  },
  {
    id: 9,
    name_en: '9 1',
    name_es: 'Peter 1',
    name_de: 'Peter 1',
    name_fr: 'Peter 1',
    name_vi: 'Peter 1',
    name_ru: 'Peter 1',
    name_zh: 'Peter 1',
    name_ja: 'Peter 1',
    name_ko: 'Peter 1',
    name_ar: 'Peter 1',
    country: 'China',
    teacher: 'Peter 0',
    disciples: ['John 2, Peter 2'],
    image: 'https://terebess.hu/zen/mesterek/Zhongfeng_Mingben.jpg',
  },
  {
    id: 10,
    name_en: '10 1',
    name_es: 'Peter 1',
    name_de: 'Peter 1',
    name_fr: 'Peter 1',
    name_vi: 'Peter 1',
    name_ru: 'Peter 1',
    name_zh: 'Peter 1',
    name_ja: 'Peter 1',
    name_ko: 'Peter 1',
    name_ar: 'Peter 1',
    country: 'China',
    teacher: 'Peter 0',
    disciples: ['John 2, Peter 2'],
    image: 'https://terebess.hu/zen/mesterek/Zhongfeng_Mingben.jpg',
  },
  {
    id: 11,
    name_en: '11 1',
    name_es: 'Peter 1',
    name_de: 'Peter 1',
    name_fr: 'Peter 1',
    name_vi: 'Peter 1',
    name_ru: 'Peter 1',
    name_zh: 'Peter 1',
    name_ja: 'Peter 1',
    name_ko: 'Peter 1',
    name_ar: 'Peter 1',
    country: 'China',
    teacher: 'Peter 0',
    disciples: ['John 2, Peter 2'],
    image: 'https://terebess.hu/zen/mesterek/Zhongfeng_Mingben.jpg',
  },
  {
    id: 12,
    name_en: '12 1',
    name_es: 'Peter 1',
    name_de: 'Peter 1',
    name_fr: 'Peter 1',
    name_vi: 'Peter 1',
    name_ru: 'Peter 1',
    name_zh: 'Peter 1',
    name_ja: 'Peter 1',
    name_ko: 'Peter 1',
    name_ar: 'Peter 1',
    country: 'China',
    teacher: 'Peter 0',
    disciples: ['John 2, Peter 2'],
    image: 'https://terebess.hu/zen/mesterek/Zhongfeng_Mingben.jpg',
  },
  {
    id: 13,
    name_en: '13 1',
    name_es: 'Peter 1',
    name_de: 'Peter 1',
    name_fr: 'Peter 1',
    name_vi: 'Peter 1',
    name_ru: 'Peter 1',
    name_zh: 'Peter 1',
    name_ja: 'Peter 1',
    name_ko: 'Peter 1',
    name_ar: 'Peter 1',
    country: 'China',
    teacher: 'Peter 0',
    disciples: ['John 2, Peter 2'],
    image: 'https://terebess.hu/zen/mesterek/Zhongfeng_Mingben.jpg',
  },
  {
    id: 14,
    name_en: '14 1',
    name_es: 'Peter 1',
    name_de: 'Peter 1',
    name_fr: 'Peter 1',
    name_vi: 'Peter 1',
    name_ru: 'Peter 1',
    name_zh: 'Peter 1',
    name_ja: 'Peter 1',
    name_ko: 'Peter 1',
    name_ar: 'Peter 1',
    country: 'China',
    teacher: 'Peter 0',
    disciples: ['John 2, Peter 2'],
    image: 'https://terebess.hu/zen/mesterek/Zhongfeng_Mingben.jpg',
  },
  {
    id: 15,
    name_en: '15 1',
    name_es: 'Peter 1',
    name_de: 'Peter 1',
    name_fr: 'Peter 1',
    name_vi: 'Peter 1',
    name_ru: 'Peter 1',
    name_zh: 'Peter 1',
    name_ja: 'Peter 1',
    name_ko: 'Peter 1',
    name_ar: 'Peter 1',
    country: 'China',
    teacher: 'Peter 0',
    disciples: ['John 2, Peter 2'],
    image: 'https://terebess.hu/zen/mesterek/Zhongfeng_Mingben.jpg',
  },
]
export default masterDb;
