const sectDb = [
  {
    id: 1,
    label: 'Guiyang',
    labelEn: 'Guiyang',
    labelJa: 'Igyô',
    color: 'red',
    founder: 'Guishan Lingyou - Yangshan Huiji',
    description: 'Guiyang',
    relation: '',
    doctrine: '',
    reference: ['https://chuahoiphuoc.net/nguon-goc-chung-bang-tong-quy-nguong/', 'https://en.wikipedia.org/wiki/Guiyang_school', 'https://en.wikipedia.org/wiki/Miyin_Temple',
      'https://zh.wikipedia.org/wiki/%E6%B2%A9%E4%BB%B0%E5%AE%97', 'https://nigioikhatsi.net/thien/thien-tong-co-du-tri-tue-vo-han-va-suc-sang-tao.html',
    'https://inf.news/en/culture/7d0433fb73e25301eea2673203f9c992.html'],
  },
  {
    id: 2,
    label: 'Linji',
    labelEn: 'Linji',
    labelJa: 'Rinzai',
    color: 'green',
    founder: 'Linji Yixuan',
    description: 'Linji',
    relation: '',
    doctrine: '',
    reference: ['https://chuahoiphuoc.net/chung-bang-tong-lam-te', 'https://en.wikipedia.org/wiki/Linji_school',
      'https://zh.wikipedia.org/wiki/%E4%B8%B4%E6%B5%8E%E5%AE%97', 'https://nigioikhatsi.net/thien/thien-tong-co-du-tri-tue-vo-han-va-suc-sang-tao.html',
    'https://inf.news/en/culture/7d0433fb73e25301eea2673203f9c992.html'],
  },
  {
    id: 3,
    label: 'Caodong',
    labelEn: 'Caodong',
    labelJa: 'Sôtô',
    color: 'blue',
    founder: 'Dongshan Liangjie - Caoshan Benji',
    description: 'Caodong',
    relation: '',
    doctrine: '',
    reference: ['https://chuahoiphuoc.net/nguon-goc-chung-bang-tong-tao-dong/', 'https://en.wikipedia.org/wiki/Caodong_school', 'https://en.wikipedia.org/wiki/Miyin_Temple',
      'https://zh.wikipedia.org/wiki/%E6%9B%B9%E6%B4%9E%E5%AE%97', 'https://nigioikhatsi.net/thien/thien-tong-co-du-tri-tue-vo-han-va-suc-sang-tao.html',
    'https://inf.news/en/culture/7d0433fb73e25301eea2673203f9c992.html'],
  },
  {
    id: 4,
    label: 'Fayan',
    labelEn: 'Fayan',
    labelJa: 'Hôgen',
    color: 'orange',
    founder: 'Fayan Wenyi',
    description: 'Fayan',
    relation: '',
    doctrine: '',
    reference: ['https://chuahoiphuoc.net/nguon-goc-chung-bang-tong-phap-nhan/', 'https://en.wikipedia.org/wiki/Fayan_school', 'https://en.wikipedia.org/wiki/Miyin_Temple',
      'https://zh.wikipedia.org/wiki/%E6%B3%95%E7%9C%BC%E5%AE%97', 'https://nigioikhatsi.net/thien/thien-tong-co-du-tri-tue-vo-han-va-suc-sang-tao.html',
    'https://inf.news/en/culture/7d0433fb73e25301eea2673203f9c992.html'],
  },
  {
    id: 5,
    label: 'Yunmen',
    labelEn: 'Yunmen',
    labelJa: 'Ummon',
    color: 'violet',
    founder: 'Yunmen Wenyan',
    description: 'Yunmen',
    relation: '',
    doctrine: '',
    reference: ['https://chuahoiphuoc.net/nguon-goc-chung-bang-tong-van-mon/', 'hhttps://en.wikipedia.org/wiki/Yunmen_Wenyan', 'https://en.wikipedia.org/wiki/Miyin_Temple',
      'https://zh.wikipedia.org/wiki/%E4%BA%91%E9%97%A8%E5%AE%97', 'https://nigioikhatsi.net/thien/thien-tong-co-du-tri-tue-vo-han-va-suc-sang-tao.html',
      'https://www.sohu.com/a/412189297_475956', 'https://thuvienhoasen.org/a9990/chuong-4-thien-pho-cap-va-bien-thai-thien-thoi-bac-tong',
      'https://vi.wikipedia.org/wiki/V%C3%A2n_M%C3%B4n_t%C3%B4ng', 'https://inf.news/en/culture/7d0433fb73e25301eea2673203f9c992.html'
    ],
  },
  {
    id: 6,
    label: 'Yangqi',
    labelEn: 'Yangqi',
    labelJa: 'Yangqi',
    color: 'green',
    founder: 'Yangqi Fanghui',
    description: 'Yangqi',
    relation: 'Linji',
    doctrine: '',
    reference: ['',
      'https://zh.wikipedia.org/wiki/%E6%9D%A8%E5%B2%90%E5%AE%97', 'https://vi.wikipedia.org/wiki/D%C6%B0%C6%A1ng_K%C3%AC_ph%C3%A1i'],
  },
  {
    id: 7,
    label: 'Huanglong',
    labelEn: 'Huanglong',
    labelJa: 'Huanglong',
    color: 'green',
    founder: 'Huanglong Huinan',
    description: 'Huanglong',
    relation: 'Linji',
    doctrine: '',
    reference: ['',
      'https://zh.wikipedia.org/wiki/%E9%BB%83%E9%BE%8D%E5%AE%97'],
  },
  {
    id: 100,
    label: 'others',
    color: 'indigo',
    description: '',
  },
  {
    id: 101,
    label: 'none',
    color: 'gray',
    description: '',
  },
]
export default sectDb;
