const CnCaodongMasterDb = [
  {
    id: '38.5.2',
    hasContent: true,
    eminent: true,
    name_en: 'Dongshan Liangjie',
    name_es: 'Dongshan Liangjie',
    name_de: 'Dongshan Liangjie',
    name_fr: 'Dongshan Liangjie',
    name_vi: 'Động Sơn Lương Giới (Ngộ Bổn Đại sư)',
    name_ru: 'Dongshan Liangjie',
    name_zh: '洞山 良价',
    name_ja: 'Tōzan Ryōkai',
    name_ko: '동산량개 Tongsan Lianggae',
    name_ar: 'Dongshan Liangjie',
    birth_death_time: ['807', '869'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Yunyan Tansheng'],
    successors: ['Yunju Daoying', 'Caoshan Benji'],
    disciples: ['Yunju Daoying', 'Caoshan Benji', 'Sushan Kuangren', 'Jiufeng Puman', 'Baoji Xiujing', 'Tiantong Weiqi',
      'Longya Judun', 'Qinshan Wensui', 'Yuezhou Qianfeng', 'Qinglin Shiqian', 'Jingdiao Xianzu', 'Yuezhou Qianfeng'],
    image: 'https://terebess.hu/zen/mesterek/Ma-Yuan_Dongshan.jpg',
    reference: ['https://hoavouu.com/a39664/ngu-luc-thien-su-dong-son-ngo-ban', 'https://pl.wikipedia.org/wiki/Dongshan_Liangjie',
      'https://drive.google.com/file/d/1SvmWiqhC8prbUZrvXV7WqnI7dVaddd98/view',
      'https://tangthuphathoc.net/thuy-chau-dong-son-luong-gioi-thien-su-ngu-luc',
      'https://blog.phapthihoi.org/gt-member/ts-dong-son-luong-gioi/'],
  },
  {
    id: '39.6.1',
    eminent: true,
    name_en: 'Caoshan Benji',
    name_es: 'Caoshan Benji',
    name_de: 'Caoshan Benji',
    name_fr: 'Caoshan Benji',
    name_vi: 'Tào Sơn Bản Tịch',
    name_ru: 'Caoshan Benji',
    name_zh: '曹山本寂',
    name_ja: 'Sōzan Honjaku',
    name_ko: 'Caoshan Benji',
    name_ar: 'Caoshan Benji',
    birth_death_time: ['840', '901'],
    records: '',
    sect: ['Caodong'],
    country: 'China',
    place: '-',
    teachers: ['Dongshan Liangjie'],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '39.6.9',
    hasContent: true,
    eminent: true,
    name_en: 'Yunju Daoying',
    name_es: 'Yunju Daoying',
    name_de: 'Yunju Daoying',
    name_fr: 'Yunju Daoying',
    name_vi: 'Vân Cư Đạo Ưng',
    name_ru: 'Yunju Daoying',
    name_zh: '雲居道膺',
    name_ja: 'Ungo Dōyō',
    name_ko: 'Yunju Daoying',
    name_ar: 'Yunju Daoying',
    birth_death_time: ['835', '902'],
    records: '',
    sect: ['Caodong'],
    country: 'China',
    place: '-',
    teachers: ['Dongshan Liangjie'],
    successors: ['Tong\'an Daopi'],
    disciples: ['Tongan Daopi', 'Taekyŏng Yŏŏm (K)', 'Sŏngak Hyŏngmi (K)', 'Chinch\'ŏl Iŏm (K)'],
    image: 'https://terebess.hu/zen/mesterek/woodcut/39-3.jpg',
    reference: ['https://terebess.hu/zen/mesterek/YunjuDaoying.html', 'https://en.wikipedia.org/wiki/Yunju_Daoying',
      'https://vi.wikipedia.org/wiki/V%C3%A2n_C%C6%B0_%C4%90%E1%BA%A1o_%C6%AFng', 'https://pl.wikipedia.org/wiki/Yunju_Daoying'],
  },
]
export default CnCaodongMasterDb;
