const CnGuiyangMasterDb = [
  {
    id: '37.4.4',
    hasContent: true,
    eminent: true,
    name_en: 'Guishan Lingyou',
    name_es: 'Guishan Lingyou',
    name_de: 'Guishan Lingyou',
    name_fr: 'Guishan Lingyou',
    name_vi: 'Quy Sơn Linh Hựu (Đại Viên Đại sư)',
    name_ru: 'Guishan Lingyou',
    name_zh: '潙山靈祐',
    name_ja: 'Isan Reiyû',
    name_ko: 'Guishan Lingyou',
    name_ar: 'Guishan Lingyou',
    birth_death_time: ['771', '853'],
    records: '',
    sect: ['Guishan'],
    country: 'China',
    place: 'Quy Sơn - Đàm Châu',
    teachers: ['Tianhuang Daowu'],
    successors: ['Yangshan Huiji'],
    disciples: ['Yangshan Huiji', 'Lingyun Zhiqin', 'Xiangyan Zhixian'],
    image: '/images/avatar.png',
    collections: ['https://thuvienhoasen.org/images/file/OI6imJ1G0QgQAJ8X/quy-son-ngu-luc.pdf'],
    reference: ['https://terebess.hu/zen/guishan.html', 'https://en.wikipedia.org/wiki/Guishan_Lingyou', 'https://vi.wikipedia.org/wiki/Quy_S%C6%A1n_Linh_H%E1%BB%B1u', 'http://thuongchieu.net/index.php/phapthoai/suphu/4804-tslinhhuu', 'https://phatphapungdung.com/phap-bao/ngu-luc-cua-thien-su-dam-chau-quy-son-linh-huu-164038.html', 'https://thuvienhoasen.org/images/file/OI6imJ1G0QgQAJ8X/quy-son-ngu-luc.pdf'],
  },
  {
    id: '38.5.4',
    eminent: true,
    name_en: 'Yangshan Huiji',
    name_es: 'Yangshan Huiji',
    name_de: 'Yangshan Huiji',
    name_fr: 'Yangshan Huiji',
    name_vi: 'Ngưỡng Sơn Huệ Tịch',
    name_ru: 'Yangshan Huiji',
    name_zh: '仰山慧寂',
    name_ja: 'Kyōzan Ejaku',
    name_ko: '안산혜적 Angsan Hyejŏk',
    name_ar: 'Yangshan Huiji',
    birth_death_time: ['807', '883'],
    records: '',
    sect: ['Guishan'],
    country: 'China',
    place: '-',
    teachers: ['Guishan Lingyou'],
    successors: ['Nanta Guangyong'],
    disciples: ['Nanta Guangyong'],
    image: '/images/avatar.png',
    reference: [''],
  },
]
export default CnGuiyangMasterDb;
