const CnLv58MasterDb = [
  {
    id: '90.57.1',
    name_en: 'Yuelang Quanding',
    name_es: 'Yuelang Quanding',
    name_de: 'Yuelang Quanding',
    name_fr: 'Yuelang Quanding',
    name_ru: 'Yuelang Quanding',
    name_ar: 'Yuelang Quanding',
    name_ko: 'Yuelang Quanding',
    name_ja: 'Yuelang Quanding',
    name_zh: '月朗全定',
    name_vi: 'Nguyệt Lãng',
    other_name_vi: '',
    nickname_vi: 'Hư Vân',
    worship_tower: '',
    birth_death_time: ['1855', '1915'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: 'Gaomin Temple/Monastery (高旻寺), Hanjiang District, Yangzhou, China',
    teachers: [''],
    successors: ['Laiguo Miaoshu'],
    disciples: ['Laiguo Miaoshu'],
    image: '/images/avatar.png',
    reference: ['https://www.mdpi.com/2077-1444/15/5/627', 'https://terebess.hu/zen/mesterek/7.pdf'],
  },
]
export default CnLv58MasterDb;
