const CnLv32MasterDb = [
  {
    id: '65.32.1',
    hasContent: true,
    name_en: 'Wuyi Yuanlai',
    other_name_en: 'Boshan Yuanlai',
    name_ja: 'Mui Genrai',
    name_zh: '無異元來',
    other_name_zh: '博山, 大艤)',
    name_vi: 'Vô Dị Nguyên Lai',
    other_name_vi: 'Bác Sơn Nguyên Lai',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1575', '1630'],
    epoch: '',
    records: '',
    sect: ['Caodong', 'Boshan Line (博山糸)'],
    country: '🇨🇳',
    place: 'Boshan (博山)',
    teachers: ['Wuming Huijing'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://phatgiao.org.vn/tu-dien-phat-hoc-online/vo-di-nguyen-lai-k6100.html', 'https://terebess.hu/zen/boshan.html',
    'https://vn.thamtosuthien.net/about/Thien-su-Bac-son.phattrien.net', 'https://londonchanmeditation.org/lineage/'],
  },
  {
    id: '65.32.2',
    hasContent: true,
    name_en: 'Huitai Yuanjing',
    name_ja: 'Maidai Genkyō',
    name_zh: '晦臺元鏡',
    name_vi: 'Hối Đài Nguyên Cảnh',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['25/6/1577', '13/7/1630'],
    epoch: '',
    records: '',
    sect: ['Caodong'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Wuming Huijing'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/H%E1%BB%91i_%C4%90%C3%A0i_Nguy%C3%AAn_C%E1%BA%A3nh', 'https://terebess.hu/zen/mesterek/HuitaiYuanjing.html'],
  },
  {
    id: '65.32.3',
    hasContent: true,
    name_en: 'Yuanjue Yuanxian',
    other_name_en: 'Gushan Yuanxian',
    name_ja: 'Yōkaku Genken',
    name_zh: '永覺元賢 (鼓山)',
    other_name_zh: '鼓山',
    name_vi: 'Vĩnh Giác Nguyên Hiền',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1578', '1657'],
    epoch: '',
    records: '',
    sect: ['Caodong', 'Gushan Line (鼓山糸)'],
    country: '🇨🇳',
    place: 'Gushan (鼓山)',
    teachers: ['Wuming Huijing'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/V%C4%A9nh_Gi%C3%A1c_Nguy%C3%AAn_Hi%E1%BB%81n', 'https://terebess.hu/zen/mesterek/YuanjueYuanxian.html'],
  },
  {
    id: '65.32.4',
    name_en: 'Xiaoyan Debao',
    name_ja: 'Getsushin Tokuhō',
    name_zh: '月心德寶',
    name_vi: 'Tiếu Nham Đức Bảo',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1512', '1581'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: '🇨🇳',
    place: 'Quan Âm Am (觀音庵), Yến Đô (燕都, Tỉnh Hà Bắc)',
    teachers: ['Wuwen Mingcong'],
    successors: ['Yunqi Zhuhong'],
    disciples: ['Yunqi Zhuhong', 'Huanyou Zhenchuan'],
    image: '/images/avatar.png',
    reference: [''],
  },
]
export default CnLv32MasterDb;
