const CnLv37MasterDb = [
  {
    id: '70.37.1',
    name_en: 'Mu’an Xingtao',
    name_ja: 'Mokuan Shōtō',
    name_zh: '木庵性瑫',
    other_name_zh: '木菴性瑫',
    name_vi: 'Mục An Xingtao',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['16/3/1611', '6/3/1684'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Yinyuan Longqi'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '70.37.2',
    name_en: '',
    name_ja: '',
    name_zh: '',
    name_vi: '',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: '🇨🇳',
    place: '-',
    teachers: [''],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: [''],
  },
]
export default CnLv37MasterDb;
