const CnLv35MasterDb = [
  {
    id: '68.35.1',
    name_en: 'Miyun Yuanwu',
    name_ja: 'Mitsu’un Engo',
    name_zh: '蜜雲円悟',
    name_vi: 'Miyun Yuanwu',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1566', '1642'],
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: 'China',
    place: '',
    teachers: ['Huanyou Zhengchuan'],
    successors: ['Feiyin Tongrong'],
    disciples: ['Feiyin Tongrong'],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '68.35.2',
    name_en: '',
    name_ja: '',
    name_zh: '',
    name_vi: '',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: 'China',
    place: '',
    teachers: ['Huanyou Zhengchuan'],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: [''],
  },
]
export default CnLv35MasterDb;
