const CnLv35MasterDb = [
  {
    id: '68.35.1',
    name_en: 'Feiyin Tongrong',
    name_ja: 'Hi’in Tsuyo',
    name_zh: '費隠通容',
    name_vi: 'Feiyin Tongrong',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1593', '1661'],
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: 'China',
    place: '',
    teachers: ['Miyun Yuanwu'],
    successors: ['Yinyuan Longqi'],
    disciples: ['Yinyuan Longqi'],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '68.35.2',
    name_en: '',
    name_ja: '',
    name_zh: '',
    name_vi: '',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    records: '',
    sect: [''],
    country: 'China',
    place: '',
    teachers: [''],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: [''],
  },
]
export default CnLv35MasterDb;
