const CnLv2MasterDb = [
  {
    id: '35.2.1',
    name_en: 'Shitou Xiqian',
    name_es: 'Shitou Xiqian',
    name_de: 'Shitou Xiqian',
    name_fr: 'Shitou Xiqian',
    name_vi: 'Thạch Đầu Hi Thiên',
    name_ru: 'Shitou Xiqian',
    name_zh: 'Shitou Xiqian',
    name_ja: 'Shitou Xiqian',
    name_ko: 'Shitou Xiqian',
    name_ar: 'Shitou Xiqian',
    birth_death_time: ['700', '790'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: 'Nantai Temple, Nanyue Heng mountain, Hunan',
    teachers: ['Dajian Huineng', 'Qingyuan Xingsi'],
    successors: ['Yaoshan Weiyan'],
    disciples: ['Yaoshan Weiyan', 'Kinh triệu Thi Lợi', 'Tianhuang Daowu', 'Danxia Tianran', 'Dadian Baotong',
      'Chiêu đề tại Đà châu Tuệ Lãng', 'Hưng quốc tại Trường sa Chấn Lãng', 'Đàm châu Đại Xuyên',
      'Phần châu Thạch Thê', 'Pháp môn tại Phụng tường Phật Đà', 'Đàm châu Hoa Lâm', 'Triều châu Đại Điên',
      'Đàm châu Khoáng – Trường Tỳ', 'Thủy Không', 'Hải lăng Đại Biện', 'Chử Kinh', 'Hành châu Đạo Tiên',
      'Hán châu Thường Thanh', 'Phước châu Toái Thạch', 'Thương châu Thương Lãnh', 'Thường châu Nghĩa Hưng',
    ],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Shitou_Xiqian.jpg/220px-Shitou_Xiqian.jpg',
    reference: [''],
  },
  {
    id: '35.2.2',
    name_en: 'Mazu Daoyi',
    name_es: 'Mazu Daoyi',
    name_de: 'Mazu Daoyi',
    name_fr: 'Mazu Daoyi',
    name_vi: 'Mã Tổ Đạo Nhất (Đại Tịch Đại sư)',
    name_ru: 'Mazu Daoyi',
    name_zh: '馬祖道一',
    name_ja: 'Baso Dōitsu',
    name_ko: 'Mazu Daoyi',
    name_ar: 'Mazu Daoyi',
    birth_death_time: ['709', '788'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: 'Gonggong mountain, Nankang, Ganzhou, southern Jiangxi',
    teachers: ['Nanyue Huairang'],
    successors: ['-'],
    disciples: ['Baizhang Huaihai', 'Dazhu Huihai', 'Damei Fachang', 'Ehu Dayi', 'Xitang Zhizang',
      'Nanquan Puyuan', 'Fenzhou Wuye', 'Guizong Zhichang', 'Zhangjing Huaiyun', 'Yanguan Qian',
      'Layman Pangyun', 'Mayu Baoche', 'Panshan Baoji', 'Luzu Baoyun', 'Zhongyi Hongen', 'Wujiu Youxuan',
      'Zhangjing Huaihui', 'Panshan Baoji',
      'An phong Hoài Không', 'Bách Linh', 'Bách nham Ninh Triết',
 'Bách Trượng Duy Chính', 'Bạch Hổ Pháp Tuyên', 'Bản Khê', 'Cam tuyền Chí Hiền',
 'Càn Nguyên Huy', 'Côn Sơn Định Giác', 'Cổ Tự', 'Diêm quan Tề An',
 'Dương Châu Trí Thông', 'Dương kỳ Chân Thúc', 'Đài châu Thường Triệt Bách nham', 'Đại Dương',
 'Đại Dương Hy Hạng', 'Đại hội Đạo Ngộ', 'Đảnh châu Hồng Ân Trung ấp', 'Động An',
 'Giang Tây Bề Thọ', 'Giang tây Nhượng Bắc lan', 'Hiện sơn Định Khánh', 'Hoa châu Sách',
 'Hoa lâm Thiện Giác', 'Hà Trung Bảo Khánh', 'Hà Trung Hoài Tắc', 'Hàng châu Trí Tạng',
 'Hàng châu Tự Mãn Ly thôn ', 'Hàng châu Đả Địa', 'Hán nam Lương tân', 'Hưng Bình',
 'Hạo Anh', 'Hải lăng Khánh Vân', 'Hồ nam Như Hội', 'Hồng châu Huyền Hư',
 'Hồng loa Sơn', 'Kim Ngưu', 'Kim quật Duy Trực', 'Kinh châu Bảo Tích',
 'Kinh châu Linh Nhu', 'Kinh châu Thảo Đường', 'Kinh nam Đạo Bản Bảo chánh', 'Kinh triệu Duy Khoan',
 'Kinh triệu Giác Bình', 'Kinh triệu Hoài Thao', 'Kinh triệu Sùng',
 'Kinh Triệu Trí Tạng', 'La phù Tư Quảng', 'La phù Đạo Hạnh', 'Liên châu Nguyên Đề',
 'Long nha Viên Sướng', 'Long Sơn', 'Luyện sơn Thần Ngoạn', 'Lã hậu Ninh Bí',
 'Lô sơn Pháp Tạng', 'Lạc kinh Như Mãn Phật quang ', 'Lặc đàm Duy Kiến', 'Lặc đàm Pháp Hội',
 'Lặc đàm Thường Hưng', 'Lễ châu Quảng Trừng Đại đồng', 'Lễ châu Trí Thông', 'Lễ châu Đạo Hạnh Minh khê',
 'Lỗ tổ Bảo Vân', 'Lộ phủ Nguyên Lễ', 'Lộ Phủ Pháp Nhu', 'Lợi Sơn',
 'Mã đầu Thần Tạng', 'Mông Khê', 'Mặc Giản', 'Mặc Nhãn',
 'Mễ Lãnh', 'Nam nguyên Đại Minh', 'Nam nhạc Trí Châu', 'Nghĩa hưng Thắng Biện',
 'Ngũ tiết Linh Mặc', 'Ngũ đài Đặng ẩn Phong', 'Ngọc châu Hồng Đàm', 'Ngọc châu Vô Đẳng',
 'Ngọc mổ Tiêu Nhiên', 'Ngọc đài Duy Nhiên', 'Nhũ Nguyên', 'Ô Cửu',
 'Phong sơn Hồng Tuấn', 'phu Hà trung Pháp Tạng', 'Phù Bôi', 'Phù dung Thái Dục',
 'Phước Khê', 'Phật Áo', 'Phục ngưu Tự Tại', 'Quang minh Phổ Mãn',
 'Quy dương Vô Liễu', 'Quật sơn Đạo Viên', 'Sam sơn Trí Kiên', 'Song lãnh Đạo Phương',
 'Sùng Thái', 'Tam giác Tổng Ấn', 'Thiên mục Minh Giác', 'Thiều châu Thanh Hạ',
 'Thường châu Minh Cán', 'Thạch củng Tuệ Tạng', 'Thạch Cửu', 'Thạch Lâm',
 'Thạch sương Đại Thiện', 'Thủy Lão', 'Thủy Đường', 'Tiêu Diêu',
 'Trì Châu Đàm Ký Hội Sơn', 'Tuyền Châu Tuệ Trung', 'Tây Sơn Chủ tọa Lượng', 'Tây Viên Đàm Tạng',
 'Tùng Sơn', 'Tùy châu Đại sư Hồng Sơn', 'Tú Khê', 'Tương Châu Thường Kiên',
 'Tượng nguyên Hoài Thản', 'Tắc Xuyên', 'Tề châu Đạo Nham', 'Tề Phong',
 'Tử Ngọc Đạo Thông', 'Tử Âm Duy Kiến', 'Việt Châu Duy Hiến', 'Vân Thủy Tĩnh Tông',
 'Vân Tú Thần Giám', 'Vương Cốc hạnh Minh', 'Xứ châu Pháp Tạng', 'Xứ châu Xitang Zhicang',
    ],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: ['https://terebess.hu/zen/mazu.html'],
  },
  {
    id: '35.2.3',
    hasContent: true,
    name_en: 'Danyuan Yingzhen',
    name_es: 'Danyuan Yingzhen',
    name_de: 'Danyuan Yingzhen',
    name_fr: 'Danyuan Yingzhen',
    name_vi: 'Đam Nguyên Ứng Chân',
    name_ru: 'Danyuan Yingzhen',
    name_zh: '耽源應真',
    name_ja: 'Tangen Ōshin',
    name_ko: "탐원응진 T'amwŏn Ŭngjin",
    name_ar: 'Danyuan Yingzhen',
    birth_death_time: ['8th cen.', '9th cen.'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: 'Danyuan mountain, Qizhou',
    teachers: ['Nanyang Huizhong'],
    successors: [''],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '35.2.4',
    name_en: 'Cizhou Faru',
    name_es: 'Cizhou Faru',
    name_de: 'Cizhou Faru',
    name_fr: 'Cizhou Faru',
    name_vi: 'Từ Châu Pháp Như',
    name_ru: 'Cizhou Faru',
    name_zh: '磁州法如',
    name_ja: 'Cizhou Faru',
    name_ko: 'Cizhou Faru',
    name_ar: 'Cizhou Faru',
    birth_death_time: ['723', '811'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Heze Shenhui'],
    successors: ['Kinh Nam Duy Trung'],
    disciples: ['Kinh Nam Duy Trung'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '35.2.5',
    name_en: 'Wutai Wuming',
    name_es: 'Wǔtái Wúmíng',
    name_de: 'Wǔtái Wúmíng',
    name_fr: 'Wǔtái Wúmíng',
    name_vi: 'Ngũ Đài Vô Danh',
    name_ru: 'Wǔtái Wúmíng',
    name_zh: '五臺無名',
    name_ja: 'Godai Mumyō',
    name_ko: 'Wǔtái Wúmíng',
    name_ar: 'Wǔtái Wúmíng',
    birth_death_time: ['722', '793'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Heze Shenhui'],
    successors: [''],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '35.2.6',
    name_en: 'Dàoxuán',
    name_es: 'Dàoxuán',
    name_de: 'Dàoxuán',
    name_fr: 'Dàoxuán',
    name_vi: 'Đạo Tuyền',
    name_ru: 'Dàoxuán',
    name_zh: '道璿',
    name_ja: 'Dōsen',
    name_ko: 'Dàoxuán',
    name_ar: 'Dàoxuán',
    birth_death_time: ['702', '760'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Songshan Puji'],
    successors: [''],
    disciples: ['Hành Biểu (行表)'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '35.2.7',
    name_en: 'Nangaku Myōsan',
    name_es: 'Nangaku Myōsan',
    name_de: 'Nangaku Myōsan',
    name_fr: 'Nangaku Myōsan',
    name_vi: 'Nam Nhạc Minh Toàn',
    name_ru: 'Nangaku Myōsan',
    name_zh: '南嶽明瓚',
    name_ja: 'Nangaku Myōsan',
    name_ko: 'Nangaku Myōsan',
    name_ar: 'Nangaku Myōsan',
    birth_death_time: ['722', '793'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Songshan Puji'],
    successors: [''],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '35.2.8',
    name_en: 'Wúxiàng',
    name_es: 'Wúxiàng',
    name_de: 'Wúxiàng',
    name_fr: 'Wúxiàng',
    name_vi: 'Vô Tướng',
    name_ru: 'Wúxiàng',
    name_zh: '無相',
    name_ja: 'Musō',
    name_ko: 'Wúxiàng',
    name_ar: 'Wúxiàng',
    birth_death_time: ['684', '762'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Chùjì (普寂)'],
    successors: [''],
    disciples: ['Wúzhù (無住)'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '35.2.9',
    name_en: '峻極',
    name_es: '峻極',
    name_de: '峻極',
    name_fr: '峻極',
    name_vi: 'Tuấn Cực',
    name_ru: '峻極',
    name_zh: '峻極',
    name_ja: '峻極',
    name_ko: '峻極',
    name_ar: '峻極',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Phá Táo Đọa (破竈墮)'],
    successors: [''],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '35.2.10',
    name_en: 'Hōji',
    name_es: 'Hōji',
    name_de: 'Hōji',
    name_fr: 'Hōji',
    name_vi: 'Ngưu Đầu Pháp Trì',
    name_ru: 'Hōji',
    name_zh: '法持',
    name_ja: 'Hōji',
    name_ko: 'Hōji',
    name_ar: 'Hōji',
    birth_death_time: ['635', '702'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Ehō (慧方)'],
    successors: [''],
    disciples: ['Chii (智威) - Ngưu Đầu Trí Oai'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '35.2.11',
    name_en: '惟政',
    name_es: '惟政',
    name_de: '惟政',
    name_fr: '惟政',
    name_vi: 'Duy Chính',
    name_ru: '惟政',
    name_zh: '惟政',
    name_ja: '惟政',
    name_ko: '惟政',
    name_ar: '惟政',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Songshan Puji'],
    successors: [''],
    disciples: ['Chí Chân (志眞)'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '35.2.12',
    name_en: 'Jingzhong Wuxiang',
    name_es: 'Jingzhong Wuxiang',
    name_de: 'Jingzhong Wuxiang',
    name_fr: 'Jingzhong Wuxiang',
    name_vi: 'Ích Châu Vô Tướng / Tịnh Chúng Vô Tương',
    name_ru: 'Jingzhong Wuxiang',
    name_zh: '浄衆無相',
    name_ja: 'Jōshū Musō',
    name_ko: '정중무상 Chǒngjung Musang',
    name_ar: 'Jingzhong Wuxiang',
    birth_death_time: ['684/680', '762/765'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Zizhou Chuji'],
    successors: [''],
    disciples: ['Jingzhong Shenhui', 'Baotang Wuzhu', 'Sang-shi', 'Tongchuan Ji'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: ['https://pl.wikipedia.org/wiki/Jingzhong_Wuxiang', 'https://terebess.hu/zen/mesterek/Musang.html'],
  },
  {
    id: '35.2.13',
    name_en: 'Cao bưu Đàm Ảnh',
    name_es: 'Cao bưu Đàm Ảnh',
    name_de: 'Cao bưu Đàm Ảnh',
    name_fr: 'Cao bưu Đàm Ảnh',
    name_vi: 'Cao bưu Đàm Ảnh',
    name_ru: 'Cao bưu Đàm Ảnh',
    name_zh: 'Cao bưu Đàm Ảnh',
    name_ja: 'Cao bưu Đàm Ảnh',
    name_ko: 'Cao bưu Đàm Ảnh',
    name_ar: 'Cao bưu Đàm Ảnh',
    birth_death_time: ['?', '?'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '',
    teachers: ['Lục hợp Đại Giác'],
    successors: [''],
    disciples: ['Thái sơn Minh Luyện'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
]
export default CnLv2MasterDb;
