const CnLv0MasterDb = [
  {
    id: '29',
    generation: '29',
    name_en: 'Dazu Huike',
    name_es: 'Dazu Huike',
    name_de: 'Dazu Huike',
    name_fr: 'Dazu Huike',
    name_vi: 'Huệ Khả (Nhị Tổ)',
    name_ru: 'Dazu Huike',
    name_zh: '道育慧可 (大祖慧可)',
    name_ja: 'Dazu Huike',
    name_ko: 'Dazu Huike',
    name_ar: 'Dazu Huike',
    birth_death_time: ['487?', '593'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Bodhidharma'],
    successors: ['Jianzhi Sengcan'],
    disciples: ['Jianzhi Sengcan'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Huike_thinking.jpg/220px-Huike_thinking.jpg',
    reference: [''],
    youtubeId: [''],

  },
  {
    id: '30',
    generation: '30',
    name_en: 'Jianzhi Sengcan',
    name_es: 'Jianzhi Sengcan',
    name_de: 'Jianzhi Sengcan',
    name_fr: 'Jianzhi Sengcan',
    name_vi: 'Tăng Xán (Tam Tổ)',
    name_ru: 'Jianzhi Sengcan',
    name_zh: '鑑智僧璨',
    name_ja: 'Jianzhi Sengcan',
    name_ko: 'Jianzhi Sengcan',
    name_ar: 'Jianzhi Sengcan',
    birth_death_time: ['496?', '606'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Dazu Huike'],
    successors: ['Dayi Daoxin'],
    disciples: ['Dayi Daoxin'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Sengcan.jpg/220px-Sengcan.jpg',
    reference: [''],
    youtubeId: [''],

  },
  {
    id: '31.1',
    generation: '31',
    name_en: 'Dayi Daoxin',
    name_es: 'Dayi Daoxin',
    name_de: 'Dayi Daoxin',
    name_fr: 'Dayi Daoxin',
    name_vi: 'Đạo Tín (Tứ Tổ)',
    name_ru: 'Dayi Daoxin',
    name_zh: '道信',
    name_ja: 'Dōshin',
    name_ko: 'Dayi Daoxin',
    name_ar: 'Dayi Daoxin',
    birth_death_time: ['580', '651'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Jianzhi Sengcan'],
    successors: ['Daman Hongren'],
    disciples: ['Daman Hongren'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/5/59/Daoxin.jpg',
    reference: [''],
    youtubeId: [''],

  },
  {
    id: '32.1',
    generation: '32',
    name_en: 'Daman Hongren',
    name_es: 'Daman Hongren',
    name_de: 'Daman Hongren',
    name_fr: 'Daman Hongren',
    name_vi: 'Hoằng Nhẫn (Ngũ Tổ)',
    name_ru: 'Daman Hongren',
    name_zh: '弘忍',
    name_ja: 'Kōnin',
    name_ko: 'Daman Hongren',
    name_ar: 'Daman Hongren',
    birth_death_time: ['601', '674'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Dayi Daoxin'],
    successors: ['Dajian Huineng'],
    disciples: ['Dajian Huineng'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Hongren.jpg/220px-Hongren.jpg',
    reference: [''],
    youtubeId: [''],

  },
  {
    id: '32.2',
    generation: '32',
    name_en: 'Niutou Farong',
    name_es: 'Niutou Farong',
    name_de: 'Niutou Farong',
    name_fr: 'Niutou Farong',
    name_vi: 'Ngưu Đầu Pháp Dung',
    name_ru: 'Niutou Farong',
    name_zh: '牛頭 法融',
    name_ja: 'Gozu Hōyū',
    name_ko: 'Niutou Farong',
    name_ar: 'Niutou Farong',
    birth_death_time: ['594', '657'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Dayi Daoxin'],
    successors: ['-'],
    disciples: ['Niutou Chigan'],
    image: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRkU91_ZqrRFlSID55wIXjbUlrgozQfeOM1bN6NR53fUSMNWrwJ',
    reference: [''],
    youtubeId: [''],

  },
  {
    id: '33.1',
    generation: '33',
    name_en: 'Dajian Huineng (Liuzu)',
    name_es: 'Dajian Huineng (Sexto Patriarca)',
    name_de: 'Dajian Huineng (Sechster Patriarch)',
    name_fr: 'Dajian Huineng (sixième patriarche)',
    name_vi: 'Huệ Năng (Lục Tổ)',
    name_ru: 'Дацзянь Хуэйнэн (Шестой Патриарх)',
    name_zh: '大鑒惠能 (六祖)',
    name_ja: '大建恵能 (Daikan Enō)',
    name_ko: '혜능 (Daegam Hyeneung) (육조)',
    name_ar: 'داجيان هوينينج (البطريرك السادس)',
    birth_death_time: ['638', '713'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: 'Nanhua temple, Shaoguan, Guangdong',
    teachers: ['Daman Hongren'],
    successors: ['-'],
    disciples: ['Qingyuan Xingsi', 'Shitou Xiqian', 'Nanyue Huairang',],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Huineng.jpg/220px-Huineng.jpg',
    reference: [''],
    youtubeId: [''],

  },
  {
    id: '33.2',
    generation: '33',
    name_en: 'Niu-tou Chigan',
    name_es: 'Niu-tou Chigan',
    name_de: 'Niu-tou Chigan',
    name_fr: 'Niu-tou Chigan',
    name_vi: 'Ngưu Đầu Trí Nham',
    name_ru: 'Niu-tou Chigan',
    name_zh: '牛頭 智巖',
    name_ja: 'Gozu Chigan',
    name_ko: 'Niu-tou Chigan',
    name_ar: 'Niu-tou Chigan',
    birth_death_time: ['600', '677'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Niu-tou Fa-jung'],
    successors: ['-'],
    disciples: ['Ehō'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
    youtubeId: [''],

  },
  {
    id: '33.3',
    generation: '33',
    hasContent: true,
    name_en: 'Yuquan Shenxiu',
    name_es: 'Yuquan Shenxiu',
    name_de: 'Yuquan Shenxiu',
    name_fr: 'Yuquan Shenxiu',
    name_vi: 'Ngọc Tuyền Thần Tú ',
    name_ru: 'Yuquan Shenxiu',
    name_zh: '玉泉 神秀',
    name_ja: 'Jinshū',
    name_ko: 'Yuquan Shenxiu',
    name_ar: 'Yuquan Shenxiu',
    birth_death_time: ['605/606', '706'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: 'Jade Spring Temple (玉泉寺) - Yuquan Tiantai (玉泉天台), Yuquan Mountain (玉泉山), Jingxi Prefecture (荆溪府), within the scope of Dangyang, Hubei Province',
    teachers: ['Daman Hongren'],
    successors: [''],
    disciples: ['Dōsen (道璿)', 'Tung Sơn Huệ Tịch (嵩山慧寂)', 'Kinh Triệu Nghĩa Phước (京兆 義福)', 'Yìfú', 'Kính Hiền', 'Pǔjì', 'Huệ Minh'],
    image: 'https://upload.wikimedia.org/wikipedia/en/2/2d/Shenxiu-invert.jpg',
    reference: [''],
    youtubeId: [''],

  },
  {
    id: '33.4',
    generation: '33',
    name_en: '慧安 (Huệ An)',
    name_es: '慧安',
    name_de: '慧安',
    name_fr: '慧安',
    name_vi: 'Huệ An',
    name_ru: '慧安',
    name_zh: '慧安',
    name_ja: '慧安',
    name_ko: '慧安',
    name_ar: '慧安',
    birth_death_time: ['582', '709'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '',
    teachers: ['Daman Hongren'],
    successors: [''],
    disciples: ['Phá Táo Đọa', 'Đạo Lượng'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
    youtubeId: [''],

  },
  {
    id: '33.5',
    generation: '33',
    name_en: 'Zhishen',
    name_es: 'Zhìshēn',
    name_de: 'Zhìshēn',
    name_fr: 'Zhìshēn',
    name_vi: 'Trí Sân',
    name_ru: 'Zhìshēn',
    name_zh: '智詵',
    name_ja: 'Chisen',
    name_ko: 'Zhìshēn',
    name_ar: 'Zhìshēn',
    birth_death_time: ['609', '702'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '',
    teachers: ['Daman Hongren'],
    successors: [''],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
    youtubeId: [''],

  },
]
export default CnLv0MasterDb;
