const CnLv3MasterDb = [
  {
    id: '36.3.1',
    name_en: 'Kinh Nam Duy Trung',
    name_ja: 'Kinh Nam Duy Trung',
    name_zh: '荊南惟忠',
    name_vi: 'Kinh Nam Duy Trung',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Cizhou Faru'],
    successors: ['Toại Châu Đạo Viên'],
    disciples: ['Toại Châu Đạo Viên'],
    image: '/images/avatar.png',
    reference: ['https://ngulucthien.com/thien-su-duy-trung/'],
  },
  {
    id: '36.3.2',
    hasContent: true,
    isEminent: true,
    name_en: 'Yaoshan Weiyan',
    name_ja: 'Yakusan Igen',
    name_zh: '藥山惟儼',
    name_vi: 'Dược Sơn Duy Nghiễm',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['745', '827'],
    epoch: '',
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Shitou Xiqian', 'Mazu Daoyi'],
    successors: [],
    disciples: ['Yunyan Tansheng', 'Chuanzi Decheng', 'Daowu Yuanzhi'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/b/bc/Yaoshan_Weiyan_Image.jpg',
    reference: ['https://pl.wikipedia.org/wiki/Yaoshan_Weiyan', 'https://terebess.hu/zen/yaoshan.html'],
  },
  {
    id: '36.3.3',
    hasContent: true,
    name_en: 'Tianhuang Daowu',
    name_ja: 'Tennō Dōgō',
    name_zh: '天皇道悟',
    name_vi: 'Thiên Hoàng Đạo Ngộ',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['748', '807'],
    epoch: '',
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Shitou Xiqian', 'Jingshan Faqin'],
    successors: ['Longtan Chongxin'],
    disciples: ['Longtan Chongxin'],
    image: '/images/avatar.png',
    reference: ['https://ngulucthien.com/thien-su-dao-ngo-747-806/'],
  },
  {
    id: '36.3.4',
    hasContent: true,
    name_en: 'Dadian Baotong',
    name_ja: 'Daiten Hōtsū',
    name_zh: '大顛寶通',
    name_vi: 'Đại Điên Bảo Thông',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['732', '824'],
    epoch: '',
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Shitou Xiqian'],
    successors: ['Sanping Yizhong'],
    disciples: ['Sanping Yizhong'],
    image: '/images/avatar.png',
    reference: ['https://ngulucthien.com/thien-su-baothong-dai-dien-732-824/', 'https://vi.wikipedia.org/wiki/%C4%90%E1%BA%A1i_%C4%90i%C3%AAn_B%E1%BA%A3o_Th%C3%B4ng',
    'https://giacngo.vn/thien-su-dai-dien-va-han-vu-post211.html', 'https://thuvienhoasen.org/a28617/han-du-thien-su-dai-dien-bao-thong',
      'https://thienphatgiao.org/thien-su-trung-hoa-t1p12/'
    ],
  },
  {
    id: '36.3.5',
    hasContent: true,
    name_en: 'Danxia Tianran',
    name_ja: 'Ranka Rennen',
    other_name_ja: 'Tanka Tennen',
    name_zh: '丹霞天然',
    name_vi: 'Đan Hà Thiên Nhiên',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['739', '824'],
    epoch: '',
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Shitou Xiqian', 'Mazu Daoyi'],
    successors: ['Cuiwei Wuxue'],
    disciples: ['Cuiwei Wuxue'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/%C4%90an_H%C3%A0_Thi%C3%AAn_Nhi%C3%AAn', 'https://blog.phapthihoi.org/tu-dien-phat-giao/don-ha-thien-nhien/', 'https://blog.phapthihoi.org/gt-member/ts-don-ha-thien-nhien/', 'https://phatgiao.org.vn/tu-dien-phat-hoc-online/don-ha-thien-nhien-k3922.html', 'https://quangduc.com/a71933/35-thien-su-don-ha-thien-nhien', 'https://quangduc.com/a69744/thien-su-don-ha-thien-nhien-739-824-doi-thu-3-sau-luc-to-hue-nang'],
  },
  {
    id: '36.3.6',
    hasContent: true,
    name_en: 'Baizhang Huaihai',
    name_ja: 'Hyakujō Ekai',
    name_zh: '百丈懷海',
    name_vi: 'Bá Trượng Hoài Hải',
    other_name_vi: 'Bách Trượng Hoài Hải',
    nickname_vi: 'Ðại Trí',
    worship_tower: '',
    birth_death_time: ['720', '814'],
    epoch: '',
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Mazu Daoyi'],
    successors: ['Huangbo Xiyun'],
    disciples: ['Huangbo Xiyun', 'Guishan Lingyou', 'Baizhang Niepan / Fazheng', 'Guishan Da’an',
      'Wufeng Changguan', 'Guling Shencan', 'Guannan Daochang'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/B%C3%A1ch_Tr%C6%B0%E1%BB%A3ng_Ho%C3%A0i_H%E1%BA%A3i'],
  },
  {
    id: '36.3.7',
    name_en: 'Wúzhù',
    name_ja: 'Mujū',
    name_zh: '無住',
    name_vi: 'Vô Trụ',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['714', '774'],
    epoch: '',
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Wúxiàng (無相)'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '36.3.8',
    name_en: '志眞',
    name_ja: '志眞',
    name_zh: '志眞',
    name_vi: 'Chí Chân',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Duy Chính (惟政)'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '36.3.10',
    name_en: 'Niutou Zhiwei',
    name_ja: 'Niutou Zhiwei',
    name_zh: '智威 ',
    name_vi: 'Ngưu Đầu Trí Oai',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['646', '722'],
    epoch: '',
    records: '',
    sect: ['Niutou (Oxhead)'],
    country: 'China',
    place: '-',
    teachers: ['Niutou Fazhi-'],
    successors: ['Helin Xuansu'],
    disciples: ['Echū - Ngưu Đầu Tuệ Trung', 'Helin Xuansu', 'Tuyên Châu An quốc Huyền Dĩnh', 'Thư châu Sùng Tuệ'],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '36.3.11',
    hasContent: true,
    name_en: 'Ehu Dayi',
    name_ja: 'Gako Taigi',
    name_zh: '鵝湖大義',
    name_vi: 'Nga Hồ Đại Nghĩa',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['746', '818'],
    epoch: '',
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Mazu Daoyi'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Ehu_Dayi', 'https://phatgiao.org.vn/tu-dien-phat-hoc-online/dai-nghia-k32793.html'],
  },
  {
    id: '36.3.12',
    hasContent: true,
    name_en: 'Damei Fachang',
    name_ja: 'Daibai Hōjō',
    name_zh: '大梅法常',
    name_vi: 'Đại Mai Pháp Thường',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['752', '839'],
    epoch: '',
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Mazu Daoyi'],
    successors: [''],
    disciples: ['Juzi', 'Hangzhou Tianlong'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/%C4%90%E1%BA%A1i_Mai_Ph%C3%A1p_Th%C6%B0%E1%BB%9Dng',
      'https://terebess.hu/zen/damei.html', 'https://blog.phapthihoi.org/gt-member/ts-dai-mai-phap-thuong/'],
  },
  {
    id: '36.3.13',
    hasContent: true,
    name_en: 'Dazhu Huihai',
    name_ja: 'Daishū Ekai',
    name_zh: '大珠慧海',
    name_vi: 'Đại Châu Huệ Hải',
    other_name_vi: 'Đại Châu Tuệ Hải',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['713?', '812?'],
    epoch: '',
    records: '',
    sect: ['-'],
    country: 'China',
    place: 'Việt Châu',
    teachers: ['Mazu Daoyi'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/%C4%90%E1%BA%A1i_Ch%C3%A2u_Hu%E1%BB%87_H%E1%BA%A3i',
      'https://terebess.hu/zen/huihai-eng1.html', 'https://en.wikipedia.org/wiki/Dazhu_Huihai', ''],
  },
  {
    id: '36.3.14',
    name_en: 'Xitang Zhizang',
    name_ja: 'Seidô Chizô',
    name_zh: '西堂智藏',
    name_vi: 'Tây Đường Trí Tạng',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['735', '814'],
    epoch: '',
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Mazu Daoyi'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://terebess.hu/zen/mesterek/XitangZhizang.html', 'https://vi.wikipedia.org/wiki/T%C3%A2y_%C4%90%C6%B0%E1%BB%9Dng_Tr%C3%AD_T%E1%BA%A1ng',
      'https://blog.phapthihoi.org/gt-member/ts-tay-duong-tri-tang/', 'https://pl.wikipedia.org/wiki/Xitang_Zhizang',
    ],
  },
  {
    id: '36.3.15',
    hasContent: true,
    name_en: 'Nanquan Puyuan',
    nickname_en: 'Wang laoshi',
    name_ja: 'Nansen Fugan',
    name_zh: '南泉普願',
    nickname_zh: '王老師',
    name_vi: 'Nam Tuyền Phổ Nguyện',
    other_name_vi: '',
    nickname_vi: 'Vương Lão Sư',
    worship_tower: '',
    birth_death_time: ['748/749', '835'],
    epoch: '',
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Mazu Daoyi'],
    successors: [''],
    disciples: ['Zhuyu Ozhou', 'Xichan', 'Baima Tanzhao', 'Changsha Jingcen', 'Zhongnan Yunji',
      'Zihu Lizong', 'Taizhou Shengguang', 'Lugeng', 'Chŏlgam Toyun', 'Zhaozhou Congshen', ],
    image: '/images/avatar.png',
    reference: ['https://terebess.hu/zen/nanquan.html', 'https://en.wikipedia.org/wiki/Nanquan_Puyuan', 'https://pl.wikipedia.org/wiki/Nanquan_Puyuan'],
  },
  {
    id: '36.3.16',
    name_en: 'Fenzhou Wuye',
    name_ja: 'Funshū Mugyō',
    name_zh: '汾州無業',
    name_vi: 'Phần Châu Vô Nghiệp',
    other_name_vi: 'Đại Đạt Vô Nghiệp',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['760/761', '821/823'],
    epoch: '',
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Mazu Daoyi'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://terebess.hu/zen/nanquan.html', 'https://phatgiao.org.vn/tu-dien-phat-hoc-online/phan-chau-vo-nghiep-k1902.html'],
  },
  {
    id: '36.3.18',
    name_en: 'Jingzhong Shenhui',
    name_ja: 'Jingzhong Shenhui',
    name_zh: '淨衆神會',
    name_vi: 'Tĩnh Trung Thần Hội',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['720', '794'],
    epoch: '',
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Jingzhong Wuxiang'],
    successors: ['Shengshou Nanyin'],
    disciples: ['Shengshou Nanyin'],
    image: '/images/avatar.png',
    reference: ['https://www.degruyter.com/document/doi/10.1515/9780824896461-006/pdf?licenseType=restricted'],
  },
  {
    id: '36.3.19',
    name_en: 'Baotang Wuzhu',
    name_ja: 'Hotō Mujū',
    name_zh: '保唐无住',
    name_vi: 'Bảo Đường Vô Trụ',
    other_name_vi: 'Bảo Đường Mô Trú',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['714', '774'],
    epoch: '',
    records: '',
    sect: ['-'],
    country: 'China',
    place: 'Bảo Đường, Ích Châu',
    teachers: ['Jingzhong Wuxiang'],
    successors: [''],
    disciples: ['Longyou Fayuan', 'Changjingjin', 'Zhengbianzhi', 'Liaojianxing'],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '36.3.20',
    name_en: 'Thái sơn Minh Luyện',
    name_ja: 'Thái sơn Minh Luyện',
    name_zh: 'Thái sơn Minh Luyện',
    name_vi: 'Thái sơn Minh Luyện',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: ['-'],
    country: 'China',
    place: '',
    teachers: ['Cao Bưu Đàm Ảnh'],
    successors: [''],
    disciples: ['Dương châu Tỉnh Thái'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '36.3.21',
    hasContent: true,
    name_en: 'Zhangjing Huaihui',
    name_ja: 'Shōkei Eki',
    name_zh: '章敬懷暉',
    name_vi: 'Chương Kính Hoài Huy',
    other_name_vi: 'Hoài Uẩn',
    nickname_vi: 'Đại Giác',
    worship_tower: '',
    birth_death_time: ['754/756', '815'],
    epoch: '',
    records: '',
    sect: ['-'],
    country: 'China',
    place: 'Kinh Triệu',
    teachers: ['Mazu Daoyi'],
    successors: [''],
    disciples: ['Hoằng Biện', 'Trí Chân'],
    image: '/images/avatar.png',
    reference: ['https://blog.phapthihoi.org/gt-member/ts-chuong-kinh-hoai-uan/',
      'https://phatgiao.org.vn/tu-dien-phat-hoc-online/chuong-kinh-hoai-huy-k3599.html',
      'https://nigioikhatsi.net/thien/khe-ngo-tu-nga.html'],
  },
  {
    id: '36.3.22',
    hasContent: true,
    name_en: 'Panshan Baoji',
    name_ja: 'Banzan Hōshaku',
    name_zh: '盤山寳積, ',
    name_vi: 'Bàn Sơn Bảo Tích',
    other_name_vi: '',
    nickname_vi: 'Ngưng Tịch',
    worship_tower: 'Chân Tế',
    birth_death_time: ['720', '814'],
    epoch: '',
    records: '',
    sect: ['-'],
    country: 'China',
    place: 'Panshan, Jizhou, Tiānjīn',
    teachers: ['Mazu Daoyi'],
    successors: [''],
    disciples: ['Zhenzhou Puhua'],
    image: '/images/avatar.png',
    reference: ['https://phatgiao.org.vn/tu-dien-phat-hoc-online/ban-son-bao-tich-k3353.html',
      'https://vi.wikipedia.org/wiki/B%C3%A0n_S%C6%A1n_B%E1%BA%A3o_T%C3%ADch',
      'https://terebess.hu/zen/panshan.html'],
  },
  {
    id: '36.3.23',
    hasContent: true,
    name_en: 'Guizong Zhichang',
    name_ja: 'Kisu Chijô',
    name_zh: '归宗智常',
    name_vi: 'Quy Tông Trí Thường',
    other_name_vi: 'Qui Tông Trí Thường',
    nickname_vi: 'Chí Chơn',
    worship_tower: '',
    birth_death_time: ['-', '827'],
    epoch: '',
    records: '',
    sect: ['-'],
    country: 'China',
    place: 'Lushan (Lô Sơn)',
    teachers: ['Mazu Daoyi'],
    successors: ['Gaoan Dayu'],
    disciples: ['Gaoan Dayu'],
    image: '/images/avatar.png',
    reference: ['https://blog.phapthihoi.org/gt-member/ts-quy-tong-tri-thuong', 'https://nigioikhatsi.net/thien/quy-tong-chem-ran.html',
      'http://www.thuongchieu.net/index.php/chuyende/thiensutrunghoa/1285-thin-s-tri-thng', 'https://terebess.hu/zen/mesterek/GuizongZhichang.html'],
  },
  {
    id: '36.3.24',
    name_en: 'Gushan Lingjiao',
    other_name_en: 'Hongzhou Lingjiao',
    name_ja: 'Gushan Lingjiao',
    name_zh: '古山 靈嶠',
    name_vi: 'Cổ Sơn Linh Kiệu',
    other_name_vi: 'Cổ Sơn Linh Kiệu',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: ['-'],
    country: 'China',
    place: 'Gushan',
    teachers: ['Mazu Daoyi'],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: ['https://blog.phapthihoi.org/gt-member/ts-linh-kieu/'],
  },
  {
    id: '36.3.25',
    hasContent: true,
    name_en: 'Tanzhou Dachuan',
    name_ja: 'Tanzhou Dachuan',
    name_zh: '潭州大川',
    name_vi: 'Đàm Châu Đại Xuyên',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Shitou Xiqian'],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: ['https://ngulucthien.com/thien-su-dai-xuyen/'],
  },
  {
    id: '36.3.26',
    hasContent: true,
    name_en: 'Pangyun Jushi',
    other_name_en: 'Layman Pangyun',
    name_ja: 'Hōun koji',
    name_zh: '龐蘊居士',
    other_name_zh: '龐居士',
    name_vi: 'Bàng Uẩn Cư Sĩ',
    other_name_vi: 'Bàng Long Uẩn, Bàng Cư Sĩ',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['740', '808'],
    epoch: '',
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Mazu Daoyi'],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Pangyun_Jushi', 'https://vi.wikipedia.org/wiki/B%C3%A0ng_Long_U%E1%BA%A9n',
      'https://en.wikipedia.org/wiki/Layman_Pang'],
  },
  {
    id: '36.3.27',
    hasContent: true,
    name_en: 'Yanguan Qian',
    name_ja: 'Engan Saian',
    other_name_ja: 'Enkan Seian',
    name_zh: '鹽官齊安',
    name_vi: 'Diêm Quan Tề An',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['750', '842'],
    epoch: '',
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Mazu Daoyi'],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: ['https://phatgiao.org.vn/tu-dien-phat-hoc-online/diem-quan-te-an-k587.html', 'https://phatgiao.org.vn/tu-dien-phat-hoc-online/diem-quan-te-an-k3692.html',
      'https://blog.phapthihoi.org/gt-member/ts-diem-quan-te-an/', 'https://terebess.hu/zen/yanguan.html'],
  },
  {
    id: '36.3.28',
    name_en: 'Shigong Huicang',
    name_ja: 'Sakkyō Ezō',
    name_zh: '石鞏慧藏',
    name_vi: 'Thạch Củng Huệ Tạng',
    other_name_vi: 'Thạch Củng Tuệ Tạng',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '8th - 9th century',
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Mazu Daoyi'],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: ['https://phatgiao.org.vn/tu-dien-phat-hoc-online/thach-cung-hue-tang-k2488.html',
      'https://phatgiao.org.vn/tu-dien-phat-hoc-online/thach-cung-hue-tang-k16842.html', 'http://truclamdaigiac.net/chi-tiet/tu-ngam-lai-vang-trang-minh.html',
      'https://blog.phapthihoi.org/gt-member/ts-thach-cung-hue-tang/', 'https://terebess.hu/zen/shigong.html'],
  },
]
export default CnLv3MasterDb;
