const CnLv57MasterDb = [
  {
    id: '90.57.1',
    name_en: 'Mingxuan Xirui',
    name_es: 'Mingxuan Xirui',
    name_de: 'Mingxuan Xirui',
    name_fr: 'Mingxuan Xirui',
    name_ru: 'Mingxuan Xirui',
    name_ar: 'Mingxuan Xirui',
    name_ko: 'Mingxuan Xirui',
    name_ja: 'Mingxuan Xirui',
    name_zh: '明轩西瑞',
    name_vi: 'Minh Hiên Hi Nhụy',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: ['Linji'],
    country: 'China',
    place: 'Gaomin Temple/Monastery (高旻寺), Hanjiang District, Yangzhou, China',
    teachers: ['Yuelang Quanding'],
    successors: ['Laiguo Miaoshu'],
    disciples: ['Laiguo Miaoshu'],
    image: '/images/avatar.png',
    reference: ['https://www.mdpi.com/2077-1444/15/5/627', 'https://terebess.hu/zen/mesterek/7.pdf'],
  },
]
export default CnLv57MasterDb;
