const CnLv31MasterDb = [
  {
    id: '64.31.1',
    hasContent: true,
    name_en: 'Wuming Huijing',
    name_ja: 'Mumyō Ekyō',
    name_zh: '無明慧經',
    name_vi: 'Vô Minh Huệ Kinh',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1548', '1618'],
    epoch: '',
    records: '',
    sect: ['Caodong'],
    country: 'China',
    place: '-',
    teachers: ['Yunkong Changzhong'],
    successors: ['Wuyi Yuanlai', 'Huitai Yuanjing', 'Yuanjue Yuanxian'],
    disciples: ['Wuyi Yuanlai', 'Huitai Yuanjing', 'Yuanjue Yuanxian'],
    image: '/images/avatar.png',
    reference: ['', 'https://londonchanmeditation.org/lineage/'],
  },
  {
    id: '64.31.2',
    name_en: 'Wuwen Mingcong',
    name_ja: 'Mubun Shōsō',
    name_zh: '無聞正聰',
    name_vi: 'Vô Văn Minh Thông',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', '1543'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: 'China',
    place: '-',
    teachers: ['Tianqi Benrui'],
    successors: ['Xiaoyan Debao'],
    disciples: ['Xiaoyan Debao'],
    image: '/images/avatar.png',
    reference: [''],
  },
]
export default CnLv31MasterDb;
