const CnLv8MasterDb = [
  {
    id: '41.8.1',
    name_en: 'Fengxue Yanzhao',
    name_es: 'Fengxue Yanzhao',
    name_de: 'Fengxue Yanzhao',
    name_fr: 'Fengxue Yanzhao',
    name_vi: 'Phong Huyệt Diên Chiểu',
    name_ru: 'Fengxue Yanzhao',
    name_zh: '風穴延沼',
    name_ja: 'Fuketsu Enshō',
    name_ko: 'Fengxue Yanzhao',
    name_ar: 'Fengxue Yanzhao',
    birth_death_time: ['896', '973'],
    records: '',
    sect: ['Linji'],
    country: 'China',
    place: '-',
    teachers: ['Nanyuan Huiyong'],
    successors: ['Shoushan Xingnian'],
    disciples: ['Shoushan Xingnian'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/Phong_Huy%E1%BB%87t_Di%C3%AAn_Chi%E1%BB%83u', 'https://pl.wikipedia.org/wiki/Fengxue_Yanzhao',],

  },
  {
    id: '41.8.2',
    name_en: 'Luohan Guichen',
    name_es: 'Luohan Guichen',
    name_de: 'Luohan Guichen',
    name_fr: 'Luohan Guichen',
    name_vi: 'La Hán Quế Sâm (Địa Tạng Đại sư)',
    name_ru: 'Luohan Guichen',
    name_zh: '羅漢桂琛 (地藏)',
    name_ja: 'Rakan Keichin/Keijin (Chizō)',
    name_ko: 'Luohan Guichen',
    name_ar: 'Luohan Guichen',
    birth_death_time: ['867', '928'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Xuansha Shibei', 'Xuefeng Yicun'],
    successors: ['Fayan Wenyi'],
    disciples: ['Fayan Wenyi', 'Longji Shaoxiu', 'Tianbing Congyi', 'Qingqi Hongjin'],
    image: '/images/avatar.png',
    reference: ['https://terebess.hu/zen/luohan.html', 'https://quangduc.com/p156a69697/52/thien-su-la-han-que-sam-867-928-vi-thien-su-dat-nen-mong-cho-thien-phai-phap-nhan', 'https://vi.wikipedia.org/wiki/La_H%C3%A1n_Qu%E1%BA%BF_S%C3%A2m'],

  },
  {
    id: '41.8.3',
    name_en: 'Xianglin Chengyuan',
    name_es: 'Xianglin Chengyuan',
    name_de: 'Xianglin Chengyuan',
    name_fr: 'Xianglin Chengyuan',
    name_vi: 'Hương Lâm Trừng Viễn',
    name_ru: 'Xianglin Chéngyuan',
    name_zh: '香林澄遠',
    name_ja: 'Kyōrin Chōon',
    name_ko: 'Xianglin Chengyuan',
    name_ar: 'Xianglin Chengyuan',
    birth_death_time: ['908', '987'],
    records: '',
    sect: ['Yunmen'],
    country: 'China',
    place: '-',
    teachers: ['Yunmen Wenyan'],
    successors: ['Zhimen Guangzuo'],
    disciples: ['Zhimen Guangzuo'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/H%C6%B0%C6%A1ng_L%C3%A2m_Tr%E1%BB%ABng_Vi%E1%BB%85n'],

  },
  {
    id: '41.8.4',
    name_en: 'Dongshan Shouchu',
    name_es: 'Dongshan Shouchu',
    name_de: 'Dongshan Shouchu',
    name_fr: 'Dongshan Shouchu',
    name_vi: 'Động Sơn Thủ Sơ',
    name_ru: 'Dongshan Shouchu',
    name_zh: '洞山守初',
    name_ja: 'Tōsan Shusho',
    name_ko: '동산수초 Tongsan Sucho',
    name_ar: 'Dongshan Shouchu',
    birth_death_time: ['910', '990'],
    records: '',
    sect: ['Yunmen'],
    country: 'China',
    place: '-',
    teachers: ['Yunmen Wenyan'],
    successors: [''],
    disciples: ['Nanyue Liangya'],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '41.8.5',
    name_en: 'Deshan Yuanmi',
    name_es: 'Deshan Yuanmi',
    name_de: 'Deshan Yuanmi',
    name_fr: 'Deshan Yuanmi',
    name_vi: 'Đức Sơn Duyên Mật',
    name_ru: 'Deshan Yuanmi',
    name_zh: '德山緣密',
    name_ja: 'Tokusan Emmitsu',
    name_ko: 'Deshan Yuanmi',
    name_ar: 'Deshan Yuanmi',
    birth_death_time: ['', ''],
    records: '',
    sect: ['Yunmen'],
    country: 'China',
    place: '-',
    teachers: ['Yunmen Wenyan'],
    successors: [''],
    disciples: ['Wenshu Yingzhen Monju Ôshin'],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '41.8.6',
    name_en: 'Shuangquan Renyu',
    name_es: 'Shuangquan Renyu',
    name_de: 'Shuangquan Renyu',
    name_fr: 'Shuangquan Renyu',
    name_vi: 'Song Tuyền Nhân Úc',
    name_ru: 'Shuangquan Renyu',
    name_zh: '雙泉仁郁',
    name_ja: 'Shuangquan Renyu',
    name_ko: 'Shuangquan Renyu',
    name_ar: 'Shuangquan Renyu',
    birth_death_time: ['', ''],
    records: '',
    sect: ['Yunmen'],
    country: 'China',
    place: '-',
    teachers: ['Yunmen Wenyan'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '41.8.7',
    name_en: 'Baling Haojian',
    name_es: 'Baling Haojian',
    name_de: 'Baling Haojian',
    name_fr: 'Baling Haojian',
    name_vi: 'Ba Lăng Hạo Giám',
    name_ru: 'Baling Haojian',
    name_zh: '巴陵顥鑒',
    name_ja: 'Baling Haojian',
    name_ko: 'Baling Haojian',
    name_ar: 'Baling Haojian',
    birth_death_time: ['', ''],
    records: '',
    sect: ['Yunmen'],
    country: 'China',
    place: '-',
    teachers: ['Yunmen Wenyan'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '41.8.8',
    name_en: 'Fengxian Daoshen',
    name_es: 'Fengxian Daoshen',
    name_de: 'Fengxian Daoshen',
    name_fr: 'Fengxian Daoshen',
    name_vi: 'Phụng Tiên Đạo Thâm',
    name_ru: 'Fengxian Daoshen',
    name_zh: '奉先道深',
    name_ja: 'Hōsen Dōshin',
    name_ko: '봉선도심 Pongsŏn Tosim',
    name_ar: 'Fengxian Daoshen',
    birth_death_time: ['', ''],
    records: '',
    sect: ['Yunmen'],
    country: 'China',
    place: '-',
    teachers: ['Yunmen Wenyan'],
    successors: [''],
    disciples: ['Lianhua Fengxiang', 'Xiang Anzhu'],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Fengxian_Daoshen'],
  },
  {
    id: '41.8.9',
    name_en: 'Tongan Guanzhi',
    name_es: 'Tongan Guanzhi',
    name_de: 'Tongan Guanzhi',
    name_fr: 'Tongan Guanzhi',
    name_vi: 'Đồng An Quán Chí',
    name_ru: 'Tongan Guanzhi',
    name_zh: '同安觀志',
    name_ja: 'Dōan Kanshi',
    name_ko: 'Tongan Guanzhi',
    name_ar: 'Tongan Guanzhi',
    birth_death_time: ['910', '970'],
    records: '',
    sect: ['Caodong'],
    country: 'China',
    place: '-',
    teachers: ['Tongan Daopi'],
    successors: ['Liangshan Yuanguan'],
    disciples: ['Liangshan Yuanguan'],
    image: '/images/avatar.png',
    reference: ['https://en.wikipedia.org/wiki/Tongan_Guanzhi', 'https://vi.wikipedia.org/wiki/%C4%90%E1%BB%93ng_An_Qu%C3%A1n_Ch%C3%AD',
    'https://pl.wikipedia.org/wiki/Tong%E2%80%99an_Guanzhi'],
  },
  {
    id: '41.8.10',
    name_en: 'Mingzhao Deqian',
    name_es: 'Mingzhao Deqian',
    name_de: 'Mingzhao Deqian',
    name_fr: 'Mingzhao Deqian',
    name_vi: 'Minh Chiêu Đức Khiêm',
    name_ru: 'Mingzhao Deqian',
    name_zh: '明招德謙',
    name_ja: 'Myōshō Tokke',
    name_ko: '명초덕겸 Myŏngch’o Tŏkkyŏm',
    name_ar: 'Mingzhao Deqian',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: 'Mingzhao Shan - Minh Chiêu Sơn (明招山)',
    teachers: ['Luoshan Daoxian'],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Mingzhao_Deqian', 'https://phatgiao.org.vn/tu-dien-phat-hoc-online/minh-chieu-duc-khiem-k4536.html', 'https://tangthuphathoc.net/thuat_ngu/minh-chieu-duc-khiem-tu-dien-dao-uyen', 'https://terebess.hu/zen/mesterek/mingzhao.pdf', 'https://terebess.hu/zen/mesterek/MingzhaoDeqian.html'],
  },
]
export default CnLv8MasterDb;
