const CnLv5MasterDb = [
  {
    id: '38.1',
    name_en: 'Guifeng Zongmi',
    name_es: 'Guifeng Zongmi',
    name_de: 'Guifeng Zongmi',
    name_fr: 'Guifeng Zongmi',
    name_vi: 'Khuê Phong Tông Mật',
    name_ru: 'Guifeng Zongmi',
    name_zh: '圭峰宗密',
    name_ja: 'Guifeng Zongmi',
    name_ko: 'Guifeng Zongmi',
    name_ar: 'Guifeng Zongmi',
    birth_death_time: ['780', '841'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: 'Zhongnan mountain',
    teachers: ['Toại Châu Đạo Viên'],
    successors: ['-'],
    disciples: [],
    image: '/images/avatar.png',
    reference: [''],
    koans: ['',],
  },
  {
    id: '38.2',
    name_en: 'Dongshan Liangjie',
    name_es: 'Dongshan Liangjie',
    name_de: 'Dongshan Liangjie',
    name_fr: 'Dongshan Liangjie',
    name_vi: 'Động Sơn Lương Giới',
    name_ru: 'Dongshan Liangjie',
    name_zh: '洞山 良价',
    name_ja: 'Tōzan Ryōkai',
    name_ko: 'Dongshan Liangjie',
    name_ar: 'Dongshan Liangjie',
    birth_death_time: ['807', '869'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Yunyan Tansheng'],
    successors: ['Yunju Daoying', 'Caoshan Benji'],
    disciples: [],
    image: '/images/avatar.png',
    reference: [''],
    koans: ['',],
  },
  {
    id: '38.3',
    hasContent: true,
    name_en: 'Deshan Xuanjian',
    name_es: 'Deshan Xuanjian',
    name_de: 'Deshan Xuanjian',
    name_fr: 'Deshan Xuanjian',
    name_vi: 'Đức Sơn Tuyên Giám',
    name_ru: 'Deshan Xuanjian',
    name_zh: '德山宣鑒',
    name_ja: 'Tokusan Senkan',
    name_ko: '덕산선감 Tŏksan Sŏngam',
    name_ar: 'Deshan Xuanjian',
    birth_death_time: ['780', '865'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: 'Wuling, Hunan',
    teachers: ['Longtan Chongxin'],
    successors: ['-'],
    disciples: [],
    image: 'https://terebess.hu/zen/deshan3.jpg',
    image2: 'https://upload.wikimedia.org/wikipedia/commons/5/5f/To_san_Hszuan_csien780.2-865.jpg',
    reference: ['https://terebess.hu/zen/deshan3.jpg'],
    koans: ['',],
  },
  {
    id: '38.4',
    name_en: 'Yangshan Huiji',
    name_es: 'Yangshan Huiji',
    name_de: 'Yangshan Huiji',
    name_fr: 'Yangshan Huiji',
    name_vi: 'Ngưỡng Sơn Huệ Tịch',
    name_ru: 'Yangshan Huiji',
    name_zh: '仰山慧寂',
    name_ja: 'Kyōzan Ejaku',
    name_ko: '안산혜적 Angsan Hyejŏk',
    name_ar: 'Yangshan Huiji',
    birth_death_time: ['807', '883'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Guishan Lingyou'],
    successors: ['Nanta Guangyong'],
    disciples: ['Nanta Guangyong'],
    image: '/images/avatar.png',
    reference: [''],
    koans: ['',],
  },
  {
    id: '38.5',
    name_en: 'Linji Yixuan',
    name_es: 'Linji Yixuan',
    name_de: 'Linji Yixuan',
    name_fr: 'Linji Yixuan',
    name_vi: 'Lâm Tế Nghĩa Huyền',
    name_ru: 'Linji Yixuan',
    name_zh: '臨濟義玄',
    name_ja: 'Rinzai Gigen',
    name_ko: 'Linji Yixuan',
    name_ar: 'Linji Yixuan',
    birth_death_time: ['?', '866/867'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Huangbo Xiyun'],
    successors: ['Xinghua Cunjiang'],
    disciples: ['Xinghua Cunjiang', 'Sansheng Huiran'],
    image: '/images/avatar.png',
    reference: [''],
    koans: ['',],
  },
  {
    id: '38.6',
    name_en: 'Muzhou Daoming/Daozong',
    name_es: 'Muzhou Daoming',
    name_de: 'Muzhou Daoming',
    name_fr: 'Muzhou Daoming',
    name_vi: 'Mục Châu Đạo Minh (Trần Tôn Túc)',
    name_ru: 'Muzhou Daoming',
    name_zh: '睦州 道明/道蹤',
    name_ja: 'Muzhou Daoming',
    name_ko: 'Muzhou Daoming',
    name_ar: 'Muzhou Daoming',
    birth_death_time: ['780', '877'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: 'Guanyin Temple, Muzhou (Zhejiang now) ⇨ Longxing Temple (Guanyin Pavilion), Longgang district, Shenzhen city, Guangdong province',
    teachers: ['Huangbo Xiyun'],
    successors: [''],
    disciples: [],
    image: 'https://terebess.hu/zen/mesterek/woodcut/38-3.jpg',
    reference: ['https://terebess.hu/zen/muzhou.html'],
    koans: ['',],
  },
  {
    id: '38.7',
    name_en: 'Pei Xiu',
    name_es: 'Pei Xiu',
    name_de: 'Pei Xiu',
    name_fr: 'Pei Xiu',
    name_vi: 'Bùi Hưu (tướng quốc)',
    name_ru: 'Pei Xiu',
    name_zh: '裴休 (Pei Xiu)',
    name_ja: 'Haikyū',
    name_ko: 'Pei Xiu',
    name_ar: 'Pei Xiu',
    birth_death_time: ['797?', '870?'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: 'Henan province',
    teachers: ['Huangbo Xiyun'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://blog.phapthihoi.org/gt-member/tuong-quoc-bui-huu/','https://vi.wikipedia.org/wiki/B%C3%B9i_H%C6%B0u', 'https://phatgiao.org.vn/tu-dien-phat-hoc-online/bui-huu-k338.html', 'https://phatgiao.org.vn/tu-dien-phat-hoc-online/bui-huu-k30587.html', 'https://tinhtan.org/2021/01/17/dich-va-binh-tho-dam-lac-dam-cua-te-tuong-bui-huu-791-846'],
    koans: ['',],
  },
  {
    id: '38.8',
    name_en: 'Kinzan Dōkin',
    name_es: 'Kinzan Dōkin',
    name_de: 'Kinzan Dōkin',
    name_fr: 'Kinzan Dōkin',
    name_vi: 'Kính Sơn Đạo Khâm ',
    name_ru: 'Kinzan Dōkin',
    name_zh: '徑山道欽',
    name_ja: 'Kinzan Dōkin',
    name_ko: 'Kinzan Dōkin',
    name_ar: 'Kinzan Dōkin',
    birth_death_time: ['714', '792'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '',
    teachers: ['Huyền Tố (玄素)'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: [''],
    koans: ['',],
  },
  {
    id: '38.9',
    hasContent: true,
    name_en: 'Shishuang Qingzhu',
    name_es: 'Shishuang Qingzhu',
    name_de: 'Shishuang Qingzhu',
    name_fr: 'Shishuang Qingzhu',
    name_vi: 'Thạch Sương Khánh Chư',
    name_ru: 'Shishuang Qingzhu',
    name_zh: '石霜慶諸',
    name_ja: 'Sekisō Keisho',
    name_ko: 'Shishuang Qingzhu',
    name_ar: 'Shishuang Qingzhu',
    birth_death_time: ['807', '888'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '',
    teachers: ['Daowu Yuanzhi'],
    successors: [''],
    disciples: ['Zhangzhuo Xiucai', 'Jiufeng Daoqian'],
    image: '/images/avatar.png',
    reference: ['https://blog.phapthihoi.org/gt-member/ts-thach-suong-khanh-chu/', 'https://hoavouu.com/a17583/03-thien-su-khanh-chu-o-thach-suong', 'https://phatgiao.org.vn/tu-dien-phat-hoc-online/thach-suong-that-khu-k42432.html'],
    koans: ['',],
  },
]
export default CnLv5MasterDb;
