const CnLv0MasterDb = [
  {
    id: '29',
    name_en: 'Dazu Huike',
    name_ja: 'Taiso Eka',
    name_zh: '道育慧可',
    other_name_zh: '大祖慧可',
    name_vi: 'Huệ Khả',
    other_name_vi: 'Thần Quang',
    nickname_vi: 'Nhị Tổ',
    birth_death_time: ['487?', '593'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Bodhidharma'],
    successors: ['Jianzhi Sengcan'],
    disciples: ['Jianzhi Sengcan', 'Tăng Na', 'Tương Châu Tuệ Mãn', 'Cư sĩ Lưu Hướng'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Huike_thinking.jpg/220px-Huike_thinking.jpg',
    reference: [''],
  },
  {
    id: '30.1',
    name_en: 'Jianzhi Sengcan',
    name_ja: 'Kanchi Sōsan',
    name_zh: '鑑智僧璨',
    name_vi: 'Tăng Xán',
    nickname_vi: 'Tam Tổ',
    birth_death_time: ['496?', '606'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dazu Huike'],
    successors: ['Dayi Daoxin'],
    disciples: ['Dayi Daoxin'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Sengcan.jpg/220px-Sengcan.jpg',
    reference: [''],
  },
  {
    id: '30.2',
    name_en: 'Tăng Na',
    name_ja: 'Tăng Na',
    name_zh: 'Tăng Na',
    name_vi: 'Tăng Na',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dazu Huike'],
    successors: [''],
    disciples: [],
    image: '',
    reference: [''],
  },
  {
    id: '30.3',
    name_en: 'Tương Châu Tuệ Mãn',
    name_ja: 'Tương Châu Tuệ Mãn',
    name_zh: 'Tương Châu Tuệ Mãn',
    name_vi: 'Tương Châu Tuệ Mãn',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dazu Huike'],
    successors: [''],
    disciples: ['Hiện Sơn Thần Định', 'Bảo Nguyệt', 'Cư sĩ Hoa Nhàn', 'Đại sĩ Hóa Công', 'Hòa Công', 'Cư sĩ Liệu'],
    image: '',
    reference: [''],
  },
  {
    id: '30.4',
    name_en: 'cư sĩ Hướng',
    name_ja: 'cư sĩ Hướng',
    name_zh: 'cư sĩ Hướng',
    name_vi: 'cư sĩ Hướng',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dazu Huike'],
    successors: [''],
    disciples: [],
    image: '',
    reference: [''],
  },
  {
    id: '31.1',
    name_en: 'Dayi Daoxin',
    name_ja: 'Daii Dōshin',
    name_zh: '道信',
    name_vi: 'Đạo Tín',
    nickname_vi: 'Tứ Tổ',
    birth_death_time: ['580', '651'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Jianzhi Sengcan'],
    successors: ['Daman Hongren'],
    disciples: ['Daman Hongren', 'Niutou Farong'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/5/59/Daoxin.jpg',
    reference: [''],
  },
  {
    id: '31.2',
    name_en: 'Cư sĩ Hoa Nhàn',
    name_ja: 'Cư sĩ Hoa Nhàn',
    name_zh: 'Cư sĩ Hoa Nhàn',
    name_vi: 'Cư sĩ Hoa Nhàn',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Tương Châu Tuệ Mãn'],
    successors: [''],
    disciples: ['Đàm Thúy'],
    image: '',
    reference: [''],
  },
  {
    id: '32.1',
    name_en: 'Daman Hongren',
    name_ja: 'Daiman Konin',
    other_name_ja: 'Gunin',
    name_zh: '弘忍',
    name_vi: 'Đại Mãn Hoằng Nhẫn',
    other_name_vi: 'Hoàng Mai',
    nickname_vi: 'Ngũ Tổ',
    birth_death_time: ['601', '674'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dayi Daoxin'],
    successors: ['Dajian Huineng'],
    disciples: ['Dajian Huineng'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Hongren.jpg/220px-Hongren.jpg',
    reference: [''],
  },
  {
    id: '32.2',
    hasContent: true,
    name_en: 'Niutou Farong',
    name_ja: 'Gozu Hōyū',
    name_zh: '牛頭 法融',
    other_name_zh: '心銘',
    name_vi: 'Ngưu Đầu Pháp Dung',
    birth_death_time: ['594', '657'],
    epoch: '',
    records: '',
    sect: ['Niutou (Oxhead)'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dayi Daoxin'],
    successors: ['-'],
    disciples: ['Niutou Zhiyan', 'Kim Lăng Đàm Thôi', 'Kinh Châu Đại Tố', 'U Thê Nguyệt Không', 'Bạch Mã Đạo Diễn',
      'Tân An Định Trang', 'Bành Thành Trí Sai', 'Quảng Châu Đạo Thọ', 'Hồ Châu Trí Sảng', 'Tân Châu Đổ Mặc',
      'Thượng Nguyên Trí Thành'],
    image: 'https://i.pinimg.com/736x/59/ef/78/59ef78ca5fa903bb4b843c2b40db4970.jpgg',
    reference: [''],
  },
  {
    id: '32.3',
    name_en: 'Đàm Thúy',
    name_ja: 'Đàm Thúy',
    name_zh: 'Đàm Thúy',
    name_vi: 'Đàm Thúy',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Cư sĩ Hoa Nhàn'],
    successors: [''],
    disciples: ['Diên lăng Tuệ Giản', 'Bành thành Tuệ Sai', 'Định lâm Tuệ Cương'],
    image: '',
    reference: [''],
  },
  {
    id: '33.1',
    name_en: 'Dajian Huineng',
    other_name_en: 'Liuzu, Caoxi Huineng',
    name_ja: 'Daikan Enō',
    name_zh: '大鑒惠能 (六祖)',
    other_name_zh: '六祖, 大建恵能',
    name_vi: 'Huệ Năng',
    other_name_vi: '',
    nickname_vi: 'Lục Tổ',
    original_name_vi: '',
    worship_tower: '',
    birth_death_time: ['638', '713'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: 'Nanhua temple, Shaoguan, Guangdong',
    teachers: ['Daman Hongren'],
    successors: ['-'],
    disciples: ['Qingyuan Xingsi', 'Shitou Xiqian', 'Nanyue Huairang', 'Biandan Xiaoliao', 'Hongzhou Fada', 'Jizhou Zhicheng'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Huineng.jpg/220px-Huineng.jpg',
    reference: [''],
  },
  {
    id: '33.2',
    name_en: 'Niutou Zhiyan',
    name_ja: 'Gozu Chigan',
    other_name_ja: 'Chigen',
    name_zh: '牛頭 智巖',
    name_vi: 'Ngưu Đầu Trí Nham',
    birth_death_time: ['600', '677'],
    epoch: '',
    records: '',
    sect: ['Niutou (Oxhead)'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Niutou Farong'],
    successors: ['Niutou Huifang'],
    disciples: ['Niutou Huifang', 'Cảnh Đàm ở Đông đô', 'Chí Trường ở Tương châu', 'Đoan Phục ở Ích châu', 'Quy Nhân ở Long quang', 'Biện Tài ở Tương dương', 'Pháp Tuấn ở Hán nam', 'Mẫn Cổ ở Tây xuyên'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '33.3',
    hasContent: true,
    name_en: 'Yuquan Shenxiu',
    name_ja: 'Jinshū',
    name_zh: '玉泉 神秀',
    name_vi: 'Ngọc Tuyền Thần Tú ',
    birth_death_time: ['605/606', '706'],
    epoch: '',
    records: '',
    sect: ['Northern'],
    country: '🇨🇳',
    place: 'Jade Spring Temple (玉泉寺) - Yuquan Tiantai (玉泉天台), Yuquan Mountain (玉泉山), Jingxi Prefecture (荆溪府), within the scope of Dangyang, Hubei Province',
    teachers: ['Daman Hongren'],
    successors: [''],
    disciples: ['Dōsen (道璿)', 'Tung Sơn Huệ Tịch (嵩山慧寂)', 'Kinh Triệu Nghĩa Phước (京兆 義福)', 'Yìfú', 'Kính Hiền', 'Pǔjì', 'Huệ Minh'],
    image: 'https://upload.wikimedia.org/wikipedia/en/2/2d/Shenxiu-invert.jpg',
    reference: [''],
  },
  {
    id: '33.4',
    name_en: 'Laoan Huian',
    other_name_en: 'Songyue Huian',
    name_ja: 'Rōan Ean',
    name_zh: '老安慧安',
    name_vi: 'Lão An Huệ An',
    birth_death_time: ['582', '709'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Daman Hongren'],
    successors: [''],
    disciples: ['Phá Táo Đọa', 'Đạo Lượng'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: ['https://zh.wikipedia.org/zh-hant/%E5%B5%A9%E5%B6%BD%E6%85%A7%E5%AE%89', 'https://pl.wikipedia.org/wiki/Lao%E2%80%99an_Hui%E2%80%99an', ''],
  },
  {
    id: '33.5',
    hasContent: true,
    name_en: 'Zizhou Zhishen',
    name_zh: '智詵',
    name_ja: 'Shishū Chishin',
    name_vi: 'Tử Châu Trí Sân',
    other_name_vi: 'Tư Châu Trí Sằn',
    birth_death_time: ['609', '702'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Daman Hongren'],
    successors: [''],
    disciples: ['Zizhou Chuji'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: ['https://pl.wikipedia.org/wiki/Zizhou_Zhishen'],
  },
  {
    id: '33.6',
    name_en: 'Định Lâm Tuệ Cương',
    name_ja: 'Định Lâm Tuệ Cương',
    name_zh: 'Định Lâm Tuệ Cương',
    name_vi: 'Định Lâm Tuệ Cương',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Đàm Thúy'],
    successors: [''],
    disciples: ['Lục Hợp Đại Giác'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '33.7',
    name_en: 'Thượng Nguyên Trí Thành',
    name_ja: 'Thượng Nguyên Trí Thành',
    name_zh: 'Thượng Nguyên Trí Thành',
    name_vi: 'Thượng Nguyên Trí Thành',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Niutou Farong'],
    successors: [''],
    disciples: ['Định Châu'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
]
export default CnLv0MasterDb;
