const CnLv6MasterDb = [
  {
    id: '39.6.1',
    generation: '39',
    name_en: 'Caoshan Benji',
    name_es: 'Caoshan Benji',
    name_de: 'Caoshan Benji',
    name_fr: 'Caoshan Benji',
    name_vi: 'Tào Sơn Bản Tịch',
    name_ru: 'Caoshan Benji',
    name_zh: '曹山本寂',
    name_ja: 'Sōzan Honjaku',
    name_ko: 'Caoshan Benji',
    name_ar: 'Caoshan Benji',
    birth_death_time: ['840', '883'],
    records: '',
    sect: '-',
    country: 'China',
    place: '-',
    teachers: ['Dongshan Liangjie'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '39.6.2',
    generation: '39',
    hasContent: true,
    name_en: 'Xinghua Cunjiang',
    name_es: 'Xinghua Cunjiang',
    name_de: 'Xinghua Cunjiang',
    name_fr: 'Xinghua Cunjiang',
    name_vi: 'Hưng Hóa Tồn Tương',
    name_ru: 'Xinghua Cunjiang',
    name_zh: '興化存奬',
    name_ja: 'Kōke Zonshō',
    name_ko: 'Xinghua Cunjiang',
    name_ar: 'Xinghua Cunjiang',
    birth_death_time: ['830', '888'],
    records: '',
    sect: '-',
    country: 'China',
    place: '-',
    teachers: ['Linji Yixuan'],
    successors: ['Nanyuan Huiyong'],
    disciples: ['Nanyuan Huiyong'],
    image: '/images/avatar.png',
    reference: ['https://terebess.hu/zen/xinghua.html', 'https://phatgiao.org.vn/tu-dien-phat-hoc-online/hung-hoa-ton-tuong-k4195.html', 'https://vi.wikipedia.org/wiki/H%C6%B0ng_H%C3%B3a_T%E1%BB%93n_T%C6%B0%C6%A1ng', 'http://thuongchieu.net/index.php/chuyende/thiensutrunghoa/1680-hng-hoa-tn-tng-thin-s', 'https://blog.phapthihoi.org/gt-member/ts-hung-hoa-ton-tuong'],
  },
  {
    id: '39.6.3',
    generation: '39',
    hasContent: true,
    name_en: 'Sansheng Huiran',
    name_es: 'Sansheng Huiran',
    name_de: 'Sansheng Huiran',
    name_fr: 'Sansheng Huiran',
    name_vi: 'Tam Thánh Huệ Nhiên',
    name_ru: 'Sansheng Huiran',
    name_zh: '三聖慧然',
    name_ja: 'Sanshō Enen',
    name_ko: '삼성혜연 Samsŏng Hyeyŏn',
    name_ar: 'Sansheng Huiran',
    birth_death_time: ['', ''],
    records: '',
    sect: '-',
    country: 'China',
    place: '-',
    teachers: ['Linji Yixuan'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://blog.phapthihoi.org/gt-member/ts-tam-thanh-hue-nhien/', 'https://vi.wikipedia.org/wiki/Tam_Th%C3%A1nh_Hu%E1%BB%87_Nhi%C3%AAn', 'https://pl.wikipedia.org/wiki/Sansheng_Huiran'],
  },
  {
    id: '39.6.4',
    generation: '39',
    name_en: '陳操',
    name_es: '陳操',
    name_de: '陳操',
    name_fr: '陳操',
    name_vi: 'Mục Châu Trần Tháo (thượng thư)',
    name_ru: '陳操',
    name_zh: '陳操',
    name_ja: '陳操',
    name_ko: '陳操',
    name_ar: '陳操',
    birth_death_time: ['', ''],
    records: '',
    sect: '-',
    country: 'China',
    place: 'Muzhou',
    teachers: ['Muzhou Daoming'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://blog.phapthihoi.org/gt-member/ts-muc-chau-tran-thao/', 'http://thuongchieu.net/index.php/chuyende/vuonthien/847-bai-5--hoang-ba-tat-mt-tat','http://thuongchieu.net/index.php?option=com_content&view=article&id=1262:bai-85--lao-bang-th--t&catid=44:vn-thin-rng-ngc&Itemid=355',],
  },
  {
    id: '39.6.5',
    generation: '39',
    name_en: 'Zhangzhuo Xiucai',
    name_es: 'Zhangzhuo Xiucai',
    name_de: 'Zhangzhuo Xiucai',
    name_fr: 'Zhangzhuo Xiucai',
    name_vi: 'Trương Chuyết Tú Tài',
    name_ru: 'Zhangzhuo Xiucai',
    name_zh: '張拙秀才',
    name_ja: 'Chōsetsu Shūsai',
    name_ko: 'Zhangzhuo Xiucai',
    name_ar: 'Zhangzhuo Xiucai',
    birth_death_time: ['', ''],
    records: '',
    sect: '-',
    country: 'China',
    place: '-',
    teachers: ['Shishuang Qingzhu'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '39.6.6',
    generation: '39',
    hasContent: true,
    name_en: 'Jiufeng Daoqian',
    name_es: 'Jiufeng Daoqian',
    name_de: 'Jiufeng Daoqian',
    name_fr: 'Jiufeng Daoqian',
    name_vi: 'Cửu Phong Ðạo Kiền',
    name_ru: 'Jiufeng Daoqian',
    name_zh: '九峰道虔',
    name_ja: 'Kyūhō Dōken',
    name_ko: '구봉도건 Kubong Togŏn',
    name_ar: 'Jiufeng Daoqian',
    birth_death_time: ['', '923'],
    records: '',
    sect: '-',
    country: 'China',
    place: '-',
    teachers: ['Shishuang Qingzhu'],
    successors: [''],
    disciples: ['Heshan Wuyin', 'Baofeng Yanmao', 'Guangmu Xingxiu', "Tong'an Changcha", 'Letan Kuangwu'],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Jiufeng_Daoqian', 'https://www.reddit.com/r/Koans/comments/160eeb/jiufengs_one_who_transmits_words_221_of_300/', 'https://www.rongmotamhon.net/daouyen/Data/Ph_C/C84.htm'],
  },
  {
    id: '39.6.7',
    generation: '39',
    name_en: 'Xuefeng Yicun',
    name_es: 'Xuefeng Yicun',
    name_de: 'Xuefeng Yicun',
    name_fr: 'Xuefeng Yicun',
    name_vi: 'Tuyết Phong Nghĩa Tồn',
    name_ru: 'Xuefeng Yicun',
    name_zh: '雪峰义存',
    name_ja: 'Seppō Gison',
    name_ko: 'Xuefeng Yicun',
    name_ar: 'Xuefeng Yicun',
    birth_death_time: ['822', '908'],
    records: '',
    sect: '-',
    country: 'China',
    place: '-',
    teachers: ['Deshan Xuanjian'],
    successors: [''],
    disciples: ['Xuansha Shibei', 'Yunmen Wenyan', 'Baofu Congzhan', 'Changqing Huileng'],
    image: '/images/avatar.png',
    reference: ['https://terebess.hu/zen/xuefeng.html', 'https://wikipedia.org/wiki/Xuefeng_Yicun'],
  },
  {
    id: '39.6.8',
    generation: '39',
    name_en: 'Niaoke Daolin',
    name_es: 'Niaoke Daolin',
    name_de: 'Niaoke Daolin',
    name_fr: 'Niaoke Daolin',
    name_vi: 'Đạo Lâm Ô Khòa',
    name_ru: 'Niaoke Daolin',
    name_zh: '鳥窠道林',
    name_ja: 'Niaoke Daolin',
    name_ko: 'Niaoke Daolin',
    name_ar: 'Niaoke Daolin',
    birth_death_time: ['741', '824'],
    records: '',
    sect: '-',
    country: 'China',
    place: '-',
    teachers: ['Kinzan Dōkin'],
    successors: [''],
    disciples: ['Hàng Châu Hội Thông'],
    image: '/images/avatar.png',
    reference: ['https://en.wikipedia.org/wiki/Niaoke_Daolin'],
  },
  {
    id: '39.6.9',
    generation: '39',
    name_en: 'Yunju Daoying',
    name_es: 'Yunju Daoying',
    name_de: 'Yunju Daoying',
    name_fr: 'Yunju Daoying',
    name_vi: 'Vân Cư Đạo Ưng',
    name_ru: 'Yunju Daoying',
    name_zh: '雲居道膺',
    name_ja: 'Ungo Dōyō',
    name_ko: 'Yunju Daoying',
    name_ar: 'Yunju Daoying',
    birth_death_time: ['835', '902'],
    records: '',
    sect: '-',
    country: 'China',
    place: '-',
    teachers: ['Dongshan Liangjie'],
    successors: ['Tongan Daopi'],
    disciples: ['Tongan Daopi'],
    image: 'https://terebess.hu/zen/mesterek/woodcut/39-3.jpg',
    reference: ['https://terebess.hu/zen/mesterek/YunjuDaoying.html', 'https://en.wikipedia.org/wiki/Yunju_Daoying', 'https://vi.wikipedia.org/wiki/V%C3%A2n_C%C6%B0_%C4%90%E1%BA%A1o_%C6%AFng'],
  },
]
export default CnLv6MasterDb;
