const CnLv10MasterDb = [
  {
    id: '43.10.1',
    hasContent: 'true',
    name_en: 'Fenyang Shanzhao',
    name_es: 'Fenyang Shanzhao',
    name_de: 'Fenyang Shanzhao',
    name_fr: 'Fenyang Shanzhao',
    name_ru: 'Fenyang Shanzhao',
    name_ja: 'Funyō Zenshō',
    name_ko: '분양선소 Punyang Sŏnso',
    name_ar: 'Fenyang Shanzhao',
    name_zh: '汾陽善昭',
    name_vi: 'Phần Dương Thiện Chiêu',
    other_name_vi: 'Phần Dương Thiện Chiếu',
    nickname_vi: 'Vô Đức',
    worship_tower: '',
    birth_death_time: ['947', '1024'],
    records: '',
    sect: ['Linji'],
    country: 'China',
    place: '-',
    teachers: ['Shoushan Xingnian'],
    successors: ['Shishuang Chuyuan'],
    disciples: ['Shishuang Chuyuan'],
    image: '/images/avatar.png',
    reference: ['https://terebess.hu/zen/fenyang.html', 'https://pl.wikipedia.org/wiki/Fenyang_Shanzhao', 'https://vi.wikipedia.org/wiki/Ph%E1%BA%A7n_D%C6%B0%C6%A1ng_Thi%E1%BB%87n_Chi%E1%BA%BFu'],
  },
  {
    id: '43.10.2',
    hasContent: 'true',
    name_en: 'Tiantai Deshao',
    name_es: 'Tiantai Deshao',
    name_de: 'Tiantai Deshao',
    name_fr: 'Tiantai Deshao',
    name_ru: 'Tiantai Deshao',
    name_ja: 'Tendai Tokushō',
    name_ko: 'Tiantai Deshao',
    name_ar: 'Tiantai Deshao',
    name_zh: '天台德韶',
    name_vi: 'Thiên Thai Đức Thiều',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['891', '972'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Fayan Wenyi'],
    successors: [''],
    disciples: ['Yongming Yanshou', 'Trường Thọ Bằng Ngạn', 'Đại Ninh Khả Hoằng', 'Hoa Nghiêm Chí Phùng (五雲志逢, 910-986)', 'Vĩnh An Đạo Nguyên (永安道原)'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/Thi%C3%AAn_Thai_%C4%90%E1%BB%A9c_Thi%E1%BB%81u'],
  },
  {
    id: '43.10.3',
    hasContent: 'true',
    name_en: 'Xuedou Chongxian',
    name_es: 'Xuedou Chongxian',
    name_de: 'Xuedou Chongxian',
    name_fr: 'Xuedou Chongxian',
    name_ru: 'Xuedou Chongxian',
    name_ja: 'Setchō Jūken',
    name_ko: 'Xuedou Chongxian',
    name_ar: 'Xuedou Chongxian',
    name_zh: '雪竇重顯',
    name_vi: 'Tuyết Đậu Trọng Hiển',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['980', '1052'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Zhimen Guangzuo'],
    successors: [''],
    disciples: ['Tianyi Yihuai', 'Chengtian Chuanzong', 'Thảo Đường - 草堂 - 997-1047 - Tuân Phát Hỉ Túc'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/Tuy%E1%BA%BFt_%C4%90%E1%BA%ADu_Tr%E1%BB%8Dng_Hi%E1%BB%83n',
      'https://en.wikipedia.org/wiki/Xuedou_Chongxian', 'https://terebess.hu/zen/Xuedou.html'],
  },
  {
    id: '43.10.4',
    name_en: 'Kaixian Shanxian',
    name_es: 'Kaixian Shanxian',
    name_de: 'Kaixian Shanxian',
    name_fr: 'Kaixian Shanxian',
    name_ru: 'Kaixian Shanxian',
    name_ja: 'Kaixian Shanxian',
    name_ko: 'Kaixian Shanxian',
    name_ar: 'Kaixian Shanxian',
    name_zh: '開先善添',
    other_name_zh: '開先善暹',
    name_vi: 'Khai Tiên Thiện Tiêm',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    records: '',
    sect: ['Yunmen'],
    country: 'China',
    place: '-',
    teachers: ['Deshan Huiyuan'],
    successors: ['Fuyin Liaoyuan'],
    disciples: ['Fuyin Liaoyuan'],
    image: '/images/avatar.png',
    reference: ['https://www.buddhistelibrary.org/en/albums/central/Dhamma_books/07-1_Gongan_I_web.pdf',
      'https://mvseon.com/wp-content/uploads/2020/04/07-2_Gongan_II_web.pdf', 'https://terebess.hu/zen/mesterek/fold.pdf',
      'https://wisdomexperience.org/wp-content/uploads/2019/10/BPhil-3-Lesson-5-Reading-3.pdf',
      'https://ibdigital.uib.es/greenstone/sites/bdeo/collect/worksKoreanBuddhism/index/assoc/Collecte/d_Works_/Korean_B/uddhism_/v07_02.dir/Collected_Works_Korean_Buddhism_v07_02.pdf'],
  },
  {
    id: '43.10.5',
    name_en: 'Jiufeng Qin',
    name_es: 'Jiufeng Qin',
    name_de: 'Jiufeng Qin',
    name_fr: 'Jiufeng Qin',
    name_ru: 'Jiufeng Qin',
    name_ja: 'Kyūhō Gon',
    name_ko: '구봉근 Kubong Kŭn',
    name_ar: 'Jiufeng Qin',
    name_zh: '九峰勤',
    name_vi: 'Cửu Phong Cần',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Zhimen Guangzuo'],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '43.10.6',
    hasContent: 'true',
    name_en: 'Shexian Guixing',
    name_es: 'Shexian Guixing',
    name_de: 'Shexian Guixing',
    name_fr: 'Shexian Guixing',
    name_ru: 'Shexian Guixing',
    name_ja: 'Shōgen Kisei',
    other_name_ja: 'Sekken Kisei',
    name_ko: '섭현귀성 Sŏphyŏn Kwisŏng',
    name_ar: 'Shexian Guixing',
    name_zh: '葉縣歸省',
    name_vi: 'Diệp Huyện Quy Tỉnh',
    other_name_vi: 'Diệp Huyện Qui Tỉnh',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    records: '',
    sect: ['Linji'],
    country: 'China',
    place: '-',
    teachers: ['Shoushan Xingnian'],
    successors: [''],
    disciples: ['Fushan Fayuan'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/Di%E1%BB%87p_Huy%E1%BB%87n_Quy_T%E1%BB%89nh',
      'https://pl.wikipedia.org/wiki/Shexian_Guixing'],
  },
  {
    id: '43.10.7',
    hasContent: 'true',
    name_en: 'Dayang Jingxuan',
    other_name_en: 'Taiyang Jingxuan',
    name_es: 'Dayang Jingxuan',
    name_de: 'Dayang Jingxuan',
    name_fr: 'Dayang Jingxuan',
    name_ru: 'Dayang Jingxuan',
    name_ko: '대양경현 Taeyang Kyŏnghyŏn',
    name_ar: 'Dayang Jingxuan',
    name_ja: 'Taiyō Keigen',
    name_zh: '大陽警玄',
    name_vi: 'Đại Dương Kỉnh Huyền',
    other_name_vi: 'Thái Dương Cảnh Huyền',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['943', '1027'],
    records: '',
    sect: ['Caodong'],
    country: 'China',
    place: 'Dayang mountain',
    teachers: ['Liangshan Yuanguan'],
    successors: ['Touzi Yiqing*'],
    disciples: ['Touzi Yiqing*'],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Dayang_Jingxuan', 'https://pl.wikipedia.org/wiki/Shexian_Guixing'],
  },
  {
    id: '43.10.8',
    hasContent: 'true',
    name_en: 'Sanjiao Zhisong',
    other_name_en: 'Tang Ming',
    name_es: 'Sanjiao Zhisong',
    name_de: 'Sanjiao Zhisong',
    name_fr: 'Sanjiao Zhisong',
    name_ru: 'Sanjiao Zhisong',
    name_ko: 'Sanjiao Zhisong',
    name_ar: 'Sanjiao Zhisong',
    name_ja: 'Sanjiao Zhisong',
    name_zh: '三交智嵩',
    other_name_zh: '承天, 唐明',
    name_vi: 'Tam Giao Trí Tung',
    nickname_vi: 'Đường Minh',
    other_name_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    records: '',
    sect: ['Linji'],
    country: 'China',
    place: 'Chengtian monastery, Bingzhou (upstream Fenshui river, Shanxi)',
    teachers: ['Shoushan Xingnian'],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '43.10.9',
    hasContent: 'true',
    name_en: 'Dongshan Xiaocong',
    name_es: 'Dongshan Xiaocong',
    name_de: 'Dongshan Xiaocong',
    name_fr: 'Dongshan Xiaocong',
    name_ru: 'Dongshan Xiaocong',
    name_ar: 'Dongshan Xiaocong',
    name_ko: 'Dongshan Xiaocong',
    name_ja: 'Dōzan Kyōsō',
    name_zh: '洞山曉聰',
    name_vi: 'Động Sơn Hiểu Thông',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['?', '1030'],
    records: '',
    sect: ['Yunmen'],
    country: 'China',
    place: 'Dongshan, Junzhou (Gaoan, Jiangxi province)',
    teachers: ['Wenshu Yingzhen'],
    successors: ['Fori Qisong'],
    disciples: ['Fori Qisong'],
    image: '/images/square/meta-image-square-1.jpg',
    reference: ['https://phatgiao.org.vn/tu-dien-phat-hoc-online/dong-son-hieu-thong-k3950.html'],
  },
  {
    id: '43.10.10',
    hasContent: 'true',
    name_en: 'Dongshan Zibao',
    name_es: 'Dongshan Zibao',
    name_de: 'Dongshan Zibao',
    name_fr: 'Dongshan Zibao',
    name_ru: 'Dongshan Zibao',
    name_ar: 'Dongshan Zibao',
    name_ko: 'Dongshan Zibao',
    name_ja: 'Dongshan Zibao',
    name_zh: '洞山自寶',
    name_vi: 'Động Sơn Tự Bảo',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    records: '',
    sect: ['Yunmen'],
    country: 'China',
    place: 'Dongshan, Junzhou (Gaoan, Jiangxi province)',
    teachers: ['Wuzu Shijie'],
    successors: [''],
    disciples: [''],
    image: '/images/square/meta-image-square-1.jpg',
    reference: [''],
  },
  {
    id: '43.10.11',
    hasContent: 'true',
    name_en: 'Letan Huaicheng',
    name_es: 'Letan Huaicheng',
    name_de: 'Letan Huaicheng',
    name_fr: 'Letan Huaicheng',
    name_ru: 'Letan Huaicheng',
    name_ar: 'Letan Huaicheng',
    name_ko: 'Letan Huaicheng',
    name_ja: 'Letan Huaicheng',
    name_zh: '泐潭懷澄',
    name_vi: 'Lặc Đàm Hoài Trừng',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    records: '',
    sect: ['Yunmen'],
    country: 'China',
    place: '',
    teachers: ['Wuzu Shijie'],
    successors: ['Yuwang Huailian'],
    disciples: ['Yuwang Huailian'],
    image: '/images/square/meta-image-square-1.jpg',
    reference: ['https://blog.phapthihoi.org/gt-member/0-ts-lac-dam-hoai-trung/',
      'https://tuvienquangduc.com.au/Thien/124thienluan2-1a.html'],
  },
]
export default CnLv10MasterDb;
