const CnLv20MasterDb = [
  {
    id: '53.20.1',
    name_en: 'Wuzhun Shifan',
    name_es: 'Wuzhun Shifan',
    name_de: 'Wuzhun Shifan',
    name_fr: 'Wuzhun Shifan',
    name_vi: 'Vô Chuẩn Sư Phạm',
    name_ru: 'Wuzhun Shifan',
    name_zh: '無準師範 (Bushun Shihan)',
    name_ja: 'Kōke Zonshō',
    name_ko: 'Wuzhun Shifan',
    name_ar: 'Wuzhun Shifan',
    birth_death_time: ['1177', '1249'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Poan Zuxian'],
    successors: [''],
    disciples: ['Wuxue Zuyuan', 'Enni Benen', 'Xueyan Zuqin'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/V%C3%B4_Chu%E1%BA%A9n_S%C6%B0_Ph%E1%BA%A1m',],
  },
  {
    id: '53.20.2',
    name_en: 'Xueting Fuyu',
    name_es: 'Xueting Fuyu',
    name_de: 'Xueting Fuyu',
    name_fr: 'Xueting Fuyu',
    name_vi: 'Tuyết Đình Phúc Dụ',
    name_ru: 'Xueting Fuyu',
    name_zh: '雪庭福裕',
    name_ja: 'Xueting Fuyu',
    name_ko: 'Xueting Fuyu',
    name_ar: 'Xueting Fuyu',
    birth_death_time: ['1203', '1275'],
    records: '',
    sect: ['Caodong'],
    country: 'China',
    place: '-',
    teachers: ['Wansong Xingxiu'],
    successors: ['Lingyin Wentai'],
    disciples: ['Lingyin Wentai'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/Tuy%E1%BA%BFt_%C4%90%C3%ACnh_Ph%C3%BAc_D%E1%BB%A5',],
  },
]
export default CnLv20MasterDb;
