const CnLv19MasterDb = [
  {
    id: '52.19.1',
    name_en: 'Poan Zuxian',
    name_ja: 'Hoan Sosen',
    name_zh: '破庵祖先',
    name_vi: 'Phá Am Tổ Tiên',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1136', '1211'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Mian Xianjie'],
    successors: ['Wuzhun Shifan'],
    disciples: ['Wuzhun Shifan'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/Ph%C3%A1_Am_T%E1%BB%95_Ti%C3%AAn',],
  },
  {
    id: '52.19.2',
    name_en: 'Songyuan Chongyue',
    name_ja: 'Shōgen Sūgaku',
    name_zh: '松源崇岳',
    name_vi: 'Tùng Nguyên Sùng Nhạc',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1132/1139', '1202/1209'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Mian Xianjie'],
    successors: [''],
    disciples: ['Wuming Huixin', 'Yun’an Puyan'],
    image: '/images/avatar.png',
    reference: ['https://www.erct.com/2-ThoVan/NNT/Vomonquan/20-Dailucluongnhan.htm', 'http://en.lingyinsi.org/list_332.html',
      'https://phatgiao.org.vn/tu-dien-phat-hoc-online/tung-nguyen-sung-nhac-k3098.html', 'https://tangthuphathoc.net/tudien/tung-nguyen-sung-nhac-tu-dien-dao-uyen/',
      'https://pl.wikipedia.org/wiki/Songyuan_Chongyue', 'https://terebess.hu/zen/mesterek/SongyuanChongyue.html'
    ],
  },
  {
    id: '52.19.3',
    name_en: 'Tào Nguyên Đạo Sinh',
    name_ja: 'Tào Nguyên Đạo Sinh',
    name_zh: 'Tào Nguyên Đạo Sinh',
    name_vi: 'Tào Nguyên Đạo Sinh',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Mian Xianjie'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '52.19.4',
    name_en: 'Wansong Xingxiu',
    name_ja: 'Wansong Xingxiu',
    name_zh: '萬松行秀',
    name_vi: 'Vạn Tùng Hành Tú',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1166', '1246'],
    epoch: '',
    records: '',
    sect: ['Caodong'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Xueyan Huiman'],
    successors: ['Xueting Fuyu'],
    disciples: ['Xueting Fuyu'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/V%E1%BA%A1n_T%C3%B9ng_H%C3%A0nh_T%C3%BA',],
  },
  {
    id: '52.19.5',
    name_en: 'Eisai Myōan',
    other_name_en: 'Myōan Yōsai',
    name_ja: 'Senkō Kokushi',
    other_name_ja: 'Shukke taikō',
    name_zh: '栄西明菴',
    other_name_zh: '明菴榮西',
    name_vi: 'Tuyết Am Tùng Cẩn',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1141', '1215'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Huanglong'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Xu\'an Huaichang'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://terebess.hu/zen/mesterek/eisai.html',],
  },
]
export default CnLv19MasterDb;
