const CnLv10MasterDb = [
  {
    id: '43.10.1',
    hasContent: 'true',
    name_en: 'Fenyang Shanzhao',
    name_ja: 'Funyō Zenshō',
    name_zh: '汾陽善昭',
    pinyin: '',
    name_vi: 'Phần Dương Thiện Chiêu',
    other_name_vi: 'Phần Dương Thiện Chiếu',
    nickname_vi: 'Vô Đức',
    worship_tower: '',
    birth_death_time: ['947', '1024'],
    epoch: '',
    records: '',
    sect: ['Linji'],
    country: 'China',
    place: '-',
    teachers: ['Shoushan Xingnian'],
    successors: ['Shishuang Chuyuan'],
    disciples: ['Shishuang Chuyuan', 'Dongshan Shouzhi', 'Dayu Shouzhi', 'Langye Huijue'],
    image: '/images/avatar.png',
    reference: ['https://terebess.hu/zen/fenyang.html', 'https://pl.wikipedia.org/wiki/Fenyang_Shanzhao',
      'https://vi.wikipedia.org/wiki/Ph%E1%BA%A7n_D%C6%B0%C6%A1ng_Thi%E1%BB%87n_Chi%E1%BA%BFu'],
  },
  {
    id: '43.10.2',
    hasContent: 'true',
    name_en: 'Tiantai Deshao',
    name_ja: 'Tendai Tokushō',
    name_zh: '天台德韶',
    pinyin: '',
    name_vi: 'Thiên Thai Đức Thiều',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['891', '972'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Fayan Wenyi'],
    successors: [''],
    disciples: ['Yongming Yanshou', 'Trường Thọ Bằng Ngạn', 'Đại Ninh Khả Hoằng', 'Wuyun Zhifeng - Hoa Nghiêm Chí Phùng (五雲志逢, 910-986)',
      ' Yong’an Daoyuan - Vĩnh An Đạo Nguyên (永安道原)', 'Đoan Lộc Bản Tiên 端鹿本先 (942-1008)', 'Hoa Nghiêm Huệ Đạt 華嚴慧達 (909-985)', 'Longce Xiaorong - 龍冊曉榮'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/Thi%C3%AAn_Thai_%C4%90%E1%BB%A9c_Thi%E1%BB%81u', 'https://pl.wikipedia.org/wiki/Jingde_chuandeng_lu'],
  },
  {
    id: '43.10.3',
    hasContent: 'true',
    name_en: 'Xuedou Chongxian',
    name_ja: 'Setchō Jūken',
    name_zh: '雪竇重顯',
    name_vi: 'Tuyết Đậu Trọng Hiển',
    other_name_vi: 'Tuyết Đậu Trùng Hiển',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['980', '1052'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Zhimen Guangzuo'],
    successors: [''],
    disciples: ['Tianyi Yihuai', 'Chengtian Chuanzong', 'Thảo Đường - 草堂 - 997-1047 - Tuân Phát Hỉ Túc'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/Tuy%E1%BA%BFt_%C4%90%E1%BA%ADu_Tr%E1%BB%8Dng_Hi%E1%BB%83n',
      'https://en.wikipedia.org/wiki/Xuedou_Chongxian', 'https://terebess.hu/zen/Xuedou.html'],
  },
  {
    id: '43.10.4',
    name_en: 'Kaixian Shanxian',
    name_ja: 'Kaixian Shanxian',
    name_zh: '開先善添',
    other_name_zh: '開先善暹',
    pinyin: '',
    name_vi: 'Khai Tiên Thiện Tiêm',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    records: '',
    sect: ['Yunmen'],
    country: 'China',
    place: '-',
    teachers: ['Deshan Huiyuan'],
    successors: ['Fuyin Liaoyuan'],
    disciples: ['Fuyin Liaoyuan'],
    image: '/images/avatar.png',
    reference: ['https://www.buddhistelibrary.org/en/albums/central/Dhamma_books/07-1_Gongan_I_web.pdf',
      'https://mvseon.com/wp-content/uploads/2020/04/07-2_Gongan_II_web.pdf', 'https://terebess.hu/zen/mesterek/fold.pdf',
      'https://wisdomexperience.org/wp-content/uploads/2019/10/BPhil-3-Lesson-5-Reading-3.pdf',
      'https://ibdigital.uib.es/greenstone/sites/bdeo/collect/worksKoreanBuddhism/index/assoc/Collecte/d_Works_/Korean_B/uddhism_/v07_02.dir/Collected_Works_Korean_Buddhism_v07_02.pdf'],
  },
  {
    id: '43.10.5',
    name_en: 'Jiufeng Qin',
    name_ja: 'Kyūhō Gon',
    name_zh: '九峰勤',
    pinyin: '',
    name_vi: 'Cửu Phong Cần',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Zhimen Guangzuo'],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '43.10.6',
    hasContent: 'true',
    name_en: 'Shexian Guixing',
    name_ja: 'Shōgen Kisei',
    other_name_ja: 'Sekken Kisei',
    name_zh: '葉縣歸省',
    pinyin: '',
    name_vi: 'Diệp Huyện Quy Tỉnh',
    other_name_vi: 'Diệp Huyện Qui Tỉnh',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    records: '',
    sect: ['Linji'],
    country: 'China',
    place: '-',
    teachers: ['Shoushan Xingnian'],
    successors: [''],
    disciples: ['Fushan Fayuan'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/Di%E1%BB%87p_Huy%E1%BB%87n_Quy_T%E1%BB%89nh',
      'https://pl.wikipedia.org/wiki/Shexian_Guixing'],
  },
  {
    id: '43.10.7',
    hasContent: 'true',
    name_en: 'Dayang Jingxuan',
    other_name_en: 'Taiyang Jingxuan',
    name_ja: 'Taiyō Keigen',
    name_zh: '大陽警玄',
    pinyin: '',
    name_vi: 'Đại Dương Kỉnh Huyền',
    other_name_vi: 'Thái Dương Cảnh Huyền',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['943', '1027'],
    records: '',
    sect: ['Caodong'],
    country: 'China',
    place: 'Dayang mountain',
    teachers: ['Liangshan Yuanguan'],
    successors: ['Touzi Yiqing*'],
    disciples: ['Touzi Yiqing*'],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Dayang_Jingxuan', 'https://pl.wikipedia.org/wiki/Shexian_Guixing'],
  },
  {
    id: '43.10.8',
    hasContent: 'true',
    name_en: 'Sanjiao Zhisong',
    other_name_en: 'Tang Ming',
    name_ja: 'Sanjiao Zhisong',
    name_zh: '三交智嵩',
    other_name_zh: '承天, 唐明',
    pinyin: '',
    name_vi: 'Tam Giao Trí Tung',
    nickname_vi: 'Đường Minh',
    other_name_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    records: '',
    sect: ['Linji'],
    country: 'China',
    place: 'Chengtian monastery, Bingzhou (upstream Fenshui river, Shanxi)',
    teachers: ['Shoushan Xingnian'],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '43.10.9',
    hasContent: 'true',
    name_en: 'Dongshan Xiaocong',
    name_ja: 'Dōzan Kyōsō',
    name_zh: '洞山曉聰',
    pinyin: '',
    name_vi: 'Động Sơn Hiểu Thông',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', '1030'],
    records: '',
    sect: ['Yunmen'],
    country: 'China',
    place: 'Dongshan, Junzhou (Gaoan, Jiangxi province)',
    teachers: ['Wenshu Yingzhen'],
    successors: ['Fori Qisong'],
    disciples: ['Fori Qisong'],
    image: '/images/square/meta-image-square-1.jpg',
    reference: ['https://phatgiao.org.vn/tu-dien-phat-hoc-online/dong-son-hieu-thong-k3950.html'],
  },
  {
    id: '43.10.10',
    hasContent: 'true',
    name_en: 'Dongshan Zibao',
    name_ja: 'Dongshan Zibao',
    name_zh: '洞山自寶',
    pinyin: '',
    name_vi: 'Động Sơn Tự Bảo',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    records: '',
    sect: ['Yunmen'],
    country: 'China',
    place: 'Dongshan, Junzhou (Gaoan, Jiangxi province)',
    teachers: ['Wuzu Shijie'],
    successors: [''],
    disciples: [''],
    image: '/images/square/meta-image-square-1.jpg',
    reference: [''],
  },
  {
    id: '43.10.11',
    hasContent: 'true',
    name_en: 'Letan Huaicheng',
    name_ja: 'Letan Huaicheng',
    name_zh: '泐潭懷澄',
    pinyin: '',
    name_vi: 'Lặc Đàm Hoài Trừng',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    records: '',
    sect: ['Yunmen'],
    country: 'China',
    place: '',
    teachers: ['Wuzu Shijie'],
    successors: ['Yuwang Huailian'],
    disciples: ['Yuwang Huailian'],
    image: '/images/square/meta-image-square-1.jpg',
    reference: ['https://blog.phapthihoi.org/gt-member/0-ts-lac-dam-hoai-trung/',
      'https://tuvienquangduc.com.au/Thien/124thienluan2-1a.html'],
  },
  {
    id: '43.10.12',
    hasContent: true,
    name_en: 'Beichan Zhixian',
    name_ja: 'Beichan Zhixian',
    name_zh: '北禪智賢',
    pinyin: '',
    name_vi: 'Bắc Thiền Trí Hiền',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    records: '',
    sect: ['Yunmen'],
    country: 'China',
    place: 'viện Bắc thiền tại Thường ninh Hành châu (Hồ nam)',
    teachers: ['Fuyan Liangya'],
    successors: ['Fachang Yiyu'],
    disciples: ['Fachang Yiyu'],
    image: '/images/avatar.png',
    reference: ['https://phatgiao.org.vn/tu-dien-phat-hoc-online/bac-thien-phanh-nguu-k29322.html',],
  },
  {
    id: '43.10.13',
    hasContent: 'true',
    name_en: 'Chongshou Qichou',
    name_ja: 'Sūju Keichū',
    name_zh: '崇寿契稠',
    other_name_zh: '崇壽契稠',
    pinyin: '',
    name_vi: 'Sùng Thọ Khế Trừu',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', '992'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Fayan Wenyi'],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Chongshou_Qichou'],
  },
  {
    id: '43.10.14',
    hasContent: 'true',
    name_en: 'Guizong Cezhen',
    name_ja: 'Kishū Sakushin',
    name_zh: '归宗策真',
    pinyin: '',
    other_name_zh: '崇壽契稠',
    name_vi: 'Qui Tông Sách Chân',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', '972'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Fayan Wenyi'],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Guizong_Cezhen'],
  },
  {
    id: '43.10.15',
    hasContent: 'true',
    name_en: 'Baoen Huiming',
    name_ja: 'Baoen Huiming',
    name_zh: '報恩慧明',
    pinyin: '',
    name_vi: 'Báo Ân Huệ Minh',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['884/889', '954/959'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Fayan Wenyi'],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: ['https://hoavouu.com/p24a17646/60-thien-su-hue-minh-o-chua-bao-an'],
  },
  {
    id: '43.10.16',
    hasContent: 'true',
    name_en: 'Baizhang Daoheng',
    other_name_en: 'Baizhang Daochang',
    name_ja: 'Baizhang Daoheng',
    name_zh: '百丈道恒',
    pinyin: 'Pai Chang Tao Ch’ang',
    name_vi: 'Bá Trượng Đạo Hằng',
    other_name_vi: 'Bách Trượng Đạo Hằng',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', '991'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Fayan Wenyi'],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: ['https://zenmarrow.com/Single?id=56&index=sho', 'https://zenmarrow.com/Single?id=26&index=sho'],
  },
  {
    id: '43.10.17',
    name_en: 'Xingyang Ciduo',
    name_ja: 'Xingyang Ciduo',
    name_zh: '興陽詞鐸',
    pinyin: '',
    name_vi: 'Xingyang Ciduo',
    other_name_vi: 'Bách Trượng Đạo Hằng',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: ['Guiyang'],
    country: 'China',
    place: '-',
    teachers: ['Sanjiao Zhiqian'],
    successors: ['Deqing Yanche (Xuyun)'],
    disciples: ['Deqing Yanche (Xuyun)'],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Xingyang_Ciduo'],
  },
]
export default CnLv10MasterDb;
