const CnLv28MasterDb = [
  {
    id: '61.28.1',
    name_en: 'Yuezhou Wenzai',
    name_ja: 'Yuezhou Wenzai',
    name_zh: '月舟文載',
    name_vi: 'Nguyệt Chu Văn Tải',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1452', '1524'],
    epoch: '',
    records: '',
    sect: ['Caodong'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Wufang Kecong'],
    successors: ['Zongjing Zongshu'],
    disciples: ['Zongjing Zongshu'],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '61.28.2',
    name_en: 'Haizhou Puci',
    name_ja: 'Kaishū Eiji',
    name_zh: '海舟普慈',
    name_vi: 'Hải Chu Phổ Từ',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1355/1393?', '1450/1461?'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dongming Huichan'],
    successors: ['Baofeng Mingxuan'],
    disciples: ['Baofeng Mingxuan'],
    image: '/images/avatar.png',
    reference: [''],
  }
]
export default CnLv28MasterDb;
