const CnLv58MasterDb = [
  {
    id: '91.58.1',
    hasContent: true,
    name_en: 'Deqing Yanche',
    other_name_en: 'Xuyun, Hsu Yun, Xuyun Xingche',
    name_es: 'Deqing Yanche',
    name_de: 'Deqing Yanche',
    name_fr: 'Deqing Yanche',
    name_ru: 'Deqing Yanche',
    name_ar: 'Deqing Yanche',
    name_ko: 'Deqing Yanche',
    name_ja: 'Deqing Yanche',
    name_zh: '德清演徹',
    other_name_zh: '虛雲性徹',
    nickname_zh: '虛雲',
    name_vi: 'Đức Thanh Diễn Triệt',
    other_name_vi: '',
    nickname_vi: 'Hư Vân',
    worship_tower: '',
    birth_death_time: ['1840', '1959'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: 'Zhenru Temple, Jiangxi, China',
    teachers: ['Shanci Changkai', 'Yung Ching', 'Miaolian Dihua 妙莲地华 / Juehua 觉华 (42nd Linji)',
      'Xingyang Ciduo 兴阳词铎 (7th Weiyang/Guiyang)',
      'Yi’an Shenjing 已庵深淨 (11th Yunmen)',
      'Xiangfu Liangqing 祥符良庆 (7th Fayan)',
      'Dingfeng Yaocheng 鼎峰耀成 (46th Caodong)',
    ],
    successors: [''],
    disciples: ['Fohui Kuanyin'],
    image: '/images/avatar.png',
    reference: ['https://en.m.wikipedia.org/wiki/Xuyun', 'https://terebess.hu/zen/mesterek/Xuyun.html'],
  }
]
export default CnLv58MasterDb;
