const CnLv33MasterDb = [
  {
    id: '65.32.1',
    hasContent: true,
    name_en: '',
    name_es: '',
    name_de: '',
    name_fr: '',
    name_ru: '',
    name_zh: '',
    name_ja: '',
    name_ko: '',
    name_ar: '',
    name_vi: '',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '',
    teachers: [''],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: [''],
  }
]
export default CnLv33MasterDb;
