const CnLv6MasterDb = [
  {
    id: 39.1,
    name_en: 'Caoshan Benji',
    name_es: 'Caoshan Benji',
    name_de: 'Caoshan Benji',
    name_fr: 'Caoshan Benji',
    name_vi: 'Tào Sơn Bản Tịch',
    name_ru: 'Caoshan Benji',
    name_zh: '曹山本寂',
    name_ja: 'Sōzan Honjaku',
    name_ko: 'Caoshan Benji',
    name_ar: 'Caoshan Benji',
    birth_death_time: ['840', '883'],
    records: '',
    sect: '-',
    country: 'China',
    place: '-',
    teachers: ['Dongshan Liangjie'],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: 39.2,
    name_en: 'Xinghua Cunjiang',
    name_es: 'Xinghua Cunjiang',
    name_de: 'Xinghua Cunjiang',
    name_fr: 'Xinghua Cunjiang',
    name_vi: 'Hưng Hóa Tồn Tương',
    name_ru: 'Xinghua Cunjiang',
    name_zh: '興化存奬',
    name_ja: 'Kōke Zonshō',
    name_ko: 'Xinghua Cunjiang',
    name_ar: 'Xinghua Cunjiang',
    birth_death_time: ['830', '888'],
    records: '',
    sect: '-',
    country: 'China',
    place: '-',
    teachers: ['Linji Yixuan'],
    successors: ['Nanyuan Huiyong'],
    disciples: ['Nanyuan Huiyong'],
    image: '/images/avatar.png',
    reference: ['https://terebess.hu/zen/xinghua.html', 'https://phatgiao.org.vn/tu-dien-phat-hoc-online/hung-hoa-ton-tuong-k4195.html', 'https://vi.wikipedia.org/wiki/H%C6%B0ng_H%C3%B3a_T%E1%BB%93n_T%C6%B0%C6%A1ng'],
  },
]
export default CnLv6MasterDb;
