const CnLv56MasterDb = [
  {
    id: '89.56.1',
    name_en: 'Yuelang Quanding',
    name_ja: 'Getsurō Zentei',
    name_zh: '月朗全定',
    name_vi: 'Nguyệt Lãng Quan Đỉnh',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: ['Linji'],
    country: 'China',
    place: 'Gaomin Temple/Monastery (高旻寺), Hanjiang District, Yangzhou, China',
    teachers: ['Langhui Shirong'],
    successors: ['Mingxuan Xirui'],
    disciples: ['Mingxuan Xirui'],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '89.56.2',
    name_en: 'Chuchan Quanzhen',
    name_ja: 'Sozen Zenshin',
    name_zh: '楚禅全振',
    name_vi: 'Chu Chân Quán Chân',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: ['Linji'],
    country: 'China',
    place: 'Gaomin Temple/Monastery (高旻寺), Hanjiang District, Yangzhou, China',
    teachers: ['Langhui Shirong'],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: [''],
  },
]
export default CnLv56MasterDb;
