const CnLv11MasterDb = [
  {
    id: '44.11.1',
    hasContent: true,
    name_en: 'Shishuang Chuyuan',
    other_name_en: 'Ciming',
    name_ja: 'Sekisō Soen',
    name_zh: '石霜楚圓',
    pinyin: '',
    nickname_zh: '慈明',
    name_vi: 'Thạch Sương Sở Viên',
    other_name_vi: '',
    nickname_vi: 'Từ Minh',
    worship_tower: '',
    birth_death_time: ['986', '1039'],
    epoch: '',
    records: '',
    sect: ['Linji'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Fenyang Shanzhao'],
    successors: ['Yangqi Fanghui', 'Huanglong Huinan'],
    disciples: ['Yangqi Fanghui', 'Huanglong Huinan', 'Cuiyan Kezhen', 'Daning Daokuan', 'Daowu Wuzhen', 'Guquan Dadao'],
    image: 'https://terebess.hu/zen/mesterek/Ciming.gif',
    reference: ['https://terebess.hu/zen/shishuang.html', 'https://en.wikipedia.org/wiki/Shishuang_Temple',
      'https://vi.wikipedia.org/wiki/Th%E1%BA%A1ch_S%C6%B0%C6%A1ng_S%E1%BB%9F_Vi%C3%AAn', 'https://pl.wikipedia.org/wiki/Shishuang_Chuyuan'],
  },
  {
    id: '44.11.2',
    hasContent: true,
    name_en: 'Yongming Yanshou',
    name_ja: 'Yōmyō Enju',
    name_zh: '永明延壽',
    other_name_zh: '永明延寿',
    pinyin: '',
    name_vi: 'Vĩnh Minh Diên Thọ',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['904', '976'],
    epoch: '',
    records: '',
    sect: ['Fayan', 'Pure land'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Tiantai Deshao'],
    successors: [''],
    disciples: ['Triều Minh Viện Tân (朝明院津)', 'Phú Dương Tử Bàng (富陽子蒙)'],
    image: '',
    reference: ['https://en.wikipedia.org/wiki/Yongming_Yanshou', 'https://blog.phapthihoi.org/tu-dien-phat-giao/vinh-minh-dien-tho/'],
  },
  {
    id: '44.11.3',
    hasContent: true,
    name_en: 'Fuyin Liaoyuan',
    name_ja: 'Butsuin Ryōgen',
    name_zh: '佛印了元',
    pinyin: '',
    name_vi: 'Phật Ấn Liễu Nguyên',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1032', '1098'],
    epoch: '',
    records: '',
    sect: ['Yunmen'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Kaixian Shanxian'],
    successors: [''],
    disciples: [],
    image: '',
    reference: ['https://terebess.hu/zen/mesterek/fold.pdf'],
  },
  {
    id: '44.11.4',
    hasContent: true,
    name_en: 'Tianyi Yihuai',
    name_ja: 'Tenne Gikai',
    name_zh: '天衣義懷',
    pinyin: '',
    name_vi: 'Thiên Y Nghĩa Hoài',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['993', '1064'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Xuedou Chongxian'],
    successors: ['Yuantong Fashen'],
    disciples: ['Yuantong Fashen - Viên Thông Pháp Tú - Entsû Hôshû', 'Yang Wuwei - Yô Mui', 'Shi Zongben - Viên Chiếu Tông Bản - 圓照宗本 - 1020?-1099'],
    image: '',
    reference: ['https://vi.wikipedia.org/wiki/Thi%C3%AAn_Y_Ngh%C4%A9a_Ho%C3%A0i'],
  },
  {
    id: '44.11.5',
    hasContent: true,
    name_en: 'Chengtian Chuanzong',
    name_ja: 'Shōten Denshū',
    name_zh: '承天传宗',
    other_name_zh: '承天傳宗',
    pinyin: '',
    name_vi: 'Thừa Thiên Truyền Tông',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Xuedou Chongxian'],
    successors: [''],
    disciples: [],
    image: '',
    reference: ['https://pl.wikipedia.org/wiki/Chengtian_Chuanzong'],
  },
  {
    id: '44.11.6',
    hasContent: true,
    name_en: 'Thảo Đường',
    name_ja: 'Thảo Đường',
    name_zh: '草堂',
    pinyin: '',
    name_vi: 'Thảo Đường',
    other_name_vi: 'Tuân Phát Hỉ Túc',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['997', '1047'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Xuedou Chongxian'],
    successors: [''],
    disciples: [],
    image: '',
    reference: ['https://vi.wikipedia.org/wiki/Th%E1%BA%A3o_%C4%90%C6%B0%E1%BB%9Dng'],
  },
  {
    id: '44.11.7',
    hasContent: true,
    name_en: 'Fushan Fayuan',
    name_ja: 'Fuzan Hōen',
    name_zh: '浮山法遠',
    pinyin: '',
    name_vi: 'Phù Sơn Pháp Viễn',
    other_name_vi: '',
    nickname_vi: 'Viên Giám',
    worship_tower: '',
    birth_death_time: ['991', '1067'],
    epoch: '',
    records: '',
    sect: ['Linji'],
    country: '🇨🇳',
    place: 'Phù Sơn (浮山), Thư Châu (舒州, Tỉnh An Huy)',
    teachers: ['Shexian Guixing'],
    successors: ['Touzi Yiqing*'],
    disciples: ['Touzi Yiqing*'],
    image: '',
    reference: ['https://pl.wikipedia.org/wiki/Fushan_Fayuan', 'https://phatgiao.org.vn/tu-dien-phat-hoc-online/phu-son-phap-vien-k5043.html'],
  },
  {
    id: '44.11.8',
    hasContent: true,
    name_en: 'Yuwang Huailian',
    other_name_en: 'Dajue Huailian',
    name_ja: 'Yuwang Huailian',
    name_zh: '育王懷璉',
    pinyin: '',
    name_vi: 'Dục Vương Hoài Liễn',
    other_name_vi: 'Hoài Liên',
    nickname_vi: 'Đại Giác',
    worship_tower: '',
    birth_death_time: ['1010', '1090/1091'],
    epoch: '',
    records: '',
    sect: ['Yunmen'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Letan Huaicheng'],
    successors: [''],
    disciples: [],
    image: '',
    reference: ['https://blog.phapthihoi.org/tu-dien-phat-giao/dai-giac-hoai-lien/'],
  },
  {
    id: '44.11.9',
    name_en: 'Fori Qisong',
    name_ja: 'Butsunichi Sessū',
    name_zh: '佛日契嵩',
    pinyin: '',
    name_vi: 'Phật Nhật Khế Tung',
    other_name_vi: 'Trọng Linh, Tiềm Tử',
    nickname_vi: 'Minh Giáo',
    worship_tower: '',
    birth_death_time: ['1007', '1072'],
    epoch: '',
    records: '',
    sect: ['Yunmen'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dongshan Xiaocong'],
    successors: [''],
    disciples: [],
    image: '',
    reference: ['https://pl.wikipedia.org/wiki/Fori_Qisong'],
  },
  {
    id: '44.11.10',
    name_en: 'Fachang Yiyu',
    other_name_en: 'Fashang Yu; Fachang Yu',
    name_ja: 'Fachang Yiyu',
    name_zh: '法昌倚遇',
    pinyin: '',
    name_vi: 'Pháp Xương Ỷ Ngộ',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: ['Yunmen'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Beichan Zhixian'],
    successors: [''],
    disciples: [],
    image: '',
    reference: ['https://hoavouu.com/a17657/69-thien-su-y-ngo-o-phap-xuong'],
  },
  {
    id: '44.11.11',
    hasContent: true,
    name_en: 'Wuyun Zhifeng',
    name_ja: 'Wuyun Zhifeng',
    name_zh: '永明延壽',
    pinyin: '',
    name_vi: 'Hoa Nghiêm Chí Phùng',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['904', '976'],
    epoch: '',
    records: '',
    sect: ['Fayan'],
    country: '🇨🇳',
    place: 'núi Ngũ Vân',
    teachers: ['Tiantai Deshao'],
    successors: [''],
    disciples: [],
    image: '',
    reference: ['https://en.wikipedia.org/wiki/Yongming_Yanshou', 'https://blog.phapthihoi.org/tu-dien-phat-giao/vinh-minh-dien-tho/'],
  },
]
export default CnLv11MasterDb;
