const CnLv15MasterDb = [
  {
    id: '48.15.1',
    hasContent: true,
    isEminent: true,
    name_en: 'Yuanwu Keqin',
    name_ja: 'Engo Kokugon',
    name_zh: '圓悟克勤',
    pinyin: '',
    name_vi: 'Viên Ngộ Khắc Cần',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1063', '1135'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: 'China',
    place: '-',
    teachers: ['Wuzu Fayan'],
    successors: [''],
    disciples: ['Huqiu Shaolong', 'Huguo Jingyuan?', 'Wuyong Jingquan?', 'Dahui Zonggao', 'Miyin Anmin',
      'Foxing Fatai', 'Cunpu Chanren', 'Xiangyun Tanyi', 'Xiatang Huiyuan'
    ],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/Vi%C3%AAn_Ng%E1%BB%99_Kh%E1%BA%AFc_C%E1%BA%A7n',],
  },
  {
    id: '48.15.2',
    name_en: 'Kaifu Daoning',
    name_ja: 'Kaifuku Dōnei',
    name_zh: '開福道寧',
    pinyin: '',
    name_vi: 'Khai Phúc Đạo Ninh',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1053', '1113'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: 'China',
    place: '-',
    teachers: ['Wuzu Fayan'],
    successors: ['Yuehan Shanguo'],
    disciples: ['Yuehan Shanguo'],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Kaifu_Daoning',],
  },
  {
    id: '48.15.3',
    name_en: 'Puzhao Yibian',
    name_ja: 'Puzhao Yibian',
    name_zh: '普照一辯',
    pinyin: '',
    name_vi: 'Phổ Chiếu Nhất Biện',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1081', '1149'],
    epoch: '',
    records: '',
    sect: ['Caodong'],
    country: 'China',
    place: '-',
    teachers: ['Lumen Zijue'],
    successors: ['Lingyan Sengbao'],
    disciples: ['Lingyan Sengbao'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/Ph%E1%BB%95_Chi%E1%BA%BFu_Nh%E1%BA%A5t_Bi%E1%BB%87n',],
  },
  {
    id: '48.15.4',
    hasContent: true,
    isEminent: true,
    name_en: 'Foyan Qingyuan',
    name_ja: 'Butsugen Seion',
    name_zh: '佛眼清遠',
    pinyin: '',
    name_vi: 'Phật Nhãn Thanh Viễn',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1067', '1120'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: 'China',
    place: 'Thiên Ninh Vạn Thọ Tự (天寧萬壽寺)  Thư Châu; Long Môn Tự (龍門寺); Bảo Sơn Tự (褒山寺) ở Hòa Châu (和州, Tỉnh An Huy)',
    teachers: ['Wuzu Fayan'],
    successors: ['Zhu’an Shigui'],
    disciples: ['Gao’an Shanwu' , 'Zhu’an Shigui'],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Foyan_Qingyuan', 'https://phatgiao.org.vn/tu-dien-phat-hoc-online/phat-nhan-thanh-vien-k4994.html'],
  },
]
export default CnLv15MasterDb;
