const CnLv17MasterDb = [
  {
    id: '50.17.1',
    name_en: 'Yingan Tanhua',
    name_es: 'Yingan Tanhua',
    name_de: 'Yingan Tanhua',
    name_fr: 'Yingan Tanhua',
    name_vi: 'Ứng Am Đàm Hoa',
    name_ru: 'Yingan Tanhua',
    name_zh: '應菴曇華',
    name_ja: 'Ōan Donge',
    name_ko: 'Yingan Tanhua',
    name_ar: 'Yingan Tanhua',
    birth_death_time: ['1103', '1163'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Huqiu Shaolong'],
    successors: ['Mian Xianjie'],
    disciples: ['Mian Xianjie', 'Hoà Sơn Tâm Giám'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/%E1%BB%A8ng_Am_%C4%90%C3%A0m_Hoa',],
  },
  {
    id: '50.17.2',
    name_en: 'Wakuan Shitai',
    name_es: 'Wakuan Shitai',
    name_de: 'Wakuan Shitai',
    name_fr: 'Wakuan Shitai',
    name_vi: 'Hoặc Am Sư Thể',
    name_ru: 'Wakuan Shitai',
    name_zh: '或菴師體 ',
    name_ja: 'Huoan Shiti',
    name_ko: 'Wakuan Shitai',
    name_ar: 'Wakuan Shitai',
    birth_death_time: ['1108', '1179'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Huguo Jingyuan'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://terebess.hu/zen/entangling.html', 'https://www.bachduongky.net/danh-muc/huyen-quan-tu-tri-quan/3', 'http://chimvie3.free.fr/27/vomonquan.htm', 'https://nigioikhatsi.net/kinhsach-pdf/CotNhucCuaThien_TranTrucLam.pdf'],
  },
  {
    id: '50.17.3',
    name_en: 'Fozhao Deguang',
    name_es: 'Fozhao Deguang',
    name_de: 'Fozhao Deguang',
    name_fr: 'Fozhao Deguang',
    name_vi: 'Fozhao Deguang',
    name_ru: 'Fozhao Deguang',
    name_zh: 'Fozhao Deguang ',
    name_ja: 'Fozhao Deguang',
    name_ko: 'Fozhao Deguang',
    name_ar: 'Fozhao Deguang',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Dahui Zonggao'],
    successors: [''],
    disciples: ['Jingshan Ruyan', 'Pojian Jujian'],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '50.17.4',
    name_en: 'Tế Điên Đạo Tế',
    name_es: 'Tế Điên Đạo Tế',
    name_de: 'Tế Điên Đạo Tế',
    name_fr: 'Tế Điên Đạo Tế',
    name_vi: 'Tế Điên Đạo Tế',
    name_ru: 'Tế Điên Đạo Tế',
    name_zh: 'Tế Điên Đạo Tế ',
    name_ja: 'Tế Điên Đạo Tế',
    name_ko: 'Tế Điên Đạo Tế',
    name_ar: 'Tế Điên Đạo Tế',
    birth_death_time: ['1130 ', '1209'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Shi Huiyuan'],
    successors: [''],
    disciples: [],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Daoji.JPG/250px-Daoji.JPG',
    reference: ['https://vi.wikipedia.org/wiki/T%E1%BA%BF_C%C3%B4ng',],
  },
]
export default CnLv17MasterDb;
