const CnLv33MasterDb = [
  {
    id: '66.33.1',
    name_en: 'Yunqi Zhuhong',
    name_ja: 'Unsei Shukō',
    name_zh: '雲棲袾宏',
    name_vi: 'Vân Thê Châu Hoằng',
    other_name_vi: 'Liên Trì Đại Sư',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1535', '1615'],
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Xiaoyan Debao'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '66.33.2',
    name_en: 'Huanyou Zhengchuan',
    name_ja: 'Genyū Shōden',
    name_zh: '幻有正傳',
    name_vi: 'Huyễn Hữu Chính Truyền',
    other_name_vi: 'Huyễn Hữu Chánh Truyền',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1549', '14/2/1614'],
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: '🇨🇳',
    place: 'Vũ Môn Thiền Viện (禹門禪院) -Long Trì Sơn (龍池山), Kinh Khê - 3 năm; Bí Ma Nham Tự (秘魔巖寺) - Thanh Lương Sơn (清涼山); khai sáng Phổ Chiếu Tự (普照寺) - Yến Sơn (燕山, Tỉnh Hà Bắc)',
    teachers: ['Xiaoyan Debao'],
    successors: ['Miyun Yuanwu'],
    disciples: ['Miyun Yuanwu', 'Yufeng Yuanxin', 'Tianyin Yuanxiu'],
    image: '/images/avatar.png',
    reference: ['https://phatgiao.org.vn/tu-dien-phat-hoc-online/huyen-huu-chanh-truyen-k4231.html'],
  },
]
export default CnLv33MasterDb;
