const CnLv2MasterDb = [
  {
    id: 36.1,
    name_en: 'Kinh Nam Duy Trung',
    name_es: 'Kinh Nam Duy Trung',
    name_de: 'Kinh Nam Duy Trung',
    name_fr: 'Kinh Nam Duy Trung',
    name_vi: 'Kinh Nam Duy Trung',
    name_ru: 'Kinh Nam Duy Trung',
    name_zh: '荊南惟忠',
    name_ja: 'Kinh Nam Duy Trung',
    name_ko: 'Kinh Nam Duy Trung',
    name_ar: 'Kinh Nam Duy Trung',
    birth_death_time: ['', ''],
    records: '',
    sect: '-',
    country: 'China',
    place: '-',
    teachers: ['Từ Châu Pháp Như'],
    successors: ['Toại Châu Đạo Viên'],
    disciples: ['Toại Châu Đạo Viên'],
    image: '/images/avatar.png',
  },
  {
    id: 36.2,
    name_en: 'Yaoshan Weiyan',
    name_es: 'Yaoshan Weiyan',
    name_de: 'Yaoshan Weiyan',
    name_fr: 'Yaoshan Weiyan',
    name_vi: 'Dược Sơn Duy Nghiễm',
    name_ru: 'Yaoshan Weiyan',
    name_zh: '藥山惟儼',
    name_ja: 'Yakusan Igen',
    name_ko: 'Yaksan Yuǒm',
    name_ar: 'Yaoshan Weiyan',
    birth_death_time: ['745', '827'],
    records: '',
    sect: '-',
    country: 'China',
    place: '-',
    teachers: ['Shitou Xiqian', 'Mazu Daoyi'],
    successors: ['Yunyan Tansheng'],
    disciples: ['Yunyan Tansheng'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/b/bc/Yaoshan_Weiyan_Image.jpg',
  },
  {
    id: 36.3,
    name_en: 'Tianhuang Daowu',
    name_es: 'Tianhuang Daowu',
    name_de: 'Tianhuang Daowu',
    name_fr: 'Tianhuang Daowu',
    name_vi: 'Tianhuang Daowu',
    name_ru: 'Tianhuang Daowu',
    name_zh: '天皇道悟',
    name_ja: 'Tianhuang Daowu',
    name_ko: 'Tianhuang Daowu',
    name_ar: 'Tianhuang Daowu',
    birth_death_time: ['748', '807'],
    records: '',
    sect: '-',
    country: 'China',
    place: '-',
    teachers: ['Shitou Xiqian'],
    successors: ['Longtan Chongxin'],
    disciples: ['Longtan Chongxin'],
    image: '/images/avatar.png',
  },
  {
    id: 36.5,
    name_en: 'Baizhang Huaihai',
    name_es: 'Baizhang Huaihai',
    name_de: 'Baizhang Huaihai',
    name_fr: 'Baizhang Huaihai',
    name_vi: 'Long Đàm Sùng Tín',
    name_ru: 'Baizhang Huaihai',
    name_zh: '龍潭崇信',
    name_ja: 'Baizhang Huaihai',
    name_ko: 'Baizhang Huaihai',
    name_ar: 'Baizhang Huaihai',
    birth_death_time: ['', ''],
    records: '',
    sect: '-',
    country: 'China',
    place: '-',
    teachers: ['Mazu Daoyi'],
    successors: ['-'],
    disciples: ['-'],
    image: '/images/avatar.png',
  },
  {
    id: 66,
    name_en: 'Yangshan Huiji',
    name_es: 'Yangshan Huiji',
    name_de: 'Yangshan Huiji',
    name_fr: 'Yangshan Huiji',
    name_vi: 'Ngưỡng Sơn Huệ Tịch',
    name_ru: 'Yangshan Huiji',
    name_zh: '仰山慧寂',
    name_ja: 'Kyōzan Ejaku',
    name_ko: '안산혜적 Angsan Hyejŏk',
    name_ar: 'Yangshan Huiji',
    birth_death_time: ['807', '883'],
    records: '',
    sect: '-',
    country: 'China',
    place: '-',
    teachers: ['Guishan Lingyou'],
    successors: ['Nanta Guangyong'],
    disciples: ['Nanta Guangyong'],
    image: '/images/avatar.png',
  },

]
export default CnLv2MasterDb;
