const CnLv1MasterDb = [
  {
    id: '34.1.1',
    name_en: 'Qingyuan Xingsi',
    name_es: 'Qingyuan Xingsi',
    name_de: 'Qingyuan Xingsi',
    name_fr: 'Qingyuan Xingsi',
    name_vi: 'Thanh Nguyên Hành Tư',
    name_ru: 'Qingyuan Xingsi',
    name_zh: '青原行思',
    name_ja: 'Seigen Gyōshi',
    name_ko: 'Chǒngwǒn Haengsa',
    name_ar: 'Qingyuan Xingsi',
    birth_death_time: ['660', '740'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: 'Qingyuan mountain, near Quanzhou, Fujian',
    teachers: ['Dajian Huineng'],
    successors: ['Shitou Xiqian'],
    disciples: ['Shitou Xiqian'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/0/01/Qingyuan_Xingsi.jpg',
    reference: [''],
  },
  {
    id: '34.1.2',
    name_en: 'Nanyang Huizhong',
    name_es: 'Nanyang Huizhong',
    name_de: 'Nanyang Huizhong',
    name_fr: 'Nanyang Huizhong',
    name_vi: 'Nam Dương Huệ Trung (Ðại Chứng, Quốc Sư)',
    name_ru: 'Nanyang Huizhong',
    name_zh: '南陽慧忠',
    name_ja: "Nan'yō Echū",
    name_ko: "Namyang Hyech'ung",
    name_ar: 'Nanyang Huizhong',
    birth_death_time: ['675', '775'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: 'Nantai Temple, Nanyue Heng mountain, Hunan',
    teachers: ['Dajian Huineng'],
    successors: ['Danyuan Yingzhen'],
    disciples: ['Danyuan Yingzhen', 'Suzong - (vua Túc Tông - Lý Hanh)', 'Daizong - (vua Đại Tông - Lý Dự)', 'Đặng Châu Duy Giới', 'Khai phủ Tôn Tri Hữu'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/1/1d/Nanyang_Huizhong.jpg',
    reference: ['https://en.wikipedia.org/wiki/Nanyang_Huizhong', 'https://terebess.hu/zen/mesterek/NanyangHuizhong.html', 'https://vi.wikipedia.org/wiki/Nam_D%C6%B0%C6%A1ng_Hu%E1%BB%87_Trung'],
  },
  {
    id: '34.1.3',
    name_en: 'Nanyue Huairang',
    name_es: 'Nanyue Huairang',
    name_de: 'Nanyue Huairang',
    name_fr: 'Nanyue Huairang',
    name_vi: 'Nam Nhạc Hoài Nhượng',
    name_ru: 'Nanyue Huairang',
    name_zh: '南嶽懐譲',
    name_ja: 'Nangaku Ejõ',
    name_ko: 'Nanyue Huairang',
    name_ar: 'Nanyue Huairang',
    birth_death_time: ['677', '744'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['Mazu Daoyi'],
    disciples: ['Mazu Daoyi', 'Nam Nhạc Thường Hoạt', 'Trí Đạt', 'Thản Nhiên', 'Triều Châu Thần Chiếu',
      'Dương châu Nghiêm Lăng', 'Tân La Bản Như', 'Huyền Thịnh', 'Đông Vụ Pháp Không'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.4',
    name_en: 'Heze Shenhui',
    name_es: 'Heze Shenhui',
    name_de: 'Heze Shenhui',
    name_fr: 'Heze Shenhui',
    name_vi: 'Hà Trạch Thần Hội',
    name_ru: 'Heze Shenhui',
    name_zh: '荷澤神會',
    name_ja: "Kataku Jinne",
    name_ko: 'Heze Shenhui',
    name_ar: 'Heze Shenhui',
    birth_death_time: ['684', '758'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: 'Heze temple, Luoyang, Hénán',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: ['Cizhou Faru', 'Wutai Wuming', 'Đại Thạch Phước Lâm, Hoàng Châu', 'Thủy Mông Quang Bảo',
      'Tây Ẩn Chuẩn Bình Hoài An', 'Tuệ Diễn ở Lễ Dương', 'Hoài Không ở Hà Thang', 'Viên Chấn ở Nam Dương',
      'Quảng Phu ở Nghi Xuân', 'Hạnh Giác ở Giang Lăng', 'Thần Anh ở núi Ngũ đài', 'Vô Sinh ở núi Ngũ đài',
      'Hạo Ngọc ở Nam Nhạc', 'Chí Mãn ở Tuyên Châu', 'Lãng ở Phù Châu', 'Linh Thản ở Quảng Lăng',
      'Thông Ẩn ở Ninh Châu', 'Nam Ấn ở Ích Châu', 'Hà Nam Duẫn Lý Thường'
    ],
    image: 'https://upload.wikimedia.org/wikipedia/commons/4/48/HezeShenhuiDrawing.jpg',
    image2: 'https://terebess.hu/zen/Shenhui.jpg',
    reference: ['https://terebess.hu/zen/shenhui.html', 'https://en.wikipedia.org/wiki/Shenhui'],
  },
  {
    id: '34.1.5',
    name_en: 'Thiều Châu Pháp Hải',
    name_es: 'Thiều Châu Pháp Hải',
    name_de: 'Thiều Châu Pháp Hải',
    name_fr: 'Thiều Châu Pháp Hải',
    name_vi: 'Thiều Châu Pháp Hải',
    name_ru: 'Thiều Châu Pháp Hải',
    name_zh: '韶州法海',
    name_ja: 'Thiều Châu Pháp Hải',
    name_ko: 'Thiều Châu Pháp Hải',
    name_ar: 'Thiều Châu Pháp Hải',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.6',
    name_en: 'Vĩnh Gia Huyền Giác',
    name_es: 'Vĩnh Gia Huyền Giác',
    name_de: 'Vĩnh Gia Huyền Giác',
    name_fr: 'Vĩnh Gia Huyền Giác',
    name_vi: 'Vĩnh Gia Huyền Giác',
    name_ru: 'Vĩnh Gia Huyền Giác',
    name_zh: '玄覺禪師',
    name_ja: 'Vĩnh Gia Huyền Giác',
    name_ko: 'Vĩnh Gia Huyền Giác',
    name_ar: 'Vĩnh Gia Huyền Giác',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: 'Wenzhou (永嘉)',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.8',
    name_en: 'Cát Châu Chí Thành',
    name_es: 'Cát Châu Chí Thành',
    name_de: 'Cát Châu Chí Thành',
    name_fr: 'Cát Châu Chí Thành',
    name_vi: 'Cát Châu Chí Thành',
    name_ru: 'Cát Châu Chí Thành',
    name_zh: '吉州志誠禪師',
    name_ja: 'Cát Châu Chí Thành',
    name_ko: 'Cát Châu Chí Thành',
    name_ar: 'Cát Châu Chí Thành',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.9',
    name_en: 'Giang Tây Chí Triệt',
    name_es: 'Giang Tây Chí Triệt',
    name_de: 'Giang Tây Chí Triệt',
    name_fr: 'Giang Tây Chí Triệt',
    name_vi: 'Giang Tây Chí Triệt',
    name_ru: 'Giang Tây Chí Triệt',
    name_zh: '江西志徹禪師',
    name_ja: 'Giang Tây Chí Triệt',
    name_ko: 'Giang Tây Chí Triệt',
    name_ar: 'Giang Tây Chí Triệt',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.10',
    hasContent: true,
    name_en: 'Biandan Xiaoliao',
    name_es: 'Biandan Xiaoliao',
    name_de: 'Biandan Xiaoliao',
    name_fr: 'Biandan Xiaoliao',
    name_vi: 'Biển Đam Hiểu Liễu / Biển Đảm Hiểu Liễu',
    name_ru: 'Biandan Xiaoliao',
    name_zh: '匾擔曉了',
    name_ja: 'Hentan Goryo',
    name_ko: 'Biandan Xiaoliao',
    name_ar: 'Biandan Xiaoliao',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: ['https://terebess.hu/english/master.html','https://wwzc.org/book/export/html/267', 'https://ngulucthien.com/thien-su-hieu-lieu/'],
  },
  {
    id: '34.1.11',
    name_en: 'Hà Bắc Trí Hoàng',
    name_es: 'Hà Bắc Trí Hoàng',
    name_de: 'Hà Bắc Trí Hoàng',
    name_fr: 'Hà Bắc Trí Hoàng',
    name_vi: 'Hà Bắc Trí Hoàng',
    name_ru: 'Hà Bắc Trí Hoàng',
    name_zh: '河北智隍',
    name_ja: 'Hà Bắc Trí Hoàng',
    name_ko: 'Hà Bắc Trí Hoàng',
    name_ar: 'Hà Bắc Trí Hoàng',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.12',
    hasContent: true,
    name_en: 'Hongzhou Fada',
    name_es: 'Hongzhou Fada',
    name_de: 'Hongzhou Fada',
    name_fr: 'Hongzhou Fada',
    name_vi: 'Hồng Châu Pháp Đạt',
    name_ru: 'Hongzhou Fada',
    name_zh: '洪州法达',
    name_ja: 'Hongzhou Fada',
    name_ko: 'Hongzhou Fada',
    name_ar: 'Hongzhou Fada',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.13',
    name_en: 'Thọ Châu Trí Thông',
    name_es: 'Thọ Châu Trí Thông',
    name_de: 'Thọ Châu Trí Thông',
    name_fr: 'Thọ Châu Trí Thông',
    name_vi: 'Thọ Châu Trí Thông',
    name_ru: 'Thọ Châu Trí Thông',
    name_zh: '壽州智通禪師',
    name_ja: 'Thọ Châu Trí Thông',
    name_ko: 'Thọ Châu Trí Thông',
    name_ar: 'Thọ Châu Trí Thông',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.14',
    name_en: 'Tín Châu Trí Thường',
    name_es: 'Tín Châu Trí Thường',
    name_de: 'Tín Châu Trí Thường',
    name_fr: 'Tín Châu Trí Thường',
    name_vi: 'Tín Châu Trí Thường',
    name_ru: 'Tín Châu Trí Thường',
    name_zh: '信州智常禪師',
    name_ja: 'Tín Châu Trí Thường',
    name_ko: 'Tín Châu Trí Thường',
    name_ar: 'Tín Châu Trí Thường',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.15',
    name_en: 'Quảng Châu Chí Đạo',
    name_es: 'Quảng Châu Chí Đạo',
    name_de: 'Quảng Châu Chí Đạo',
    name_fr: 'Quảng Châu Chí Đạo',
    name_vi: 'Quảng Châu Chí Đạo',
    name_ru: 'Quảng Châu Chí Đạo',
    name_zh: '廣州志道禪師',
    name_ja: 'Quảng Châu Chí Đạo',
    name_ko: 'Quảng Châu Chí Đạo',
    name_ar: 'Quảng Châu Chí Đạo',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.16',
    name_en: 'Quảng Châu Pháp Tánh Ấn Tông',
    name_es: 'Quảng Châu Pháp Tánh Ấn Tông',
    name_de: 'Quảng Châu Pháp Tánh Ấn Tông',
    name_fr: 'Quảng Châu Pháp Tánh Ấn Tông',
    name_vi: 'Quảng Châu Pháp Tánh Ấn Tông',
    name_ru: 'Quảng Châu Pháp Tánh Ấn Tông',
    name_zh: '-',
    name_ja: 'Quảng Châu Pháp Tánh Ấn Tông',
    name_ko: 'Quảng Châu Pháp Tánh Ấn Tông',
    name_ar: 'Quảng Châu Pháp Tánh Ấn Tông',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.17',
    name_en: 'Vụ Châu Huyền Sách',
    name_es: 'Vụ Châu Huyền Sách',
    name_de: 'Vụ Châu Huyền Sách',
    name_fr: 'Vụ Châu Huyền Sách',
    name_vi: 'Vụ Châu Huyền Sách',
    name_ru: 'Vụ Châu Huyền Sách',
    name_zh: '婺州玄策禪師',
    name_ja: 'Vụ Châu Huyền Sách',
    name_ko: 'Vụ Châu Huyền Sách',
    name_ar: 'Vụ Châu Huyền Sách',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: 'Vụ Châu',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.18',
    name_en: 'Tào Khê Linh Thao',
    name_es: 'Tào Khê Linh Thao',
    name_de: 'Tào Khê Linh Thao',
    name_fr: 'Tào Khê Linh Thao',
    name_vi: 'Tào Khê Linh Thao',
    name_ru: 'Tào Khê Linh Thao',
    name_zh: '曹谿令韜',
    name_ja: 'Tào Khê Linh Thao',
    name_ko: 'Tào Khê Linh Thao',
    name_ar: 'Tào Khê Linh Thao',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: 'Tào Khê',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.19',
    name_en: 'Ni Vô Tận Tạng',
    name_es: 'Ni Vô Tận Tạng',
    name_de: 'Ni Vô Tận Tạng',
    name_fr: 'Ni Vô Tận Tạng',
    name_vi: 'Ni Vô Tận Tạng',
    name_ru: 'Ni Vô Tận Tạng',
    name_zh: '無盡藏尼',
    name_ja: 'Ni Vô Tận Tạng',
    name_ko: 'Ni Vô Tận Tạng',
    name_ar: 'Ni Vô Tận Tạng',
    birth_death_time: ['?', '676'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.20',
    name_en: 'Kỳ Đà La',
    name_es: 'Kỳ Đà La',
    name_de: 'Kỳ Đà La',
    name_fr: 'Kỳ Đà La',
    name_vi: 'Kỳ Đà La',
    name_ru: 'Kỳ Đà La',
    name_zh: 'Kỳ Đà La',
    name_ja: 'Kỳ Đà La',
    name_ko: 'Kỳ Đà La',
    name_ar: 'Kỳ Đà La',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: '-',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: 'https://upload.wikimedia.org/wikipedia/commons/0/01/Qingyuan_Xingsi.jpg',
    reference: [''],
  },
  {
    id: '34.1.21',
    name_en: 'Tịnh An',
    name_es: 'Tịnh An',
    name_de: 'Tịnh An',
    name_fr: 'Tịnh An',
    name_vi: 'Tịnh An',
    name_ru: 'Tịnh An',
    name_zh: 'Tịnh An',
    name_ja: "Tịnh An",
    name_ko: "Tịnh An",
    name_ar: 'Tịnh An',
    birth_death_time: ['675', '755'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.22',
    name_en: 'Tâm',
    name_es: 'Tâm',
    name_de: 'Tâm',
    name_fr: 'Tâm',
    name_vi: 'Tâm',
    name_ru: 'Tâm',
    name_zh: 'Tâm',
    name_ja: 'Tâm',
    name_ko: 'Tâm',
    name_ar: 'Tâm',
    birth_death_time: ['677', '744'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: [''],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.23',
    name_en: 'Định Chơn',
    name_es: 'Định Chơn',
    name_de: 'Định Chơn',
    name_fr: 'Định Chơn',
    name_vi: 'Định Chơn / La Phù Định Chân',
    name_ru: 'Định Chơn',
    name_zh: 'Định Chơn',
    name_ja: 'Định Chơn',
    name_ko: 'Định Chơn',
    name_ar: 'Định Chơn',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: 'La Phù',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: ['Linh Vân'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.24',
    name_en: 'Kiên Cố',
    name_es: 'Kiên Cố',
    name_de: 'Kiên Cố',
    name_fr: 'Kiên Cố',
    name_vi: 'Kiên Cố',
    name_ru: 'Thiều Châu Pháp Hải',
    name_zh: '韶州法海',
    name_ja: 'Thiều Châu Pháp Hải',
    name_ko: 'Thiều Châu Pháp Hải',
    name_ar: 'Thiều Châu Pháp Hải',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.25',
    name_en: 'Đạo Tiến',
    name_es: 'Đạo Tiến',
    name_de: 'Đạo Tiến',
    name_fr: 'Đạo Tiến',
    name_vi: 'Đạo Tiến',
    name_ru: 'Đạo Tiến',
    name_zh: 'Đạo Tiến',
    name_ja: 'Đạo Tiến',
    name_ko: 'Đạo Tiến',
    name_ar: 'Đạo Tiến',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.26',
    name_en: 'Thiện Khoái',
    name_es: 'Thiện Khoái',
    name_de: 'Thiện Khoái',
    name_fr: 'Thiện Khoái',
    name_vi: 'Thiện Khoái',
    name_ru: 'Thiện Khoái',
    name_zh: 'Thiện Khoái',
    name_ja: 'Thiện Khoái',
    name_ko: 'Thiện Khoái',
    name_ar: 'Thiện Khoái',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.27',
    name_en: 'Duyên Tố',
    name_es: 'Duyên Tố',
    name_de: 'Duyên Tố',
    name_fr: 'Duyên Tố',
    name_vi: 'Duyên Tố',
    name_ru: 'Duyên Tố',
    name_zh: 'Duyên Tố',
    name_ja: 'Duyên Tố',
    name_ko: 'Duyên Tố',
    name_ar: 'Duyên Tố',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: [],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.28',
    name_en: 'Tông Nhất',
    name_es: 'Tông Nhất',
    name_de: 'Tông Nhất',
    name_fr: 'Tông Nhất',
    name_vi: 'Tông Nhất',
    name_ru: 'Tông Nhất',
    name_zh: 'Tông Nhất',
    name_ja: 'Tông Nhất',
    name_ko: 'Tông Nhất',
    name_ar: 'Tông Nhất',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: [],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.29',
    name_en: 'Thiên Hiện',
    name_es: 'Thiên Hiện',
    name_de: 'Thiên Hiện',
    name_fr: 'Thiên Hiện',
    name_vi: 'Thiên Hiện',
    name_ru: 'Thiên Hiện',
    name_zh: 'Thiên Hiện',
    name_ja: 'Thiên Hiện',
    name_ko: 'Thiên Hiện',
    name_ar: 'Thiên Hiện',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.30',
    name_en: 'Phạm Hạnh',
    name_es: 'Phạm Hạnh',
    name_de: 'Phạm Hạnh',
    name_fr: 'Phạm Hạnh',
    name_vi: 'Phạm Hạnh',
    name_ru: 'Phạm Hạnh',
    name_zh: 'Phạm Hạnh',
    name_ja: 'Phạm Hạnh',
    name_ko: 'Phạm Hạnh',
    name_ar: 'Phạm Hạnh',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.31',
    name_en: 'Tự Tại',
    name_es: 'Tự Tại',
    name_de: 'Tự Tại',
    name_fr: 'Tự Tại',
    name_vi: 'Tự Tại',
    name_ru: 'Tự Tại',
    name_zh: 'Tự Tại',
    name_ja: 'Tự Tại',
    name_ko: 'Tự Tại',
    name_ar: 'Tự Tại',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.32',
    name_en: 'Hàm Thông',
    name_es: 'Hàm Thông',
    name_de: 'Hàm Thônh',
    name_fr: 'Hàm Thônh',
    name_vi: 'Hàm Thông',
    name_ru: 'Hàm Thông',
    name_zh: 'Hàm Thông',
    name_ja: 'Hàm Thông',
    name_ko: 'Hàm Thông',
    name_ar: 'Hàm Thông',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.33',
    name_en: 'Thái Tường',
    name_es: 'Thái Tường',
    name_de: 'Thái Tường',
    name_fr: 'Thái Tường',
    name_vi: 'Thái Tường',
    name_ru: 'Thái Tường',
    name_zh: 'Thái Tường',
    name_ja: 'Thái Tường',
    name_ko: 'Thái Tường',
    name_ar: 'Thái Tường',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.34',
    name_en: 'Pháp Tịnh',
    name_es: 'Pháp Tịnh',
    name_de: 'Pháp Tịnh',
    name_fr: 'Pháp Tịnh',
    name_vi: 'Pháp Tịnh',
    name_ru: 'Pháp Tịnh',
    name_zh: 'Pháp Tịnh',
    name_ja: 'Pháp Tịnh',
    name_ko: 'Pháp Tịnh',
    name_ar: 'Pháp Tịnh',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.35',
    name_en: 'Biện Tài',
    name_es: 'Biện Tài',
    name_de: 'Biện Tài',
    name_fr: 'Biện Tài',
    name_vi: 'Biện Tài',
    name_ru: 'Biện Tài',
    name_zh: 'Biện Tài',
    name_ja: 'Biện Tài',
    name_ko: 'Biện Tài',
    name_ar: 'Biện Tài',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.36',
    name_en: 'Dạo Dung',
    name_es: 'Dạo Dung',
    name_de: 'Dạo Dung',
    name_fr: 'Dạo Dung',
    name_vi: 'Dạo Dung',
    name_ru: 'Dạo Dung',
    name_zh: 'Dạo Dung',
    name_ja: 'Dạo Dung',
    name_ko: 'Dạo Dung',
    name_ar: 'Dạo Dung',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.37',
    name_en: 'Ngô Đầu-đà',
    name_es: 'Ngô Đầu-đà',
    name_de: 'Ngô Đầu-đà',
    name_fr: 'Ngô Đầu-đà',
    name_vi: 'Ngô Đầu-đà',
    name_ru: 'Ngô Đầu-đà',
    name_zh: 'Ngô Đầu-đà',
    name_ja: 'Ngô Đầu-đà',
    name_ko: 'Ngô Đầu-đà',
    name_ar: 'Ngô Đầu-đà',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.38',
    name_en: 'Đạo Anh',
    name_es: 'Đạo Anh',
    name_de: 'Đạo Anh',
    name_fr: 'Đạo Anh',
    name_vi: 'Đạo Anh',
    name_ru: 'Đạo Anh',
    name_zh: 'Đạo Anh',
    name_ja: 'Đạo Anh',
    name_ko: 'Đạo Anh',
    name_ar: 'Đạo Anh',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.39',
    name_en: 'Trí Bổn',
    name_es: 'Trí Bổn',
    name_de: 'Trí Bổn',
    name_fr: 'Trí Bổn',
    name_vi: 'Trí Bổn',
    name_ru: 'Trí Bổn',
    name_zh: 'Trí Bổn',
    name_ja: 'Trí Bổn',
    name_ko: 'Trí Bổn',
    name_ar: 'Trí Bổn',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.40',
    name_en: 'Pháp Chơn',
    name_es: 'Pháp Chơn',
    name_de: 'Pháp Chơn',
    name_fr: 'Pháp Chơn',
    name_vi: 'Pháp Chơn',
    name_ru: 'Pháp Chơn',
    name_zh: 'Pháp Chơn',
    name_ja: 'Pháp Chơn',
    name_ko: 'Pháp Chơn',
    name_ar: 'Pháp Chơn',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.41',
    name_en: 'Huyền Giai',
    name_es: 'Huyền Giai',
    name_de: 'Huyền Giai',
    name_fr: 'Huyền Giai',
    name_vi: 'Huyền Giai',
    name_ru: 'Huyền Giai',
    name_zh: 'Huyền Giai',
    name_ja: 'Huyền Giai',
    name_ko: 'Huyền Giai',
    name_ar: 'Huyền Giai',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.42',
    name_en: 'Đàm Thổi',
    name_es: 'Đàm Thổi',
    name_de: 'Đàm Thổi',
    name_fr: 'Đàm Thổi',
    name_vi: 'Đàm Thổi',
    name_ru: 'Đàm Thổi',
    name_zh: 'Đàm Thổi',
    name_ja: 'Đàm Thổi',
    name_ko: 'Đàm Thổi',
    name_ar: 'Đàm Thổi',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.43',
    name_en: 'Thích sử Vi Cừ',
    name_es: 'Thích sử Vi Cừ',
    name_de: 'Thích sử Vi Cừ',
    name_fr: 'Thích sử Vi Cừ',
    name_vi: 'Thích sử Vi Cừ',
    name_ru: 'Thích sử Vi Cừ',
    name_zh: 'Thích sử Vi Cừ',
    name_ja: 'Thích sử Vi Cừ',
    name_ko: 'Thích sử Vi Cừ',
    name_ar: 'Thích sử Vi Cừ',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.44',
    name_en: 'Yìfú',
    name_es: 'Yìfú',
    name_de: 'Yìfú',
    name_fr: 'Yìfú',
    name_vi: 'Nghĩa Phúc',
    name_ru: 'Yìfú',
    name_zh: '義福',
    name_ja: 'Gifuku',
    name_ko: 'Yìfú',
    name_ar: 'Yìfú',
    birth_death_time: ['658', '736'],
    records: '',
    sect: ['Northern'],
    country: 'China',
    place: '-',
    teachers: ['Yuquan Shenxiu'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.45',
    name_en: 'Songshan Puji',
    name_es: 'Songshan Puji',
    name_de: 'Songshan Puji',
    name_fr: 'Songshan Puji',
    name_vi: 'Tung Sơn Phổ Tịch',
    name_ru: 'Songshan Puji',
    name_zh: '嵩山普寂',
    name_ja: 'Sûzan Fujaku',
    name_ko: 'Songshan Puji',
    name_ar: 'Songshan Puji',
    birth_death_time: ['651', '739'],
    records: '',
    sect: ['Northern'],
    country: 'China',
    place: '-',
    teachers: ['Yuquan Shenxiu'],
    successors: ['-'],
    disciples: ['Dàoxuán', 'Nangaku Myōsan', 'Duy Chính (惟政)'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: ['https://terebess.hu/zen/mesterek/Puji.html', 'https://pl.wikipedia.org/wiki/Songshan_Puji'],
  },
  {
    id: '34.1.46',
    name_en: 'Đạo Lượng',
    name_es: 'Đạo Lượng',
    name_de: 'Đạo Lượng',
    name_fr: 'Đạo Lượng',
    name_vi: 'Đạo Lượng',
    name_ru: 'Đạo Lượng',
    name_zh: '道量',
    name_ja: 'Đạo Lượng',
    name_ko: 'Đạo Lượng',
    name_ar: 'Đạo Lượng',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Huệ An'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.47',
    name_en: '破竈墮',
    name_es: '破竈墮',
    name_de: '破竈墮',
    name_fr: '破竈墮',
    name_vi: 'Phá Táo Đọa',
    name_ru: '破竈墮',
    name_zh: '破竈墮',
    name_ja: '破竈墮',
    name_ko: '破竈墮',
    name_ar: '破竈墮',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Huệ An (慧安)'],
    successors: ['-'],
    disciples: ['Tuấn Cực (峻極)'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.48',
    name_en: 'Chùjì',
    name_es: 'Chùjì',
    name_de: 'Chùjì',
    name_fr: 'Chùjì',
    name_vi: 'Xử Tịch',
    name_ru: 'Chùjì',
    name_zh: '普寂',
    name_ja: 'Shojaku',
    name_ko: 'Chùjì',
    name_ar: 'Chùjì',
    birth_death_time: ['648', '734'],
    records: '',
    sect: ['Oxhead'],
    country: 'China',
    place: '-',
    teachers: ['Zhìshēn (智詵)'],
    successors: ['-'],
    disciples: ['Wúxiàng (無相)'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.49',
    hasContent: true,
    name_en: 'Ehō',
    name_es: 'Ehō',
    name_de: 'Ehō',
    name_fr: 'Ehō',
    name_vi: 'Ngưu Đầu Tuệ Phương',
    name_ru: 'Ehō',
    name_zh: '慧方',
    name_ja: 'Ehō',
    name_ko: 'Ehō',
    name_ar: 'Ehō',
    birth_death_time: ['629', '695'],
    records: '',
    sect: ['Oxhead'],
    country: 'China',
    place: '-',
    teachers: ['Zhìshēn'],
    successors: ['-'],
    disciples: ['Hōji - Ngưu Đầu Pháp Trì'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.50',
    hasContent: true,
    name_en: 'Mengshan Daoming / Huiming',
    name_es: 'Mengshan Daoming',
    name_de: 'Mengshan Daoming',
    name_fr: 'Mengshan Daoming',
    name_vi: 'Mông Sơn Đạo Minh',
    name_ru: 'Mengshan Daoming',
    name_zh: '蒙山道明',
    name_ja: 'Myo',
    name_ko: 'Mengshan Daoming',
    name_ar: 'Mengshan Daoming',
    birth_death_time: ['586', '672'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: 'Mông Sơn, Viên Châu',
    teachers: ['Dajian Huineng', 'Daman Hongren'],
    successors: [''],
    disciples: [''],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.51',
    hasContent: true,
    name_en: 'Zizhou Chuji',
    name_es: 'Zizhou Chuji',
    name_de: 'Zizhou Chuji',
    name_fr: 'Zizhou Chuji',
    name_vi: 'Tư Châu Xử Tịch / Tử Châu Yên Tĩnh',
    name_ru: 'Zizhou Chuji',
    name_zh: '淄州處寂',
    name_ja: 'Shishū Shojaku',
    name_ko: '치주처적 Chiju Chŏjŏk',
    name_ar: 'Zizhou Chuji',
    birth_death_time: ['648/669', '734/736'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '',
    teachers: ['Zizhou Zhishen'],
    successors: ['Jingzhong Wuxiang'],
    disciples: ['Jingzhong Wuxiang', 'Chengyuan (712-802)'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: ['https://pl.wikipedia.org/wiki/Zizhou_Chuji'],
  },
  {
    id: '34.1.52',
    name_en: 'Lục hợp Đại Giác',
    name_es: 'Lục hợp Đại Giác',
    name_de: 'Lục hợp Đại Giác',
    name_fr: 'Lục hợp Đại Giác',
    name_vi: 'Lục hợp Đại Giác',
    name_ru: 'Lục hợp Đại Giác',
    name_zh: 'Lục hợp Đại Giác',
    name_ja: 'Lục hợp Đại Giác',
    name_ko: 'Lục hợp Đại Giác',
    name_ar: 'Lục hợp Đại Giác',
    birth_death_time: ['?', '?'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '',
    teachers: ['Định lâm Tuệ Cương'],
    successors: [''],
    disciples: ['Cao bưu Đàm Ảnh'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.53',
    name_en: 'Định Châu',
    name_es: 'Định Châu',
    name_de: 'Định Châu',
    name_fr: 'Định Châu',
    name_vi: 'Định Châu',
    name_ru: 'Định Châu',
    name_zh: 'Định Châu',
    name_ja: 'Định Châu',
    name_ko: 'Định Châu',
    name_ar: 'Định Châu',
    birth_death_time: ['?', '?'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '',
    teachers: ['Thượng nguyên Trí Thành'],
    successors: [''],
    disciples: ['Như Độ'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
]
export default CnLv1MasterDb;
