const CnLv14MasterDb = [
  {
    id: 46.1,
    name_en: 'Wuzu Fayan',
    name_es: 'Wuzu Fayan',
    name_de: 'Wuzu Fayan',
    name_fr: 'Wuzu Fayan',
    name_vi: 'Ngũ Tổ Pháp Diễn',
    name_ru: 'Wuzu Fayan',
    name_zh: '五祖法演',
    name_ja: 'Goso Hōen',
    name_ko: 'Wuzu Fayan',
    name_ar: 'Wuzu Fayan',
    birth_death_time: ['1024?', '1104'],
    records: '',
    sect: '-',
    country: 'China',
    place: '-',
    teachers: ['Baiyun Shouduan'],
    successors: ['Yuanwu Keqin'],
    disciples: ['Yuanwu Keqin', 'Kaifu Daoning'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/Ng%C5%A9_T%E1%BB%95_Ph%C3%A1p_Di%E1%BB%85n',],
    koans: ['',],
  },
]
export default CnLv14MasterDb;
