const CnLv57MasterDb = [
  {
    id: '90.57.1',
    name_en: 'Mingxuan Xirui',
    name_ja: 'Mingxuan Xirui',
    name_zh: '明轩西瑞',
    name_vi: 'Minh Hiên Hi Nhụy',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: ['Linji'],
    country: '🇨🇳',
    place: 'Gaomin Temple/Monastery (高旻寺), Hanjiang District, Yangzhou, 🇨🇳',
    teachers: ['Yuelang Quanding'],
    successors: ['Laiguo Miaoshu'],
    disciples: ['Laiguo Miaoshu'],
    image: '/images/avatar.png',
    reference: ['https://www.mdpi.com/2077-1444/15/5/627', 'https://terebess.hu/zen/mesterek/7.pdf'],
  },
  {
    id: '90.57.2',
    name_en: 'Tieyan ',
    name_ja: '',
    name_zh: '鐵崦',
    name_vi: 'Thiết Nham',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '🇨🇳',
    teachers: [''],
    successors: ['Yuexi Xinyuan'],
    disciples: ['Yuexi Xinyuan'],
    image: '/images/avatar.png',
    reference: [''],
  },
]
export default CnLv57MasterDb;
