const CnLv34MasterDb = [
  {
    id: '67.34.1',
    name_en: 'Yunqi Zhuhong',
    name_ja: 'Unsei Shukō',
    name_zh: '雲棲袾宏',
    name_vi: 'Vân Thê Châu Hoằng',
    other_name_vi: 'Liên Trì Đại Sư',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1535', '1615'],
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: 'China',
    place: '',
    teachers: ['Xiaoyan Debao'],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '67.34.2',
    name_en: 'Huanyou Zhengchuan',
    name_ja: 'Genyū Shōden',
    name_zh: '幻有正傳',
    name_vi: 'Huanyou Zhengchuan',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1549', '1614'],
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: 'China',
    place: '',
    teachers: ['Xiaoyan Debao'],
    successors: ['Miyun Yuanwu'],
    disciples: ['Miyun Yuanwu'],
    image: '/images/avatar.png',
    reference: [''],
  },
]
export default CnLv34MasterDb;
