const CnLv30MasterDb = [
  {
    id: '63.30.1',
    name_en: 'Yunkong Changzhong',
    name_ja: 'Yunkong Changzhong',
    name_zh: '蘊空常忠',
    name_vi: 'Uẩn Không Thường Trung',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1514', '1588'],
    epoch: '',
    records: '',
    sect: ['Caodong'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Zongjing Zongshu'],
    successors: ['Wuming Huijing'],
    disciples: ['Wuming Huijing'],
    image: '/images/avatar.png',
    reference: ['https://terebess.hu/zen/mesterek/YunkongChangzhong.html', 'https://londonchanmeditation.org/lineage/'],
  },
  {
    id: '63.30.2',
    name_en: 'Tianqi Benrui',
    name_ja: 'Tenki Honzui',
    name_zh: '天奇本瑞',
    name_vi: 'Thiên Kỳ Bản Thụy',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', '1508'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Baofeng Mingxuan'],
    successors: ['Wuwen Mingcong'],
    disciples: ['Wuwen Mingcong'],
    image: '/images/avatar.png',
    reference: [''],
  },
]
export default CnLv30MasterDb;
