const CnLv11MasterDb = [
  {
    id: '44.11.1',
    hasContent: true,
    name_en: 'Shishuang Chuyuan',
    name_es: 'Shishuang Chuyuan',
    name_de: 'Shishuang Chuyuan',
    name_fr: 'Shishuang Chuyuan',
    name_vi: 'Thạch Sương Sở Viên (Từ Minh Đại sư)',
    name_ru: 'Shishuang Chuyuan',
    name_zh: '石霜楚圓 (慈明)',
    name_ja: 'Sekisō Soen',
    name_ko: 'Shishuang Chuyuan',
    name_ar: 'Shishuang Chuyuan',
    birth_death_time: ['986', '1039'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Fenyang Shanzhao'],
    successors: ['Yangqi Fanghui', 'Huanglong Huinan'],
    disciples: ['Yangqi Fanghui', 'Huanglong Huinan', 'Cuiyan Kezhen'],
    image: 'https://terebess.hu/zen/mesterek/Ciming.gif',
    reference: ['https://terebess.hu/zen/shishuang.html', 'https://en.wikipedia.org/wiki/Shishuang_Temple', 'https://vi.wikipedia.org/wiki/Th%E1%BA%A1ch_S%C6%B0%C6%A1ng_S%E1%BB%9F_Vi%C3%AAn'],
  },
  {
    id: '44.11.2',
    hasContent: true,
    name_en: 'Yongming Yanshou',
    name_es: 'Yongming Yanshou',
    name_de: 'Yongming Yanshou',
    name_fr: 'Yongming Yanshou',
    name_vi: 'Vĩnh Minh Diên Thọ',
    name_ru: 'Yongming Yanshou',
    name_zh: '永明延壽',
    name_ja: '永明延寿 - Yōmyō Enju',
    name_ko: 'Yǒngmyǒng Yǒnsu',
    name_ar: 'Yongming Yanshou',
    birth_death_time: ['904', '976'],
    records: '',
    sect: ['Fayan', 'Pure land'],
    country: 'China',
    place: '-',
    teachers: ['Tiantai Deshao'],
    successors: [''],
    disciples: ['Triều Minh Viện Tân (朝明院津)', 'Phú Dương Tử Bàng (富陽子蒙)'],
    image: '',
    reference: ['https://en.wikipedia.org/wiki/Yongming_Yanshou', 'https://blog.phapthihoi.org/tu-dien-phat-giao/vinh-minh-dien-tho/'],
  },
  {
    id: '44.11.3',
    hasContent: true,
    name_en: 'Fuyin Liaoyuan',
    name_es: 'Fuyin Liaoyuan',
    name_de: 'Fuyin Liaoyuan',
    name_fr: 'Fuyin Liaoyuan',
    name_vi: 'Phật Ấn Liễu Nguyên',
    name_ru: 'Fuyin Liaoyuan',
    name_zh: '佛印了元',
    name_ja: 'Butsuin Ryōgen',
    name_ko: 'Fuyin Liaoyuan',
    name_ar: 'Fuyin Liaoyuan',
    birth_death_time: ['1032', '1098'],
    records: '',
    sect: [''],
    country: 'China',
    place: '-',
    teachers: ['Kaixian Shanxian'],
    successors: [''],
    disciples: [],
    image: '',
    reference: ['https://terebess.hu/zen/mesterek/fold.pdf'],
  },
  {
    id: '44.11.4',
    hasContent: true,
    name_en: 'Tianyi Yihuai',
    name_es: 'Tianyi Yihuai',
    name_de: 'Tianyi Yihuai',
    name_fr: 'Tianyi Yihuai',
    name_vi: 'Thiên Y Nghĩa Hoài',
    name_ru: 'Tianyi Yihuai',
    name_zh: '天衣義懷',
    name_ja: 'Tenne Gikai',
    name_ko: 'Tianyi Yihuai',
    name_ar: 'Tianyi Yihuai',
    birth_death_time: ['993', '1064'],
    records: '',
    sect: [''],
    country: 'China',
    place: '-',
    teachers: ['Xuedou Chongxian'],
    successors: ['Yuantong Fashen'],
    disciples: ['Yuantong Fashen - Viên Thông Pháp Tú - Entsû Hôshû', 'Yang Wuwei - Yô Mui', 'Shi Zongben - Viên Chiếu Tông Bản - 圓照宗本 - 1020?-1099'],
    image: '',
    reference: ['https://vi.wikipedia.org/wiki/Thi%C3%AAn_Y_Ngh%C4%A9a_Ho%C3%A0i'],
  },
  {
    id: '44.11.5',
    hasContent: true,
    name_en: 'Chengtian Chuanzong',
    name_es: 'Chengtian Chuanzong',
    name_de: 'Chengtian Chuanzong',
    name_fr: 'Chengtian Chuanzong',
    name_vi: 'Thừa Thiên Truyền Tông',
    name_ru: 'Chengtian Chuanzong',
    name_zh: '承天传宗 / 承天傳宗',
    name_ja: 'Shōten Denshū',
    name_ko: '승천전종 Sŭngchŏn Chŏnjŏng',
    name_ar: 'Chengtian Chuanzong',
    birth_death_time: ['', ''],
    records: '',
    sect: [''],
    country: 'China',
    place: '-',
    teachers: ['Xuedou Chongxian'],
    successors: [''],
    disciples: [],
    image: '',
    reference: ['https://pl.wikipedia.org/wiki/Chengtian_Chuanzong'],
  },
  {
    id: '44.11.6',
    hasContent: true,
    name_en: 'Thảo Đường',
    name_es: 'Thảo Đường',
    name_de: 'Thảo Đường',
    name_fr: 'Thảo Đường',
    name_vi: 'Thảo Đường - Tuân Phát Hỉ Túc',
    name_ru: '草堂',
    name_zh: 'Thảo Đường',
    name_ja: 'Thảo Đường',
    name_ko: 'Thảo Đường',
    name_ar: '',
    birth_death_time: ['997', '1047'],
    records: '',
    sect: [''],
    country: 'China',
    place: '-',
    teachers: ['Xuedou Chongxian'],
    successors: [''],
    disciples: [],
    image: '',
    reference: ['https://vi.wikipedia.org/wiki/Th%E1%BA%A3o_%C4%90%C6%B0%E1%BB%9Dng'],
  },
  {
    id: '44.11.7',
    hasContent: true,
    name_en: 'Fushan Fayuan',
    name_es: 'Fushan Fayuan',
    name_de: 'Fushan Fayuan',
    name_fr: 'Fushan Fayuan',
    name_vi: 'Phù Sơn Pháp Viễn',
    name_ru: '浮山法遠',
    name_zh: 'Fushan Fayuan',
    name_ja: 'Fuzan Hōen',
    name_ko: '부산법원 Pusan ​​Pŏpwŏn',
    name_ar: 'Fushan Fayuan',
    birth_death_time: ['991', '1067'],
    records: '',
    sect: ['Linji'],
    country: 'China',
    place: '-',
    teachers: ['Shexian Guixing'],
    successors: ['Touzi Yiqing*'],
    disciples: ['Touzi Yiqing*'],
    image: '',
    reference: ['https://pl.wikipedia.org/wiki/Fushan_Fayuan'],
  },
]
export default CnLv11MasterDb;
