const CnLv1MasterDb = [
  {
    id: '34.1.1',
    hasContent: true,
    name_en: 'Qingyuan Xingsi',
    name_ja: 'Seigen Gyōshi',
    name_vi: 'Thanh Nguyên Hành Tư',
    name_zh: '青原行思',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['660', '740'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: 'Qingyuan mountain, near Quanzhou, Fujian',
    teachers: ['Dajian Huineng'],
    successors: ['Shitou Xiqian'],
    disciples: ['Shitou Xiqian'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/0/01/Qingyuan_Xingsi.jpg',
    reference: [''],
  },
  {
    id: '34.1.2',
    hasContent: true,
    name_en: 'Nanyang Huizhong',
    name_ja: "Nan'yō Echū",
    name_zh: '南陽慧忠',
    name_vi: 'Nam Dương Huệ Trung',
    other_name_vi: '',
    nickname_vi: 'Ðại Chứng, Quốc Sư',
    worship_tower: '',
    birth_death_time: ['675', '775'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: 'Nantai Temple, Nanyue Heng mountain, Hunan',
    teachers: ['Dajian Huineng'],
    successors: ['Danyuan Yingzhen'],
    disciples: ['Danyuan Yingzhen', 'Suzong - (vua Túc Tông - Lý Hanh)', 'Daizong - (vua Đại Tông - Lý Dự)', 'Đặng Châu Duy Giới', 'Khai phủ Tôn Tri Hữu'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/1/1d/Nanyang_Huizhong.jpg',
    reference: ['https://en.wikipedia.org/wiki/Nanyang_Huizhong', 'https://terebess.hu/zen/mesterek/NanyangHuizhong.html', 'https://vi.wikipedia.org/wiki/Nam_D%C6%B0%C6%A1ng_Hu%E1%BB%87_Trung'],
  },
  {
    id: '34.1.3',
    hasContent: true,
    name_en: 'Nanyue Huairang',
    name_ja: 'Nangaku Ejõ',
    name_zh: '南嶽懐譲',
    name_vi: 'Nam Nhạc Hoài Nhượng',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['677', '744'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['Mazu Daoyi'],
    disciples: ['Mazu Daoyi', 'Nam Nhạc Thường Hoạt', 'Trí Đạt', 'Thản Nhiên', 'Triều Châu Thần Chiếu',
      'Dương châu Nghiêm Lăng', 'Tân La Bản Như', 'Huyền Thịnh', 'Đông Vụ Pháp Không'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.4',
    hasContent: true,
    name_en: 'Heze Shenhui',
    name_ja: "Kataku Jinne",
    name_zh: '荷澤神會',
    name_vi: 'Hà Trạch Thần Hội',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['684', '758'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: 'Heze temple, Luoyang, Hénán',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: ['Cizhou Faru', 'Wutai Wuming', 'Đại Thạch Phước Lâm, Hoàng Châu', 'Thủy Mông Quang Bảo',
      'Tây Ẩn Chuẩn Bình Hoài An', 'Tuệ Diễn ở Lễ Dương', 'Hoài Không ở Hà Thang', 'Viên Chấn ở Nam Dương',
      'Quảng Phu ở Nghi Xuân', 'Hạnh Giác ở Giang Lăng', 'Thần Anh ở núi Ngũ đài', 'Vô Sinh ở núi Ngũ đài',
      'Hạo Ngọc ở Nam Nhạc', 'Chí Mãn ở Tuyên Châu', 'Lãng ở Phù Châu', 'Linh Thản ở Quảng Lăng',
      'Thông Ẩn ở Ninh Châu', 'Nam Ấn ở Ích Châu', 'Hà Nam Duẫn Lý Thường'
    ],
    image: 'https://upload.wikimedia.org/wikipedia/commons/4/48/HezeShenhuiDrawing.jpg',
    image2: 'https://terebess.hu/zen/Shenhui.jpg',
    reference: ['https://terebess.hu/zen/shenhui.html', 'https://en.wikipedia.org/wiki/Shenhui'],
  },
  {
    id: '34.1.5',
    name_en: 'Thiều Châu Pháp Hải',
    name_ja: 'Thiều Châu Pháp Hải',
    name_zh: '韶州法海',
    name_vi: 'Thiều Châu Pháp Hải',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.6',
    hasContent: true,
    name_en: 'Yongjia Xuanjue',
    other_name_en: 'Yisu',
    name_zh: '永嘉玄覺',
    other_name_zh: '一宿覺',
    name_ja: 'Yōka Genkaku',
    name_vi: 'Vĩnh Gia Huyền Giác',
    other_name_vi: 'Chơn Giác Đại Sư',
    nickname_vi: 'Vô Tướng',
    worship_tower: '',
    birth_death_time: ['665', '713'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: 'Wenzhou (永嘉)',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.8',
    name_en: 'Jizhou Zhicheng',
    name_ja: 'Jizhou Zhicheng',
    name_zh: '吉州志誠',
    name_vi: 'Cát Châu Chí Thành',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.9',
    name_en: 'Giang Tây Chí Triệt',
    name_ja: 'Giang Tây Chí Triệt',
    name_zh: '江西志徹禪師',
    name_vi: 'Giang Tây Chí Triệt',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.10',
    hasContent: true,
    name_en: 'Biandan Xiaoliao',
    name_ja: 'Hentan Goryo',
    name_zh: '匾擔曉了',
    name_vi: 'Biển Đam Hiểu Liễu',
    other_name_vi: 'Biển Đảm Hiểu Liễu',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: ['https://terebess.hu/english/master.html','https://wwzc.org/book/export/html/267', 'https://ngulucthien.com/thien-su-hieu-lieu/'],
  },
  {
    id: '34.1.11',
    name_en: 'Hà Bắc Trí Hoàng',
    name_ja: 'Hà Bắc Trí Hoàng',
    name_zh: '河北智隍',
    name_vi: 'Hà Bắc Trí Hoàng',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.12',
    hasContent: true,
    name_en: 'Hongzhou Fada',
    name_ja: 'Hongzhou Fada',
    name_zh: '洪州法达',
    name_vi: 'Hồng Châu Pháp Đạt',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.13',
    name_en: 'Thọ Châu Trí Thông',
    name_ja: 'Thọ Châu Trí Thông',
    name_zh: '壽州智通禪師',
    name_vi: 'Thọ Châu Trí Thông',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.14',
    name_en: 'Tín Châu Trí Thường',
    name_ja: 'Tín Châu Trí Thường',
    name_zh: '信州智常禪師',
    name_vi: 'Tín Châu Trí Thường',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.15',
    name_en: 'Quảng Châu Chí Đạo',
    name_ja: 'Quảng Châu Chí Đạo',
    name_zh: '廣州志道禪師',
    name_vi: 'Quảng Châu Chí Đạo',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.16',
    name_en: 'Quảng Châu Pháp Tánh Ấn Tông',
    name_ja: 'Quảng Châu Pháp Tánh Ấn Tông',
    name_zh: '-',
    name_vi: 'Quảng Châu Pháp Tánh Ấn Tông',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.17',
    name_en: 'Vụ Châu Huyền Sách',
    name_ja: 'Vụ Châu Huyền Sách',
    name_zh: '婺州玄策禪師',
    name_vi: 'Vụ Châu Huyền Sách',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: 'Vụ Châu',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.18',
    hasContent: true,
    name_en: 'Daixiao Lingtao',
    name_ja: 'Daixiao Lingtao',
    name_zh: '曹谿令韜',
    name_vi: 'Tào Khê Linh Thao',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['666', '760'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '南華禪寺, 漕溪, 曲江, tỉnh Quảng Đông',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.19',
    name_en: 'Ni Vô Tận Tạng',
    name_ja: 'Ni Vô Tận Tạng',
    name_zh: '無盡藏尼',
    name_vi: 'Ni Vô Tận Tạng',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', '676'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.20',
    name_en: 'Kỳ Đà La',
    name_ja: 'Kỳ Đà La',
    name_zh: 'Kỳ Đà La',
    name_vi: 'Kỳ Đà La',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '-',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: 'https://upload.wikimedia.org/wikipedia/commons/0/01/Qingyuan_Xingsi.jpg',
    reference: [''],
  },
  {
    id: '34.1.21',
    name_en: 'Tịnh An',
    name_ja: "Tịnh An",
    name_zh: "Tịnh An",
    name_vi: 'Tịnh An',
    birth_death_time: ['675', '755'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.22',
    name_en: 'Tâm',
    name_ja: 'Tâm',
    name_zh: 'Tâm',
    name_vi: 'Tâm',
    birth_death_time: ['677', '744'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: [''],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.23',
    name_en: 'Định Chơn',
    name_ja: 'Định Chơn',
    name_zh: 'Định Chơn',
    name_vi: 'Định Chơn',
    other_name_vi: 'Định Chơn',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: 'La Phù',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: ['Linh Vân'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.24',
    name_en: 'Kiên Cố',
    name_ja: 'Kiên Cố',
    name_zh: 'Kiên Cố',
    name_vi: 'Kiên Cố',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.25',
    name_en: 'Đạo Tiến',
    name_ja: 'Đạo Tiến',
    name_zh: 'Đạo Tiến',
    name_vi: 'Đạo Tiến',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.26',
    name_en: 'Thiện Khoái',
    name_ja: 'Thiện Khoái',
    name_zh: 'Thiện Khoái',
    name_vi: 'Thiện Khoái',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.27',
    name_en: 'Duyên Tố',
    name_ja: 'Duyên Tố',
    name_zh: 'Duyên Tố',
    name_vi: 'Duyên Tố',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: [],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.28',
    name_en: 'Tông Nhất',
    name_ja: 'Tông Nhất',
    name_zh: 'Tông Nhất',
    name_vi: 'Tông Nhất',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: [],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.29',
    name_en: 'Thiên Hiện',
    name_ja: 'Thiên Hiện',
    name_zh: 'Thiên Hiện',
    name_vi: 'Thiên Hiện',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.30',
    name_en: 'Phạm Hạnh',
    name_ja: 'Phạm Hạnh',
    name_zh: 'Phạm Hạnh',
    name_vi: 'Phạm Hạnh',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.31',
    name_en: 'Tự Tại',
    name_ja: 'Tự Tại',
    name_zh: 'Tự Tại',
    name_vi: 'Tự Tại',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.32',
    name_en: 'Hàm Thông',
    name_ja: 'Hàm Thông',
    name_zh: 'Hàm Thông',
    name_vi: 'Hàm Thông',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.33',
    name_en: 'Thái Tường',
    name_ja: 'Thái Tường',
    name_zh: 'Thái Tường',
    name_vi: 'Thái Tường',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.34',
    name_en: 'Pháp Tịnh',
    name_ja: 'Pháp Tịnh',
    name_zh: 'Pháp Tịnh',
    name_vi: 'Pháp Tịnh',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.35',
    name_en: 'Biện Tài',
    name_ja: 'Biện Tài',
    name_zh: 'Biện Tài',
    name_vi: 'Biện Tài',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.36',
    name_en: 'Dạo Dung',
    name_ja: 'Dạo Dung',
    name_zh: 'Dạo Dung',
    name_vi: 'Dạo Dung',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.37',
    name_en: 'Ngô Đầu-đà',
    name_ja: 'Ngô Đầu-đà',
    name_zh: 'Ngô Đầu-đà',
    name_vi: 'Ngô Đầu-đà',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.38',
    name_en: 'Đạo Anh',
    name_ja: 'Đạo Anh',
    name_zh: 'Đạo Anh',
    name_vi: 'Đạo Anh',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.39',
    name_en: 'Trí Bổn',
    name_ja: 'Trí Bổn',
    name_zh: 'Trí Bổn',
    name_vi: 'Trí Bổn',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.40',
    name_en: 'Pháp Chơn',
    name_ja: 'Pháp Chơn',
    name_zh: 'Pháp Chơn',
    name_vi: 'Pháp Chơn',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.41',
    name_en: 'Huyền Giai',
    name_ja: 'Huyền Giai',
    name_zh: 'Huyền Giai',
    name_vi: 'Huyền Giai',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.42',
    name_en: 'Chung Sơn Đàm Thổi',
    name_ja: 'Chung Sơn Đàm Thổi',
    name_zh: 'Chung Sơn Đàm Thổi',
    name_vi: 'Chung Sơn Đàm Thôi',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.43',
    name_en: 'Thích sử Vi Cừ',
    name_ja: 'Thích sử Vi Cừ',
    name_zh: 'Thích sử Vi Cừ',
    name_vi: 'Thích sử Vi Cừ',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.44',
    name_en: 'Yìfú',
    name_ja: 'Gifuku',
    name_zh: '義福',
    name_vi: 'Nghĩa Phúc',
    birth_death_time: ['658', '736'],
    epoch: '',
    records: '',
    sect: ['Northern'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Yuquan Shenxiu'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.45',
    name_en: 'Songshan Puji',
    name_ja: 'Sûzan Fujaku',
    name_zh: '嵩山普寂',
    name_vi: 'Tung Sơn Phổ Tịch',
    birth_death_time: ['651', '739'],
    epoch: '',
    records: '',
    sect: ['Northern'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Yuquan Shenxiu'],
    successors: ['-'],
    disciples: ['Dàoxuán', 'Nangaku Myōsan', 'Duy Chính (惟政)'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: ['https://terebess.hu/zen/mesterek/Puji.html', 'https://pl.wikipedia.org/wiki/Songshan_Puji'],
  },
  {
    id: '34.1.46',
    name_en: 'Đạo Lượng',
    name_ja: 'Đạo Lượng',
    name_zh: '道量',
    name_vi: 'Đạo Lượng',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Huệ An'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.47',
    name_en: '破竈墮',
    name_ja: '破竈墮',
    name_zh: '破竈墮',
    name_vi: 'Phá Táo Đọa',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Huệ An (慧安)'],
    successors: ['-'],
    disciples: ['Tuấn Cực (峻極)'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.48',
    name_en: 'Tzu-chou Ch’u-chi',
    other_name_en: 'Jingzhong Zhixian',
    name_ja: 'Shojaku',
    name_zh: '浄衆',
    name_vi: 'Tư Châu Xử Tịch',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['648', '734'],
    epoch: '',
    records: '',
    sect: ['Oxhead'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Zizhou Chiji'],
    successors: ['-'],
    disciples: ['Wúxiàng (無相)'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.49',
    hasContent: true,
    name_en: 'Niutou Huifang',
    name_ja: 'Niutou Huifang',
    name_zh: '牛頭 慧方',
    name_vi: 'Ngưu Đầu Huệ Phương',
    other_name_vi: 'Ngưu Đầu Tuệ Phương',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['629', '695'],
    epoch: '',
    records: '',
    sect: ['Niutou (Oxhead)'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Niutou Zhiyan'],
    successors: ['Niutou Fazhi'],
    disciples: ['Niutou Fazhi'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.50',
    hasContent: true,
    name_en: 'Mengshan Daoming',
    other_name_en: 'Huiming',
    name_ja: 'Myo',
    name_zh: '蒙山道明',
    name_vi: 'Mông Sơn Đạo Minh',
    other_name_vi: 'Huệ Minh',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['586', '672'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: 'Mông Sơn, Viên Châu',
    teachers: ['Dajian Huineng', 'Daman Hongren'],
    successors: [''],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.51',
    hasContent: true,
    name_en: 'Zizhou Chuji',
    name_ja: 'Shishū Shojaku',
    name_zh: '淄州處寂',
    name_vi: 'Tư Châu Xử Tịch / Tử Châu Yên Tĩnh',
    birth_death_time: ['648/669', '734/736'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Zizhou Zhishen'],
    successors: ['Jingzhong Wuxiang'],
    disciples: ['Jingzhong Wuxiang', 'Chengyuan (712-802)'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: ['https://pl.wikipedia.org/wiki/Zizhou_Chuji'],
  },
  {
    id: '34.1.52',
    name_en: 'Lục Hợp Đại Giác',
    name_ja: 'Lục Hợp Đại Giác',
    name_zh: 'Lục Hợp Đại Giác',
    name_vi: 'Lục Hợp Đại Giác',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Định Lâm Tuệ Cương'],
    successors: [''],
    disciples: ['Cao bưu Đàm Ảnh'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.53',
    name_en: 'Định Châu',
    name_ja: 'Định Châu',
    name_zh: 'Định Châu',
    name_vi: 'Định Châu',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Thượng Nguyên Trí Thành'],
    successors: [''],
    disciples: ['Như Độ'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '34.1.54',
    hasContent: true,
    name_en: 'Sikong Benjing',
    name_ja: 'Shikū Honjō',
    name_zh: '司空本净',
    name_vi: 'Tư Không Bổn Tịnh',
    birth_death_time: ['667', '761'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: 'Anhui province, Sikong moutain, Balian Monastery',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: ['https://pl.m.wikipedia.org/wiki/Sikong_Benjing'],
  },
]
export default CnLv1MasterDb;
