const CnLv5MasterDb = [
  {
    id: '38.5.1',
    name_en: 'Guifeng Zongmi',
    name_ja: 'Guifeng Zongmi',
    name_zh: '圭峰宗密',
    name_vi: 'Khuê Phong Tông Mật',
    other_name_vi: 'Khoa Phong Tông Mật',
    nickname_vi: 'Định Tuệ, Thanh Liên',
    worship_tower: '',
    birth_death_time: ['780', '841'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: 'Zhongnan mountain',
    teachers: ['Toại Châu Đạo Viên'],
    successors: ['-'],
    disciples: [],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '38.5.2',
    hasContent: true,
    name_en: 'Dongshan Liangjie',
    name_ja: 'Tōzan Ryōkai',
    name_zh: '洞山 良价',
    name_vi: 'Động Sơn Lương Giới',
    other_name_vi: '',
    nickname_vi: 'Ngộ Bổn',
    worship_tower: '',
    birth_death_time: ['807', '869'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Yunyan Tansheng'],
    successors: ['Yunju Daoying', 'Caoshan Benji'],
    disciples: ['Yunju Daoying', 'Caoshan Benji', 'Sushan Kuangren', 'Jiufeng Puman', 'Baoji Xiujing', 'Tiantong Weiqi',
      'Longya Judun', 'Qinshan Wensui', 'Yuezhou Qianfeng', 'Qinglin Shiqian', 'Jingdiao Xianzu', 'Yuezhou Qianfeng'],
    image: 'https://terebess.hu/zen/mesterek/Ma-Yuan_Dongshan.jpg',
    reference: ['https://hoavouu.com/a39664/ngu-luc-thien-su-dong-son-ngo-ban', 'https://pl.wikipedia.org/wiki/Dongshan_Liangjie',
      'https://drive.google.com/file/d/1SvmWiqhC8prbUZrvXV7WqnI7dVaddd98/view',
      'https://tangthuphathoc.net/thuy-chau-dong-son-luong-gioi-thien-su-ngu-luc',
      'https://blog.phapthihoi.org/gt-member/ts-dong-son-luong-gioi/'],
  },
  {
    id: '38.5.3',
    hasContent: true,
    name_en: 'Deshan Xuanjian',
    name_ja: 'Tokusan Senkan',
    name_zh: '德山宣鑒',
    name_vi: 'Đức Sơn Tuyên Giám',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['780', '865'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: 'Wuling, Hunan',
    teachers: ['Longtan Chongxin'],
    successors: ['-'],
    disciples: ['Xuefeng Yicun', 'Yantou Quanhuo'],
    image: 'https://terebess.hu/zen/deshan3.jpg',
    image2: 'https://upload.wikimedia.org/wikipedia/commons/5/5f/To_san_Hszuan_csien780.2-865.jpg',
    reference: ['https://terebess.hu/zen/deshan3.jpg'],
  },
  {
    id: '38.5.4',
    name_en: 'Yangshan Huiji',
    name_ja: 'Kyōzan Ejaku',
    name_zh: '仰山慧寂',
    name_vi: 'Ngưỡng Sơn Huệ Tịch',
    other_name_vi: '',
    nickname_vi: 'Trí Thông',
    worship_tower: 'Diệu Quang',
    birth_death_time: ['807', '883'],
    epoch: '',
    records: '',
    sect: ['Guiyang'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Guishan Lingyou'],
    successors: ['Nanta Guangyong'],
    disciples: ['Nanta Guangyong', 'Wuzhu Wenxi', 'Xita Guangmu', 'Miaoxin', 'Wŏnnang Taet’ong', 'Sunji Yoo'],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Yangshan_Huiji'],
  },
  {
    id: '38.5.5',
    hasContent: true,
    name_en: 'Linji Yixuan',
    name_ja: 'Rinzai Gigen',
    name_zh: '臨濟義玄',
    name_vi: 'Lâm Tế Nghĩa Huyền',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', '866/867'],
    epoch: '',
    records: '',
    sect: ['Linji'],
    country: '🇨🇳',
    place: 'Zhengzhou',
    teachers: ['Huangbo Xiyun'],
    successors: ['Xinghua Cunjiang'],
    disciples: ['Weifu Dajue', 'Xinghua Cunjiang', 'Sansheng Huiran', 'Baoshou Yanzhao', 'Zhiyi Daozhe', 'Guanqi Zhixian', 'Luopu Yuan’an',
      'Tongfeng Anzhu', 'Zhenzhou Wanshou', 'Youzhou Tangong', 'Zhexi Shanquan', 'Dingzhou Cuichan', 'Zhuoshou Kepu', 'Fubei Anzhu',
      'Xiangzhou Licun', 'Xingshan Jianhong', 'Guanqi Ezhou (Guanxi)', 'Ding Shanzuo', 'Qisong', 'Yunshan', 'Shanyang Anzhu',
      'Huxi Anzhu (sun)', 'Cangzhou Meicang', 'Silla Zhiyi'
    ],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/L%C3%A2m_T%E1%BA%BF_Ngh%C4%A9a_Huy%E1%BB%81n',
      'https://quangduc.com/p157a72140/quyen-12-lam-te-nghia-huyen-vi-to-cua-lam-te-tong-',
      'https://quangduc.com/p157a72156/quyen-28-cac-ngu-luc-dac-biet-cua-11-vi-thien-su'],
  },
  {
    id: '38.5.6',
    hasContent: true,
    name_en: 'Muzhou Daoming',
    other_name_en: 'Muzhou Daozong',
    name_ja: 'Muzhou Daoming',
    name_zh: '睦州道明',
    other_name_zh: '道蹤',
    name_vi: 'Mục Châu Đạo Minh',
    other_name_vi: '',
    nickname_vi: 'Trần Tôn Túc',
    worship_tower: '',
    birth_death_time: ['780', '877'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: 'Guanyin Temple, Muzhou (Zhejiang now)',
    teachers: ['Huangbo Xiyun'],
    successors: [''],
    disciples: [],
    image: 'https://terebess.hu/zen/mesterek/woodcut/38-3.jpg',
    reference: ['https://terebess.hu/zen/muzhou.html'],
  },
  {
    id: '38.5.7',
    name_en: 'Pei Xiu',
    name_ja: 'Haikyū',
    name_zh: '裴休',
    name_vi: 'Bùi Hưu',
    other_name_vi: '',
    nickname_vi: 'Tướng quốc',
    worship_tower: '',
    birth_death_time: ['797?', '870?'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: 'Henan province',
    teachers: ['Huangbo Xiyun'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://blog.phapthihoi.org/gt-member/tuong-quoc-bui-huu/','https://vi.wikipedia.org/wiki/B%C3%B9i_H%C6%B0u', 'https://phatgiao.org.vn/tu-dien-phat-hoc-online/bui-huu-k338.html', 'https://phatgiao.org.vn/tu-dien-phat-hoc-online/bui-huu-k30587.html', 'https://tinhtan.org/2021/01/17/dich-va-binh-tho-dam-lac-dam-cua-te-tuong-bui-huu-791-846'],
  },
  {
    id: '38.5.8',
    name_en: 'Jingshan Faqin',
    other_name_en: 'Jingshan Daoqin, Jingshan Yuanming',
    name_ja: 'Kinzan Faqin',
    other_name_ja: 'Keizan Hōkin / Keizan Dōkin',
    name_zh: '徑山法欽',
    other_name_zh: '徑山道欽',
    name_vi: 'Kính Sơn Pháp Khâm',
    other_name_vi: 'Kính Sơn Đạo Khâm',
    nickname_vi: 'Quốc Nhất',
    worship_tower: '',
    birth_death_time: ['714', '792'],
    epoch: '',
    records: '',
    sect: ['Niutou (Oxhead)'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Helin Xuansu'],
    successors: [''],
    disciples: ['Niaoke Daolin', 'Hàng Ma Sùng Huệ', 'Fahai', 'Zhangxin Chonghui', 'Funiu Zucai', 'Niaoke Guoyi?'],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Jingshan_Faqin'],
  },
  {
    id: '38.5.9',
    hasContent: true,
    name_en: 'Shishuang Qingzhu',
    name_ja: 'Sekisō Keisho',
    name_zh: '石霜慶諸',
    name_vi: 'Thạch Sương Khánh Chư',
    other_name_vi: '',
    nickname_vi: 'Phổ Hội',
    worship_tower: '',
    birth_death_time: ['807', '888'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Daowu Yuanzhi'],
    successors: [''],
    disciples: ['Zhangzhuo Xiucai', 'Jiufeng Daoqian', 'Daguang Juhui', 'Yungai Zhiyuan', 'Nanji Sengyi', 'Yongquan Jingxin'],
    image: '/images/avatar.png',
    reference: ['https://blog.phapthihoi.org/gt-member/ts-thach-suong-khanh-chu/',
      'https://hoavouu.com/a17583/03-thien-su-khanh-chu-o-thach-suong',
      'https://phatgiao.org.vn/tu-dien-phat-hoc-online/thach-suong-that-khu-k42432.html'
    ],
  },
  {
    id: '38.5.10',
    name_en: 'Lingyun Zhiqin',
    other_name_en: 'Lingyun Zhijian, Ling-yun Chih-ch’in',
    name_ja: 'Reiun Shigon',
    name_zh: '靈雲志勤',
    name_vi: 'Linh Vân Chí Cần',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: 'Tang dynasty',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Guishan Lingyou'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://thuvienhoasen.org/images/file/jFMpvZ1G0QgQALUw/vuon-thien-rung-ngoc-thong-thien-dich-0.pdf',
      'https://www.niemphat.vn/downloads/thien-tong/hoc-thien/vuon-thien-rung-ngoc-thong-thien.pdf',
      'http://thuongchieu.net/index.php?option=com_content&view=article&id=853:bai-6--linh-van-trong-thy-hoa&catid=44:vn-thin-rng-ngc&Itemid=355',
      'https://vi.wikipedia.org/wiki/Linh_V%C3%A2n_Ch%C3%AD_C%E1%BA%A7n', 'https://pl.wikipedia.org/wiki/Lingyun_Zhiqin'
    ],
  },
  {
    id: '38.5.11',
    name_en: 'Xiangyan Zhixian',
    name_ja: 'Kyōgen Chikan',
    name_zh: '香嚴智閑',
    name_vi: 'Hương Nghiêm Trí Nhàn',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['820', '898'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Guishan Lingyou'],
    successors: [''],
    disciples: ['Diên Khánh Pháp Đoan'],
    image: '/images/avatar.png',
    reference: ['https://en.wikipedia.org/wiki/Xiangyan_Zhixian', 'https://vi.wikipedia.org/wiki/H%C6%B0%C6%A1ng_Nghi%C3%AAm_Tr%C3%AD_Nh%C3%A0n'],
  }, //id: '38.5.12.K', 'Chinghyo Choljung'
  {
    id: '38.5.13',
    name_en: 'Yanyang Shanxin',
    name_ja: 'Genyō Zenshin',
    name_zh: '嚴陽善信',
    name_vi: 'Nghiêm Sương Thiện Tín',
    other_name_vi: 'Diên Dương Sơn Tân',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Zhaozhou Congshen'],
    successors: [''],
    disciples: [],
    image: '/',
    reference: ['https://pl.wikipedia.org/wiki/Yanyang_Shanxin'],
  },
  {
    id: '38.5.14',
    hasContent: true,
    name_en: 'Jinhua Juzhi',
    name_ja: 'Kinka Kuchi',
    name_zh: '金华俱胝',
    name_vi: 'Kim Hoa Câu Chi',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Hangzhou Tianlong'],
    successors: [''],
    disciples: [],
    image: '/',
    reference: ['https://pl.wikipedia.org/wiki/Jinhua_Juzhi'],
  },
  {
    id: '38.5.15',
    hasContent: true,
    name_en: 'Touzi Datong',
    name_ja: 'Tōsu Daidō',
    name_zh: '投子大同',
    name_vi: 'Đầu Tử Đại Đồng',
    other_name_vi: '',
    nickname_vi: 'Từ Tế',
    worship_tower: '',
    birth_death_time: ['819', '914'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: 'Touzishan',
    teachers: ['Cuiwei Wuxue'],
    successors: [''],
    disciples: [],
    image: '/',
    reference: ['https://terebess.hu/zen/touzi.html', 'https://pl.wikipedia.org/wiki/Touzi_Datong', 'https://dieungu.org/a30498/doi-thu-nam-sau-luc-to'],
  },
  {
    id: '38.5.16',
    hasContent: true,
    name_en: 'Jiashan Shanhui',
    name_ja: 'Kyōzan Zen’e',
    name_zh: '夾山善會',
    name_vi: 'Giáp Sơn Thiện Hội',
    other_name_vi: '',
    nickname_vi: 'Truyền Minh',
    worship_tower: 'Vĩnh Tế',
    birth_death_time: ['805', '881'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Chuanzi Decheng'],
    successors: ['Luopu Yuan’an'],
    disciples: ['Luopu Yuan’an'],
    image: '/',
    reference: ['https://pl.wikipedia.org/wiki/Jiashan_Shanhui'],
  },
  {
    id: '38.5.17',
    hasContent: true,
    name_en: 'Moshan Liaoran',
    name_ja: 'Massan Ryōnen',
    name_zh: '末山了然',
    name_vi: 'Mạc Sơn Liễu Nhiên',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', '895'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Gaoan Dayu'],
    successors: [''],
    disciples: [],
    image: '/',
    reference: ['https://terebess.hu/zen/mesterek/MoshanLiaoran.html', 'http://thuongchieu.net/index.php/chuyende/thiensutrunghoa/1676-ni-liu-nhien-mt-sn',
    'http://thuongchieu.net/index.php/chuyende/thiensutrunghoa/1676-ni-liu-nhien-mt-sn'],
  },
  {
    id: '38.5.18',
    hasContent: true,
    name_en: 'Xuedou Changtong',
    name_ja: 'Xuedou Changtong',
    name_zh: '雪竇常通',
    name_vi: 'Tuyết Đậu Thường Thông',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['834', '905'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: 'Mingzhou',
    teachers: ['Changsha Jingcen'],
    successors: [''],
    disciples: [],
    image: '/',
    reference: ['https://hoavouu.com/p24a17590/10-thien-su-thuong-thong-o-nui-tuyet-dau', 'http://m.fodizi.tw/f04/40615.html'],
  },
  {
    id: '38.5.19',
    hasContent: true,
    name_en: 'Xingshan Jianghong',
    name_ja: 'Xingshan Jianghong',
    name_zh: '杏山鑒洪',
    name_vi: 'Hạnh Sơn Giáp Hồng',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Yunyan Tansheng'],
    successors: [''],
    disciples: [],
    image: '/',
    reference: ['https://quangduc.com/p157a72143/quyen-15-dong-son-luong-gioi-'],
  },
  {
    id: '38.5.20',
    hasContent: true,
    name_en: 'Thần Sơn Tăng Mật',
    name_ja: 'Thần Sơn Tăng Mật',
    name_zh: 'Thần Sơn Tăng Mật',
    name_vi: 'Thần Sơn Tăng Mật',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Yunyan Tansheng'],
    successors: [''],
    disciples: [],
    image: '/',
    reference: ['https://hoavouu.com/p24a17582/02-thien-su-tang-mat'],
  },
  {
    id: '38.5.21',
    name_en: 'Dasui Fazhen',
    name_ja: 'Daizui Hōshin',
    other_name_ja: 'Taizui Hōshin',
    name_zh: '大隨法真',
    name_vi: 'Đại Tuỳ Pháp Chân',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['834/878', '919/963'],
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Guishan Da’an'],
    successors: [''],
    disciples: [],
    image: '/',
    reference: ['https://pl.wikipedia.org/wiki/Dasui_Fazhen', 'https://terebess.hu/zen/dasui.html'],
  },
  {
    id: '38.5.22',
    name_en: 'Liu Tiemo',
    name_ja: 'Ryūtetsuma',
    name_zh: '劉鐵磨',
    name_vi: 'Lưu Thiết Ma',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '9th century',
    records: '',
    sect: ['Guiyang'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Guishan Lingyou'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Liu_Tiemo'],
  },
  {
    id: '38.5.23',
    name_en: 'Jingzhao Mihu',
    name_ja: 'Kyōchō Beiko',
    other_name_ja: 'Keichō Beiko',
    name_zh: '劉鐵磨',
    name_vi: 'Kinh Triệu Mễ Hồ',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '9th century',
    records: '',
    sect: ['Guiyang'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Guishan Lingyou'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Jingzhao_Mihu', 'https://terebess.hu/zen/mesterek/mihu.html'],
  },
]
export default CnLv5MasterDb;
