const CnLv55MasterDb = [
  {
    id: '88.55.1',
    name_en: 'Langhui Shirong',
    name_es: 'Langhui Shirong',
    name_de: 'Langhui Shirong',
    name_fr: 'Langhui Shirong',
    name_ru: 'Langhui Shirong',
    name_ar: 'Langhui Shirong',
    name_ko: 'Langhui Shirong',
    name_ja: 'Rōki Riji',
    name_zh: '朗辉事融',
    name_vi: '',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: ['Linji'],
    country: 'China',
    place: 'Gaomin Temple/Monastery (高旻寺), Hanjiang District, Yangzhou, China',
    teachers: [''],
    successors: ['Yuelang Quanding'],
    disciples: ['Yuelang Quanding', 'Chuchan Quanzhen'],
    image: '/images/avatar.png',
    reference: [''],
  },
]
export default CnLv55MasterDb;
