const CnLv12MasterDb = [
  {
    id: '45.12.1',
    hasContent: true,
    name_en: 'Yangqi Fanghui',
    name_ja: 'Yōgi Hōe',
    name_zh: '楊岐方會',
    pinyin: '',
    name_vi: 'Dương Kỳ Phương Hội',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['992', '1049'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Shishuang Chuyuan'],
    successors: ['Baiyun Shouduan'],
    disciples: ['Baiyun Shouduan', 'Baoning Renyong'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/D%C6%B0%C6%A1ng_K%C3%AC_Ph%C6%B0%C6%A1ng_H%E1%BB%99i',],
    youtubeId: [''],
  },
  {
    id: '45.12.2',
    hasContent: true,
    name_en: 'Huanglong Huinan',
    name_ja: 'Ōryō Enan',
    name_zh: '黃龍慧南',
    pinyin: '',
    name_vi: 'Hoàng Long Huệ Nam',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1002', '1069'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Huanglong'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Shishuang Chuyuan'],
    successors: [''],
    disciples: ['Baofeng Kewen', 'Huitang Zuxin', 'Donglin Changcong', 'Xuefeng Daoyuan', 'Baoben Huiyuan',
      'Huangbo Weisheng - 黃蘗惟勝 (Northern Song Dynasty)', 'Letan Hongying - 泐潭洪英 (1012–1070)', 'Yunju Yuanyou - 雲居元祐 (1027–1092)',
      'Guishan Huaixiu (Dagui Hauixiu) - 大溈懷秀 (Northern Song Dynasty)', 'Yungai Shouzhi (1025–1115)', 'Huilin Dexun (1107-1110)',
      'Fuyan Cigan (Nanyue Cikan)', 'Guizong Zhizhi - 歸宗志芝 (Northern Song Dynasty)'
    ],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/Ho%C3%A0ng_Long_Hu%E1%BB%87_Nam', 'https://pl.wikipedia.org/wiki/Huanglong_Huinan'],
  },
  {
    id: '45.12.3',
    hasContent: true,
    name_en: 'Cuiyan Kezhen',
    name_ja: 'Suigan Kakushin',
    name_zh: '翠巖可真',
    pinyin: '',
    name_vi: 'Thúy Nham Khả Chân',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', '1064'],
    epoch: '',
    records: '',
    sect: ['Linji'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Shishuang Chuyuan'],
    successors: ['Dagui Muzhe'],
    disciples: ['Dagui Muzhe'],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Cuiyan_Kezhen'],
  },
  {
    id: '45.12.4',
    hasContent: true,
    name_en: 'Touzi Yiqing',
    name_ja: 'Tōsu Gisei',
    name_zh: '投子義青',
    pinyin: '',
    name_vi: 'Đầu Tử Nghĩa Thanh',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1032', '1083'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Caodong'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Fushan Fayuan', 'Dayang Jingxuan'],
    successors: [''],
    disciples: ['Dahong Bao’en', 'Furong Daokai'],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Touzi_Yiqing'],
  },
]
export default CnLv12MasterDb;
