const CnLv9MasterDb = [
  {
    id: '42.9.1',
    hasContent: true,
    name_en: 'Shoushan Xingnian',
    other_name_en: 'Shoushan Shengnian',
    name_ja: 'Kōke Zonshō',
    name_zh: '首山省念',
    name_vi: 'Thủ Sơn Tỉnh Niệm',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['926', '993'],
    epoch: '',
    records: '',
    sect: ['Linji'],
    country: 'China',
    place: '-',
    teachers: ['Fengxue Yanzhao'],
    successors: ['Fenyang Shanzhao'],
    disciples: ['Fenyang Shanzhao', 'Shexian Guixing', 'Guyin Yuncong', 'Sanjiao Zhisong',
      'Guanghui Yuanlian', 'Shending Hongyin', 'Shoushan Huaizhi' ],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/Th%E1%BB%A7_S%C6%A1n_T%E1%BB%89nh_Ni%E1%BB%87m', 'https://pl.wikipedia.org/wiki/Shoushan_Xingnian'],
  },
  {
    id: '42.9.2',
    hasContent: true,
    name_en: 'Fayan Wenyi',
    name_ja: 'Hōgen Buneki',
    name_zh: '法眼文益',
    name_vi: 'Pháp Nhãn Văn Ích',
    other_name_vi: '',
    nickname_vi: 'Thanh Lương, Tuệ Tịch',
    worship_tower: '',
    birth_death_time: ['885', '958'],
    epoch: '',
    records: '',
    sect: ['Fayan'],
    country: 'China',
    place: '-',
    teachers: ['Luohan Guichen'],
    successors: ['Tiantai Deshao'],
    disciples: ['Tiantai Deshao', 'Quy Tông Nghĩa Nhu (Guizong Yirou, 歸宗義柔)',  'Chongshou Qichou',
      'Baizhang Daoheng - Bách Trượng Đạo Hằng (百丈道恆,?-991/992)',
      'Qingliang Taiqin / Qingliang Fadeng - Thanh Lương Pháp Đăng Thái Khâm (泰欽法燈,?-974)',
      'Baoen Huiming', 'Baoen Xuanze - 报恩玄则', 'Lingyin Qingshuo', 'Guizong Cezhen - 归宗策真', 'Baoci Xingyan - 报慈行言'
    ],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/Ph%C3%A1p_Nh%C3%A3n_V%C4%83n_%C3%8Dch',],
  },
  {
    id: '42.9.3',
    hasContent: true,
    name_en: 'Zhimen Guangzuo',
    name_ja: 'Chimon Kōso',
    name_zh: '智門光祚',
    name_vi: 'Trí Môn Quang Tộ',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['?', '1031'],
    epoch: '',
    records: '',
    sect: ['Yunmen'],
    country: 'China',
    place: '-',
    teachers: ['Xianglin Chéngyuan'],
    successors: ['Xuedou Chongxian'],
    disciples: ['Xuedou Chongxian', 'Jiufeng Qin'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/Tr%C3%AD_M%C3%B4n_Quang_T%E1%BB%99',],
  },
  {
    id: '42.9.4',
    name_en: 'Deshan Huiyuan',
    name_ja: 'Deshan Huiyuan',
    name_zh: '德山慧遠 / 德善慧遠',
    name_vi: 'Đức Sơn Huệ Viễn',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: ['Yunmen'],
    country: 'China',
    place: '-',
    teachers: ['Shuangquan Renyu'],
    successors: ['Kaixian Shanxian'],
    disciples: ['Kaixian Shanxian'],
    image: '/images/avatar.png',
    reference: ['https://brill.com/downloadpdf/book/edcoll/9789004271647/B9789004271647_020.xml',],
  },
  {
    id: '42.9.5',
    name_en: 'Wenshu Yingzhen',
    name_ja: 'Monju Ôshin',
    name_zh: '文殊応真',
    name_vi: 'Văn Thù Ứng Chơn',
    other_name_vi: 'Văn Thù Ứng Chân',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: ['Yunmen'],
    country: 'China',
    place: '-',
    teachers: ['Deshan Yuanmi'],
    successors: ['Dongshan Xiaocong'],
    disciples: ['Dongshan Xiaocong'],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '42.9.6',
    hasContent: true,
    name_en: 'Lianhua Fengxiang',
    name_ja: 'Renge Hôshô',
    name_zh: '蓮華峰祥',
    name_vi: 'Liên Hoa Phong Tường',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: ['Yunmen'],
    country: 'China',
    place: '-',
    teachers: ['Shuangquan Renyu'],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Lianhua_Fengxiang',],
  },
  {
    id: '42.9.7',
    name_en: 'Liangshan Yuanguan',
    name_ja: 'Ryōzan Enkan',
    name_zh: '梁山緣觀',
    name_vi: 'Lương Sơn Duyên Quán',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['920', '990'],
    epoch: '',
    records: '',
    sect: ['Caodong'],
    country: 'China',
    place: '-',
    teachers: ['Tongan Guanzhi'],
    successors: ['Dayang Jingxuan'],
    disciples: ['Dayang Jingxuan (Taiyang)', 'Shimen Huiche? (Shimena Xiana)'],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Liangshan_Yuanguan', 'https://vi.wikipedia.org/wiki/L%C6%B0%C6%A1ng_S%C6%A1n_Duy%C3%AAn_Qu%C3%A1n',
    'https://en.wikipedia.org/wiki/Liangshan_Yuanguan'],
  },
  {
    id: '42.9.8',
    hasContent: true,
    name_en: 'Wuzu Shijie',
    name_ja: 'Goso Shikai',
    name_zh: '五祖師戒',
    name_vi: 'Ngũ Tổ Sư Giới',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: ['Yunmen'],
    country: 'China',
    place: 'Wuzushan (五祖山) (Phùng mậu sơn, Đông Sơn), Hoàng Mai district (黃梅), Hubei province) & Đại Ngu Sơn (大愚山), Cao An district (高安縣, Jiangxi province) ',
    teachers: ['Shuangquan Shikuang'],
    successors: ['Dongshan Zibao'],
    disciples: ['Dongshan Zibao', 'Letan Huaicheng (泐潭懷澄)'],
    image: '/images/avatar.png',
    reference: ['https://phatgiao.org.vn/tu-dien-phat-hoc-online/ngu-to-su-gioi-k4692.html',],
  },
  {
    id: '42.9.9',
    hasContent: true,
    name_en: 'Fuyan Liangya',
    name_ja: 'Fuyan Liangya',
    name_zh: '福巖良雅',
    name_vi: 'Phúc Nghiêm Lương Nhã',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: ['Yunmen'],
    country: 'China',
    place: 'Tanzhou',
    teachers: ['Dongshan Shouchu'],
    successors: ['Beichan Zhixian'],
    disciples: ['Beichan Zhixian'],
    image: '/images/avatar.png',
    reference: ['https://phatgiao.org.vn/tu-dien-phat-hoc-online/bac-thien-phanh-nguu-k29322.html',],
  },
  {
    id: '42.9.10',
    hasContent: 'true',
    name_en: 'Baoen Qicong',
    name_ja: 'Baoen Qicong',
    name_zh: '報恩契從',
    name_vi: 'Báo Ân Khế Tùng',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Mingzhao Deqian'],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: ['https://zenmarrow.com/Single?id=214&index=sho'],
  },
  {
    id: '42.9.11',
    name_en: 'Sanjiao Zhiqian',
    name_ja: 'Sanjiao Zhiqian',
    name_zh: '三角志謙',
    name_vi: 'Tam Giác Chí Khiêm',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: ['Guiyang'],
    country: 'China',
    place: '-',
    teachers: ['Guizhen Deshao'],
    successors: ['Xingyang Ciduo'],
    disciples: ['Xingyang Ciduo'],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Sanjiao_Zhiqian'],
  },
]
export default CnLv9MasterDb;
