const CnLv24MasterDb = [
  {
    id: 57.1,
    name_en: 'Tenjo Isoku',
    name_es: 'Tenjo Isoku',
    name_de: 'Tenjo Isoku',
    name_fr: 'Tenjo Isoku',
    name_vi: 'Thiên Như Duy Tắc',
    name_ru: 'Tenjo Isoku',
    name_zh: '天如惟則',
    name_ja: 'Tenjo Isoku',
    name_ko: 'Tenjo Isoku',
    name_ar: 'Tenjo Isoku',
    birth_death_time: ['?', '1354'],
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: 'China',
    place: '-',
    teachers: ['Zhongfeng Mingben'],
    successors: ['-'],
    disciples: ['-'],
    image: '/',
    reference: ['http://www.thuongchieu.net/index.php/phapthoai/suphu/4207-thiensunhutac', 'https://duylucthien.wordpress.com/2024/01/12/thien-nhu-duy-tac-thien-su/', 'https://thuvienhoasen.org/a8016/thien-nhu-dai-su', 'https://ph.tinhtong.vn/Home/MP3?p=MP3*Tinh+Do+Hoac+Van+-+Thien+Nhu+Duy+Tac', 'https://ngulucthien.com/thien-su-duy-tac/', ''],
  },
]
export default CnLv24MasterDb;
