const CnLv23MasterDb = [
  {
    id: '56.23.1',
    hasContent: true,
    name_en: 'Zhongfeng Mingben',
    name_es: 'Zhongfeng Mingben',
    name_de: 'Zhongfeng Mingben',
    name_fr: 'Zhongfeng Mingben',
    name_vi: 'Trung Phong Minh Bản',
    name_ru: 'Zhongfeng Mingben',
    name_zh: '中峰明本',
    name_ja: 'Zhongfeng Mingben',
    name_ko: 'Zhongfeng Mingben',
    name_ar: 'Zhongfeng Mingben',
    birth_death_time: ['', ''],
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: 'China',
    place: '-',
    teachers: ['Gaofeng Yuanmiao'],
    successors: ['-'],
    disciples: ['Thiên Như Duy Tắc-Tenjo Isoku', 'Cổ Tiên Ấn Nguyên', 'Thiên Nham Nguyên Trường-Sengan Genchō', 'Cô Phong Giác Minh-Kohō Kakumyō'],
    image: 'https://terebess.hu/zen/mesterek/Zhongfeng_Mingben.jpg',
    reference: ['http://www.thuongchieu.net/index.php/phapthoai/suphu/4194-tstrungphongban', 'https://vi.wikipedia.org/wiki/Trung_Phong_Minh_B%E1%BA%A3n'],
    collections: ['https://tangthuphathoc.net/thien-muc-minh-bon-thien-su-tap-luc-quyen-0001/', 'https://tangthuphathoc.net/thien-muc-minh-bon-thien-su-tap-luc-quyen-0002/', 'https://tangthuphathoc.net/thien-muc-minh-bon-thien-su-tap-luc-quyen-0003/'],
    youtubeId: ['i5I899Ht89c', 'plJmknVMv3c', '3y1vJNWIMxA',],
  },
  {
    id: '56.23.2',
    name_en: 'Chunzuo Wencai',
    name_es: 'Chunzuo Wencai',
    name_de: 'Chunzuo Wencai',
    name_fr: 'Chunzuo Wencai',
    name_vi: 'Thuần Chuyết Văn Tài',
    name_ru: 'Chunzuo Wencai',
    name_zh: '淳拙文才',
    name_ja: 'Chunzuo Wencai',
    name_ko: 'Chunzuo Wencai',
    name_ar: 'Chunzuo Wencai',
    birth_death_time: ['1273', '1352'],
    records: '',
    sect: ['Caodong'],
    country: 'China',
    place: '-',
    teachers: ['Huanyuan Fuyu'],
    successors: ['Songting Ziyan'],
    disciples: ['Songting Ziyan'],
    image: '/images/avatar.png',
    reference: [''],
  },
]
export default CnLv23MasterDb;
