const CnLv13MasterDb = [
  {
    id: '46.13.1',
    name_en: 'Baiyun Shouduan',
    name_ja: 'Hakuun Shutan',
    name_zh: '白雲守端',
    pinyin: '',
    name_vi: 'Bạch Vân Thủ Đoan',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1025', '1072'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Yangqi Fanghui'],
    successors: ['Wuzu Fayan'],
    disciples: ['Wuzu Fayan'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/B%E1%BA%A1ch_V%C3%A2n_Th%E1%BB%A7_%C4%90oan',],
  },
  {
    id: '46.13.2',
    hasContent: true,
    name_en: 'Yungai Shouzhi',
    name_ja: 'Ungai Shuchi',
    name_zh: '雲蓋守智',
    pinyin: '',
    name_vi: 'Vân Cái Thủ Trí',
    other_name_vi: 'Vân Cái Thọ Chi',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1025', '1115'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Huanglong'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Huanglong Huinan'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/Ph%E1%BA%ADt_gi%C3%A1o_h%E1%BB%87_ph%E1%BA%A3', 'http://www.fodizi.tw/f04/42092.html',
      'https://bodhi.takungpao.com/ptls/club/2015-09/3147870_app.html?tkpc=4', 'http://www.njqls.com/newsInfo.asp?ID=2536'],
  },
  {
    id: '46.13.3',
    name_en: 'Baofeng Kewen',
    other_name_en: 'Letan Kewen, Yunan Kewen',
    name_ja: 'Shinjō Kokubun',
    other_name_ja: 'Unan Kokumon',
    name_zh: '眞淨克文',
    other_name_zh: '雲庵克文, 寶峰克文 (寳峰克文), 泐潭克文',
    pinyin: '',
    name_vi: 'Bảo Phong Khắc Văn',
    other_name_vi: 'Lặc Đàm Khắc Văn, Bảo Phong Khắc Văn, Chơn Tịnh Khắc Văn, Chân Tịnh Khắc Văn, Vân Am Khắc Văn',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1025', '1102'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Huanglong'],
    country: '🇨🇳',
    place: 'Yun’an, Letan',
    teachers: ['Huanglong Huinan'],
    successors: ['Letan Wenzhun'],
    disciples: ['Letan Wenzhun'],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Yun%E2%80%99an_Kewen',
      'https://vi.wikipedia.org/wiki/Ch%C3%A2n_T%E1%BB%8Bnh_Kh%E1%BA%AFc_V%C4%83n'],
  },
  {
    id: '46.13.4',
    hasContent: true,
    name_en: 'Huitang Zuxin',
    name_ja: 'Kaidō Soshin',
    other_name_ja: 'Maidō Soshin',
    name_zh: '晦堂祖心',
    pinyin: '',
    name_vi: 'Hối Đường Tổ Tâm',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1025', '1100'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Huanglong'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Huanglong Huinan'],
    successors: ['Sixin Wuxin'],
    disciples: ['Lingyuan Weiqing', 'Sixin Wuxin', 'Caotang Shanqing', 'Baofu Benquan'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/H%E1%BB%91i_%C4%90%C6%B0%E1%BB%9Dng_T%E1%BB%95_T%C3%A2m', 'https://terebess.hu/zen/mesterek/HuitangZuxin.html',
      'https://pl.wikipedia.org/wiki/Huitang_Zuxin'],
  },
  {
    id: '46.13.5',
    hasContent: true,
    name_en: 'Baoning Renyong',
    other_name_en: 'Bao’eng Renyong',
    name_ja: 'Hōnei Ninyū',
    other_name_ja: 'Honei Jinyū',
    name_zh: '保寧仁勇',
    other_name_zh: '保寧仁勇',
    pinyin: '',
    name_vi: 'Bảo Ninh Nhân Dũng',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', '1046?'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: '🇨🇳',
    place: 'Baoning Temple (宝宁寺/寶寧寺/Bǎoníng Sì), Yuelu District of Changsha, Hunan',
    teachers: ['Yangqi Fanghui'],
    successors: [''],
    disciples: ['Thọ Thánh Trí Uyên (壽聖智淵)', 'Thọ Thánh Sở Văn (壽聖楚文)', 'Bảo Tích Tông Ánh (寶積宗映)', 'Cảnh Phước Nhật Dư (景福日余)'],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Bao%E2%80%99eng_Renyong',],
  },
  {
    id: '46.13.6',
    hasContent: true,
    name_en: 'Dagui Muzhe',
    other_name_en: 'Guishan Muzhe',
    name_zh: '大沩慕哲',
    other_name_zh: '大溈慕哲',
    pinyin: '',
    name_vi: 'Đại Qui Mộ Triết',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', '1132'],
    epoch: '',
    records: '',
    sect: ['Linji'],
    country: '🇨🇳',
    place: 'Guishan',
    teachers: ['Cuiyan Kezhen'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Dagui_Muzhe',],
  },
  {
    id: '46.13.7',
    hasContent: true,
    name_en: 'Furong Daokai',
    name_ja: 'Fuyō Dōkai',
    name_zh: '芙蓉道楷',
    name_vi: 'Phù Dung Đạo Khải',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1042', '1118'],
    epoch: '',
    records: '',
    sect: ['Caodong'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Touzi Yiqing'],
    successors: [''],
    disciples: ['Danxia Zichun', 'Huizhao Qingyu', 'Hongzhi Zhengjue', 'Lumen Zijue'],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Furong_Daokai',],
  },
  {
    id: '46.13.8',
    name_en: 'Donglin Changcong',
    other_name_en: 'Zhaojue Changzong',
    name_ja: 'Tōrin Jōsō',
    name_zh: '東林常聰',
    other_name_zh: '東林常總',
    pinyin: '',
    name_vi: 'Đông Lâm Thường Thông',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1025', '1091'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Huanglong'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Huanglong Huinan'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://phatgiao.org.vn/tu-dien-phat-hoc-online/dong-lam-thuong-thong-k3939.html',
      'https://www.sklib.cn/booklib/databasedetail?SiteID=122&ID=6947403&searchText=%25E4%25BD%259B%25E5%258D%25B0&fromSubID=',
      'https://cbetaonline.dila.edu.tw/zh/X1263'],
  },
  {
    id: '46.13.9',
    name_en: 'Letan Hongying',
    other_name_en: 'Baofeng Hongying',
    name_ja: 'Letan Hongying',
    name_zh: '泐潭洪英, ',
    name_vi: 'Lặc Đàm Hồng Anh',
    other_name_vi: 'Bảo Phong Hồng Anh',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1012', '1070'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Huanglong'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Huanglong Huinan'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://zenmarrow.com/lineage-chart?m=120'],
  },
]
export default CnLv13MasterDb;
