const CnLv3MasterDb = [
  {
    id: 36.1,
    name_en: 'Kinh Nam Duy Trung',
    name_es: 'Kinh Nam Duy Trung',
    name_de: 'Kinh Nam Duy Trung',
    name_fr: 'Kinh Nam Duy Trung',
    name_vi: 'Kinh Nam Duy Trung',
    name_ru: 'Kinh Nam Duy Trung',
    name_zh: '荊南惟忠',
    name_ja: 'Kinh Nam Duy Trung',
    name_ko: 'Kinh Nam Duy Trung',
    name_ar: 'Kinh Nam Duy Trung',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Cizhou Faru'],
    successors: ['Toại Châu Đạo Viên'],
    disciples: ['Toại Châu Đạo Viên'],
    image: '/images/avatar.png',
    reference: ['https://ngulucthien.com/thien-su-duy-trung/'],
  },
  {
    id: 36.2,
    name_en: 'Yaoshan Weiyan',
    name_es: 'Yaoshan Weiyan',
    name_de: 'Yaoshan Weiyan',
    name_fr: 'Yaoshan Weiyan',
    name_vi: 'Dược Sơn Duy Nghiễm',
    name_ru: 'Yaoshan Weiyan',
    name_zh: '藥山惟儼',
    name_ja: 'Yakusan Igen',
    name_ko: 'Yaksan Yuǒm',
    name_ar: 'Yaoshan Weiyan',
    birth_death_time: ['745', '827'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Shitou Xiqian', 'Mazu Daoyi'],
    successors: ['Yunyan Tansheng'],
    disciples: ['Yunyan Tansheng'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/b/bc/Yaoshan_Weiyan_Image.jpg',
  },
  {
    id: 36.3,
    name_en: 'Tianhuang Daowu',
    name_es: 'Tianhuang Daowu',
    name_de: 'Tianhuang Daowu',
    name_fr: 'Tianhuang Daowu',
    name_vi: 'Thiên Hoàng Đạo Ngộ',
    name_ru: 'Tianhuang Daowu',
    name_zh: '天皇道悟',
    name_ja: 'Tianhuang Daowu',
    name_ko: 'Tianhuang Daowu',
    name_ar: 'Tianhuang Daowu',
    birth_death_time: ['748', '807'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Shitou Xiqian'],
    successors: ['Longtan Chongxin'],
    disciples: ['Longtan Chongxin'],
    image: '/images/avatar.png',
    reference: ['https://ngulucthien.com/thien-su-dao-ngo-747-806/'],
  },
  {
    id: 36.4,
    name_en: 'Dadian Baotong',
    name_es: 'Dadian Baotong',
    name_de: 'Dadian Baotong',
    name_fr: 'Dadian Baotong',
    name_vi: 'Đại Điên Bảo Thông',
    name_ru: 'Dadian Baotong',
    name_zh: '大顛寶通',
    name_ja: 'Daiten Hōtsū',
    name_ko: 'Dadian Baotong',
    name_ar: 'Dadian Baotong',
    birth_death_time: ['?', '819'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Shitou Xiqian'],
    successors: ['Sanping Yizhong'],
    disciples: ['Sanping Yizhong'],
    image: '/images/avatar.png',
    reference: ['https://ngulucthien.com/thien-su-baothong-dai-dien-732-824/'],
  },
  {
    id: 36.5,
    name_en: 'Danxia Tianran',
    name_es: 'Danxia Tianran',
    name_de: 'Danxia Tianran',
    name_fr: 'Danxia Tianran',
    name_vi: 'Đan Hà Thiên Nhiên',
    name_ru: 'Danxia Tianran',
    name_zh: '丹霞天然',
    name_ja: 'Ranka Rennen',
    name_ko: 'Danxia Tianran',
    name_ar: 'Danxia Tianran',
    birth_death_time: ['739', '824'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Shitou Xiqian', 'Mazu Daoyi'],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: 36.6,
    name_en: 'Baizhang Huaihai',
    name_es: 'Baizhang Huaihai',
    name_de: 'Baizhang Huaihai',
    name_fr: 'Baizhang Huaihai',
    name_vi: 'Long Đàm Sùng Tín',
    name_ru: 'Baizhang Huaihai',
    name_zh: '龍潭崇信',
    name_ja: 'Baizhang Huaihai',
    name_ko: 'Baizhang Huaihai',
    name_ar: 'Baizhang Huaihai',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Mazu Daoyi'],
    successors: ['Huangbo Xiyun'],
    disciples: ['Huangbo Xiyun', 'Yunyan Tansheng', 'Huangbo Xiyun'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/B%C3%A1ch_Tr%C6%B0%E1%BB%A3ng_Ho%C3%A0i_H%E1%BA%A3i'],
  },
]
export default CnLv3MasterDb;
