const CnLv21MasterDb = [
  {
    id: '54.21.1',
    hasContent: true,
    name_en: 'Xueyan Zuqin',
    other_name_en: 'Xueyan Huilang',
    name_ja: 'Seggan Sokin',
    name_zh: '雪巖祖欽',
    other_name_zh: '法欽, 惠朗',
    name_vi: 'Tuyết Nham Tổ Khâm',
    other_name_vi: 'Pháp Khâm',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1215/1216?', '1287'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Wuzhun Shifan'],
    successors: ['Gaofeng Yuanmiao'],
    disciples: ['Gaofeng Yuanmiao'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/Tuy%E1%BA%BFt_Nham_T%E1%BB%95_Kh%C3%A2m',
      'https://terebess.hu/zen/mesterek/XueyanZuqin.html', 'http://www.thuongchieu.net/index.php/phapthoai/suphu/4162-thiensutuyetkham'
    ],
    youtubeId: ['KpoUcjH7bRM'],
  },
  {
    id: '54.21.2',
    hasContent: true,
    name_en: 'Lingyin Wentai',
    name_ja: 'Lingyin Wentai',
    name_zh: '靈隱文泰',
    name_vi: 'Linh Ẩn Văn Thái',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['-', '1289'],
    records: '',
    sect: ['Caodong'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Xueting Fuyu'],
    successors: ['Huanyuan Fuyu'],
    disciples: ['Huanyuan Fuyu'],
    image: '/images/avatar.png',
    reference: [''],
  },
]
export default CnLv21MasterDb;
