const CnLv4MasterDb = [
  {
    id: 37.1,
    name_en: 'Toại Châu Đạo Viên',
    name_es: 'Toại Châu Đạo Viên',
    name_de: 'Toại Châu Đạo Viên',
    name_fr: 'Toại Châu Đạo Viên',
    name_vi: 'Đại Đức Đạo Viên / Toại Châu Đạo Viên',
    name_ru: 'Toại Châu Đạo Viên',
    name_zh: '遂州道圓/大德道圓',
    name_ja: 'Toại Châu Đạo Viên',
    name_ko: 'Toại Châu Đạo Viên',
    name_ar: 'Toại Châu Đạo Viên',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Kinh Nam Duy Trung'],
    successors: ['Khuê Phong Tông Mật'],
    disciples: ['Khuê Phong Tông Mật'],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: 37.2,
    name_en: 'Yunyan Tansheng',
    name_es: 'Yunyan Tansheng',
    name_de: 'Yunyan Tansheng',
    name_fr: 'Yunyan Tansheng',
    name_vi: 'Vân Nham Đàm Thạnh',
    name_ru: 'Yunyan Tansheng',
    name_zh: '雲巖曇晟',
    name_ja: 'Ungan Donjō',
    name_ko: 'Unam Tamsŭng',
    name_ar: 'Yunyan Tansheng',
    birth_death_time: ['780', '841'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Yaoshan Weiyan, Baizhang Huaihai'],
    successors: ['Dongshan Liangjie'],
    disciples: ['Dongshan Liangjie'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Yunyan_Tansheng_Image_Zen.jpg/220px-Yunyan_Tansheng_Image_Zen.jpg',
    reference: [''],
  },
  {
    id: 37.3,
    name_en: 'Longtan Chongxin',
    name_es: 'Longtan Chongxin',
    name_de: 'Longtan Chongxin',
    name_fr: 'Longtan Chongxin',
    name_vi: 'Long Đàm Sùng Tín',
    name_ru: 'Longtan Chongxin',
    name_zh: '龍潭崇信',
    name_ja: 'Ryūtan Sōshin',
    name_ko: '룡담숭신 Lyongdam Sungsin',
    name_ar: 'Longtan Chongxin',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Tianhuang Daowu'],
    successors: ['Deshan Xuanjian'],
    disciples: ['Deshan Xuanjian'],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: 37.4,
    name_en: 'Guishan Lingyou',
    name_es: 'Guishan Lingyou',
    name_de: 'Guishan Lingyou',
    name_fr: 'Guishan Lingyou',
    name_vi: 'Quy Sơn Linh Hựu',
    name_ru: 'Guishan Lingyou',
    name_zh: '潙山靈祐',
    name_ja: 'Isan Reiyû',
    name_ko: 'Guishan Lingyou',
    name_ar: 'Guishan Lingyou',
    birth_death_time: ['771', '853'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Tianhuang Daowu'],
    successors: ['Yangshan Huiji'],
    disciples: ['Yangshan Huiji'],
    image: '/images/avatar.png',
    collections: ['https://thuvienhoasen.org/images/file/OI6imJ1G0QgQAJ8X/quy-son-ngu-luc.pdf'],
    reference: ['https://terebess.hu/zen/guishan.html', 'https://en.wikipedia.org/wiki/Guishan_Lingyou', 'https://vi.wikipedia.org/wiki/Quy_S%C6%A1n_Linh_H%E1%BB%B1u', 'http://thuongchieu.net/index.php/phapthoai/suphu/4804-tslinhhuu', 'https://phatphapungdung.com/phap-bao/ngu-luc-cua-thien-su-dam-chau-quy-son-linh-huu-164038.html', 'https://thuvienhoasen.org/images/file/OI6imJ1G0QgQAJ8X/quy-son-ngu-luc.pdf'],
  },
  {
    id: 37.5,
    name_en: 'Sanping Yizhong',
    name_es: 'Sanping Yizhong',
    name_de: 'Sanping Yizhong',
    name_fr: 'Sanping Yizhong',
    name_vi: 'Tam Bình Nghĩa Trung',
    name_ru: 'Sanping Yizhong',
    name_zh: '三平義忠',
    name_ja: 'Sanping Yizhong',
    name_ko: 'Sanping Yizhong',
    name_ar: 'Sanping Yizhong',
    birth_death_time: ['781', '872'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Dadian Baotong'],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    collections: [''],
    reference: ['https://terebess.hu/zen/shigong.html'],
  },
  {
    id: 37.6,
    name_en: 'Cuiwei Wuxue',
    name_es: 'Cuiwei Wuxue',
    name_de: 'Cuiwei Wuxue',
    name_fr: 'Cuiwei Wuxue',
    name_vi: 'Thúy Vi Vô Học/Ngọc',
    name_ru: 'Cuiwei Wuxue',
    name_zh: '翠微無學',
    name_ja: 'Suibi Mugaku',
    name_ko: 'Cuiwei Wuxue',
    name_ar: 'Cuiwei Wuxue',
    birth_death_time: ['739', '824'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Danxia Tianran'],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    collections: [''],
    reference: ['https://terebess.hu/zen/mesterek/CuiweiWuxue.html', 'https://vi.wikipedia.org/wiki/Th%C3%BAy_Vi_V%C3%B4_H%E1%BB%8Dc', 'https://blog.phapthihoi.org/tu-dien-phat-giao/thuy-vi-vo-hoc/'],
  },
  {
    id: 37.7,
    name_en: 'Huangbo Xiyun',
    name_es: 'Huangbo Xiyun',
    name_de: 'Huangbo Xiyun',
    name_fr: 'Huangbo Xiyun',
    name_vi: 'Hoàng Bá Hi Vận',
    name_ru: 'Huangbo Xiyun',
    name_zh: '黃蘖希運',
    name_ja: 'Obaku kiun',
    name_ko: 'Huangbo Xiyun',
    name_ar: 'Huangbo Xiyun',
    birth_death_time: ['?', '850'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Baizhang Huaihai'],
    successors: ['Linji Yixuan'],
    disciples: ['Linji Yixuan'],
    image: '/',
    reference: [''],
  },
]
export default CnLv4MasterDb;
