const CnLv13MasterDb = [
  {
    id: '46.13.1',
    name_en: 'Baiyun Shouduan',
    name_es: 'Baiyun Shouduan',
    name_de: 'Baiyun Shouduan',
    name_fr: 'Baiyun Shouduan',
    name_vi: 'Bạch Vân Thủ Đoan',
    name_ru: 'Baiyun Shouduan',
    name_zh: '白雲守端',
    name_ja: 'Hakuun Shutan',
    name_ko: 'Baiyun Shouduan',
    name_ar: 'Baiyun Shouduan',
    birth_death_time: ['1025', '1072'],
    records: '',
    sect: ['Linji - Yangqi'],
    country: 'China',
    place: '-',
    teachers: ['Yangqi Fanghui'],
    successors: ['Wuzu Fayan'],
    disciples: ['Wuzu Fayan'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/B%E1%BA%A1ch_V%C3%A2n_Th%E1%BB%A7_%C4%90oan',],
  },
  {
    id: '46.13.2',
    name_en: 'Yungai Shouzhi',
    name_es: 'Yungai Shouzhi',
    name_de: 'Yungai Shouzhi',
    name_fr: 'Yungai Shouzhi',
    name_vi: '',
    name_ru: 'Yungai Shouzhi',
    name_zh: '興化存奬',
    name_ja: 'Kōke Zonshō',
    name_ko: 'Yungai Shouzhi',
    name_ar: 'Yungai Shouzhi',
    birth_death_time: ['830', '888'],
    records: '',
    sect: ['Linji'],
    country: 'China',
    place: '-',
    teachers: ['Linji Yixuan'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '46.13.3',
    name_en: 'Baofeng Kewen',
    name_es: 'Baofeng Kewen',
    name_de: 'Baofeng Kewen',
    name_fr: 'Baofeng Kewen',
    name_vi: '',
    name_ru: 'Baofeng Kewen',
    name_zh: '興化存奬',
    name_ja: 'Kōke Zonshō',
    name_ko: 'Baofeng Kewen',
    name_ar: 'Baofeng Kewen',
    birth_death_time: ['830', '888'],
    records: '',
    sect: ['Linji'],
    country: 'China',
    place: '-',
    teachers: ['Linji Yixuan'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '46.13.4',
    name_en: 'Huitang Zuxin',
    name_es: 'Huitang Zuxin',
    name_de: 'Huitang Zuxin',
    name_fr: 'Huitang Zuxin',
    name_vi: '',
    name_ru: 'Huitang Zuxin',
    name_zh: '興化存奬',
    name_ja: 'Kōke Zonshō',
    name_ko: 'Huitang Zuxin',
    name_ar: 'Huitang Zuxin',
    birth_death_time: ['830', '888'],
    records: '',
    sect: ['Linji'],
    country: 'China',
    place: '-',
    teachers: ['Linji Yixuan'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '46.13.5',
    hasContent: true,
    name_en: 'Baoning Renyong',
    name_es: 'Baoning Renyong',
    name_de: 'Baoning Renyong',
    name_fr: 'Baoning Renyong',
    name_vi: 'Bảo Ninh Nhân Dũng',
    name_ru: 'Baoning Renyong',
    name_zh: '保寧仁勇/保宁仁勇',
    name_ja: 'Hōnei Ninyū',
    name_ko: 'Baoning Renyong',
    name_ar: 'Baoning Renyong',
    birth_death_time: ['?', '1046?'],
    records: '',
    sect: ['Linji - Yangqi'],
    country: 'China',
    place: 'Baoning Temple (宝宁寺/寶寧寺/Bǎoníng Sì - Bảo Ninh Tự), Yuelu District of Changsha, Hunan',
    teachers: ['Yangqi Fanghui'],
    successors: [''],
    disciples: ['Thọ Thánh Trí Uyên (壽聖智淵), Thọ Thánh Sở Văn (壽聖楚文), Bảo Tích Tông Ánh (寶積宗映), Cảnh Phước Nhật Dư (景福日余)'],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '46.13.6',
    hasContent: true,
    name_en: 'Dagui Muzhe (Guishan)',
    name_es: 'Dagui Muzhe',
    name_de: 'Dagui Muzhe',
    name_fr: 'Dagui Muzhe',
    name_vi: 'Đại Qui Mộ Triết',
    name_ru: 'Dagui Muzhe',
    name_zh: '大沩慕哲 / 大溈慕哲',
    name_ja: 'Daii Botetsu',
    name_ko: '대?모철 Tae? Mochŏl',
    name_ar: 'Dagui Muzhe',
    birth_death_time: ['?', '1132'],
    records: '',
    sect: ['Linji'],
    country: 'China',
    place: '',
    teachers: ['Cuiyan Kezhen'],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Dagui_Muzhe',],
  },
  {
    id: '46.13.7',
    hasContent: true,
    name_en: 'Furong Daokai',
    name_es: 'Furong Daokai',
    name_de: 'Furong Daokai',
    name_fr: 'Furong Daokai',
    name_vi: 'Phù Dung Đạo Khải',
    name_ru: 'Furong Daokai',
    name_zh: '芙蓉道楷',
    name_ja: 'Fuyō Dōkai',
    name_ko: '부용도해 Puyong Tohae',
    name_ar: 'Furong Daokai',
    birth_death_time: ['1042', '1118'],
    records: '',
    sect: ['Caodong'],
    country: 'China',
    place: '',
    teachers: ['Touzi Yiqing'],
    successors: [''],
    disciples: ['Danxia Zichun', 'Huizhao Qingyu', 'Hongzhi Zhengjue', 'Lumen Zijue'],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Furong_Daokai',],
  },
]
export default CnLv13MasterDb;
