const CnLv9MasterDb = [
  {
    id: '42.9.1',
    name_en: 'Shoushan Xingnian',
    name_es: 'Shoushan Xingnian',
    name_de: 'Shoushan Xingnian',
    name_fr: 'Shoushan Xingnian',
    name_vi: 'Thủ Sơn Tỉnh Niệm',
    name_ru: 'Shoushan Xingnian',
    name_zh: '首山省念',
    name_ja: 'Kōke Zonshō',
    name_ko: 'Shoushan Xingnian',
    name_ar: 'Shoushan Xingnian',
    birth_death_time: ['926', '993'],
    records: '',
    sect: ['Linji'],
    country: 'China',
    place: '-',
    teachers: ['Fengxue Yanzhao'],
    successors: ['Fenyang Shanzhao'],
    disciples: ['Fenyang Shanzhao', 'Shexian Guixing', 'Guyin Yuncong' , 'Tiefo Zhisong' ],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/Th%E1%BB%A7_S%C6%A1n_T%E1%BB%89nh_Ni%E1%BB%87m', 'https://pl.wikipedia.org/wiki/Shoushan_Xingnian'],
  },
  {
    id: '42.9.2',
    hasContent: true,
    name_en: 'Fayan Wenyi',
    name_es: 'Fayan Wenyi',
    name_de: 'Fayan Wenyi',
    name_fr: 'Fayan Wenyi',
    name_vi: 'Pháp Nhãn Văn Ích (Thanh Lương, Tuệ Tịch Đại sư)',
    name_ru: 'Fayan Wenyi',
    name_zh: '法眼文益',
    name_ja: 'Hōgen Buneki',
    name_ko: 'Fayan Wenyi',
    name_ar: 'Fayan Wenyi',
    birth_death_time: ['885', '958'],
    records: '',
    sect: ['Fayan'],
    country: 'China',
    place: '-',
    teachers: ['Luohan Guichen'],
    successors: ['Tiantai Deshao'],
    disciples: ['Tiantai Deshao', 'Quy Tông Nghĩa Nhu (歸宗義柔)',  'Sùng Thọ Khế Trù (崇壽契稠)',  'Bách Trượng Đạo Hằng (百丈道恆,?-991/992)',  'Pháp Đăng Thái Khâm (泰欽法燈,?-974)', ],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/Ph%C3%A1p_Nh%C3%A3n_V%C4%83n_%C3%8Dch',],
  },
  {
    id: '42.9.3',
    name_en: 'Zhimen Guangzuo',
    name_es: 'Zhimen Guangzuo',
    name_de: 'Zhimen Guangzuo',
    name_fr: 'Zhimen Guangzuo',
    name_vi: 'Trí Môn Quang Tộ',
    name_ru: 'Zhimen Guangzuo',
    name_zh: '智門光祚',
    name_ja: 'Chimon Kōso',
    name_ko: 'Zhimen Guangzuo',
    name_ar: 'Zhimen Guangzuo',
    birth_death_time: ['?', '1031'],
    records: '',
    sect: ['Yunmen'],
    country: 'China',
    place: '-',
    teachers: ['Xianglin Chéngyuan'],
    successors: ['Xuedou Chongxian'],
    disciples: ['Xuedou Chongxian', 'Jiufeng Qin'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/Tr%C3%AD_M%C3%B4n_Quang_T%E1%BB%99',],
  },
  {
    id: '42.9.4',
    name_en: 'Deshan Huiyuan',
    name_es: 'Deshan Huiyuan',
    name_de: 'Deshan Huiyuan',
    name_fr: 'Deshan Huiyuan',
    name_vi: 'Đức Sơn Huệ Viễn',
    name_ru: 'Deshan Huiyuan',
    name_zh: '德山慧遠 / 德善慧遠',
    name_ja: 'Deshan Huiyuan',
    name_ko: 'Deshan Huiyuan',
    name_ar: 'Deshan Huiyuan',
    birth_death_time: ['', ''],
    records: '',
    sect: ['Yunmen'],
    country: 'China',
    place: '-',
    teachers: ['Shuangquan Renyu'],
    successors: ['Kaixian Shanxian'],
    disciples: ['Kaixian Shanxian'],
    image: '/images/avatar.png',
    reference: ['https://brill.com/downloadpdf/book/edcoll/9789004271647/B9789004271647_020.xml',],
  },
  {
    id: '42.9.5',
    name_en: 'Wenshu Yingzhen',
    name_es: 'Wenshu Yingzhen',
    name_de: 'Wenshu Yingzhen',
    name_fr: 'Wenshu Yingzhen',
    name_vi: 'Wenshu Yingzhen',
    name_ru: 'Wenshu Yingzhen',
    name_zh: 'Wenshu Yingzhen',
    name_ja: 'Monju Ôshin',
    name_ko: 'Wenshu Yingzhen',
    name_ar: 'Wenshu Yingzhen',
    birth_death_time: ['', ''],
    records: '',
    sect: ['Yunmen'],
    country: 'China',
    place: '-',
    teachers: ['Shuangquan Renyu'],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '42.9.6',
    name_en: 'Lianhua Fengxiang',
    name_es: 'Lianhua Fengxiang',
    name_de: 'Lianhua Fengxiang',
    name_fr: 'Lianhua Fengxiang',
    name_vi: 'Liên Hoa Phông Tường',
    name_ru: 'Lianhua Fengxiang',
    name_zh: '蓮華峰祥',
    name_ja: 'Renge Hôshô',
    name_ko: '련화봉상 Lyŏnhwa Pongsang',
    name_ar: 'Lianhua Fengxiang',
    birth_death_time: ['', ''],
    records: '',
    sect: ['Yunmen'],
    country: 'China',
    place: '-',
    teachers: ['Shuangquan Renyu'],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Lianhua_Fengxiang',],
  },
  {
    id: '42.9.7',
    name_en: 'Liangshan Yuanguan',
    name_es: 'Liangshan Yuanguan',
    name_de: 'Liangshan Yuanguan',
    name_fr: 'Liangshan Yuanguan',
    name_vi: 'Lương Sơn Duyên Quán',
    name_ru: 'Liangshan Yuanguan',
    name_zh: '梁山緣觀',
    name_ja: 'Ryōzan Enkan',
    name_ko: '량산연관 Lyangsan Yŏngwan',
    name_ar: 'Liangshan Yuanguan',
    birth_death_time: ['920', '990'],
    records: '',
    sect: ['Caodong'],
    country: 'China',
    place: '-',
    teachers: ['Tongan Guanzhi'],
    successors: ['Dayang Jingxuan'],
    disciples: ['Dayang Jingxuan (Taiyang)', 'Shimen Huiche? (Shimena Xiana)'],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Liangshan_Yuanguan', 'https://vi.wikipedia.org/wiki/L%C6%B0%C6%A1ng_S%C6%A1n_Duy%C3%AAn_Qu%C3%A1n',
    'https://en.wikipedia.org/wiki/Liangshan_Yuanguan'],
  },
]
export default CnLv9MasterDb;
