const CnLv14MasterDb = [
  {
    id: '47.14.1',
    hasContent: true,
    isEminent: true,
    name_en: 'Wuzu Fayan',
    name_es: 'Wuzu Fayan',
    name_de: 'Wuzu Fayan',
    name_fr: 'Wuzu Fayan',
    name_ru: 'Wuzu Fayan',
    name_ja: 'Goso Hōen',
    name_ko: 'Wuzu Fayan',
    name_ar: 'Wuzu Fayan',
    name_zh: '五祖法演',
    name_vi: 'Ngũ Tổ Pháp Diễn',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1024?', '1104'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: 'China',
    place: 'Thái Bình Tự (太平寺) vùng Thư Châu (舒州, Tỉnh An Huy)',
    teachers: ['Baiyun Shouduan'],
    successors: ['Yuanwu Keqin'],
    disciples: ['Yuanwu Keqin', 'Kaifu Daoning', 'Foyan Qingyuan'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/Ng%C5%A9_T%E1%BB%95_Ph%C3%A1p_Di%E1%BB%85n', 'https://phatgiao.org.vn/tu-dien-phat-hoc-online/ngu-to-phap-dien-k1576.html'],
  },
  {
    id: '47.14.2',
    name_en: 'Lumen Zijue',
    name_es: 'Lumen Zijue',
    name_de: 'Lumen Zijue',
    name_fr: 'Lumen Zijue',
    name_ru: 'Lumen Zijue',
    name_ja: 'Rokumon Jikaku',
    name_ko: 'Lumen Zijue',
    name_ar: 'Lumen Zijue',
    name_zh: '鹿門自覺',
    name_vi: 'Lộc Môn Tự Giác',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['-', '1117'],
    records: '',
    sect: ['Caodong'],
    country: 'China',
    place: '-',
    teachers: ['Furong Daokai'],
    successors: ['Puzhao Yibian'],
    disciples: ['Puzhao Yibian'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/L%E1%BB%99c_M%C3%B4n_T%E1%BB%B1_Gi%C3%A1c',
      'https://phatgiao.org.vn/tu-dien-phat-hoc-online/loc-mon-tu-giac-k4442.html',
    ],
  },
  {
    id: '47.14.3',
    hasContent: true,
    name_en: 'Letan Wenzhun',
    other_name_en: 'Zhantang Wenzhun, Baofeng Wenzhun',
    name_es: 'Letan Wenzhun',
    name_de: 'Letan Wenzhun',
    name_fr: 'Letan Wenzhun',
    name_ru: 'Letan Wenzhun',
    name_ar: 'Letan Wenzhun',
    name_ko: 'Letan Wenzhun',
    name_ja: 'Rokutan Monjun',
    other_name_ja: 'Tandō Monjun',
    name_zh: '泐潭文準',
    other_name_zh: '湛堂文準, 寶峰文準',
    name_vi: 'Lặc Đàm Văn Chuẩn',
    other_name_vi: 'Trạm Đường Văn Chuẩn, Bảo Phong Văn Chuẩn',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1061', '1115'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Huanglong'],
    country: 'China',
    place: 'Letan Baofeng Temple (泐潭寶峰寺)',
    teachers: ['Baofeng Kewen'],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: ['https://phatgiao.org.vn/tu-dien-phat-hoc-online/lac-dam-van-chuan-k4354.html',
      'https://phatgiao.org.vn/tu-dien-phat-hoc-online/tram-duong-van-chuan-k5721.html'],
  },
  {
    id: '47.14.4',
    hasContent: true,
    name_en: 'Lingyuan Weiqing',
    other_name_en: 'Changuan Cejin',
    name_es: 'Lingyuan Weiqing',
    name_de: 'Lingyuan Weiqing',
    name_fr: 'Lingyuan Weiqing',
    name_ru: 'Lingyuan Weiqing',
    name_ar: 'Lingyuan Weiqing',
    name_ko: 'Lingyuan Weiqing',
    name_ja: 'Reigen Isei',
    name_zh: '靈源惟清',
    other_name_zh: '禪關策進',
    name_vi: 'Linh Nguyên Duy Thanh',
    other_name_vi: '',
    nickname_vi: 'Phật Thọ',
    worship_tower: '',
    birth_death_time: ['', '1117'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Huanglong'],
    country: 'China',
    place: 'Taiping Zen Temple, Shuzhou (Tang Dynasty) renamed Tongan County, Huaining County (now Qianshan City, Anhui Province) ➡️ 崇恩院, 黄山 ➡️ 昭黙堂',
    teachers: ['Huitang Zuxin'],
    successors: [''],
    disciples: ['Foxin Bencai - 佛心本才 (Northern Song Dynasty)', 'Zhangling Shouzhuo - 長靈守卓 (1066-1124)'],
    image: '/images/avatar.png',
    reference: ['https://terebess.hu/zen/mesterek/LingyuanWeiqing.html',
      'https://phatgiao.org.vn/tu-dien-phat-hoc-online/linh-nguyen-duy-thanh-k4424.html'],
  },
]
export default CnLv14MasterDb;
