const CnLv37MasterDb = [
  {
    id: '70.37.1',
    name_en: 'Yinyuan Longqi',
    name_ja: 'Ingen Ryuki',
    name_zh: '隠元隆琦',
    name_vi: 'Yinyuan Longqi',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1592', '1673'],
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: 'China',
    place: '',
    teachers: ['Huanyou Zhengchuan'],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '70.37.2',
    name_en: '',
    name_ja: '',
    name_zh: '',
    name_vi: '',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: 'China',
    place: '',
    teachers: [''],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: [''],
  },
]
export default CnLv37MasterDb;
