const CnLv30MasterDb = [
  {
    id: '62.29.1',
    name_en: 'Yunkong Changzhong',
    name_es: 'Yunkong Changzhong',
    name_de: 'Yunkong Changzhong',
    name_fr: 'Yunkong Changzhong',
    name_ru: 'Yunkong Changzhong',
    name_ja: 'Yunkong Changzhong',
    name_ko: 'Yunkong Changzhong',
    name_ar: 'Yunkong Changzhong',
    name_zh: '蘊空常忠',
    name_vi: 'Uẩn Không Thường Trung',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1514', '1588'],
    epoch: '',
    records: '',
    sect: ['Caodong'],
    country: 'China',
    place: '-',
    teachers: ['Zongjing Zongshu'],
    successors: ['Wuming Huijing'],
    disciples: ['Wuming Huijing'],
    image: '/images/avatar.png',
    reference: ['https://terebess.hu/zen/mesterek/YunkongChangzhong.html', 'https://londonchanmeditation.org/lineage/'],
  }
]
export default CnLv30MasterDb;
