const CnLv23MasterDb = [
  {
    id: '56.23.1',
    hasContent: true,
    name_en: 'Zhongfeng Mingben',
    name_ja: 'Chūhō Myōhon',
    name_zh: '中峰明本',
    name_vi: 'Trung Phong Minh Bản',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1263', '1323'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Gaofeng Yuanmiao'],
    successors: ['-'],
    disciples: ['Tianru Weize', 'Qianyan Yuanzhang', 'Kohō Kakumyō', 'Kosen Ingen'],
    image: 'https://terebess.hu/zen/mesterek/Zhongfeng_Mingben.jpg',
    reference: ['http://www.thuongchieu.net/index.php/phapthoai/suphu/4194-tstrungphongban', 'https://vi.wikipedia.org/wiki/Trung_Phong_Minh_B%E1%BA%A3n'],
    collections: ['https://tangthuphathoc.net/thien-muc-minh-bon-thien-su-tap-luc-quyen-0001/', 'https://tangthuphathoc.net/thien-muc-minh-bon-thien-su-tap-luc-quyen-0002/', 'https://tangthuphathoc.net/thien-muc-minh-bon-thien-su-tap-luc-quyen-0003/'],
    youtubeId: ['i5I899Ht89c', 'plJmknVMv3c', '3y1vJNWIMxA',],
  },
  {
    id: '56.23.2',
    name_en: 'Chunzuo Wencai',
    name_ja: 'Chunzuo Wencai',
    name_zh: '淳拙文才',
    name_vi: 'Thuần Chuyết Văn Tài',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1273', '1352'],
    records: '',
    sect: ['Caodong'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Huanyuan Fuyu'],
    successors: ['Songting Ziyan'],
    disciples: ['Songting Ziyan'],
    image: '/images/avatar.png',
    reference: [''],
  },
]
export default CnLv23MasterDb;
