const CnLv22MasterDb = [
  {
    id: '55.22.1',
    hasContent: true,
    name_en: 'Gaofeng Yuanmiao',
    name_ja: 'Kōhō Genmyō',
    name_zh: '高峰原妙',
    name_vi: 'Cao Phong Nguyên Diệu',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: 'China',
    place: '-',
    teachers: ['Xueyan Zuqin'],
    successors: ['Zhongfeng Mingben'],
    disciples: ['Zhongfeng Mingben'],
    image: 'https://terebess.hu/zen/mesterek/woodcut/55.jpg',
    reference: ['https://vi.wikipedia.org/wiki/Cao_Phong_Nguy%C3%AAn_Di%E1%BB%87u', 'https://terebess.hu/zen/mesterek/GaofengYuanmiao.html', 'http://www.thuongchieu.net/index.php/phapthoai/suphu/4171-tscaophongdieu'],
    youtubeId: ['2eAlynd_JTE'],
  },
  {
    id: '55.22.2',
    hasContent: true,
    name_en: 'Huanyuan Fuyu',
    name_ja: 'Huanyuan Fuyu',
    name_zh: '還源福遇',
    name_vi: 'Hoàn Nguyên Phúc Ngộ',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1245', '1313'],
    records: '',
    sect: ['Caodong'],
    country: 'China',
    place: '-',
    teachers: ['Xueyan Zuqin'],
    successors: ['Chunzuo Wencai'],
    disciples: ['Chunzuo Wencai'],
    image: '/images/avatar.png',
    reference: [''],
  },
]
export default CnLv22MasterDb;
