const CnLv27MasterDb = [
  {
    id: '60.27.1',
    name_en: 'Wufang Kecong',
    name_es: 'Wufang Kecong',
    name_de: 'Wufang Kecong',
    name_fr: 'Wufang Kecong',
    name_ru: 'Wufang Kecong',
    name_ja: 'Wufang Kecong',
    name_ko: 'Wufang Kecong',
    name_ar: 'Wufang Kecong',
    name_zh: '無方可從',
    name_vi: 'Vô Phương Khả Tùng',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1420', '1483'],
    epoch: '',
    records: '',
    sect: ['Caodong'],
    country: 'China',
    place: '-',
    teachers: ['Jukong Qibin'],
    successors: ['Yuezhou Wenzai'],
    disciples: ['Yuezhou Wenzai'],
    image: '/images/avatar.png',
    reference: [''],
  }
]
export default CnLv27MasterDb;
