const CnLv16MasterDb = [
  {
    id: '49.16.1',
    isEminent: true,
    name_en: 'Huqiu Shaolong',
    name_ja: 'Kukyū Jōryū',
    name_zh: '虎丘紹隆',
    pinyin: '',
    name_vi: 'Hổ Khâu Thiệu Long',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1077', '1136'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: 'China',
    place: '-',
    teachers: ['Yuanwu Keqin'],
    successors: ['Yingan Tanhua'],
    disciples: ['Yingan Tanhua'],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '49.16.2',
    name_en: 'Huguo Jingyuan',
    name_ja: 'Gokoku Keigen',
    name_zh: '護國景元',
    pinyin: '',
    name_vi: 'Hộ Quốc Cảnh Nguyên',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1094', '1146'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: 'China',
    place: '-',
    teachers: ['Yuanwu Keqin'],
    successors: [''],
    disciples: ['Wakuan Shitai', 'Xingshan Weiguan', 'Huoan Shiti'],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Huguo_Jingyuan',],
  },
  {
    id: '49.16.3',
    hasContent: true,
    isEminent: true,
    name_en: 'Dahui Zonggao',
    name_ja: 'ダイエシュウコウ Daie Shūkō',
    name_zh: '大慧宗杲',
    pinyin: '',
    name_vi: 'Đại Huệ Tông Cảo',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1089', '1163'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi', 'Dahui'],
    country: 'China',
    place: '-',
    teachers: ['Yuanwu Keqin'],
    successors: [''],
    disciples: ['Fozhao Deguang', 'Zishou Miaozong', 'Kaixi Daoqian', 'Miaodao Dingguang', 'Xiangyun Tanyi', 'Wuji Lepai',
      'Ci’an Shoujing (此庵守淨)', 'Yishan Chongmi (伊山冲密, Zhongmi)', 'Ke-an Huiran (可庵慧然, Xuefeng)'],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Dahui_Zonggao', 'https://terebess.hu/zen/dahui.html'],
  },
  {
    id: '49.16.4',
    name_en: 'Xiatang Huiyuan',
    other_name_en: 'Lingyin Huiyuan, Fohai Huiyuan, Shi Huiyuan',
    name_ja: 'Xiatang Huiyuan',
    name_zh: '瞎堂慧遠',
    other_name_zh: '佛海慧遠',
    pinyin: '',
    name_vi: 'Hạt Đường Huệ Viễn',
    other_name_vi: 'Phật Hải Huệ Viễn',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1103', '1176'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: 'China',
    place: '',
    death_place: '',
    teachers: ['Yuanwu Keqin'],
    successors: [''],
    disciples: ['Jigong Daoji', 'Duệ Sơn Giác A'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/H%E1%BA%A1t_%C4%90%C6%B0%E1%BB%9Dng_Hu%E1%BB%87_Vi%E1%BB%85n',],
  },
  {
    id: '49.16.5',
    name_en: 'Yuehan Shanguo',
    name_ja: 'Gettan Zenka',
    name_zh: '月庵善果',
    pinyin: '',
    name_vi: 'Nguyệt Am Thiện Quả',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1079', '1152'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: 'China',
    place: '-',
    teachers: ['Kaifu Daoning'],
    successors: ['Laoan Zudeng'],
    disciples: ['Laoan Zudeng'],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Yue%E2%80%99an_Shanguo',],
  },
  {
    id: '49.16.6',
    name_en: 'Lingyan Sengbao',
    name_ja: 'Lingyan Sengbao',
    name_zh: '靈巖僧寶',
    pinyin: '',
    name_vi: 'Đại Minh Tăng Bảo',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1114', '1171'],
    epoch: '',
    records: '',
    sect: ['Caodong'],
    country: 'China',
    place: '-',
    teachers: ['Puzhao Yibian'],
    successors: ['Yushan Shiti'],
    disciples: ['Yushan Shiti'],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '49.16.7',
    name_en: 'Miyin Anmin',
    name_ja: 'Miyin Anmin',
    name_zh: '密印安民',
    pinyin: '',
    name_vi: 'Mễ Âm An Dân',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1086', '1136'],
    epoch: 'Northern Song Dynasty',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: 'China',
    place: '-',
    teachers: ['Yuanwu Keqin'],
    successors: ['Biefeng Baoyin'],
    disciples: ['Biefeng Baoyin'],
    image: '/images/avatar.png',
    reference: ['https://terebess.hu/zen/Hearing-in-Chan.pdf',],
  },
]
export default CnLv16MasterDb;
