const CnLv58MasterDb = [
  {
    id: '91.58.1',
    hasContent: true,
    name_en: 'Deqing Yanche',
    other_name_en: 'Xuyun, Hsu Yun, Xuyun Xingche',
    name_es: 'Deqing Yanche',
    name_de: 'Deqing Yanche',
    name_fr: 'Deqing Yanche',
    name_ru: 'Deqing Yanche',
    name_ar: 'Deqing Yanche',
    name_ko: 'Deqing Yanche',
    name_ja: 'Deqing Yanche',
    name_zh: '德清演徹',
    other_name_zh: '虛雲性徹',
    nickname_zh: '虛雲',
    name_vi: 'Đức Thanh Diễn Triệt',
    other_name_vi: '',
    nickname_vi: 'Hư Vân',
    worship_tower: '',
    birth_death_time: ['1840', '1959'],
    records: '',
    sect: ['Linji', 'Yangqi', 'Guiyang', 'Yunmen', 'Fayan', 'Caodong'],
    country: 'China',
    place: 'Zhenru Temple, Jiangxi, China',
    teachers: ['Shanci Changkai', 'Yung Ching', 'Miaolian Dihua 妙莲地华 / Juehua 觉华 (42nd Linji)',
      'Xingyang Ciduo 兴阳词铎 (7th Weiyang/Guiyang)', 'Yi’an Shenjing 已庵深淨 (11th Yunmen)',
      'Xiangfu Liangqing 祥符良庆 (7th Fayan)', 'Dingfeng Yaocheng 鼎峰耀成 (46th Caodong)',
    ],
    successors: [''],
    disciples: ['Fohui Kuanyin'],
    image: '/images/avatar.png',
    reference: ['https://en.m.wikipedia.org/wiki/Xuyun', 'https://terebess.hu/zen/mesterek/Xuyun.html',
      'https://www.dharmasite.net/HuVanHoaThuongHoaTruyen/bookcover.htm'],
  },
  {
    id: '91.58.2',
    hasContent: true,
    name_en: 'Laiguo Miaoshu',
    other_name_en: 'Miaoshu Laiguo, Lai-Ko',
    name_es: 'Laiguo Miaoshu',
    name_de: 'Laiguo Miaoshu',
    name_fr: 'Laiguo Miaoshu',
    name_ru: 'Laiguo Miaoshu',
    name_ar: 'Laiguo Miaoshu',
    name_ko: 'Laiguo Miaoshu',
    name_ja: 'Raika Myōju',
    other_name_ja: 'Myōju Raika',
    name_zh: '來果妙樹',
    other_name_zh: '妙树来果',
    name_vi: 'Lai Quả Diệu Thọ',
    other_name_vi: 'Lai Quả Diệu Thư',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1881', '1953'],
    epoch: '',
    records: '',
    sect: ['Linji'],
    country: 'China',
    place: 'Gaomin Temple/Monastery (高旻寺), Hanjiang District, Yangzhou, China',
    teachers: ['Mingxuan Xirui'],
    successors: ['Gaomin Delin'],
    disciples: ['Gaomin Delin'],
    image: '/images/avatar.png',
    reference: ['https://dmcb.dila.edu.tw/dmcb/Laiguo_%E4%BE%86%E6%9E%9C', 'https://www.mdpi.com/2077-1444/15/5/627',
      'https://www.hanshansi.org/download/zx/200703/200703f17.htm', 'https://www.zhonghuadiancang.com/foxuebaodian/17865/335053.html',
      'https://vn.thamtosuthien.net/about/Thien-su-Lai-Qua.phattrien.net', 'https://terebess.hu/zen/mesterek/7.pdf'
    ],
  }
]
export default CnLv58MasterDb;
