const CnLv4MasterDb = [
  {
    id: '37.4.1',
    name_en: 'Đại Đức Đạo Viên',
    name_ja: 'Đại Đức Đạo Viên',
    name_zh: '遂州道圓',
    other_name_zh: '大德道圓',
    name_vi: 'Đại Đức Đạo Viên',
    other_name_vi: 'Toại Châu Đạo Viên',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: 'Toại Châu',
    teachers: ['Kinh Nam Duy Trung'],
    successors: ['Guifeng Zongmi'],
    disciples: ['Guifeng Zongmi'],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '37.4.2',
    hasContent: true,
    name_en: 'Yunyan Tansheng',
    name_zh: '雲巖曇晟',
    name_ja: 'Ungan Donjō',
    name_vi: 'Vân Nham Đàm Thịnh',
    other_name_vi: 'Vân Nham Đàm Thạnh',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['780', '841'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Yaoshan Weiyan, Baizhang Huaihai'],
    successors: ['Dongshan Liangjie'],
    disciples: ['Dongshan Liangjie', 'Xingshan Jianghong', 'Thần Sơn Tăng Mật'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Yunyan_Tansheng_Image_Zen.jpg/220px-Yunyan_Tansheng_Image_Zen.jpg',
    reference: ['https://blog.phapthihoi.org/gt-member/ts-van-nham-dam-thanh/'],
  },
  {
    id: '37.4.3',
    hasContent: true,
    name_en: 'Longtan Chongxin',
    name_ja: 'Ryūtan Sōshin',
    name_zh: '龍潭崇信',
    name_vi: 'Long Đàm Sùng Tín',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Tianhuang Daowu'],
    successors: ['Deshan Xuanjian'],
    disciples: ['Deshan Xuanjian'],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '37.4.4',
    hasContent: true,
    name_en: 'Guishan Lingyou',
    name_ja: 'Isan Reiyû',
    name_zh: '潙山靈祐',
    name_vi: 'Quy Sơn Linh Hựu',
    other_name_vi: '',
    nickname_vi: 'Đại Viên',
    worship_tower: '',
    birth_death_time: ['771', '853'],
    epoch: '',
    records: '',
    sect: ['Guiyang'],
    country: '🇨🇳',
    place: 'Quy Sơn - Đàm Châu',
    teachers: ['Tianhuang Daowu'],
    successors: ['Yangshan Huiji'],
    disciples: ['Yangshan Huiji', 'Lingyun Zhiqin', 'Xiangyan Zhixian', 'Xiangyan Zhixian', 'Liu Tiemo',
      'Jiufeng Zihui', 'Jingzhao Mihu', 'Jingshan Hongyin', 'Shuanfeng'],
    image: '/images/avatar.png',
    collections: ['https://thuvienhoasen.org/images/file/OI6imJ1G0QgQAJ8X/quy-son-ngu-luc.pdf'],
    reference: ['https://terebess.hu/zen/guishan.html', 'https://en.wikipedia.org/wiki/Guishan_Lingyou', 'https://vi.wikipedia.org/wiki/Quy_S%C6%A1n_Linh_H%E1%BB%B1u', 'http://thuongchieu.net/index.php/phapthoai/suphu/4804-tslinhhuu', 'https://phatphapungdung.com/phap-bao/ngu-luc-cua-thien-su-dam-chau-quy-son-linh-huu-164038.html', 'https://thuvienhoasen.org/images/file/OI6imJ1G0QgQAJ8X/quy-son-ngu-luc.pdf'],
  },
  {
    id: '37.4.5',
    name_en: 'Sanping Yizhong',
    name_ja: 'Sanping Yizhong',
    name_zh: '三平義忠',
    name_vi: 'Tam Bình Nghĩa Trung',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['781', '872'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dadian Baotong'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    collections: [''],
    reference: ['https://terebess.hu/zen/shigong.html'],
  },
  {
    id: '37.4.6',
    hasContent: true,
    name_en: 'Cuiwei Wuxue',
    name_ja: 'Suibi Mugaku',
    name_zh: '翠微無學',
    name_vi: 'Thúy Vi Vô Học',
    other_name_vi: 'Thúy Vi Vô Ngọc',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['739', '824'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Danxia Tianran'],
    successors: [''],
    disciples: ['Touzi Datong'],
    image: '/images/avatar.png',
    collections: [''],
    reference: ['https://terebess.hu/zen/mesterek/CuiweiWuxue.html', 'https://vi.wikipedia.org/wiki/Th%C3%BAy_Vi_V%C3%B4_H%E1%BB%8Dc', 'https://blog.phapthihoi.org/tu-dien-phat-giao/thuy-vi-vo-hoc/'],
  },
  {
    id: '37.4.7',
    hasContent: true,
    name_en: 'Huangbo Xiyun',
    name_ja: 'Obaku Kiun',
    name_zh: '黃蘖希運',
    name_vi: 'Hoàng Bá Hy Vận',
    other_name_vi: '',
    nickname_vi: 'Đoạn Tế',
    birth_death_time: ['', '850'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    death_place: 'Huangbo mountain',
    teachers: ['Baizhang Huaihai'],
    successors: ['Linji Yixuan'],
    disciples: ['Linji Yixuan'],
    image: '/',
    reference: [''],
  },
  {
    id: '37.4.9',
    name_en: 'Echū',
    name_ja: 'Echū',
    name_zh: '慧忠',
    name_vi: 'Ngưu Đầu Tuệ Trung',
    birth_death_time: ['683', '769'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: 'Ngưu Đầu Sơn',
    teachers: ['Chii (智威)'],
    successors: [''],
    disciples: ['Thiên thai Duy Tắc Phật Quật', 'Thái Bạch Quán Tông', 'Kim Lăng Huệ Thiệp'],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '37.4.10',
    hasContent: true,
    name_en: 'Helin Xuansu',
    name_ja: 'Gakurin Genso',
    name_zh: '鶴林玄素',
    name_vi: 'Hạc Lâm Huyền Tố',
    other_name_vi: 'Nhuận Châu Huyền Tố',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['668/688', '752'],
    epoch: '',
    records: '',
    sect: ['Niutou (Oxhead)'],
    country: '🇨🇳',
    place: 'Nhuận Châu',
    teachers: ['Niutou Zhiwei'],
    successors: ['Jingshan Daoqin'],
    disciples: ['Jingshan Daoqin', 'Ngô Trung Pháp Kính', 'Wuxing Fahai - Ngô Hưng Pháp Hải', 'Tử Sơn Hạo Nhiên',
      'Kim Hoa Đàm Ích', 'Ngô Môn Viên Cảnh'],
    image: '/images/avatar.png',
    reference: ['https://phatgiao.org.vn/tu-dien-phat-hoc-online/hac-lam-huyen-to-k4041.html'],
  },
  {
    id: '37.4.11',
    name_en: 'Tuyên Châu Huyền Dĩnh',
    name_ja: 'Tuyên Châu Huyền Dĩnh',
    name_zh: 'Tuyên Châu Huyền Dĩnh',
    name_vi: 'Tuyên Châu Huyền Dĩnh',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: 'Tuyên Châu',
    teachers: ['Chii (智威)'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '37.4.12',
    name_en: 'Daowu Yuanzhi',
    name_ja: 'Dōgo Enchi',
    name_zh: '道吾圓智',
    name_vi: 'Đạo Ngô Viên Trí',
    birth_death_time: ['769', '835'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Yaoshan Weiyan'],
    successors: ['Shishuang Qingzhu'],
    disciples: ['Shishuang Qingzhu'],
    image: '/',
    reference: [''],
  },
  {
    id: '37.4.13',
    hasContent: true,
    name_en: 'Zhaozhou Congshen',
    name_ja: '趙州従シン Jōshū Jūshin',
    name_zh: '趙州從諗',
    name_vi: 'Triệu Châu Tùng Thẩm',
    other_name_vi: 'Triệu Châu Tòng Thẩm',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['778', '897'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Nanquan Puyuan'],
    successors: [''],
    disciples: ['Yanyang Shanxin / Yanyang Shanzhao', 'Yanyang Cunsu', 'Huicong', 'Guangxiao Huijiao',
      'Guoqing Yuanfeng', 'Wenyuan', 'Muzhen Tulang'],
    image: '/',
    reference: ['https://pl.wikipedia.org/wiki/Zhaozhou_Congshen', ''],
  },
  {
    id: '37.4.14',
    hasContent: true,
    name_en: 'Changsha Jingcen',
    name_ja: 'Chōsha Keijin',
    name_zh: '長沙景岑',
    name_vi: 'Trường Sa Cảnh Sầm',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['788', '868'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Nanquan Puyuan'],
    successors: [''],
    disciples: ['Xuedou Changtong'],
    image: '/',
    reference: ['https://terebess.hu/zen/mesterek/ChangshaJingcen.html', 'https://pl.wikipedia.org/wiki/Changsha_Jingcen',
      'http://thuongchieu.net/index.php/phapthoai/suphu/4834-tscanhsam', 'https://blog.phapthihoi.org/gt-member/ts-truong-sa-canh-sam/',
      'https://phatgiao.org.vn/tu-dien-phat-hoc-online/truong-sa-canh-sam-k3027.html#google_vignette'],
  },
  {
    id: '37.4.16',
    name_en: 'Hangzhou Tianlong',
    name_ja: 'Kōshū Tenryū',
    name_zh: '杭州天龍',
    name_vi: 'Hàng Châu Thiên Long',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Damei Fachang'],
    successors: ['Jinhua Juzhi'],
    disciples: ['Jinhua Juzhi'],
    image: '/',
    reference: ['https://pl.wikipedia.org/wiki/Hangzhou_Tianlong', 'https://blog.phapthihoi.org/gt-member/ts-hang-chau-thien-long/'],
  },
  {
    id: '37.4.17',
    name_en: 'Baizhang Niepan',
    name_ja: 'Hyakujo Nehan',
    name_zh: '百丈涅槃',
    name_vi: 'Bách Trượng Nết Bàn',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['749', '819'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Baizhang Huaihai'],
    successors: [''],
    disciples: [],
    image: '/',
    reference: ['https://pl.wikipedia.org/wiki/Baizhang_Niepan'],
  },
  {
    id: '37.4.18',
    name_en: 'Guannan Daochang',
    name_ja: 'Kannan Dōjō',
    name_zh: '關南道常',
    name_vi: 'Quan Nam Đạo Thường',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Baizhang Huaihai'],
    successors: [''],
    disciples: [],
    image: '/',
    reference: ['https://pl.wikipedia.org/wiki/Guannan_Daochang'],
  },
  {
    id: '37.4.19',
    name_en: 'Guishan Da’an',
    other_name_en: 'Changqing Da’an',
    name_ja: 'Isan Daian',
    other_name_ja: 'Chōkei Daian, Ranan',
    name_zh: '潙山大安',
    other_name_zh: '溈山大安 , 長慶大安',
    name_vi: 'Quy Sơn Đại An',
    other_name_vi: 'Trường Khánh Đại An',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['793', '883'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Baizhang Huaihai'],
    successors: [''],
    disciples: ['Lingshu Rumin', 'Dasui Fazhen'],
    image: '/',
    reference: ['https://pl.wikipedia.org/wiki/Guishan_Da%E2%80%99an', 'https://terebess.hu/zen/mesterek/ChangqingDaan.html'],
  },
  {
    id: '37.4.20',
    name_en: 'Wufeng Changguan',
    name_ja: 'Gohō Jōkan',
    name_zh: '五峰常觀',
    name_vi: 'Ngũ Phong Thường Quan',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Baizhang Huaihai'],
    successors: [''],
    disciples: [],
    image: '/',
    reference: ['https://pl.wikipedia.org/wiki/Wufeng_Changguan'],
  },
  {
    id: '37.4.21',
    hasContent: true,
    name_en: 'Zhenzhou Puhua',
    name_ja: 'Jinshu Fuke',
    name_zh: '鎮州普化',
    name_vi: 'Trấn Châu Phổ Hóa',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['770', '840/860'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Panshan Baoji'],
    successors: [''],
    disciples: [],
    image: '/',
    reference: ['https://blog.phapthihoi.org/gt-member/ts-tran-chau-pho-hoa/', 'https://terebess.hu/zen/mesterek/Puhua.html', 'https://en.wikipedia.org/wiki/Puhua'],
  },
  {
    id: '37.4.22',
    hasContent: true,
    name_en: 'Chuanzi Decheng',
    name_ja: 'Senji Tokujō',
    name_zh: '船字德誠',
    name_vi: 'Thuyền Tử Đức Thành',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Yaoshan Weiyan'],
    successors: ['Jiashan Shanhui'],
    disciples: ['Jiashan Shanhui'],
    image: '/',
    reference: ['https://pl.wikipedia.org/wiki/Chuanzi_Decheng'],
  },
  {
    id: '37.4.23',
    name_en: 'Gaoan Dayu',
    name_ja: 'Senji Tokujō',
    name_zh: '高安大愚',
    name_vi: 'Cao An Đại Ngu',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Guizong Zhichang'],
    successors: ['Moshan Liaoran'],
    disciples: ['Moshan Liaoran'],
    image: '/',
    reference: ['https://terebess.hu/zen/mesterek/GaoanDayu.html'],
  },
  {
    id: '37.4.24',
    hasContent: true,
    name_en: 'Zihu Lizong',
    name_ja: 'Shiko Rishō',
    name_zh: '子湖利蹤',
    name_vi: 'Tử Hồ Lợi Tung',
    other_name_vi: 'Tử Hồ Lý Tông',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['800', '880'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Nanquan Puyuan'],
    successors: [''],
    disciples: [],
    image: '/',
    reference: ['https://terebess.hu/zen/mesterek/ZihuLizong.html', 'https://blog.phapthihoi.org/gt-member/ts-tu-ho-ly-tong/',
    'https://zenmarrow.com/lineage-chart?m=266'],
  },
]
export default CnLv4MasterDb;
