const CnLv36MasterDb = [
  {
    id: '69.36.1',
    name_en: 'Yinyuan Longqi',
    name_ja: 'Ingen Ryuki',
    name_zh: '隠元隆琦',
    name_vi: 'Ân Nguyên Long Kỳ',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1592', '1673'],
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Feiyin Tongrong'],
    successors: [''],
    disciples: ['Mu’an Xingtao', 'Duzhan Xingrong', 'Duzhan Xingrong'],
    image: '/images/avatar.png',
    reference: ['https://terebess.hu/zen/mesterek/Ingen.html', 'https://en.wikipedia.org/wiki/Ingen'],
  },
  {
    id: '69.36.2',
    name_en: '',
    name_ja: '',
    name_zh: '',
    name_vi: '',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: [''],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: [''],
  },
]
export default CnLv36MasterDb;
