const CnLv18MasterDb = [
  {
    id: '51.18.1',
    name_en: 'Mian Xianjie',
    name_ja: 'Mittan Kanketsu',
    name_zh: '密庵咸傑',
    name_vi: 'Mật Am Hàm Kiệt',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1107/1118', '1186'],
    epoch: '',
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Yingan Tanhua'],
    successors: [''],
    disciples: ['Songyuan Chongyue', 'Poan Zuxian'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/M%E1%BA%ADt_Am_H%C3%A0m_Ki%E1%BB%87t',],

  },
  {
    id: '51.18.2',
    name_en: 'Xueyan Huiman',
    name_ja: 'Xueyan Huiman',
    name_zh: '雪巖慧滿',
    name_vi: 'Tuyết Nham Như Mãn',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['-', '1206'],
    epoch: '',
    records: '',
    sect: ['Caodong'],
    country: 'China',
    place: '-',
    teachers: ['Yushan Shiti'],
    successors: ['Wansong Xingxiu'],
    disciples: ['Wansong Xingxiu'],
    image: '/images/avatar.png',
    reference: ['',],

  },
]
export default CnLv18MasterDb;
