const CnLv19MasterDb = [
  {
    id: '52.19.1',
    name_en: 'Poan Zuxian',
    name_es: 'Poan Zuxian',
    name_de: 'Poan Zuxian',
    name_fr: 'Poan Zuxian',
    name_vi: 'Phá Am Tổ Tiên',
    name_ru: 'Poan Zuxian',
    name_zh: '破庵祖先',
    name_ja: 'Hoan Sosen',
    name_ko: 'Poan Zuxian',
    name_ar: 'Poan Zuxian',
    birth_death_time: ['1136', '1211'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Mian Xianjie'],
    successors: ['Wuzhun Shifan'],
    disciples: ['Wuzhun Shifan'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/Ph%C3%A1_Am_T%E1%BB%95_Ti%C3%AAn',],
  },
  {
    id: '52.19.2',
    name_en: 'Songyuan Chongyue',
    name_es: 'Songyuan Chongyue',
    name_de: 'Songyuan Chongyue',
    name_fr: 'Songyuan Chongyue',
    name_vi: 'Tùng Nguyên Sùng Nhạc',
    name_ru: 'Songyuan Chongyue',
    name_zh: '松源崇岳',
    name_ja: 'Shōgen Sūgaku',
    name_ko: '송원숭악 Songwon Sungak',
    name_ar: 'Songyuan Chongyue',
    birth_death_time: ['1132/1139', '1202/1209'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Mian Xianjie'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://www.erct.com/2-ThoVan/NNT/Vomonquan/20-Dailucluongnhan.htm', 'http://en.lingyinsi.org/list_332.html',
      'https://phatgiao.org.vn/tu-dien-phat-hoc-online/tung-nguyen-sung-nhac-k3098.html', 'https://tangthuphathoc.net/tudien/tung-nguyen-sung-nhac-tu-dien-dao-uyen/',
      'https://pl.wikipedia.org/wiki/Songyuan_Chongyue', 'https://terebess.hu/zen/mesterek/SongyuanChongyue.html'
    ],
  },
  {
    id: '52.19.3',
    name_en: 'Tào Nguyên Đạo Sinh',
    name_es: 'Tào Nguyên Đạo Sinh',
    name_de: 'Tào Nguyên Đạo Sinh',
    name_fr: 'Tào Nguyên Đạo Sinh',
    name_vi: 'Tào Nguyên Đạo Sinh',
    name_ru: 'Tào Nguyên Đạo Sinh',
    name_zh: 'Tào Nguyên Đạo Sinh',
    name_ja: 'Tào Nguyên Đạo Sinh',
    name_ko: 'Tào Nguyên Đạo Sinh',
    name_ar: 'Tào Nguyên Đạo Sinh',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Mian Xianjie'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '52.19.4',
    name_en: 'Wansong Xingxiu',
    name_es: 'Wansong Xingxiu',
    name_de: 'Wansong Xingxiu',
    name_fr: 'Wansong Xingxiu',
    name_vi: 'Vạn Tùng Hành Tú',
    name_ru: 'Wansong Xingxiu',
    name_zh: '萬松行秀',
    name_ja: 'Wansong Xingxiu',
    name_ko: 'Wansong Xingxiu',
    name_ar: 'Wansong Xingxiu',
    birth_death_time: ['1166', '1246'],
    records: '',
    sect: ['Caodong'],
    country: 'China',
    place: '-',
    teachers: ['Xueyan Huiman'],
    successors: ['Xueting Fuyu'],
    disciples: ['Xueting Fuyu'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/V%E1%BA%A1n_T%C3%B9ng_H%C3%A0nh_T%C3%BA',],
  },
]
export default CnLv19MasterDb;
