const CnLv14MasterDb = [
  {
    id: '47.14.1',
    name_en: 'Wuzu Fayan',
    name_es: 'Wuzu Fayan',
    name_de: 'Wuzu Fayan',
    name_fr: 'Wuzu Fayan',
    name_vi: 'Ngũ Tổ Pháp Diễn',
    name_ru: 'Wuzu Fayan',
    name_zh: '五祖法演',
    name_ja: 'Goso Hōen',
    name_ko: 'Wuzu Fayan',
    name_ar: 'Wuzu Fayan',
    birth_death_time: ['1024?', '1104'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Baiyun Shouduan'],
    successors: ['Yuanwu Keqin'],
    disciples: ['Yuanwu Keqin', 'Kaifu Daoning'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/Ng%C5%A9_T%E1%BB%95_Ph%C3%A1p_Di%E1%BB%85n',],
  },
  {
    id: '47.14.2',
    name_en: 'Lumen Zijue',
    name_es: 'Lumen Zijue',
    name_de: 'Lumen Zijue',
    name_fr: 'Lumen Zijue',
    name_vi: 'Lộc Môn Tự Giác',
    name_ru: 'Lumen Zijue',
    name_zh: '鹿門自覺',
    name_ja: 'Rokumon Jikaku',
    name_ko: 'Lumen Zijue',
    name_ar: 'Lumen Zijue',
    birth_death_time: ['-', '1117'],
    records: '',
    sect: ['Caodong'],
    country: 'China',
    place: '-',
    teachers: ['Furong Daokai'],
    successors: ['Puzhao Yibian'],
    disciples: ['Puzhao Yibian'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/L%E1%BB%99c_M%C3%B4n_T%E1%BB%B1_Gi%C3%A1c',
      'https://phatgiao.org.vn/tu-dien-phat-hoc-online/loc-mon-tu-giac-k4442.html',
    ],
  },
]
export default CnLv14MasterDb;
