const CnLv4MasterDb = [
  {
    id: '37.4.1',
    name_en: 'Toại Châu Đạo Viên',
    name_es: 'Toại Châu Đạo Viên',
    name_de: 'Toại Châu Đạo Viên',
    name_fr: 'Toại Châu Đạo Viên',
    name_vi: 'Đại Đức Đạo Viên / Toại Châu Đạo Viên',
    name_ru: 'Toại Châu Đạo Viên',
    name_zh: '遂州道圓/大德道圓',
    name_ja: 'Toại Châu Đạo Viên',
    name_ko: 'Toại Châu Đạo Viên',
    name_ar: 'Toại Châu Đạo Viên',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: 'Toại Châu',
    teachers: ['Kinh Nam Duy Trung'],
    successors: ['Guifeng Zongmi'],
    disciples: ['Guifeng Zongmi'],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '37.4.2',
    hasContent: true,
    name_en: 'Yunyan Tansheng',
    name_es: 'Yunyan Tansheng',
    name_de: 'Yunyan Tansheng',
    name_fr: 'Yunyan Tansheng',
    name_vi: 'Vân Nham Đàm Thạnh/Thịnh',
    name_ru: 'Yunyan Tansheng',
    name_zh: '雲巖曇晟',
    name_ja: 'Ungan Donjō',
    name_ko: 'Unam Tamsŭng',
    name_ar: 'Yunyan Tansheng',
    birth_death_time: ['780', '841'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Yaoshan Weiyan, Baizhang Huaihai'],
    successors: ['Dongshan Liangjie'],
    disciples: ['Dongshan Liangjie'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Yunyan_Tansheng_Image_Zen.jpg/220px-Yunyan_Tansheng_Image_Zen.jpg',
    reference: ['https://blog.phapthihoi.org/gt-member/ts-van-nham-dam-thanh/'],
  },
  {
    id: '37.4.3',
    hasContent: true,
    name_en: 'Longtan Chongxin',
    name_es: 'Longtan Chongxin',
    name_de: 'Longtan Chongxin',
    name_fr: 'Longtan Chongxin',
    name_vi: 'Long Đàm Sùng Tín',
    name_ru: 'Longtan Chongxin',
    name_zh: '龍潭崇信',
    name_ja: 'Ryūtan Sōshin',
    name_ko: '룡담숭신 Lyongdam Sungsin',
    name_ar: 'Longtan Chongxin',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Tianhuang Daowu'],
    successors: ['Deshan Xuanjian'],
    disciples: ['Deshan Xuanjian'],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '37.4.4',
    hasContent: true,
    name_en: 'Guishan Lingyou',
    name_es: 'Guishan Lingyou',
    name_de: 'Guishan Lingyou',
    name_fr: 'Guishan Lingyou',
    name_vi: 'Quy Sơn Linh Hựu (Đại Viên Đại sư)',
    name_ru: 'Guishan Lingyou',
    name_zh: '潙山靈祐',
    name_ja: 'Isan Reiyû',
    name_ko: 'Guishan Lingyou',
    name_ar: 'Guishan Lingyou',
    birth_death_time: ['771', '853'],
    records: '',
    sect: ['Guishan'],
    country: 'China',
    place: 'Quy Sơn - Đàm Châu',
    teachers: ['Tianhuang Daowu'],
    successors: ['Yangshan Huiji'],
    disciples: ['Yangshan Huiji', 'Lingyun Zhiqin', 'Xiangyan Zhixian'],
    image: '/images/avatar.png',
    collections: ['https://thuvienhoasen.org/images/file/OI6imJ1G0QgQAJ8X/quy-son-ngu-luc.pdf'],
    reference: ['https://terebess.hu/zen/guishan.html', 'https://en.wikipedia.org/wiki/Guishan_Lingyou', 'https://vi.wikipedia.org/wiki/Quy_S%C6%A1n_Linh_H%E1%BB%B1u', 'http://thuongchieu.net/index.php/phapthoai/suphu/4804-tslinhhuu', 'https://phatphapungdung.com/phap-bao/ngu-luc-cua-thien-su-dam-chau-quy-son-linh-huu-164038.html', 'https://thuvienhoasen.org/images/file/OI6imJ1G0QgQAJ8X/quy-son-ngu-luc.pdf'],
  },
  {
    id: '37.4.5',
    name_en: 'Sanping Yizhong',
    name_es: 'Sanping Yizhong',
    name_de: 'Sanping Yizhong',
    name_fr: 'Sanping Yizhong',
    name_vi: 'Tam Bình Nghĩa Trung',
    name_ru: 'Sanping Yizhong',
    name_zh: '三平義忠',
    name_ja: 'Sanping Yizhong',
    name_ko: 'Sanping Yizhong',
    name_ar: 'Sanping Yizhong',
    birth_death_time: ['781', '872'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Dadian Baotong'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    collections: [''],
    reference: ['https://terebess.hu/zen/shigong.html'],
  },
  {
    id: '37.4.6',
    hasContent: true,
    name_en: 'Cuiwei Wuxue',
    name_es: 'Cuiwei Wuxue',
    name_de: 'Cuiwei Wuxue',
    name_fr: 'Cuiwei Wuxue',
    name_vi: 'Thúy Vi Vô Học (Thúy Vi Vô Ngọc)',
    name_ru: 'Cuiwei Wuxue',
    name_zh: '翠微無學',
    name_ja: 'Suibi Mugaku',
    name_ko: '취미무학 Ch’wimi Muhak',
    name_ar: 'Cuiwei Wuxue',
    birth_death_time: ['739', '824'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Danxia Tianran'],
    successors: [''],
    disciples: ['Touzi Datong'],
    image: '/images/avatar.png',
    collections: [''],
    reference: ['https://terebess.hu/zen/mesterek/CuiweiWuxue.html', 'https://vi.wikipedia.org/wiki/Th%C3%BAy_Vi_V%C3%B4_H%E1%BB%8Dc', 'https://blog.phapthihoi.org/tu-dien-phat-giao/thuy-vi-vo-hoc/'],
  },
  {
    id: '37.4.7',
    hasContent: true,
    name_en: 'Huangbo Xiyun',
    name_es: 'Huangbo Xiyun',
    name_de: 'Huangbo Xiyun',
    name_fr: 'Huangbo Xiyun',
    name_vi: 'Hoàng Bá Hy Vận',
    name_ru: 'Huangbo Xiyun',
    name_zh: '黃蘖希運',
    name_ja: 'Obaku kiun',
    name_ko: 'Huangbo Xiyun',
    name_ar: 'Huangbo Xiyun',
    birth_death_time: ['?', '850'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Baizhang Huaihai'],
    successors: ['Linji Yixuan'],
    disciples: ['Linji Yixuan'],
    image: '/',
    reference: [''],
  },
  {
    id: '37.4.9',
    name_en: 'Echū',
    name_es: 'Echū',
    name_de: 'Echū',
    name_fr: 'Echū',
    name_vi: 'Ngưu Đầu Tuệ Trung',
    name_ru: 'Echū',
    name_zh: '慧忠',
    name_ja: 'Echū',
    name_ko: 'Echū',
    name_ar: 'Echū',
    birth_death_time: ['683', '769'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: 'Ngưu Đầu Sơn',
    teachers: ['Chii (智威)'],
    successors: [''],
    disciples: ['Thiên thai Duy Tắc Phật Quật', 'Thái Bạch Quán Tông', 'Kim Lăng Huệ Thiệp'],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '37.4.10',
    hasContent: true,
    name_en: 'Gakurin Genso',
    name_es: 'Gakurin Genso',
    name_de: 'Gakurin Genso',
    name_fr: 'Gakurin Genso',
    name_vi: 'Nhuận Châu Hạc Lâm Huyền Tố',
    name_ru: 'Gakurin Genso',
    name_zh: '鶴林玄素',
    name_ja: 'Gakurin Genso',
    name_ko: 'Gakurin Genso',
    name_ar: 'Gakurin Genso',
    birth_death_time: ['668', '752'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: 'Nhuận Châu',
    teachers: ['Chii (智威)'],
    successors: [''],
    disciples: ['Jingshan Daoqin', 'Ngô Trung Pháp Kính', 'Wuxing Fahai - Ngô Hưng Pháp Hải', 'Tử Sơn Hạo Nhiên',
      'Kim Hoa Đàm Ích', 'Ngô Môn Viên Cảnh'],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '37.4.11',
    name_en: 'Tuyên Châu Huyền Dĩnh',
    name_es: 'Tuyên Châu Huyền Dĩnh',
    name_de: 'Tuyên Châu Huyền Dĩnh',
    name_fr: 'Tuyên Châu Huyền Dĩnh',
    name_vi: 'Tuyên Châu An quốc Huyền Dĩnh',
    name_ru: 'Tuyên Châu Huyền Dĩnh',
    name_zh: 'Tuyên Châu Huyền Dĩnh',
    name_ja: 'Tuyên Châu Huyền Dĩnh',
    name_ko: 'Tuyên Châu Huyền Dĩnh',
    name_ar: 'Tuyên Châu Huyền Dĩnh',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: 'Tuyên Châu',
    teachers: ['Chii (智威)'],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '37.4.12',
    name_en: 'Daowu Yuanzhi',
    name_es: 'Daowu Yuanzhi',
    name_de: 'Daowu Yuanzhi',
    name_fr: 'Daowu Yuanzhi',
    name_vi: 'Đạo Ngô Viên Trí',
    name_ru: 'Daowu Yuanzhi',
    name_zh: '道吾圓智',
    name_ja: 'Dōgo Enchi',
    name_ko: 'Daowu Yuanzhi',
    name_ar: 'Daowu Yuanzhi',
    birth_death_time: ['769', '835'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Yaoshan Weiyan'],
    successors: ['Shishuang Qingzhu'],
    disciples: ['Shishuang Qingzhu'],
    image: '/',
    reference: [''],
  },
  {
    id: '37.4.13',
    hasContent: true,
    name_en: 'Zhaozhou Congshen',
    name_es: 'Zhaozhou Congshen',
    name_de: 'Zhaozhou Congshen',
    name_fr: 'Zhaozhou Congshen',
    name_vi: 'Triệu Châu Tùng Thẩm / Triệu Châu Tòng Thẩm',
    name_ru: 'Zhaozhou Congshen',
    name_zh: '趙州從諗',
    name_ja: '趙州従シン Jōshū Jūshin',
    name_ko: '조주종심 Choju Chongsim',
    name_ar: 'Zhaozhou Congshen',
    birth_death_time: ['778', '897'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Nanquan Puyuan'],
    successors: [''],
    disciples: ['Yanyang Shanxin / Yanyang Shanzhao', 'Yanyang Cunsu', 'Huicong', 'Guangxiao Huijiao', 'Guoqing Yuanfeng', 'Wenyuan', 'Muzhen Tulang'],
    image: '/',
    reference: ['https://pl.wikipedia.org/wiki/Zhaozhou_Congshen', ''],
  },
  {
    id: '37.4.14',
    hasContent: true,
    name_en: 'Changsha Jingcen',
    name_es: 'Changsha Jingcen',
    name_de: 'Changsha Jingcen',
    name_fr: 'Changsha Jingcen',
    name_vi: 'Trường Sa Cảnh Sầm',
    name_ru: 'Changsha Jingcen',
    name_zh: '長沙景岑',
    name_ja: 'Chōsha Keijin',
    name_ko: '장사경잠 Changsa Kyŏngjam',
    name_ar: 'Changsha Jingcen',
    birth_death_time: ['788', '868'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Nanquan Puyuan'],
    successors: [''],
    disciples: [''],
    image: '/',
    reference: ['https://terebess.hu/zen/mesterek/ChangshaJingcen.html', 'https://pl.wikipedia.org/wiki/Changsha_Jingcen', 'http://thuongchieu.net/index.php/phapthoai/suphu/4834-tscanhsam', 'https://blog.phapthihoi.org/gt-member/ts-truong-sa-canh-sam/', 'https://phatgiao.org.vn/tu-dien-phat-hoc-online/truong-sa-canh-sam-k3027.html#google_vignette'],
  },
  {
    id: '37.4.16',
    name_en: 'Hangzhou Tianlong',
    name_es: 'Hangzhou Tianlong',
    name_de: 'Hangzhou Tianlong',
    name_fr: 'Hangzhou Tianlong',
    name_vi: 'Hàng Châu Thiên Long',
    name_ru: 'Hangzhou Tianlong',
    name_zh: '杭州天龍',
    name_ja: 'Kōshū Tenryū',
    name_ko: '항주천룡 Hangju Ch\'ŏnnyong',
    name_ar: 'Hangzhou Tianlong',
    birth_death_time: ['?', '?'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Damei Fachang'],
    successors: ['Jinhua Juzhi'],
    disciples: ['Jinhua Juzhi'],
    image: '/',
    reference: ['https://pl.wikipedia.org/wiki/Hangzhou_Tianlong', 'https://blog.phapthihoi.org/gt-member/ts-hang-chau-thien-long/'],
  },
  {
    id: '37.4.17',
    name_en: 'Baizhang Niepan',
    name_es: 'Baizhang Niepan',
    name_de: 'Baizhang Niepan',
    name_fr: 'Baizhang Niepan',
    name_vi: 'Bách Trượng Nết Bàn',
    name_ru: 'Baizhang Niepan',
    name_zh: '百丈涅槃',
    name_ja: 'Hyakujo Nehan',
    name_ko: 'Paekchang Nalpan',
    name_ar: 'Baizhang Niepan',
    birth_death_time: ['749', '819'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Baizhang Huaihai'],
    successors: [''],
    disciples: [''],
    image: '/',
    reference: ['https://pl.wikipedia.org/wiki/Baizhang_Niepan'],
  },
  {
    id: '37.4.18',
    name_en: 'Guannan Daochang',
    name_es: 'Guannan Daochang',
    name_de: 'Guannan Daochang',
    name_fr: 'Guannan Daochang',
    name_vi: 'Quan Nam Đạo Thường',
    name_ru: 'Guannan Daochang',
    name_zh: '關南道常',
    name_ja: 'Kannan Dōjō',
    name_ko: '관남도상 Kwannam Tosang',
    name_ar: 'Guannan Daochang',
    birth_death_time: ['?', '?'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Baizhang Huaihai'],
    successors: [''],
    disciples: [''],
    image: '/',
    reference: ['https://pl.wikipedia.org/wiki/Guannan_Daochang'],
  },
  {
    id: '37.4.19',
    name_en: 'Guishan Da’an',
    name_es: 'Guishan Da’an',
    name_de: 'Guishan Da’an',
    name_fr: 'Guishan Da’an',
    name_vi: 'Quy Sơn Đại An',
    name_ru: 'Guishan Da’an',
    name_zh: '潙山大安',
    name_ja: 'Isan Daian',
    name_ko: '규산대안 Kyusan Taean',
    name_ar: 'Guishan Da’an',
    birth_death_time: ['793', '883'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Baizhang Huaihai'],
    successors: [''],
    disciples: [''],
    image: '/',
    reference: ['https://pl.wikipedia.org/wiki/Guishan_Da%E2%80%99an'],
  },
  {
    id: '37.4.20',
    name_en: 'Wufeng Changguan',
    name_es: 'Wufeng Changguan',
    name_de: 'Wufeng Changguan',
    name_fr: 'Wufeng Changguan',
    name_vi: 'Ngũ Phong Thường Quan',
    name_ru: 'Wufeng Changguan',
    name_zh: '五峰常觀',
    name_ja: 'Gohō Jōkan',
    name_ko: '오봉상관 Obong Sanggwan',
    name_ar: 'Wufeng Changguan',
    birth_death_time: ['?', '?'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Baizhang Huaihai'],
    successors: [''],
    disciples: [''],
    image: '/',
    reference: ['https://pl.wikipedia.org/wiki/Wufeng_Changguan'],
  },
  {
    id: '37.4.21',
    hasContent: true,
    name_en: 'Zhenzhou Puhua',
    name_es: 'Zhenzhou Puhua',
    name_de: 'Zhenzhou Puhua',
    name_fr: 'Zhenzhou Puhua',
    name_vi: 'Trấn Châu Phổ Hóa',
    name_ru: 'Zhenzhou Puhua',
    name_zh: '鎮州普化',
    name_ja: 'Jinshu Fuke',
    name_ko: 'Zhenzhou Puhua',
    name_ar: 'Zhenzhou Puhua',
    birth_death_time: ['770', '840/860'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Panshan Baoji'],
    successors: [''],
    disciples: [''],
    image: '/',
    reference: ['https://blog.phapthihoi.org/gt-member/ts-tran-chau-pho-hoa/', 'https://terebess.hu/zen/mesterek/Puhua.html', 'https://en.wikipedia.org/wiki/Puhua'],
  },
  {
    id: '37.4.22',
    hasContent: true,
    name_en: 'Chuanzi Decheng',
    name_es: 'Chuanzi Decheng',
    name_de: 'Chuanzi Decheng',
    name_fr: 'Chuanzi Decheng',
    name_vi: 'Thuyền Tử Đức Thành',
    name_ru: 'Chuanzi Decheng',
    name_zh: '船字德誠',
    name_ja: 'Senji Tokujō',
    name_ko: '선자덕성 Sŏnja Tŏksŏng',
    name_ar: 'Chuanzi Decheng',
    birth_death_time: ['?', '?'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Yaoshan Weiyan'],
    successors: ['Jiashan Shanhui'],
    disciples: ['Jiashan Shanhui'],
    image: '/',
    reference: ['https://pl.wikipedia.org/wiki/Chuanzi_Decheng'],
  },
  {
    id: '37.4.23',
    name_en: 'Gaoan Dayu',
    name_es: 'Gaoan Dayu',
    name_de: 'Gaoan Dayu',
    name_fr: 'Gaoan Dayu',
    name_vi: 'Cao An Đại Ngu',
    name_ru: 'Gaoan Dayu',
    name_zh: '高安大愚',
    name_ja: 'Senji Tokujō',
    name_ko: 'Gaoan Dayu',
    name_ar: 'Gaoan Dayu',
    birth_death_time: ['?', '?'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Guizong Zhichang'],
    successors: ['Moshan Liaoran'],
    disciples: ['Moshan Liaoran'],
    image: '/',
    reference: ['https://terebess.hu/zen/mesterek/GaoanDayu.html'],
  },
]
export default CnLv4MasterDb;
