const CnLv34MasterDb = [
  {
    id: '67.34.1',
    name_en: 'Miyun Yuanwu',
    name_ja: 'Mitsu’un Engo',
    name_zh: '蜜雲円悟',
    other_name_zh: '密雲圓悟',
    name_vi: 'Mật Vân Viên Ngộ',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1566', '1642'],
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Huanyou Zhengchuan'],
    successors: ['Feiyin Tongrong'],
    disciples: ['Feiyin Tongrong'],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '67.34.2',
    name_en: 'Yufeng Yuanxin',
    name_ja: 'Gofū Enshin',
    name_zh: '語風圓信',
    name_vi: 'Ngữ Phong Viên Tín',
    other_name_vi: 'Tuyết Kiều Viên Tín, Ngữ Phong Lão Nhân',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1571', '1647'],
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Huanyou Zhengchuan'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/Ng%E1%BB%AF_Phong_Vi%C3%AAn_T%C3%ADn'],
  },
  {
    id: '67.34.3',
    name_en: 'Tianyin Yuanxiu',
    name_ja: '',
    name_zh: '天隱圓修',
    name_vi: 'Thiên Ẩn Viên Tu',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1575', '1635'],
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Huanyou Zhengchuan'],
    successors: ['Yulin Tongxiu'],
    disciples: ['Yulin Tongxiu'],
    image: '/images/avatar.png',
    reference: [''],
  },
]
export default CnLv34MasterDb;
