const CnLv12MasterDb = [
  {
    id: '45.12.1',
    hasContent: true,
    name_en: 'Yangqi Fanghui',
    name_es: 'Yangqi Fanghui',
    name_de: 'Yangqi Fanghui',
    name_fr: 'Yangqi Fanghui',
    name_vi: 'Dương Kỳ Phương Hội',
    name_ru: 'Yangqi Fanghui',
    name_zh: '楊岐方會',
    name_ja: 'Yōgi Hōe',
    name_ko: 'Yangqi Fanghui',
    name_ar: 'Yangqi Fanghui',
    birth_death_time: ['992', '1049'],
    records: '',
    sect: ['Linji - Yangqi'],
    country: 'China',
    place: '-',
    teachers: ['Shishuang Chuyuan'],
    successors: ['Baiyun Shouduan'],
    disciples: ['Baiyun Shouduan', 'Baoning Renyong'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/D%C6%B0%C6%A1ng_K%C3%AC_Ph%C6%B0%C6%A1ng_H%E1%BB%99i',],
    youtubeId: [''],
  },
  {
    id: '45.12.2',
    hasContent: true,
    name_en: 'Huanglong Huinan',
    name_es: 'Huanglong Huinan',
    name_de: 'Huanglong Huinan',
    name_fr: 'Huanglong Huinan',
    name_vi: 'Hoàng Long Huệ Nam',
    name_ru: 'Huanglong Huinan',
    name_zh: '黃龍慧南',
    name_ja: 'Ōryō Enan',
    name_ko: 'Huanglong Huinan',
    name_ar: 'Huanglong Huinan',
    birth_death_time: ['1002', '1069'],
    records: '',
    sect: ['Linji - Huanglong'],
    country: 'China',
    place: '-',
    teachers: ['Shishuang Chuyuan'],
    successors: [''],
    disciples: ['Yungai Shouzhi', 'Baofeng Kewen', 'Huitang Zuxin'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/Ho%C3%A0ng_Long_Hu%E1%BB%87_Nam', ''],
  },
  {
    id: '45.12.3',
    hasContent: true,
    name_en: 'Cuiyan Kezhen',
    name_es: 'Cuiyan Kezhen',
    name_de: 'Cuiyan Kezhen',
    name_fr: 'Cuiyan Kezhen',
    name_vi: 'Thuý Nham Chân Khả',
    name_ru: 'Cuiyan Kezhen',
    name_zh: '翠巖可真',
    name_ja: 'Suigan Kakushin',
    name_ko: '취암가진 Chwiam Kajin',
    name_ar: 'Cuiyan Kezhen',
    birth_death_time: ['?', '1064'],
    records: '',
    sect: ['Linji'],
    country: 'China',
    place: '-',
    teachers: ['Shishuang Chuyuan'],
    successors: [''],
    disciples: ['Dagui Muzhe'],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Cuiyan_Kezhen'],
  },
  {
    id: '45.12.4',
    hasContent: true,
    name_en: 'Touzi Yiqing',
    name_es: 'Touzi Yiqing',
    name_de: 'Touzi Yiqing',
    name_fr: 'Touzi Yiqing',
    name_vi: 'Đầu Tử Nghĩa Thanh',
    name_ru: 'Touzi Yiqing',
    name_zh: '投子義青',
    name_ja: 'Tōsu Gisei',
    name_ko: '투자의청 T’uja Uich’ŏng',
    name_ar: 'Touzi Yiqing',
    birth_death_time: ['1032', '1083'],
    records: '',
    sect: ['Linji', 'Caodong'],
    country: 'China',
    place: '-',
    teachers: ['Fushan Fayuan', 'Dayang Jingxuan (Taiyang Jingxuan)'],
    successors: [''],
    disciples: ['Dahong Bao\'en', 'Furong Daokai'],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Touzi_Yiqing'],
  },
]
export default CnLv12MasterDb;
