const CnLv2MasterDb = [
  {
    id: '35.2.1',
    hasContent: true,
    isEminent: true,
    name_en: 'Shitou Xiqian',
    name_ja: 'Sekitō Kisen',
    name_zh: '石頭希遷',
    pinyin: 'Shítóu Xīqiān',
    wade_giles: 'Shih-t’ou Hsi-ch’ien',
    name_vi: 'Thạch Đầu Hi Thiên',
    original_name_vi: '',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['700', '790'],
    epoch: '',
    records: '',
    sect: ['-'],
    country: 'China',
    place: 'Nantai Temple, Nanyue Heng mountain, Hunan',
    teachers: ['Dajian Huineng', 'Qingyuan Xingsi'],
    successors: ['Yaoshan Weiyan'],
    disciples: ['Yaoshan Weiyan', 'Kinh triệu Thi Lợi', 'Tianhuang Daowu', 'Danxia Tianran', 'Dadian Baotong',
      'Chiêu Đề tại Đà châu Tuệ Lãng', 'Trường sa Chấn Lãng Hưng quốc', 'Tanzhou Dachuan',
      'Phần châu Thạch Thê', 'Pháp môn tại Phụng tường Phật Đà', 'Đàm châu Hoa Lâm', 'Triều châu Đại Điên',
      'Đàm châu Khoáng – Trường Tỳ', 'Thủy Không', 'Hải lăng Đại Biện', 'Chử Kinh', 'Hành châu Đạo Tiên',
      'Hán châu Thường Thanh', 'Phước châu Toái Thạch', 'Thương châu Thương Lãnh', 'Thường châu Nghĩa Hưng',
    ],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Shitou_Xiqian.jpg/220px-Shitou_Xiqian.jpg',
    reference: ['https://terebess.hu/zen/shitou-eng.html'],
  },
  {
    id: '35.2.2',
    hasContent: true,
    isEminent: true,
    name_en: 'Mazu Daoyi',
    name_ja: 'Baso Dōitsu',
    name_zh: '馬祖道一',
    pinyin: '',
    wade_giles: '',
    name_vi: 'Mã Tổ Đạo Nhất',
    original_name_vi: '',
    other_name_vi: '',
    nickname_vi: 'Đại Tịch',
    worship_tower: '',
    birth_death_time: ['709', '788'],
    epoch: '',
    records: '',
    sect: ['-'],
    country: 'China',
    place: 'Gonggong mountain, Nankang, Ganzhou, southern Jiangxi',
    teachers: ['Nanyue Huairang'],
    successors: ['-'],
    disciples: ['Baizhang Huaihai', 'Dazhu Huihai', 'Damei Fachang', 'Ehu Dayi', 'Xitang Zhizang',
      'Nanquan Puyuan', 'Fenzhou Wuye', 'Guizong Zhichang', 'Zhangjing Huaiyun', 'Yanguan Qian',
      'Layman Pangyun (Jushi)', 'Mayu Baoche', 'Panshan Baoji', 'Luzu Baoyun', 'Zhongyi Hongen', 'Wujiu Youxuan',
      'Zhangjing Huaihui', 'Panshan Baoji', 'Ngũ Đài Đặng Ẩn Phong', 'Thạch Củng Tuệ Tạng', 'Ô Cửu', 'Yanguan Qian',
      'Tử Ngọc Đạo Thông', 'Lỗ Tổ Bảo Vân',
      'An phong Hoài Không', 'Bách Linh', 'Cổ Sơn Linh Kiệu (Hongzhou Gushan Lingjiao)', 'Bách Nham Ninh Triết',
 'Bách Trượng Duy Chính', 'Bạch Hổ Pháp Tuyên', 'Bản Khê', 'Cam tuyền Chí Hiền',
      'Càn Nguyên Huy', 'Côn Sơn Định Giác', 'Cổ Tự',
 'Dương Châu Trí Thông', 'Dương kỳ Chân Thúc', 'Đài châu Thường Triệt Bách nham', 'Đại Dương',
 'Đại Dương Hy Hạng', 'Đại hội Đạo Ngộ', 'Đảnh châu Hồng Ân Trung Ấp', 'Động An',
 'Giang Tây Bề Thọ', 'Giang tây Nhượng Bắc lan', 'Hiện sơn Định Khánh', 'Hoa châu Sách',
 'Hoa lâm Thiện Giác', 'Hà Trung Bảo Khánh', 'Hà Trung Hoài Tắc', 'Hàng Châu Trí Tạng',
 'Hàng Châu Tự Mãn Ly thôn ', 'Hàng Châu Đả Địa', 'Hán Nam Lương tân', 'Hưng Bình',
 'Hạo Anh', 'Hải Lăng Khánh Vân', 'Hồ Nam Như Hội', 'Hồng Châu Huyền Hư',
 'Hồng loa Sơn', 'Kim Ngưu', 'Kim Quật Duy Trực', 'Kinh Châu Bảo Tích',
 'Kinh Châu Linh Nhu', 'Kinh Châu Thảo Đường', 'Kinh Nam Đạo Bản Bảo chánh', 'Kinh Triệu Duy Khoan',
 'Kinh Triệu Giác Bình', 'Kinh Triệu Hoài Thao', 'Kinh Triệu Sùng',
 'Kinh Triệu Trí Tạng', 'La Phù Tư Quảng', 'La Phù Đạo Hạnh', 'Liên Châu Nguyên Đề',
 'Long nha Viên Sướng', 'Long Sơn', 'Luyện sơn Thần Ngoạn', 'Lã Hậu Ninh Bí',
 'Lô Sơn Pháp Tạng', 'Lạc Kinh Như Mãn Phật quang ', 'Lặc Đàm Duy Kiến', 'Lặc Đàm Pháp Hội',
 'Lặc Đàm Thường Hưng', 'Lễ châu Quảng Trừng Đại đồng', 'Lễ Châu Trí Thông', 'Lễ Châu Đạo Hạnh Minh khê',
 'Lộ phủ Nguyên Lễ', 'Lộ Phủ Pháp Nhu', 'Lợi Sơn',
 'Mã đầu Thần Tạng', 'Mông Khê', 'Mặc Giản', 'Mặc Nhãn',
 'Mễ Lãnh', 'Nam nguyên Đại Minh', 'Nam nhạc Trí Châu', 'Nghĩa hưng Thắng Biện',
 'Ngũ Tiết Linh Mặc', 'Ngọc Châu Hồng Đàm', 'Ngọc Châu Vô Đẳng',
 'Ngọc Mổ Tiêu Nhiên', 'Ngọc Đài Duy Nhiên', 'Nhũ Nguyên',
 'Phong sơn Hồng Tuấn', 'phu Hà trung Pháp Tạng', 'Phù Bôi', 'Phù dung Thái Dục',
 'Phước Khê', 'Phật Áo', 'Phục Ngưu Tự Tại', 'Quang minh Phổ Mãn',
 'Quy Dương Vô Liễu', 'Quật sơn Đạo Viên', 'Sam sơn Trí Kiên', 'Song lãnh Đạo Phương',
 'Sùng Thái', 'Tam giác Tổng Ấn', 'Thiên mục Minh Giác', 'Thiều châu Thanh Hạ',
 'Thường châu Minh Cán',  'Thạch Cửu', 'Thạch Lâm',
 'Thạch sương Đại Thiện', 'Thủy Lão', 'Thủy Đường', 'Tiêu Diêu',
 'Trì Châu Đàm Ký Hội Sơn', 'Tuyền Châu Tuệ Trung', 'Tây Sơn Chủ tọa Lượng', 'Tây Viên Đàm Tạng',
 'Tùng Sơn', 'Tùy châu Đại sư Hồng Sơn', 'Tú Khê', 'Tương Châu Thường Kiên',
 'Tượng Nguyên Hoài Thản', 'Tắc Xuyên', 'Tề châu Đạo Nham', 'Tề Phong',
 'Tử Âm Duy Kiến', 'Việt Châu Duy Hiến', 'Vân Thủy Tĩnh Tông',
 'Vân Tú Thần Giám', 'Vương Cốc Hạnh Minh', 'Xứ Châu Pháp Tạng',
    ],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: ['https://terebess.hu/zen/mazu.html'],
  },
  {
    id: '35.2.3',
    hasContent: true,
    isEminent: true,
    name_en: 'Danyuan Yingzhen',
    name_ja: 'Tangen Ōshin',
    name_zh: '耽源應真',
    pinyin: '',
    wade_giles: '',
    name_vi: 'Đam Nguyên Ứng Chân',
    original_name_vi: '',
    birth_death_time: ['8th cen.', '9th cen.'],
    epoch: '',
    records: '',
    sect: ['-'],
    country: 'China',
    place: 'Danyuan mountain, Qizhou',
    teachers: ['Nanyang Huizhong'],
    successors: [''],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '35.2.4',
    name_en: 'Cizhou Faru',
    name_ja: 'Cizhou Faru',
    name_zh: '磁州法如',
    pinyin: '',
    wade_giles: '',
    name_vi: 'Từ Châu Pháp Như',
    birth_death_time: ['723', '811'],
    epoch: '',
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Heze Shenhui'],
    successors: ['Kinh Nam Duy Trung'],
    disciples: ['Kinh Nam Duy Trung'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '35.2.5',
    name_en: 'Wutai Wuming',
    name_ja: 'Godai Mumyō',
    name_zh: '五臺無名',
    pinyin: '',
    wade_giles: '',
    name_vi: 'Ngũ Đài Vô Danh',
    birth_death_time: ['722', '793'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Heze Shenhui'],
    successors: [''],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '35.2.6',
    name_en: 'Dàoxuán',
    name_ja: 'Dōsen',
    name_zh: '道璿',
    name_vi: 'Đạo Tuyền',
    birth_death_time: ['702', '760'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Songshan Puji'],
    successors: [''],
    disciples: ['Hành Biểu (行表)'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '35.2.7',
    name_en: 'Nangaku Myōsan',
    name_ja: 'Nangaku Myōsan',
    name_zh: '南嶽明瓚',
    name_vi: 'Nam Nhạc Minh Toàn',
    birth_death_time: ['722', '793'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Songshan Puji'],
    successors: [''],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '35.2.8',
    name_en: 'Yizhou Wuxiang',
    name_ja: 'Musō',
    name_zh: '無相',
    name_vi: 'Ích Châu Vô Tướng',
    birth_death_time: ['684', '762'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Jingzhong Zhixian - Chùjì (普寂)'],
    successors: [''],
    disciples: ['Wúzhù (無住)'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '35.2.9',
    name_en: '峻極',
    name_ja: '峻極',
    name_zh: '峻極',
    name_vi: 'Tuấn Cực',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Phá Táo Đọa (破竈墮)'],
    successors: [''],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '35.2.10',
    name_en: 'Niutou Fazhi',
    name_ja: 'Niutou Fazhi',
    name_zh: '法持',
    name_vi: 'Ngưu Đầu Pháp Trì',
    birth_death_time: ['635', '702'],
    records: '',
    sect: ['Niutou (Oxhead)'],
    country: 'China',
    place: '-',
    teachers: ['Niutou Huifang'],
    successors: ['Niutou Zhiwei'],
    disciples: ['Niutou Zhiwei'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: ['https://pl.wikipedia.org/wiki/Niutou_Fazhi'],
  },
  {
    id: '35.2.11',
    name_en: '惟政',
    name_ja: '惟政',
    name_zh: '惟政',
    name_vi: 'Duy Chính',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Songshan Puji'],
    successors: [''],
    disciples: ['Chí Chân (志眞)'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
  {
    id: '35.2.12',
    name_en: 'Jingzhong Wuxiang',
    name_ja: 'Jōshū Musō',
    name_zh: '浄衆無相',
    name_vi: 'Ích Châu Vô Tướng',
    other_name_vi: 'Tịnh Chúng Vô Tương',
    birth_death_time: ['684/680', '762/765'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Zizhou Chuji'],
    successors: [''],
    disciples: ['Jingzhong Shenhui', 'Baotang Wuzhu', 'Sang-shi', 'Tongchuan Ji'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: ['https://pl.wikipedia.org/wiki/Jingzhong_Wuxiang', 'https://terebess.hu/zen/mesterek/Musang.html'],
  },
  {
    id: '35.2.13',
    name_en: 'Cao bưu Đàm Ảnh',
    name_ja: 'Cao bưu Đàm Ảnh',
    name_zh: 'Cao bưu Đàm Ảnh',
    name_vi: 'Cao bưu Đàm Ảnh',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '',
    teachers: ['Lục Hợp Đại Giác'],
    successors: [''],
    disciples: ['Thái sơn Minh Luyện'],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
]
export default CnLv2MasterDb;
