const CnLv19MasterDb = [
  {
    id: '52.19.1',
    name_en: 'Poan Zuxian',
    name_es: 'Poan Zuxian',
    name_de: 'Poan Zuxian',
    name_fr: 'Poan Zuxian',
    name_vi: 'Phá Am Tổ Tiên',
    name_ru: 'Poan Zuxian',
    name_zh: '破庵祖先',
    name_ja: 'Hoan Sosen',
    name_ko: 'Poan Zuxian',
    name_ar: 'Poan Zuxian',
    birth_death_time: ['1136', '1211'],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Mian Xianjie'],
    successors: ['Wuzhun Shifan'],
    disciples: ['Wuzhun Shifan'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/Ph%C3%A1_Am_T%E1%BB%95_Ti%C3%AAn',],
  },
  {
    id: '52.19.2',
    name_en: 'Songyuan Chongyue',
    name_es: 'Songyuan Chongyue',
    name_de: 'Songyuan Chongyue',
    name_fr: 'Songyuan Chongyue',
    name_vi: 'Tùng Nguyên Sùng Nhạc',
    name_ru: 'Songyuan Chongyue',
    name_zh: '興化存奬',
    name_ja: 'Kōke Zonshō',
    name_ko: 'Songyuan Chongyue',
    name_ar: 'Songyuan Chongyue',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Mian Xianjie'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://www.erct.com/2-ThoVan/NNT/Vomonquan/20-Dailucluongnhan.htm', 'https://phatgiao.org.vn/tu-dien-phat-hoc-online/tung-nguyen-sung-nhac-k3098.html', 'https://tangthuphathoc.net/tudien/tung-nguyen-sung-nhac-tu-dien-dao-uyen/'],
  },
  {
    id: '52.19.3',
    name_en: 'Tào Nguyên Đạo Sinh',
    name_es: 'Tào Nguyên Đạo Sinh',
    name_de: 'Tào Nguyên Đạo Sinh',
    name_fr: 'Tào Nguyên Đạo Sinh',
    name_vi: 'Tào Nguyên Đạo Sinh',
    name_ru: 'Tào Nguyên Đạo Sinh',
    name_zh: 'Tào Nguyên Đạo Sinh',
    name_ja: 'Tào Nguyên Đạo Sinh',
    name_ko: 'Tào Nguyên Đạo Sinh',
    name_ar: 'Tào Nguyên Đạo Sinh',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Mian Xianjie'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['',],
  },
]
export default CnLv19MasterDb;
