const CnLv29MasterDb = [
  {
    id: '62.29.1',
    name_en: 'Zongjing Zongshu',
    name_ja: 'Zongjing Zongshu',
    name_zh: '宗鏡宗書',
    name_vi: 'Đại Chương Tông Thư',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1500', '1567'],
    epoch: '',
    records: '',
    sect: ['Caodong'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Yuezhou Wenzai'],
    successors: ['-'],
    disciples: ['Huanxiu Changrun', 'Yunkong Changzhong'],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '62.29.2',
    name_en: 'Baofeng Mingxuan',
    name_ja: 'Hōbō Myōken',
    name_zh: '寶峰明瑄',
    name_vi: 'Bảo Phong Minh Tuyên',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', '1472'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Haizhou Puci'],
    successors: ['Tianqi Benrui'],
    disciples: ['Tianqi Benrui'],
    image: '/images/avatar.png',
    reference: [''],
  },
]
export default CnLv29MasterDb;
