const CnLv26MasterDb = [
  {
    id: '59.26.1',
    name_en: 'Jukong Qibin',
    name_ja: 'Jukong Qibin',
    name_zh: '俱空契斌',
    name_vi: 'Câu Không Khế Bân',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1383', '1452'],
    epoch: '',
    records: '',
    sect: ['Caodong'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Ningran Liaogai'],
    successors: ['Wufang Kecong'],
    disciples: ['Wufang Kecong'],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '59.26.2',
    name_en: 'Baozang Puchi',
    name_ja: 'Hōzō Fuji',
    name_zh: '寶藏普持',
    name_vi: 'Bảo Tạng Phổ Trì',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Wanfeng Shiwei'],
    successors: ['Dongming Huichan'],
    disciples: ['Dongming Huichan'],
    image: '/images/avatar.png',
    reference: [''],
  },
]
export default CnLv26MasterDb;
