const CnLv8MasterDb = [
  {
    id: '41.8.1',
    generation: '41',
    name_en: 'Fengxue Yanzhao',
    name_es: 'Fengxue Yanzhao',
    name_de: 'Fengxue Yanzhao',
    name_fr: 'Fengxue Yanzhao',
    name_vi: 'Phong Huyệt Diên Chiểu',
    name_ru: 'Fengxue Yanzhao',
    name_zh: '風穴延沼',
    name_ja: 'Fuketsu Enshō',
    name_ko: 'Fengxue Yanzhao',
    name_ar: 'Fengxue Yanzhao',
    birth_death_time: ['896', '973'],
    records: '',
    sect: '-',
    country: 'China',
    place: '-',
    teachers: ['Nanyuan Huiyong'],
    successors: ['Shoushan Xingnian'],
    disciples: ['Shoushan Xingnian'],
    image: '/images/avatar.png',
    reference: ['',],

  },
  {
    id: '41.8.2',
    generation: '41',
    name_en: 'Luohan Guichen',
    name_es: 'Luohan Guichen',
    name_de: 'Luohan Guichen',
    name_fr: 'Luohan Guichen',
    name_vi: 'La Hán Quế Sâm (Địa Tạng)',
    name_ru: 'Luohan Guichen',
    name_zh: '羅漢桂琛 (地藏)',
    name_ja: 'Rakan Keichin/Keijin (Chizō)',
    name_ko: 'Luohan Guichen',
    name_ar: 'Luohan Guichen',
    birth_death_time: ['867', '928'],
    records: '',
    sect: '-',
    country: 'China',
    place: '-',
    teachers: ['Xuansha Shibei', 'Xuefeng Yicun'],
    successors: ['Fayan Wenyi'],
    disciples: ['Fayan Wenyi'],
    image: '/images/avatar.png',
    reference: ['https://terebess.hu/zen/luohan.html', 'https://quangduc.com/p156a69697/52/thien-su-la-han-que-sam-867-928-vi-thien-su-dat-nen-mong-cho-thien-phai-phap-nhan', 'https://vi.wikipedia.org/wiki/La_H%C3%A1n_Qu%E1%BA%BF_S%C3%A2m'],

  },
  {
    id: '41.8.3',
    generation: '41',
    name_en: 'Xianglin Chengyuan',
    name_es: 'Xianglin Chengyuan',
    name_de: 'Xianglin Chengyuan',
    name_fr: 'Xianglin Chengyuan',
    name_vi: 'Hương Lâm Trừng Viễn',
    name_ru: 'Xianglin Chéngyuan',
    name_zh: '香林澄遠',
    name_ja: 'Kyōrin Chōon',
    name_ko: 'Xianglin Chengyuan',
    name_ar: 'Xianglin Chengyuan',
    birth_death_time: ['908', '987'],
    records: '',
    sect: 'Yunmen',
    country: 'China',
    place: '-',
    teachers: ['Yunmen Wenyan'],
    successors: ['Zhimen Guangzuo'],
    disciples: ['Zhimen Guangzuo'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/H%C6%B0%C6%A1ng_L%C3%A2m_Tr%E1%BB%ABng_Vi%E1%BB%85n'],

  },
  {
    id: '41.8.4',
    generation: '41',
    name_en: 'Dongshan Shouchu',
    name_es: 'Dongshan Shouchu',
    name_de: 'Dongshan Shouchu',
    name_fr: 'Dongshan Shouchu',
    name_vi: 'Động Sơn Thủ Sơ',
    name_ru: 'Dongshan Shouchu',
    name_zh: '洞山守初',
    name_ja: 'Tōsan Shusho',
    name_ko: '동산수초 Tongsan Sucho',
    name_ar: 'Dongshan Shouchu',
    birth_death_time: ['910', '990'],
    records: '',
    sect: 'Yunmen',
    country: 'China',
    place: '-',
    teachers: ['Yunmen Wenyan'],
    successors: [''],
    disciples: ['Nanyue Liangya'],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '41.8.5',
    generation: '41',
    name_en: 'Deshan Yuanmi',
    name_es: 'Deshan Yuanmi',
    name_de: 'Deshan Yuanmi',
    name_fr: 'Deshan Yuanmi',
    name_vi: 'Đức Sơn Duyên Mật',
    name_ru: 'Deshan Yuanmi',
    name_zh: '德山緣密',
    name_ja: 'Tokusan Emmitsu',
    name_ko: 'Deshan Yuanmi',
    name_ar: 'Deshan Yuanmi',
    birth_death_time: ['', ''],
    records: '',
    sect: 'Yunmen',
    country: 'China',
    place: '-',
    teachers: ['Yunmen Wenyan'],
    successors: [''],
    disciples: ['Wenshu Yingzhen Monju Ôshin'],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '41.8.6',
    generation: '41',
    name_en: 'Shuangquan Renyu',
    name_es: 'Shuangquan Renyu',
    name_de: 'Shuangquan Renyu',
    name_fr: 'Shuangquan Renyu',
    name_vi: 'Song Tuyền Nhân Úc',
    name_ru: 'Shuangquan Renyu',
    name_zh: '雙泉仁郁',
    name_ja: 'Shuangquan Renyu',
    name_ko: 'Shuangquan Renyu',
    name_ar: 'Shuangquan Renyu',
    birth_death_time: ['', ''],
    records: '',
    sect: 'Yunmen',
    country: 'China',
    place: '-',
    teachers: ['Yunmen Wenyan'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '41.8.7',
    generation: '41',
    name_en: 'Baling Haojian',
    name_es: 'Baling Haojian',
    name_de: 'Baling Haojian',
    name_fr: 'Baling Haojian',
    name_vi: 'Ba Lăng Hạo Giám',
    name_ru: 'Baling Haojian',
    name_zh: '巴陵顥鑒',
    name_ja: 'Baling Haojian',
    name_ko: 'Baling Haojian',
    name_ar: 'Baling Haojian',
    birth_death_time: ['', ''],
    records: '',
    sect: 'Yunmen',
    country: 'China',
    place: '-',
    teachers: ['Yunmen Wenyan'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '41.8.8',
    generation: '41',
    name_en: 'Fengxian Daoshen',
    name_es: 'Fengxian Daoshen',
    name_de: 'Fengxian Daoshen',
    name_fr: 'Fengxian Daoshen',
    name_vi: 'Phụng Tiên Đạo Thâm',
    name_ru: 'Fengxian Daoshen',
    name_zh: '奉先道深',
    name_ja: 'Hōsen Dōshin',
    name_ko: '봉선도심 Pongsŏn Tosim',
    name_ar: 'Fengxian Daoshen',
    birth_death_time: ['', ''],
    records: '',
    sect: 'Yunmen',
    country: 'China',
    place: '-',
    teachers: ['Yunmen Wenyan'],
    successors: [''],
    disciples: ['Lianhua Fengxiang', 'Xiang Anzhu'],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Fengxian_Daoshen'],
  },
]
export default CnLv8MasterDb;
