const CnLv6MasterDb = [
  {
    id: '39.6.1',
    hasContent: true,
    name_en: 'Caoshan Benji',
    name_ja: 'Sōzan Honjaku',
    name_zh: '曹山本寂',
    name_vi: 'Tào Sơn Bản Tịch',
    nickname_vi: 'Nguyên Chứng',
    original_name_vi: '',
    worship_tower: 'Phúc Viên',
    birth_death_time: ['840', '901'],
    records: '',
    sect: ['Caodong'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dongshan Liangjie'],
    successors: ['Caoshan Huixia'],
    disciples: ['Caoshan Huixia, Jingfeng Congzhi', 'Lumen Chuzhen / Lumen Zhenchan', 'Heyu Kuanghui', 'Yuwang Hongtong'],
    image: '/images/avatar.png',
    reference: ['https://phatgiao.org.vn/tu-dien-phat-hoc-online/tao-son-bon-tich-k5268.html', 'https://hoavouu.com/p24a17594/13-thien-su-bon-tich-o-tao-son-to-thu-hai-tao-dong'],
  },
  {
    id: '39.6.2',
    hasContent: true,
    name_en: 'Xinghua Cunjiang',
    name_ja: 'Kōke Zonshō',
    name_zh: '興化存奬',
    name_vi: 'Hưng Hóa Tồn Tương',
    other_name_vi: 'Hưng Hóa Tồn Tưởng',
    nickname_vi: 'Quảng Tế',
    original_name_vi: '',
    worship_tower: 'Thông Tịch',
    birth_death_time: ['830', '888'],
    records: '',
    sect: ['Linji'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Linji Yixuan'],
    successors: ['Nanyuan Huiyong'],
    disciples: ['Nanyuan Huiyong'],
    image: '/images/avatar.png',
    reference: ['https://terebess.hu/zen/xinghua.html', 'https://phatgiao.org.vn/tu-dien-phat-hoc-online/hung-hoa-ton-tuong-k4195.html',
      'https://vi.wikipedia.org/wiki/H%C6%B0ng_H%C3%B3a_T%E1%BB%93n_T%C6%B0%C6%A1ng',
      'https://hoavouu.com/p24a17596/15-thien-su-ton-tuong-o-hung-hoa',
      'https://blog.phapthihoi.org/gt-member/ts-hung-hoa-ton-tuong'
    ],
  },
  {
    id: '39.6.3',
    hasContent: true,
    name_en: 'Sansheng Huiran',
    name_ja: 'Sanshō Enen',
    name_zh: '三聖慧然',
    name_vi: 'Tam Thánh Huệ Nhiên',
    other_name_vi: '',
    nickname_vi: '',
    original_name_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    records: '',
    sect: ['Linji'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Linji Yixuan'],
    successors: [''],
    disciples: ['Zhenzhou Dabei'],
    image: '/images/avatar.png',
    reference: ['https://blog.phapthihoi.org/gt-member/ts-tam-thanh-hue-nhien/', 'https://vi.wikipedia.org/wiki/Tam_Th%C3%A1nh_Hu%E1%BB%87_Nhi%C3%AAn',
      'https://pl.wikipedia.org/wiki/Sansheng_Huiran', 'https://hoavouu.com/p24a17597/16-thien-su-hue-nhien-o-vien-tam-thanh'],
  },
  {
    id: '39.6.4',
    name_en: 'Muzhou Chen Cao',
    name_zh: '睦州陳操',
    name_ja: 'Muzhou Chen Cao',
    name_vi: 'Mục Châu Trần Tháo',
    other_name_vi: '',
    nickname_vi: 'Thượng thư Trần Tháo',
    original_name_vi: '',
    birth_death_time: ['', ''],
    records: '',
    sect: [],
    country: '🇨🇳',
    place: 'Muzhou',
    teachers: ['Muzhou Daoming'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://blog.phapthihoi.org/gt-member/ts-muc-chau-tran-thao/',
      'http://thuongchieu.net/index.php/chuyende/vuonthien/847-bai-5--hoang-ba-tat-mt-tat',
      'http://thuongchieu.net/index.php?option=com_content&view=article&id=1262:bai-85--lao-bang-th--t&catid=44:vn-thin-rng-ngc&Itemid=355',],
  },
  {
    id: '39.6.5',
    name_en: 'Zhangzhuo Xiucai',
    name_ja: 'Chōsetsu Shūsai',
    name_zh: '張拙秀才',
    name_vi: 'Trương Chuyết Tú Tài',
    other_name_vi: '',
    nickname_vi: '',
    birth_death_time: ['', ''],
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Shishuang Qingzhu'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '39.6.6',
    hasContent: true,
    name_en: 'Jiufeng Daoqian',
    name_ja: 'Kyūhō Dōken',
    name_zh: '九峰道虔',
    name_vi: 'Cửu Phong Ðạo Kiền',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', '923'],
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Shishuang Qingzhu'],
    successors: [''],
    disciples: ['Heshan Wuyin', 'Baofeng Yanmao', 'Guangmu Xingxiu', "Tong'an Changcha", 'Letan Kuangwu'],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Jiufeng_Daoqian', 'https://www.reddit.com/r/Koans/comments/160eeb/jiufengs_one_who_transmits_words_221_of_300/', 'https://www.rongmotamhon.net/daouyen/Data/Ph_C/C84.htm'],
  },
  {
    id: '39.6.7',
    hasContent: true,
    name_en: 'Xuefeng Yicun',
    name_ja: 'Seppō Gison',
    name_zh: '雪峰义存',
    name_vi: 'Tuyết Phong Nghĩa Tồn',
    other_name_vi: '',
    nickname_vi: '',
    original_name_vi: '',
    worship_tower: '',
    birth_death_time: ['822', '908'],
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Deshan Xuanjian'],
    successors: [''],
    disciples: ['Xuansha Shibei', 'Yunmen Wenyan', 'Baofu Congzhan', 'Changqing Huileng',
      'Cuiyan Lingcan', 'Jingqing Daofu', 'Taiyuan Fu',
      'Furong Lingxun', 'Zhangsheng Jiaoran', 'Lingzhao Buna (靈照布衲, 870-947, Long Hoa Linh Chiếu)',
      'Ehu Zhifu (Nga Hồ Trí Phù)', 'Dapu Xuantong (Huyền Thông Đạo Phổ)', 'Gushan Shenyan',
      'Bao’en Huaiyue (Báo Ân Hoài Nhạc)', 'Huadu Shiye (Hóa Độ Sư Úc)', 'Xiangshou Shaoxiang',
      'Anguo Hongtao', 'Jiyun Lingzhao', 'Wushi Lingguan (烏石靈觀)',
      'Yongfu Congyan', 'Fuqing Xuanna', 'Dongyan Kexiu',
      'Hushan Yanzong', 'Nanyue Weijing (Weijing Chanshi)',
      'Yueshan Jianzhen (越山鑒真)', 'Shuilong Daopu (Thụy Long Đạo Phổ - 睡龍道溥)',
      'Wŏnnap (Korean)', 'Yŏngjo (Korean)'
    ],
    image: '/images/avatar.png',
    reference: ['https://terebess.hu/zen/xuefeng.html', 'https://wikipedia.org/wiki/Xuefeng_Yicun', 'https://hoavouu.com/p24a17602/21-thien-su-nghia-ton-o-tuyet-phong'],
  },
  {
    id: '39.6.8',
    name_en: 'Niaoke Daolin',
    name_ja: 'Chōka Dōrin',
    name_zh: '鳥窠道林',
    name_vi: 'Điểu Khòa Đạo Lâm',
    other_name_vi: 'Đạo Lâm Ô Khòa',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['741', '824'],
    records: '',
    sect: ['Niutou (Oxhead)'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Kinzan Dōkin'],
    successors: [''],
    disciples: ['Hàng Châu Hội Thông'],
    image: '/images/avatar.png',
    reference: ['https://en.wikipedia.org/wiki/Niaoke_Daolin'],
  },
  {
    id: '39.6.9',
    hasContent: true,
    name_en: 'Yunju Daoying',
    name_ja: 'Ungo Dōyō',
    name_zh: '雲居道膺',
    name_vi: 'Vân Cư Đạo Ưng',
    other_name_vi: '',
    nickname_vi: '',
    original_name_vi: '',
    worship_tower: '',
    birth_death_time: ['835', '902'],
    records: '',
    sect: ['Caodong'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dongshan Liangjie'],
    successors: ['Tong’an Daopi'],
    disciples: ['Guizong Huaiyun', 'Yunju Daojian', 'Jishan Zhang', 'Langzhou Deshan', 'Tongan Daopi', 'Yongguang Yuanzhen', 'Taekyŏng Yŏŏm (K)', 'Sŏngak Hyŏngmi (K)', 'Chinch’ŏl Iŏm (K)'],
    image: 'https://terebess.hu/zen/mesterek/woodcut/39-3.jpg',
    reference: ['https://terebess.hu/zen/mesterek/YunjuDaoying.html', 'https://en.wikipedia.org/wiki/Yunju_Daoying',
      'https://vi.wikipedia.org/wiki/V%C3%A2n_C%C6%B0_%C4%90%E1%BA%A1o_%C6%AFng', 'https://pl.wikipedia.org/wiki/Yunju_Daoying',
      'https://hoavouu.com/p24a17595/14-thien-su-dao-ung-o-van-cu'
    ],
  },
  {
    id: '39.6.10',
    hasContent: true,
    name_en: 'Baoshou Yanzhao',
    name_ja: 'Hōju Enshō',
    name_zh: '寶壽延沼',
    name_vi: 'Bảo Thọ Diên Chiểu',
    other_name_vi: '',
    nickname_vi: '',
    original_name_vi: '',
    worship_tower: '',
    birth_death_time: ['830', '888'],
    records: '',
    sect: ['Linji'],
    country: '🇨🇳',
    place: 'Zhengzhou',
    teachers: ['Linji Yixuan'],
    successors: ['Xiyuan Siming'],
    disciples: ['Xiyuan Siming'],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Baoshou_Yanzhao', 'https://terebess.hu/zen/mesterek/BaoshouYanzhao.html', 'https://thuvienhoasen.org/images/file/bwafDu4e1QgQAN4Y/chu-thien-duc-vol-2.pdf'],
  },
  {
    id: '39.6.11',
    name_en: 'Daguang Juhui',
    name_ja: 'Daikō Kyokai',
    name_zh: '大光居誨',
    name_vi: 'Đại Quang Cư Hối',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['836', '903'],
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Shishuang Qingzhu'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Daguang_Juhui',],
  },
  {
    id: '39.6.12',
    hasContent: true,
    name_en: 'Yantou Quanhuo',
    name_ja: 'Gantō Zenkatsu',
    name_zh: '巖頭全豁',
    name_vi: 'Nham Đầu Toàn Hoát',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['828', '887'],
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Deshan Xuanjian'],
    successors: [''],
    disciples: ['Luoshan Daoxian', 'Ruiyan Shiyan'],
    image: '/images/avatar.png',
    reference: ['https://vi.m.wikipedia.org/wiki/Nham_%C4%90%E1%BA%A7u_To%C3%A0n_Ho%C3%A1t', 'https://en.m.wikipedia.org/wiki/Yantou_Quanhuo',
    'https://hoavouu.com/p24a17601/20-thien-su-toan-khoat-o-nham-dau'],
  },
  {
    id: '39.6.13',
    name_en: 'Luopu Yuan’an',
    name_ja: 'Rakuho Gen’an',
    name_zh: '洛浦元安',
    name_vi: 'Lạc Phố Nguyên An',
    other_name_vi: 'Lạc Phổ Nguyên An',
    nickname_vi: '',
    original_name_vi: '',
    birth_death_time: ['834', '898'],
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Jiashan Shanhui', 'Linji Yixuan'],
    successors: [''],
    disciples: ['Qianfeng Chuanchu'],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Luopu_Yuan%E2%80%99an', 'https://phatgiao.org.vn/tu-dien-phat-hoc-online/lac-pho-dau-su-k36005.html',
    'https://tangthuphathoc.net/thuat_ngu/lac-pho-hoan-huong/', 'https://tangthuphathoc.net/thuat_ngu/lac-pho-lam-chung'],
  },
  {
    id: '39.6.14',
    hasContent: true,
    name_en: 'Yungai Zhiyuan',
    name_ja: 'Yungai Zhiyuan',
    name_zh: '雲蓋志元',
    name_vi: 'Vân Cái Chí Nguyên',
    other_name_vi: '',
    nickname_vi: 'Viên Tịnh',
    worship_tower: '',
    birth_death_time: ['', ''],
    records: '',
    sect: [],
    country: '🇨🇳',
    place: 'núi Vân Cái Đàm Châu',
    teachers: ['Shishuang Qingzhu'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://nigioikhatsi.net/thien/khong-ai-biet-ong-ta.html',],
  },
  {
    id: '39.6.15',
    hasContent: true,
    name_en: 'Yongquan Jingxin',
    name_ja: 'Yongquan Jingxin',
    name_zh: '湧泉景欣',
    name_vi: 'Dũng Tuyền Cảnh Hân',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    records: '',
    sect: [],
    country: '🇨🇳',
    place: 'Dũng Tuyền, 台州市 - Tāizhōu Shì, (nay là Lâm Hải, 浙江 - Zhejiang)',
    teachers: ['Shishuang Qingzhu'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://nigioikhatsi.net/thien/khong-ai-biet-ong-ta.html',],
  },
  {
    id: '39.6.16',
    hasContent: true,
    name_en: 'Phúc Thuyền Hồng Tiến',
    name_ja: 'Phúc Thuyền Hồng Tiến',
    name_zh: '',
    name_vi: 'Phú Thuyền Hồng Tiến',
    other_name_vi: 'Phúc Thuyền Hồng Tiến',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Shishuang Qingzhu'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://nigioikhatsi.net/thien/khong-ai-biet-ong-ta.html9',],
  },
  {
    id: '39.6.17',
    name_en: 'Sushan Kuangren',
    name_ja: 'Sozan Kyōnin',
    name_zh: '疏山匡仁',
    name_vi: 'Sơ Sơn Khuôn Nhân',
    other_name_vi: 'Sớ Sơn',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['837', '909'],
    records: '',
    sect: ['Caodong'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dongshan Liangjie'],
    successors: [''],
    disciples: ['Huguo Shoucheng', 'Tongjin Kyŏngbo'],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Sushan_Kuangren'],
  },
  {
    id: '39.6.18',
    hasContent: true,
    name_en: 'Yuezhou Qianfeng',
    name_ja: 'Esshū Kempō',
    name_zh: '越州乾峰',
    name_vi: 'Việt Châu Kiền Phong',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    records: '',
    sect: ['Caodong'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Dongshan Liangjie', 'Caoshan Benji'],
    successors: [''],
    disciples: [],
    image: '',
    reference: ['https://pl.wikipedia.org/wiki/Yuezhou_Qianfeng'],
  },
  {
    id: '39.6.19',
    hasContent: true,
    name_en: 'Weifu Dajue',
    name_ja: 'Weifu Dajue',
    name_zh: '魏府大覺',
    name_vi: 'Ngụy Phủ Đại Giác',
    other_name_vi: '',
    nickname_vi: '',
    original_name_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    records: '',
    sect: ['Linji'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Linji Yixuan'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://hoavouu.com/p24a17598/17-hoa-thuong-dai-giac',
      'https://hoavouu.com/p24a17598/17-hoa-thuong-dai-giac', 'https://zenmarrow.com/Single?id=171&index=sho'
    ],
  },
  {
    id: '39.6.20',
    hasContent: true,
    name_en: 'Nanta Guangyong',
    name_ja: 'Nantō Kōyū',
    name_zh: '南塔光涌',
    name_vi: 'Nam Tháp Quang Dũng',
    other_name_vi: '',
    nickname_vi: '',
    original_name_vi: '',
    worship_tower: '',
    birth_death_time: ['850', '938'],
    records: '',
    sect: ['Guiyang'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Yangshan Huiji'],
    successors: ['Bajiao Huiqing'],
    disciples: ['Bajiao Huiqing'],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Nanta_Guangyong', 'https://zenmarrow.com/Single?id=495&index=sho',
      'https://hoavouu.com/p24a17600/19-thien-su-quang-dung-o-nam-thap'
    ],
  },
  {
    id: '39.6.21',
    hasContent: true,
    name_en: 'Xita Guangmu',
    name_ja: 'Saitō Kōboku',
    name_zh: '西塔光穆',
    name_vi: 'Tây Tháp Quang Mục',
    other_name_vi: '',
    nickname_vi: '',
    original_name_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    records: '',
    sect: ['Guiyang'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Yangshan Huiji'],
    successors: ['Zifu Rubao'],
    disciples: ['Zifu Rubao'],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Xita_Guangmu'
    ],
  },
  {
    id: '39.6.22',
    hasContent: true,
    name_en: 'Wuzhu Wenxi',
    name_ja: 'Mujaku Bunki',
    name_zh: '無著文喜',
    name_vi: 'Vô Trú Văn Hỉ',
    other_name_vi: 'Vô Trú Văn Hỷ',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['820', '899'],
    records: '',
    sect: ['Guiyang'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Yangshan Huiji'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/V%C3%B4_Tr%C6%B0%E1%BB%9Bc_V%C4%83n_H%E1%BB%89', 'https://pl.wikipedia.org/wiki/Wuzhu_Wenxi',
      'https://hoavouu.com/p24a17599/18-thien-su-van-hy'
    ],
  },
  {
    id: '39.6.23',
    hasContent: true,
    name_en: 'Miàoxìn',
    name_ja: 'Myōshin',
    name_zh: '妙信',
    name_vi: 'Diệu Tín',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    records: '',
    sect: ['Guiyang'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Yangshan Huiji'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Miaoxin'
    ],
  },
]
export default CnLv6MasterDb;
