const CnLv25MasterDb = [
  {
    id: '58.25.1',
    name_en: 'Ningran Liaogai',
    name_ja: 'Ningran Liaogai',
    name_zh: '凝然了改',
    name_vi: 'Ngưng Nhiên Liễu Cải',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1335', '1421'],
    epoch: '',
    records: '',
    sect: ['Caodong'],
    country: 'China',
    place: '-',
    teachers: ['Songting Ziyan'],
    successors: ['Jukong Qibin'],
    disciples: ['Jukong Qibin'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/Ng%C6%B0ng_Nhi%C3%AAn_Li%E1%BB%85u_C%E1%BA%A3i'],
  },
  {
    id: '58.25.2',
    name_en: 'Wanfeng Shiwei',
    name_ja: 'Manhō Jijō',
    name_zh: '萬峰時蔚',
    name_vi: 'Vạn Phong Shiwei',
    other_name_vi: 'Vạn Phong Vệ Công',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1303', '1381'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: 'China',
    place: '-',
    teachers: ['Qianyan Yuanzhang'],
    successors: ['Baozang Puchi'],
    disciples: ['Baozang Puchi'],
    image: '/images/avatar.png',
    reference: ['https://cbetaonline.dila.edu.tw/zh/JB492'],
  },
]
export default CnLv25MasterDb;
