const CnLv18MasterDb = [
  {
    id: '51.18.1',
    name_en: 'Mian Xianjie',
    name_ja: 'Mittan Kanketsu',
    name_zh: '密庵咸傑',
    name_vi: 'Mật Am Hàm Kiệt',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1107/1118', '1186'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇨🇳',
    place: '-',
    teachers: ['Yingan Tanhua'],
    successors: [''],
    disciples: ['Songyuan Chongyue', 'Poan Zuxian'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/M%E1%BA%ADt_Am_H%C3%A0m_Ki%E1%BB%87t',],
  },
  {
    id: '51.18.2',
    name_en: 'Xueyan Huiman',
    name_ja: '',
    name_zh: '雪巖慧滿',
    name_vi: 'Tuyết Nham Như Mãn',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['-', '1206'],
    epoch: '',
    records: '',
    sect: ['Caodong'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Yushan Shiti'],
    successors: ['Wansong Xingxiu'],
    disciples: ['Wansong Xingxiu'],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '51.18.3',
    name_en: 'Xue\'an Congjin',
    other_name_en: 'Tiantong Congjin',
    name_ja: 'Setsuan Jūkin',
    other_name_ja: 'Tendō Jūkin',
    name_zh: '雪庵從瑾',
    other_name_zh: '天童從瑾',
    name_vi: 'Tuyết Am Tùng Cẩn',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1115/1117', '1185/1200'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Huanglong'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Wannian Tanguan'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://terebess.hu/zen/mesterek/XueanCongjin.html',],
  },
  {
    id: '51.18.4',
    name_en: 'Xu\'an Huaichang',
    other_name_en: 'Huaibi',
    name_ja: 'Koan Eshō',
    name_zh: '虛庵懷敞',
    other_name_zh: '許菴懷敞',
    name_vi: 'Hứa Am Hoài Xương',
    other_name_vi: 'Hoài Bị',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1125', '1195'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Huanglong'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Wannian Tanguan'],
    successors: ['Myōan Eisai'],
    disciples: ['Myōan Eisai'],
    image: '/images/avatar.png',
    reference: ['https://terebess.hu/zen/mesterek/XuanHuaichang.html',],
  },
]
export default CnLv18MasterDb;
