const CnLv35MasterDb = [
  {
    id: '68.35.1',
    name_en: 'Feiyin Tongrong',
    name_ja: 'Hi’in Tsuyo',
    name_zh: '費隠通容',
    name_vi: 'Phí Ẩn Thông Dung',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1593', '1661'],
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: 'China',
    place: '',
    teachers: ['Miyun Yuanwu'],
    successors: ['Yinyuan Longqi'],
    disciples: ['Yinyuan Longqi'],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '68.35.2',
    name_en: 'Yulin Tongxiu',
    name_ja: 'Gyokurin Tsūshū',
    name_zh: '玉林通琇',
    name_vi: 'Ngọc Lâm Thông Tú',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1614', '1675'],
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: 'China',
    place: '',
    teachers: ['Tianyin Yuanxiu'],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/Ng%E1%BB%8Dc_L%C3%A2m_Th%C3%B4ng_T%C3%BA'],
  },
]
export default CnLv35MasterDb;
