const CnLv15MasterDb = [
  {
    id: '48.15.1',
    hasContent: true,
    isEminent: true,
    name_en: 'Yuanwu Keqin',
    name_ja: 'Engo Kokugon',
    name_zh: '圓悟克勤',
    pinyin: '',
    name_vi: 'Viên Ngộ Khắc Cần',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1063', '1135'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Wuzu Fayan'],
    successors: [''],
    disciples: ['Huqiu Shaolong', 'Huguo Jingyuan?', 'Wuyong Jingquan?', 'Dahui Zonggao', 'Miyin Anmin',
      'Foxing Fatai', 'Cunpu Chanren', 'Xiangyun Tanyi', 'Xiatang Huiyuan'
    ],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/Vi%C3%AAn_Ng%E1%BB%99_Kh%E1%BA%AFc_C%E1%BA%A7n',],
  },
  {
    id: '48.15.2',
    name_en: 'Kaifu Daoning',
    name_ja: 'Kaifuku Dōnei',
    name_zh: '開福道寧',
    pinyin: '',
    name_vi: 'Khai Phúc Đạo Ninh',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1053', '1113'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Wuzu Fayan'],
    successors: ['Yuehan Shanguo'],
    disciples: ['Yuehan Shanguo'],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Kaifu_Daoning',],
  },
  {
    id: '48.15.3',
    name_en: 'Puzhao Yibian',
    name_ja: 'Puzhao Yibian',
    name_zh: '普照一辯',
    pinyin: '',
    name_vi: 'Phổ Chiếu Nhất Biện',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1081', '1149'],
    epoch: '',
    records: '',
    sect: ['Caodong'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Lumen Zijue'],
    successors: ['Lingyan Sengbao'],
    disciples: ['Lingyan Sengbao'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/Ph%E1%BB%95_Chi%E1%BA%BFu_Nh%E1%BA%A5t_Bi%E1%BB%87n',],
  },
  {
    id: '48.15.4',
    hasContent: true,
    isEminent: true,
    name_en: 'Foyan Qingyuan',
    name_ja: 'Butsugen Seion',
    name_zh: '佛眼清遠',
    pinyin: '',
    name_vi: 'Phật Nhãn Thanh Viễn',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1067', '1120'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: '🇨🇳',
    place: 'Thiên Ninh Vạn Thọ Tự (天寧萬壽寺)  Thư Châu; Long Môn Tự (龍門寺); Bảo Sơn Tự (褒山寺) ở Hòa Châu (和州, Tỉnh An Huy)',
    teachers: ['Wuzu Fayan'],
    successors: ['Zhu’an Shigui'],
    disciples: ['Gao’an Shanwu' , 'Zhu’an Shigui'],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Foyan_Qingyuan', 'https://phatgiao.org.vn/tu-dien-phat-hoc-online/phat-nhan-thanh-vien-k4994.html'],
  },
  {
    id: '48.15.5',
    name_en: 'Changling Shouzhuo',
    other_name_en: 'Zhangling Shouzhuo',
    name_ja: 'Chōrei Shutaku',
    name_zh: '長靈守卓',
    pinyin: '',
    name_vi: 'Trường Linh Thủ Trác',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1060/1066', '1130/1124'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Huanglong'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Lingyuan Weiqing'],
    successors: ['Wushi Jiechen'],
    disciples: ['Wushi Jiechen'],
    image: '/images/avatar.png',
    reference: ['https://terebess.hu/zen/mesterek/ChanglingShouzhuo.html', 'https://hoavouu.com/p26a17707/4/33-thien-su-thu-trac-o-truong-linh-thien-ninh'],
  },
  {
    id: '48.15.6',
    name_en: 'Foxin Bencai',
    name_ja: '',
    name_zh: '佛心本才',
    other_name_zh: '本才佛心',
    pinyin: '',
    name_vi: 'Phật Tâm Bổn Tài',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1067', '1120'],
    epoch: 'Northern Song Dynasty',
    records: '',
    sect: ['Linji', 'Huanglong'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Lingyuan Weiqing'],
    successors: ['Biefeng Zuzhen'],
    disciples: ['Biefeng Zuzhen'],
    image: '/images/avatar.png',
    reference: ['https://terebess.hu/zen/foxin.html', 'https://hoavouu.com/p24a17708/8/34-thien-su-bon-tai-phat-tam-o-thuong-phong-dam-chau',
      'https://quangduc.com/a46541/34-thien-su-bon-tai-phat-tam-o-thuong-phong-dam-chau', 'https://blog.phapthihoi.org/gt-member/0-ts-thuong-phong-ban-tai'],
  },
  {
    id: '48.15.7',
    name_en: 'Zhìtōng',
    other_name_en: 'Weiju',
    name_ja: 'Chitssū',
    name_zh: '智通,',
    pinyin: '',
    name_vi: 'Trí Thông',
    other_name_vi: 'Không Thất Đạo Nhân',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['-', '1124'],
    epoch: '11th - 12th century',
    records: '',
    sect: ['Linji', 'Huanglong'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Lingyuan Weiqing'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/Tr%C3%AD_Th%C3%B4ng'],
  },
]
export default CnLv15MasterDb;
