const CnLv21MasterDb = [
  {
    id: '54.21.1',
    hasContent: true,
    name_en: 'Xueyan Zuqin',
    name_es: 'Xueyan Zuqin',
    name_de: 'Xueyan Zuqin',
    name_fr: 'Xueyan Zuqin',
    name_vi: 'Tuyết Nham Tổ Khâm (Pháp Khâm)',
    name_ru: 'Xueyan Zuqin',
    name_zh: '雪巖祖欽 (法欽, 惠朗)',
    name_ja: 'Seggan Sokin',
    name_ko: 'Xueyan Zuqin',
    name_ar: 'Xueyan Zuqin',
    birth_death_time: ['1215?', '1287'],
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: 'China',
    place: '-',
    teachers: ['Wuzhun Shifan'],
    successors: ['Gaofeng Yuanmiao'],
    disciples: ['Gaofeng Yuanmiao'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/Tuy%E1%BA%BFt_Nham_T%E1%BB%95_Kh%C3%A2m', 'https://terebess.hu/zen/mesterek/XueyanZuqin.html', 'http://www.thuongchieu.net/index.php/phapthoai/suphu/4162-thiensutuyetkham'],
    youtubeId: ['KpoUcjH7bRM'],
  },
  {
    id: '54.21.2',
    hasContent: true,
    name_en: 'Lingyin Wentai',
    name_es: 'Lingyin Wentai',
    name_de: 'Lingyin Wentai',
    name_fr: 'Lingyin Wentai',
    name_vi: 'Linh Ẩn Văn Thái',
    name_ru: 'Lingyin Wentai',
    name_zh: '靈隱文泰',
    name_ja: 'Lingyin Wentai',
    name_ko: 'Lingyin Wentai',
    name_ar: 'Lingyin Wentai',
    birth_death_time: ['-', '1289'],
    records: '',
    sect: ['Caodong'],
    country: 'China',
    place: '-',
    teachers: ['Xueting Fuyu'],
    successors: ['Huanyuan Fuyu'],
    disciples: ['Huanyuan Fuyu'],
    image: '/images/avatar.png',
    reference: [''],
  },
]
export default CnLv21MasterDb;
