const CnLv24MasterDb = [
  {
    id: '57.24.1',
    hasContent: true,
    name_en: 'Tianru Weize',
    name_ja: 'Tenjo Isoku',
    name_zh: '天如惟則',
    name_vi: 'Thiên Như Duy Tắc',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1286', '1354'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Zhongfeng Mingben'],
    successors: ['-'],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['http://www.thuongchieu.net/index.php/phapthoai/suphu/4207-thiensunhutac',
      'https://duylucthien.wordpress.com/2024/01/12/thien-nhu-duy-tac-thien-su/',
      'https://thuvienhoasen.org/a8016/thien-nhu-dai-su',
      'https://ph.tinhtong.vn/Home/MP3?p=MP3*Tinh+Do+Hoac+Van+-+Thien+Nhu+Duy+Tac',
      'https://ngulucthien.com/thien-su-duy-tac/', 'https://www.pusa123.com/pusa/renwu/ydgs/51717.shtml'],
  },
  {
    id: '57.24.3',
    name_en: 'Qianyan Yuanzhang',
    name_ja: 'Sengan Genchō',
    name_zh: '千巖元長',
    name_vi: 'Thiên Nham Nguyên Trường',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1284', '1357'],
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Zhongfeng Mingben'],
    successors: ['Wanfeng Shiwei'],
    disciples: ['Wanfeng Shiwei'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/Thi%C3%AAn_Nham_Nguy%C3%AAn_Tr%C6%B0%E1%BB%9Dng' ,
      'https://jmapps.ne.jp/mmag/sakka_det.html?list_count=10&person_id=369',
      'https://www.fojiaotz.com/en/about-5', 'https://www.buddhachan.org/en/lay-practitioners-in-buddhism-en/'
    ],
  },
  {
    id: '57.24.5',
    name_en: 'Songting Ziyan',
    name_ja: 'Songting Ziyan',
    name_zh: '松庭子嚴',
    name_vi: 'Tùng Đình Tử Nghiêm',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['-', '-'],
    records: '',
    sect: ['Caodong'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Chunzuo Wencai'],
    successors: ['Ningran Liaogai'],
    disciples: ['Ningran Liaogai'],
    image: '/images/avatar.png',
    reference: [''],
  },
]
export default CnLv24MasterDb;
