const CnLv17MasterDb = [
  {
    id: '50.17.1',
    hasContent: true,
    name_en: 'Yingan Tanhua',
    name_ja: 'Ōan Donge',
    name_zh: '應菴曇華',
    pinyin: '',
    name_vi: 'Ứng Am Đàm Hoa',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1103', '1163'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: 'China',
    place: 'chùa Thiên Đồng',
    teachers: ['Huqiu Shaolong'],
    successors: ['Mian Xianjie'],
    disciples: ['Mian Xianjie', 'Hoà Sơn Tâm Giám'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/%E1%BB%A8ng_Am_%C4%90%C3%A0m_Hoa',],
  },
  {
    id: '50.17.2',
    name_en: 'Wakuan Shitai',
    name_ja: 'Huoan Shiti',
    name_zh: '或菴師體',
    pinyin: '',
    name_vi: 'Hoặc Am Sư Thể',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1108', '1179'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: 'China',
    place: '-',
    teachers: ['Huguo Jingyuan'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://terebess.hu/zen/entangling.html', 'https://www.bachduongky.net/danh-muc/huyen-quan-tu-tri-quan/3',
      'http://chimvie3.free.fr/27/vomonquan.htm', 'https://nigioikhatsi.net/kinhsach-pdf/CotNhucCuaThien_TranTrucLam.pdf'],
  },
  {
    id: '50.17.3',
    hasContent: true,
    name_en: 'Zhuo’an Deguang',
    other_name_en: 'Fozhao Deguang',
    name_ja: 'Settan Tokkō',
    name_zh: '拙庵德光',
    pinyin: '',
    name_vi: 'Chuyết Am Đức Quang',
    other_name_vi: '',
    nickname_vi: 'Phật Chiếu',
    worship_tower: '',
    birth_death_time: ['1121', '1203'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: 'China',
    place: 'chùa Dục Vương',
    teachers: ['Dahui Zonggao'],
    successors: [''],
    disciples: ['Jingshan Ruyan (–1225)', 'Pojian Jujian/Bojian Jujian - Bắc Nhàn Cư Giản (1164–1246)', 'Triết Ông Như Diễm', 'Wuji Liaopai - Vô Tế Liễu Phái (1149–1224)'],
    image: '/images/avatar.png',
    reference: ['https://vi.m.wikipedia.org/wiki/Chuy%E1%BA%BFt_Am_%C4%90%E1%BB%A9c_Quang',],
  },
  {
    id: '50.17.4',
    name_en: 'Lingyin Daoji',
    other_name_en: 'Jigong',
    original_name_en: 'Li Xiuyuan',
    name_ja: '済公 道済',
    name_zh: '濟公 道濟',
    pinyin: '',
    name_vi: 'Linh Ẩn Đạo Tế',
    original_name_vi: 'Lý Tu Duyên',
    other_name_vi: '',
    nickname_vi: 'Tế Công, Tế điên',
    worship_tower: '',
    birth_death_time: ['22-12-1130/1148', '16-5-1209'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: 'China',
    place: 'Lingyin Temple',
    death_place: 'Jingci Temple, Hangzhou, Southern Song',
    teachers: ['Xiatang Huiyuan'],
    successors: [''],
    disciples: [],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Daoji.JPG/250px-Daoji.JPG',
    reference: ['https://vi.wikipedia.org/wiki/T%E1%BA%BF_C%C3%B4ng', 'https://terebess.hu/zen/mesterek/Jigong.html',
      'https://en.wikipedia.org/wiki/Ji_Gong', 'http://en.lingyinsi.org/list_224.html',
      'https://liefintaiwan.wordpress.com/2008/07/08/ji-gong%E9%81%93%E6%BF%9F%E7%A6%AA%E5%B8%AB-%E6%BF%9F%E5%85%ACthe-drunk-monka-bit-more/',
      'https://chinesemartialstudies.com/2015/03/14/ji-gong-the-adventures-of-a-mad-monk-in-chinese-martial-arts-fiction/'
    ],
  },
  {
    id: '50.17.5',
    name_en: 'Yushan Shiti',
    name_ja: 'Yushan Shiti',
    name_zh: '玉山師體',
    pinyin: '',
    name_vi: 'Vương Sơn Tăng Thế',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: ['Caodong'],
    country: 'China',
    place: '-',
    teachers: ['Lingyan Sengbao'],
    successors: ['Xueyan Huiman'],
    disciples: ['Xueyan Huiman'],
    image: '/images/avatar.png',
    reference: ['',],
  },
  /*{
    id: '50.17.6',
    hasContent: true,
    name_en: '',
    name_ja: '',
    name_zh: '',
    pinyin: '',
    name_vi: 'Hối Am Di Quang',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: 'China',
    place: 'Giáo Trung',
    teachers: ['Dahui Zonggao'],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '50.17.7',
    hasContent: true,
    name_en: '',
    name_ja: '',
    name_zh: ' ',
    pinyin: '',
    name_vi: 'Vạn Am Đạo Nhan',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: 'China',
    place: 'Đông Lâm',
    teachers: ['Dahui Zonggao'],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '50.17.8',
    hasContent: true,
    name_en: '',
    name_ja: '',
    name_zh: ' ',
    pinyin: '',
    name_vi: 'Lại Am Đảnh Nhu',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: 'China',
    place: 'chùa Tây Thiền',
    teachers: ['Dahui Zonggao'],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '50.17.9',
    hasContent: true,
    name_en: '',
    name_ja: '',
    name_zh: ' ',
    pinyin: '',
    name_vi: 'Thử Am Thủ Tịnh',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: 'China',
    place: 'chùa Tây Thiền',
    teachers: ['Dahui Zonggao'],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '50.17.10',
    hasContent: true,
    name_en: '',
    name_ja: '',
    name_zh: ' ',
    pinyin: '',
    name_vi: 'Linh Nham Trung An',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: 'China',
    place: '-',
    teachers: ['Dahui Zonggao'],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '50.17.11',
    hasContent: true,
    name_en: '',
    name_ja: '',
    name_zh: ' ',
    pinyin: '',
    name_vi: 'Biệt Phong Bảo Ấn',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: 'China',
    place: 'Cảnh Sơn',
    teachers: ['Dahui Zonggao'],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: ['',],
  },*/
  {
    id: '50.17.12',
    hasContent: true,
    name_en: 'Zishou Miaozong',
    name_ja: 'Zishou Miaozong',
    name_zh: '妙總 無著',
    pinyin: '',
    name_vi: 'Diệu Tổng Vô Trước',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1095?', '1163/1170?'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: 'China',
    place: '',
    teachers: ['Dahui Zonggao'],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: ['https://vi.m.wikipedia.org/wiki/Di%E1%BB%87u_T%E1%BB%95ng_V%C3%B4_Tr%C6%B0%E1%BB%9Bc'],
  },
]
export default CnLv17MasterDb;
