const CnLv8MasterDb = [
  {
    id: '41.8.1',
    name_en: 'Fengxue Yanzhao',
    name_ja: 'Fuketsu Enshō',
    name_zh: '風穴延沼',
    name_vi: 'Phong Huyệt Diên Chiểu',
    birth_death_time: ['896', '973'],
    records: '',
    sect: ['Linji'],
    country: 'China',
    place: '-',
    teachers: ['Nanyuan Huiyong'],
    successors: ['Shoushan Xingnian'],
    disciples: ['Shoushan Xingnian'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/Phong_Huy%E1%BB%87t_Di%C3%AAn_Chi%E1%BB%83u', 'https://pl.wikipedia.org/wiki/Fengxue_Yanzhao',],

  },
  {
    id: '41.8.2',
    name_en: 'Luohan Guichen',
    name_ja: 'Rakan Keichin',
    other_name_ja: 'Keijin (Chizō)',
    name_zh: '羅漢桂琛',
    other_name_zh: '地藏',
    name_vi: 'La Hán Quế Sâm',
    other_name_vi: '',
    nickname_vi: 'Địa Tạng',
    worship_tower: '',
    birth_death_time: ['867', '928'],
    epoch: '',
    records: '',
    sect: ['-'],
    country: 'China',
    place: '-',
    teachers: ['Xuansha Shibei', 'Xuefeng Yicun'],
    successors: ['Fayan Wenyi'],
    disciples: ['Fayan Wenyi', 'Longji Shaoxiu', 'Tianbing Congyi', 'Qingqi Hongjin'],
    image: '/images/avatar.png',
    reference: ['https://terebess.hu/zen/luohan.html', 'https://quangduc.com/p156a69697/52/thien-su-la-han-que-sam-867-928-vi-thien-su-dat-nen-mong-cho-thien-phai-phap-nhan', 'https://vi.wikipedia.org/wiki/La_H%C3%A1n_Qu%E1%BA%BF_S%C3%A2m'],

  },
  {
    id: '41.8.3',
    name_en: 'Xianglin Chengyuan',
    name_ja: 'Kyōrin Chōon',
    name_zh: '香林澄遠',
    name_vi: 'Hương Lâm Trừng Viễn',
    birth_death_time: ['908', '987'],
    records: '',
    sect: ['Yunmen'],
    country: 'China',
    place: '-',
    teachers: ['Yunmen Wenyan'],
    successors: ['Zhimen Guangzuo'],
    disciples: ['Zhimen Guangzuo'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/H%C6%B0%C6%A1ng_L%C3%A2m_Tr%E1%BB%ABng_Vi%E1%BB%85n'],

  },
  {
    id: '41.8.4',
    name_en: 'Dongshan Shouchu',
    name_ja: 'Tōsan Shusho',
    name_zh: '洞山守初',
    name_vi: 'Động Sơn Thủ Sơ',
    birth_death_time: ['910', '990'],
    records: '',
    sect: ['Yunmen'],
    country: 'China',
    place: '-',
    teachers: ['Yunmen Wenyan'],
    successors: ['Fuyan Liangya'],
    disciples: ['Fuyan Liangya'],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '41.8.5',
    name_en: 'Deshan Yuanmi',
    name_ja: 'Tokusan Emmitsu',
    name_zh: '德山緣密',
    name_vi: 'Đức Sơn Duyên Mật',
    birth_death_time: ['', ''],
    records: '',
    sect: ['Yunmen'],
    country: 'China',
    place: '-',
    teachers: ['Yunmen Wenyan'],
    successors: ['Wenshu Yingzhen'],
    disciples: ['Wenshu Yingzhen'],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '41.8.6',
    name_en: 'Shuangquan Renyu',
    name_ja: 'Shuangquan Renyu',
    name_zh: '雙泉仁郁',
    name_vi: 'Song Tuyền Nhân Úc',
    birth_death_time: ['', ''],
    records: '',
    sect: ['Yunmen'],
    country: 'China',
    place: '-',
    teachers: ['Yunmen Wenyan'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '41.8.7',
    name_en: 'Baling Haojian',
    name_ja: 'Baling Haojian',
    name_zh: '巴陵顥鑒',
    name_vi: 'Ba Lăng Hạo Giám',
    birth_death_time: ['', ''],
    records: '',
    sect: ['Yunmen'],
    country: 'China',
    place: '-',
    teachers: ['Yunmen Wenyan'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '41.8.8',
    name_en: 'Fengxian Daoshen',
    name_ja: 'Hōsen Dōshin',
    name_zh: '奉先道深',
    name_vi: 'Phụng Tiên Đạo Thâm',
    birth_death_time: ['', ''],
    records: '',
    sect: ['Yunmen'],
    country: 'China',
    place: '-',
    teachers: ['Yunmen Wenyan'],
    successors: [''],
    disciples: ['Lianhua Fengxiang', 'Xiang Anzhu'],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Fengxian_Daoshen'],
  },
  {
    id: '41.8.9',
    name_en: 'Tongan Guanzhi',
    name_ja: 'Dōan Kanshi',
    name_zh: '同安觀志',
    name_vi: 'Đồng An Quán Chí',
    birth_death_time: ['910', '970'],
    records: '',
    sect: ['Caodong'],
    country: 'China',
    place: '-',
    teachers: ['Tongan Daopi'],
    successors: ['Liangshan Yuanguan'],
    disciples: ['Liangshan Yuanguan'],
    image: '/images/avatar.png',
    reference: ['https://en.wikipedia.org/wiki/Tongan_Guanzhi', 'https://vi.wikipedia.org/wiki/%C4%90%E1%BB%93ng_An_Qu%C3%A1n_Ch%C3%AD',
    'https://pl.wikipedia.org/wiki/Tong%E2%80%99an_Guanzhi'],
  },
  {
    id: '41.8.10',
    name_en: 'Mingzhao Deqian',
    name_ja: 'Myōshō Tokke',
    name_zh: '明招德謙',
    name_vi: 'Minh Chiêu Đức Khiêm',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'China',
    place: 'Mingzhao Shan - Minh Chiêu Sơn (明招山)',
    teachers: ['Luoshan Daoxian'],
    successors: ['Baoen Qicong'],
    disciples: ['Baoen Qicong'],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Mingzhao_Deqian', 'https://phatgiao.org.vn/tu-dien-phat-hoc-online/minh-chieu-duc-khiem-k4536.html', 'https://tangthuphathoc.net/thuat_ngu/minh-chieu-duc-khiem-tu-dien-dao-uyen', 'https://terebess.hu/zen/mesterek/mingzhao.pdf', 'https://terebess.hu/zen/mesterek/MingzhaoDeqian.html'],
  },
  {
    id: '41.8.11',
    name_en: 'Shuangquan Shikuang',
    name_ja: 'Sōsen Shikan',
    name_zh: '雙泉師寛',
    name_vi: 'Song Tuyền Sư Khoan',
    nickname_vi: 'Minh Giáo',
    birth_death_time: ['', ''],
    records: '',
    sect: ['Yunmen'],
    country: 'China',
    place: 'Shuangquan Temple (雙泉寺), Suizhou (隨州), Hubei province)',
    teachers: ['Yunmen Wenyan'],
    successors: ['Wuzu Shijie'],
    disciples: ['Wuzu Shijie'],
    image: '/images/avatar.png',
    reference: ['https://phatgiao.org.vn/tu-dien-phat-hoc-online/song-tuyen-su-khoan-k5150.html'],
  },
  {
    id: '41.8.12',
    name_en: 'Guizhen Deshao',
    name_ja: 'Guizhen Deshao',
    name_zh: '归真德韶',
    name_vi: 'Quý Trân Đức Thiều',
    nickname_vi: '',
    birth_death_time: ['', ''],
    records: '',
    sect: ['Guiyang'],
    country: 'China',
    place: '',
    teachers: ['Zifu Rubao'],
    successors: ['Sanjiao Zhiqian'],
    disciples: ['Sanjiao Zhiqian'],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Guizhen_Deshao'],
  },
  {
    id: '41.8.13',
    name_en: 'Xingyang Qingrang',
    name_ja: 'Kōyō Seijō',
    name_zh: '興陽清讓',
    name_vi: 'Hưng Dương Thanh Nhường',
    nickname_vi: '',
    birth_death_time: ['', ''],
    records: '',
    sect: ['Guiyang'],
    country: 'China',
    place: '',
    teachers: ['Bajiao Huiqing'],
    successors: [''],
    disciples: [''],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Xingyang_Qingrang'],
  },
]
export default CnLv8MasterDb;
