const CnLv27MasterDb = [
  {
    id: '60.27.1',
    name_en: 'Wufang Kecong',
    name_ja: 'Wufang Kecong',
    name_zh: '無方可從',
    name_vi: 'Vô Phương Khả Tùng',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1420', '1483'],
    epoch: '',
    records: '',
    sect: ['Caodong'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Jukong Qibin'],
    successors: ['Yuezhou Wenzai'],
    disciples: ['Yuezhou Wenzai'],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '60.27.2',
    name_en: 'Dongming Huichan',
    other_name_en: 'Xubai Huichan',
    name_ja: 'Kihaku Egaku',
    name_zh: '東明慧旵',
    other_name_zh: '虗白慧旵',
    name_vi: 'Đông Minh Huệ Sâm',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1372', '1441'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: '🇨🇳',
    place: '-',
    teachers: ['Baozang Puchi'],
    successors: ['Haizhou Puci'],
    disciples: ['Haizhou Puci'],
    image: '/images/avatar.png',
    reference: [''],
  }
]
export default CnLv27MasterDb;
