const CnLv7MasterDb = [
  {
    id: '40.7.1',
    generation: '40',
    name_en: 'Nanyuan Huiyong',
    name_es: 'Nanyuan Huiyong',
    name_de: 'Nanyuan Huiyong',
    name_fr: 'Nanyuan Huiyong',
    name_vi: 'Nam Viện Huệ Ngung',
    name_ru: 'Nanyuan Huiyong',
    name_zh: '南院慧顒',
    name_ja: 'Nanin Egyō',
    name_ko: 'Nanyuan Huiyong',
    name_ar: 'Nanyuan Huiyong',
    birth_death_time: ['860', '950'],
    records: '',
    sect: 'Linji',
    country: 'China',
    place: '-',
    teachers: ['Xinghua Cunjiang'],
    successors: ['Fengxue Yanzhao'],
    disciples: ['Fengxue Yanzhao'],
    image: '/images/avatar.png',
    reference: ['https://terebess.hu/zen/nanyuan.html',],

  },
  {
    id: '40.7.2',
    generation: '40',
    hasContent: true,
    name_en: 'Heshan Wuyin',
    name_es: 'Heshan Wuyin',
    name_de: 'Heshan Wuyin',
    name_fr: 'Heshan Wuyin',
    name_vi: 'Hòa Sơn Vô Ân',
    name_ru: 'Heshan Wuyin',
    name_zh: '禾山無殷',
    name_ja: 'Kasan Muin',
    name_ko: 'Heshan Wuyin',
    name_ar: 'Heshan Wuyin',
    birth_death_time: ['884', '960'],
    records: '',
    sect: '-',
    country: 'China',
    place: '-',
    teachers: ['Jiufeng Daoqian', 'Xuefeng Yicun'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://terebess.hu/zen/mesterek/heshan.html',],

  },
  {
    id: '40.7.3',
    generation: '40',
    hasContent: true,
    name_en: 'Xuansha Shibei',
    name_es: 'Xuansha Shibei',
    name_de: 'Xuansha Shibei',
    name_fr: 'Xuansha Shibei',
    name_vi: 'Huyền Sa Sư Bị',
    name_ru: 'Xuansha Shibei',
    name_zh: '玄沙師備',
    name_ja: 'Gensha Shibi',
    name_ko: 'Xuansha Shibei',
    name_ar: 'Xuansha Shibei',
    birth_death_time: ['835', '908'],
    records: '',
    sect: '-',
    country: 'China',
    place: '-',
    teachers: ['Xuefeng Yicun'],
    successors: [''],
    disciples: [],
    image: 'https://upload.wikimedia.org/wikipedia/commons/7/7d/Hszuan_sa_Si_pej835-890.jpg',
    reference: ['https://terebess.hu/zen/xuansha.html',],
  },
  {
    id: '40.7.4',
    generation: '40',
    hasContent: true,
    name_en: 'Yunmen Wenyan',
    name_es: 'Yunmen Wenyan',
    name_de: 'Yunmen Wenyan',
    name_fr: 'Yunmen Wenyan',
    name_vi: 'Vân Môn Văn Yển',
    name_ru: 'Yunmen Wenyan',
    name_zh: '雲門文偃',
    name_ja: 'Ummon Bunen',
    name_ko: 'Yunmen Wenyan',
    name_ar: 'Yunmen Wenyan',
    birth_death_time: ['862/864', '949'],
    records: '',
    sect: 'Yunmen',
    country: 'China',
    place: '-',
    teachers: ['Xuefeng Yicun'],
    successors: [''],
    disciples: ['Song Tuyền Nhân Úc (雙泉仁郁)', 'Song Phong Quảng Ngộ (雙峰竟欽)', 'Phụng Tiên Đạo Thâm (奉先道琛)',
      'Baling Haojian - Ba Lăng Hạo Giám (巴陵顥鑒)', ' Động Sơn Thủ Sơ (洞山守初)', 'Đức Sơn Duyên Mật (德山縁密)', 'Song Tuyền Sư Khoan (雙泉師寛)',
      'Hương Lâm Trừng Viễn (奉先道琛)',],
    image: '/images/avatar.png',
    reference: ['https://terebess.hu/zen/mesterek/Yunmen.pdf', 'https://terebess.hu/zen/yunmen.html', 'https://en.wikipedia.org/wiki/Yunmen_Wenyan'],
  },
  {
    id: '40.7.5',
    generation: '40',
    hasContent: true,
    name_en: 'Baofu Congzhan',
    name_es: 'Baofu Congzhan',
    name_de: 'Baofu Congzhan',
    name_fr: 'Baofu Congzhan',
    name_vi: 'Bảo Phúc Tùng Triển (Bảo Phước Tòng Triển)',
    name_ru: 'Baofu Congzhan',
    name_zh: '保福從展',
    name_ja: 'Hōfuku Jūten',
    name_ko: '보복종전 Pobok Chongjŏn',
    name_ar: 'Baofu Congzhan',
    birth_death_time: ['860?', '928'],
    records: '',
    sect: '-',
    country: 'China',
    place: '-',
    teachers: ['Xuefeng Yicun'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://terebess.hu/zen/baofu.html',],
  },
  {
    id: '40.7.6',
    generation: '40',
    name_en: 'Changqing Huileng',
    name_es: 'Changqing Huileng',
    name_de: 'Changqing Huileng',
    name_fr: 'Changqing Huileng',
    name_vi: 'Trường Khánh Huệ Lăng',
    name_ru: 'Changqing Huileng',
    name_zh: '長慶慧稜',
    name_ja: 'Chōkei Eryō',
    name_ko: 'Changqing Huileng',
    name_ar: 'Changqing Huileng',
    birth_death_time: ['854', '932'],
    records: '',
    sect: '-',
    country: 'China',
    place: '-',
    teachers: ['Xuefeng Yicun'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://terebess.hu/zen/changqing.html', 'https://vi.wikipedia.org/wiki/Tr%C6%B0%E1%BB%9Dng_Kh%C3%A1nh_Hu%E1%BB%87_L%C4%83ng',],
  },
  {
    id: '40.7.7',
    generation: '40',
    name_en: 'Tongan Daopi',
    name_es: 'Tongan Daopi',
    name_de: 'Tongan Daopi',
    name_fr: 'Tongan Daopi',
    name_vi: 'Đồng An Đạo Phi',
    name_ru: 'Tongan Daopi',
    name_zh: '同安道丕',
    name_ja: 'Dōan Dōhi',
    name_ko: '동안도비 Tongan Tobi',
    name_ar: 'Tongan Daopi',
    birth_death_time: ['854', '932'],
    records: '',
    sect: '-',
    country: 'China',
    place: '-',
    teachers: ['Yunju Daoying'],
    successors: ['Tongan Guanzhi'],
    disciples: ['Tongan Guanzhi'],
    image: 'https://terebess.hu/zen/mesterek/woodcut/288.jpg',
    reference: ['https://terebess.hu/zen/mesterek/TonganDaopi.html', 'https://en.wikipedia.org/wiki/Tongan_Daopi', 'https://vi.wikipedia.org/wiki/%C4%90%E1%BB%93ng_An_%C4%90%E1%BA%A1o_Phi'],
  },
  {
    id: '40.7.8',
    generation: '40',
    name_en: 'Xiyuan Siming',
    name_es: 'Xiyuan Siming',
    name_de: 'Xiyuan Siming',
    name_fr: 'Xiyuan Siming',
    name_vi: 'Tây Viện Tư Minh',
    name_ru: 'Xiyuan Siming',
    name_zh: '西院思明',
    name_ja: 'Saiin Shimyō',
    name_ko: '서원사명 Sŏwon Samyŏng',
    name_ar: 'Xiyuan Siming',
    birth_death_time: ['', ''],
    records: '',
    sect: '-',
    country: 'China',
    place: '-',
    teachers: ['Baoshou Yanzhao'],
    successors: [''],
    disciples: [''],
    image: '',
    reference: ['https://pl.wikipedia.org/wiki/Xiyuan_Siming', 'https://phatgiao.org.vn/tu-dien-phat-hoc-online/tay-vien-tu-minh-k16819.html'],
  },
  {
    id: '40.7.9',
    generation: '40',
    name_en: 'Luoshan Daoxian',
    name_es: 'Luoshan Daoxian',
    name_de: 'Luoshan Daoxian',
    name_fr: 'Luoshan Daoxian',
    name_vi: 'La Sơn Đạo Nhàn',
    name_ru: 'Luoshan Daoxian',
    name_zh: '羅山道閑',
    name_ja: 'Rasan Dōkan',
    name_ko: '라산도한 Lasan Tohan',
    name_ar: 'Luoshan Daoxian',
    birth_death_time: ['', ''],
    records: '',
    sect: '-',
    country: 'China',
    place: '-',
    teachers: ['Yantou Quanhuo'],
    successors: ['Mingzhao Deqian'],
    disciples: ['Mingzhao Deqian', 'Daning Daokuan', 'Zingbing (845–919)'],
    image: '',
    reference: ['https://pl.wikipedia.org/wiki/Luoshan_Daoxian', 'https://daophatkhatsi.vn/an-pham/dich-pham/thien-ngo-phan-6.html&page=1?yy=2025&mm=2'],
  },
]
export default CnLv7MasterDb;
