const CnLv25MasterDb = [
  {
    id: '58.25.1',
    name_en: 'Ningran Liaogai',
    name_es: 'Ningran Liaogai',
    name_de: 'Ningran Liaogai',
    name_fr: 'Ningran Liaogai',
    name_vi: 'Ningran Liaogai',
    name_ru: 'Ningran Liaogai',
    name_zh: '凝然了改',
    name_ja: 'Ningran Liaogai',
    name_ko: 'Ningran Liaogai',
    name_ar: 'Ningran Liaogai',
    birth_death_time: ['1335', '1421'],
    records: '',
    sect: ['Caodong'],
    country: 'China',
    place: '-',
    teachers: ['Songting Ziyan'],
    successors: ['Jukong Qibin'],
    disciples: ['Jukong Qibin'],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/Ng%C6%B0ng_Nhi%C3%AAn_Li%E1%BB%85u_C%E1%BA%A3i'],
  },
]
export default CnLv25MasterDb;
