const InMasterDb = [
  {
    id: '0',
    hasContent: true,
    name_en: 'Shakyamuni Buddha',
    name_ja: 'Shakyamuni Buddha',
    name_zh: '释迦牟尼 佛',
    name_vi: 'Thích Ca Mâu Ni Phật',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    sect: [],
    country: '🇮🇳',
    place: '-',
    teachers: [],
    successors: ['Mahakasyapa'],
    disciples: ['Mahakasyapa'],
    image: '/images/avatar.png',
    reference: ['https://en.wikipedia.org/wiki/The_Buddha',],
  },
  {
    id: '1',
    hasContent: true,
    name_en: 'Mahakasyapa',
    name_ja: 'Makakashō',
    name_zh: '摩訶迦葉',
    name_vi: 'Ma-Ha-Ca-Diếp',
    other_name_vi: '',
    nickname_vi: 'Ẩm Quang',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    sect: [],
    country: '🇮🇳',
    place: '-',
    teachers: ['Shakyamuni Buddha'],
    successors: ['Ananda'],
    disciples: ['Ananda'],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '2',
    hasContent: true,
    name_en: 'Ananda',
    name_ja: 'Ananda',
    name_zh: '阿難陀',
    name_vi: 'A-Nan',
    other_name_vi: '',
    nickname_vi: 'Khánh Hỷ',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    sect: [],
    country: '🇮🇳',
    place: '-',
    teachers: ['Mahakasyapa'],
    successors: ['Sanakavasa'],
    disciples: ['Sanakavasa'],
    image: '/images/avatar.png',
    reference: ['',],

  },
  {
    id: '3',
    hasContent: true,
    name_en: 'Sanakavasa',
    name_ja: 'Shōnawashu',
    name_zh: '商那和修',
    name_vi: 'Thương-Na-Hòa-Tu',
    other_name_vi: '',
    nickname_vi: 'Tự Nhiên Phục',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    sect: [],
    country: '🇮🇳',
    place: '-',
    teachers: ['Ananda'],
    successors: ['Upagupta'],
    disciples: ['Upagupta'],
    image: '/images/avatar.png',
    reference: ['',],

  },
  {
    id: '4',
    hasContent: true,
    name_en: 'Upagupta',
    name_ja: 'Ubakikuta',
    name_zh: '優婆掬多',
    name_vi: 'Ưu-Ba-Cúc-Đa',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    sect: [],
    country: '🇮🇳',
    place: '-',
    teachers: ['Sanakavasa'],
    successors: ['Dhrtaka'],
    disciples: ['Dhrtaka'],
    image: '/images/avatar.png',
    reference: ['',],

  },
  {
    id: '5',
    hasContent: true,
    name_en: 'Dhrtaka',
    name_ja: 'Daitaka',
    name_zh: '提多迦',
    name_vi: 'Đề-Đa-Ca',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    sect: [],
    country: '🇮🇳',
    place: '-',
    teachers: ['Upagupta'],
    successors: ['Miccaka'],
    disciples: ['Miccaka'],
    image: '/images/avatar.png',
    reference: ['',],

  },
{
    id: '6',
    hasContent: true,
    name_en: 'Miccaka',
    name_ja: 'Mishaka',
    name_zh: '彌遮迦',
    name_vi: 'Di-Dá-Ca',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    sect: [],
    country: '🇮🇳',
    place: '-',
    teachers: ['Dhrtaka'],
    successors: ['Vasumitra'],
    disciples: ['Vasumitra'],
    image: '/images/avatar.png',
    reference: ['',],

  },
{
    id: '7',
    hasContent: true,
    name_en: 'Vasumitra',
    name_ja: 'Bashumitsu',
    other_name_ja: 'Bashumitta',
    name_zh: '婆須密',
    other_name_zh: '婆須密多',
    name_vi: 'Bà-Tu-Mật',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    sect: [],
    country: '🇮🇳',
    place: '-',
    teachers: ['Miccaka'],
    successors: ['Buddhanandi'],
    disciples: ['Buddhanandi'],
    image: '/images/avatar.png',
    reference: ['',],

  },
  {
    id: '8',
    hasContent: true,
    name_en: 'Buddhanandi',
    name_ja: 'Buddanandai',
    name_zh: '浮陀難提',
    name_vi: 'Phật-Đà-Nan-Đề',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    sect: [],
    country: '🇮🇳',
    place: '-',
    teachers: ['Vasumitra'],
    successors: ['Buddhamitra'],
    disciples: ['Buddhamitra'],
    image: '/images/avatar.png',
    reference: ['',],

  },
  {
    id: '9',
    hasContent: true,
    name_en: 'Buddhamitra',
    name_ja: 'Buddamitta',
    name_zh: '浮陀密多',
    name_vi: 'Phục-Đà-Mật-Đa',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    sect: [],
    country: '🇮🇳',
    place: ' mountain',
    teachers: ['Buddhanandi'],
    successors: ['Parsvika'],
    disciples: ['Parsvika'],
    image: '/images/avatar.png',
    reference: ['',],

  },
  {
    id: '10',
    hasContent: true,
    name_en: 'Parsvika',
    name_ja: 'Barishiba',
    other_nname_ja: 'Kyōsonja',
    name_zh: '脅尊者',
    other_nname_zh: '波栗濕縛, 婆栗濕婆',
    name_vi: 'Ba-Lật-Thấp-Phược',
    other_name_vi: 'Bà-Lật-Thấp-Bà',
    nickname_vi: 'Hiếp-Tôn-Giả',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    sect: [],
    country: '🇮🇳',
    place: '-',
    teachers: ['Buddhamitra'],
    successors: ['Punyayasas'],
    disciples: ['Punyayasas'],
    image: '/images/avatar.png',
    reference: ['',],

  },
  {
    id: '11',
    hasContent: true,
    name_en: 'Punyayasas',
    name_ja: 'Funayasha',
    name_zh: '富那夜奢',
    name_vi: 'Phú-Na-Dạ-Xa',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    sect: [],
    country: '🇮🇳',
    place: '-',
    teachers: ['Parsvika'],
    successors: ['Asvaghosha'],
    disciples: ['Asvaghosha'],
    image: '/images/avatar.png',
    reference: ['',],

  },
  {
    id: '12',
    name_en: 'Asvaghosha',
    name_ja: 'Anabotei',
    other_name_ja: 'Memyō',
    name_zh: '阿那菩提',
    other_name_zh: '馬鳴',
    name_vi: 'A-Na-Bồ-Đề',
    other_name_vi: '',
    nickname_vi: 'Mã-Minh',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    sect: [],
    country: '🇮🇳',
    place: '-',
    teachers: ['Punyayasas'],
    successors: ['Kapimala'],
    disciples: ['Kapimala'],
    image: '/images/avatar.png',
    reference: ['',],

  },
  {
    id: '13',
    name_en: 'Kapimala',
    name_ja: 'Kabimora',
    other_name_ja: 'Kabimara',
    name_zh: '迦毘摩羅',
    name_vi: 'Ca-Tỳ-Ma-La',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    sect: [],
    country: '🇮🇳',
    place: '-',
    teachers: ['Asvaghosha'],
    successors: ['Nagarjuna'],
    disciples: ['Nagarjuna'],
    image: '/images/avatar.png',
    reference: ['',],

  },
  {
    id: '14',
    name_en: 'Nagarjuna',
    name_ja: 'Na-Già-Át-Lạt-Thụ-Na',
    name_zh: '那伽閼剌樹那 (龍樹)',
    name_vi: 'Long-Thọ',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    sect: [],
    country: '🇮🇳',
    place: '-',
    teachers: ['Kapimala'],
    successors: ['Kanadeva'],
    disciples: ['Kanadeva'],
    image: '/images/avatar.png',
    reference: ['',],

  },
  {
    id: '15',
    name_en: 'Kanadeva',
    name_ja: 'Kanadaiba',
    name_zh: '迦那提婆',
    name_vi: 'Ca-Na-Đề-Bà',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    sect: [],
    country: '🇮🇳',
    place: '-',
    teachers: ['Nagarjuna'],
    successors: ['Rahulata'],
    disciples: ['Rahulata'],
    image: '/images/avatar.png',
    reference: ['',],

  },
{
    id: '16',
    name_en: 'Rahulata',
    name_zh: '羅睺羅多',
    name_ja: 'Ragorata',
    name_vi: 'La-Hầu-La-Đa',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    sect: [],
    country: '🇮🇳',
    place: '-',
    teachers: ['Kanadeva'],
    successors: ['Sanghanandi'],
    disciples: ['Sanghanandi'],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '17',
    name_en: 'Sanghanandi',
    name_ja: 'Sōgyanandai',
    name_zh: '僧伽難提',
    name_vi: 'Tăng Già Nan Đề',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    sect: [],
    country: '🇮🇳',
    place: '-',
    teachers: ['Rahulata'],
    successors: ['Gayasata'],
    disciples: ['Gayasata'],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '18',
    name_en: 'Gayasata',
    name_ja: 'Sōgyayasha',
    name_zh: '僧伽舍多',
    name_vi: 'Già Da Xá Đa',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    sect: [],
    country: '🇮🇳',
    place: '-',
    teachers: ['Sanghanandi'],
    successors: ['Kumarata'],
    disciples: ['Kumarata'],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '19',
    name_en: 'Kumarata',
    name_ja: '',
    other_name_ja: 'Kumarata',
    name_zh: '鳩摩羅多',
    name_vi: 'Cưu-Ma-La-Đa',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    sect: [],
    country: '🇮🇳',
    place: '-',
    teachers: ['Gayasata'],
    successors: ['Jayata'],
    disciples: ['Jayata'],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '20',
    name_en: 'Jayata',
    name_ja: 'Shayata',
    name_zh: '闍夜多',
    name_vi: 'Xà Dạ Đa',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    sect: [],
    country: '🇮🇳',
    place: '-',
    teachers: ['Kumarata'],
    successors: ['Vasubandhu'],
    disciples: ['Vasubandhu'],
    image: '/images/avatar.png',
    reference: ['',],
  },
{
    id: '21',
  name_en: 'Vasubandhu',
    name_vi: 'Bà-Tu-Bàn-Đầu (Thế-Thân)',
    name_zh: '婆修盤頭 (世親)',
    name_ja: 'Bashubanzu (Sejin)',
    birth_death_time: ['', ''],
    sect: [],
    country: '🇮🇳',
    place: '-',
    teachers: ['Jayata'],
    successors: ['Manorhita'],
    disciples: ['Manorhita'],
    image: '/images/avatar.png',
    reference: ['',],
  },
{
    id: '22',
    name_en: 'Manorhita',
    name_ja: 'Manura',
    name_zh: '摩拏羅',
    name_vi: 'Ma-Noa-La',
    birth_death_time: ['', ''],
    sect: [],
    country: '🇮🇳',
    place: '-',
    teachers: ['Vasubandhu'],
    successors: ['Haklena'],
    disciples: ['Haklena'],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '23',
    name_en: 'Haklenayaśas',
    name_ja: 'Kakurokuna (Kakurokunayasha)',
    name_zh: '鶴勒那 (鶴勒那夜奢) ',
    name_vi: 'Hạc-Lặc-Na',
    birth_death_time: ['', ''],
    sect: [],
    country: '🇮🇳',
    place: '-',
    teachers: ['Manorhita'],
    successors: ['Aryasimha'],
    disciples: ['Aryasimha'],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '24',
    name_en: 'Simhabodhi',
    other_name_en: 'Aryasimha',
    name_zh: '師子菩提',
    name_ja: 'Shishibodai',
    name_vi: 'Sư Tử Bồ Đề',
    other_name_vi: 'Sư Tử Trí',
    birth_death_time: ['', ''],
    sect: [],
    country: '🇮🇳',
    place: '-',
    teachers: ['Haklena'],
    successors: ['Basiasita'],
    disciples: ['Basiasita', 'Đạt Ma Đạt',],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '25.1',
    name_en: 'Basiasita',
    other_name_en: 'Vasiasita',
    name_ja: 'Bashashita',
    name_zh: '婆舍斯多',
    name_vi: 'Bà-Xá-Tư-Đa',
    birth_death_time: ['', ''],
    sect: [],
    country: '🇮🇳',
    place: '-',
    teachers: ['Aryasimha/Simhabodhi'],
    successors: ['Punyamitra'],
    disciples: ['Punyamitra'],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '25.2',
    name_en: 'Dharmadha',
    name_ja: 'Dharmadha',
    name_zh: 'Dharmadha',
    name_vi: 'Đạt Ma Đạt',
    birth_death_time: ['', ''],
    sect: [],
    country: '🇮🇳',
    place: '-',
    teachers: ['Aryasimha'],
    successors: [''],
    disciples: ['Nhân Đà La', 'Cù La Kỵ Lợi Bà'],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '26.1',
    name_en: 'Punyamitra',
    name_ja: 'Funyomitta',
    name_zh: '不如密多',
    name_vi: 'Bất-Như-Mật-Đa',
    birth_death_time: ['', ''],
    sect: [],
    country: '🇮🇳',
    place: '-',
    teachers: ['Basiasita'],
    successors: ['Prajnatara'],
    disciples: ['Prajnatara'],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '26.2',
    name_en: 'Nhân Đà La',
    name_ja: 'Nhân Đà La',
    name_zh: 'Nhân Đà La',
    name_vi: 'Nhân Đà La',
    birth_death_time: ['', ''],
    sect: [],
    country: '🇮🇳',
    place: '-',
    teachers: ['Đạt Ma Đạt'],
    successors: [''],
    disciples: ['Đạt Ma Thi Lợi Đế', 'Na Già Nan Đề', 'Phú Lâu Cầu Đa La', 'Ba La Bà Đề'],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '26.3',
    name_en: 'Cù La Kỵ Lợi Bà',
    name_ja: 'Cù La Kỵ Lợi Bà',
    name_zh: 'Cù La Kỵ Lợi Bà',
    name_vi: 'Cù La Kỵ Lợi Bà',
    birth_death_time: ['', ''],
    sect: [],
    country: '🇮🇳',
    place: '-',
    teachers: ['Đạt Ma Đạt'],
    successors: [],
    disciples: ['Bà La Bạt Ma', 'Tăng Già La Xoa'],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '27.1',
    name_en: 'Prajnatara',
    name_ja: 'Hannyatara',
    name_zh: '般若多羅',
    name_vi: 'Bát-Nhã-Đa-La',
    birth_death_time: ['', ''],
    sect: [],
    country: '🇮🇳',
    place: '-',
    teachers: ['Punyamitra'],
    successors: ['Bodhidharma'],
    disciples: ['Bodhidharma'],
    image: '/images/avatar.png',
    reference: ['',],
  },
{
    id: '27.2',

    name_en: 'Đạt Ma Thi Lợi Đế',
    name_ja: 'Đạt Ma Thi Lợi Đế',
    name_zh: 'Đạt Ma Thi Lợi Đế',
    name_vi: 'Đạt Ma Thi Lợi Đế',
  birth_death_time: ['', ''],
    sect: [],
    country: '🇮🇳',
    place: '-',
    teachers: ['Nhân Đà La'],
    successors: [''],
    disciples: ['Ma Đế Lệ Bạt La / Ma Đế Lệ Phi La', 'A Lợi Bạt Mâu / Ha Lợi Bạt Mậu'],
    image: '/images/avatar.png',
    reference: ['',],
  },
{
    id: '27.3',

    name_en: 'Phá Lâu Cầu Đa La',
    name_ja: 'Phá Lâu Cầu Đa La',
    name_zh: 'Phá Lâu Cầu Đa La',
    name_vi: 'Phá Lâu Cầu Đa La',
    birth_death_time: ['', ''],
    sect: [],
    country: '🇮🇳',
    place: '-',
    teachers: ['Nhân Đà La'],
    successors: [''],
    disciples: ['Hòa Tu Bàn Đầu', 'Đạt Ma Kha Đế', 'Chiên Đà La Đa Ba'],
    image: '/images/avatar.png',
    reference: ['',],
  },
{
    id: '27.4',

    name_en: 'Ba La Bạt Ma',
    name_ja: 'Ba La Bạt Ma',
    name_zh: 'Ba La Bạt Ma',
    name_vi: 'Ba La Bạt Ma',
    birth_death_time: ['', ''],
    sect: [],
    country: '🇮🇳',
    place: '-',
    teachers: ['Cù La Kỵ Lợi Bà'],
    successors: [''],
    disciples: ['Lặc/Nặc La Đa La', 'Bàn Đầu Đa La', 'Bà Ba Bà La / Bà La Bà Đa'],
    image: '/images/avatar.png',
    reference: ['',],
  },
{
    id: '27.5',

    name_en: 'Tăng Già La Xoa',
    name_ja: 'Tăng Già La Xoa',
    name_zh: 'Tăng Già La Xoa',
    name_vi: 'Tăng Già La Xoa',
    birth_death_time: ['', ''],
    sect: [],
    country: '🇮🇳',
    place: '-',
    teachers: ['Cù La Kỵ Lợi Bà'],
    successors: [''],
    disciples: ['Tì Xá Dã Đa La', 'Tì Lâu La Đa Ma', 'Tì Túc Xô Đa La / Tỳ-lật-sô-đa-la', 'Ưu Bà Chiên Đà / Ưu-ba-thiên-đà', 'Bà Nan Đề Đa /  Bà-nan-đề-la'],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '28',
    hasContent: true,
    name_en: 'Bodhidharma',
    other_name_en: 'Bodaidaruma',
    name_ja: '達磨 だるま Daruma',
    name_zh: '菩提達磨',
    name_vi: 'Bồ-Đề-Đạt-Ma',
    birth_death_time: ['', ''],
    sect: [],
    country: '🇮🇳',
    place: 'Shaolin Temple, Songshan mountain, Dengfeng, Zhengzhou, Henan, 🇨🇳',
    teachers: ['Prajnatara'],
    successors: ['Dazu Huike'],
    disciples: ['Dazu Huike', 'Đạo Dục', 'Đạo Phó', 'Ni Tổng Trì', '6 Tôn giả đứng đầu 6 tông Hữu tướng, Vô tướng, Định tuệ, Giới hạnh, Vô đắc, Tịch tỉnh'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/BodhidharmaYoshitoshi1887.jpg/232px-BodhidharmaYoshitoshi1887.jpg',
    reference: ['',],
  },
  {
    id: '31.2',
    hasContent: true,
    name_en: 'Vinitaruci',
    other_name_en: 'Miexi',
    name_ja: '',
    name_zh: '毘尼多流支',
    name_vi: 'Tì-ni-đa-lưu-chi',
    other_name_vi: 'Diệt Hỉ',
    birth_death_time: ['', '594'],
    sect: ['Miexi'],
    country: '🇮🇳',
    place: '-',
    teachers: ['Jianzhi Sengcan'],
    successors: ['Zhongshan Faxian'],
    disciples: ['Zhongshan Faxian'],
    image: '/',
    reference: [''],
  },
  {
    id: '34.1.7',
    name_en: 'Tây Ấn Quật Đa Tam Tạng',
    name_ja: 'Tây Ấn Quật Đa Tam Tạng',
    name_zh: '西域崛多三藏',
    name_vi: 'Tây Ấn Quật Đa Tam Tạng',
    birth_death_time: ['', ''],
    records: '',
    sect: [],
    country: '🇮🇳',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
]
export default InMasterDb;
