const InMasterDb = [
{
    id: 1,
    name_en: 'Mahakasyapa',
    name_es: 'Mahakasyapa',
    name_de: 'Mahakasyapa',
    name_fr: 'Mahakasyapa',
    name_vi: 'Ma-Ha-Ca-Diếp',
    name_ru: 'Mahakasyapa',
    name_zh: 'Mahakasyapa',
    name_ja: 'Mahakasyapa',
    name_ko: 'Mahakasyapa',
    name_ar: 'Mahakasyapa',
    birth_death_time: '-',
    sect: '-',
    country: 'India',
    place: '-',
    teachers: ['Shakyamuni Buddha'],
    successors: ['Ananda'],
    disciples: [''],
    image: '/images/avatar.png'
  },
  {
    id: 2,
    name_en: 'Ananda',
    name_es: 'Ananda',
    name_de: 'Ananda',
    name_fr: 'Ananda',
    name_vi: 'A-Nan',
    name_ru: 'Ananda',
    name_zh: 'Ananda',
    name_ja: 'Ananda',
    name_ko: 'Ananda',
    name_ar: 'Ananda',
    birth_death_time: '-',
    sect: '-',
    country: 'India',
    place: '-',
    teachers: ['Mahakasyapa'],
    successors: ['Sanakavasa'],
    disciples: [],
    image: '/images/avatar.png'
  },
  {
    id: 3,
    name_en: 'Sanakavasa',
    name_es: 'Sanakavasa',
    name_de: 'Sanakavasa',
    name_fr: 'Sanakavasa',
    name_vi: 'Thương-Na-Hòa-Tu',
    name_ru: 'Sanakavasa',
    name_zh: 'Sanakavasa',
    name_ja: 'Sanakavasa',
    name_ko: 'Sanakavasa',
    name_ar: 'Sanakavasa',
    birth_death_time: '-',
    sect: '-',
    country: 'India',
    place: '-',
    teachers: ['Ananda'],
    successors: ['Upagupta'],
    disciples: [''],
    image: '/images/avatar.png',
  },
  {
    id: 4,
    name_en: 'Upagupta',
    name_es: 'Upagupta',
    name_de: 'Upagupta',
    name_fr: 'Upagupta',
    name_vi: 'Ưu-Ba-Cúc-Đa',
    name_ru: 'Upagupta',
    name_zh: 'Upagupta',
    name_ja: 'Upagupta',
    name_ko: 'Upagupta',
    name_ar: 'Upagupta',
    birth_death_time: '-',
    sect: '-',
    country: 'India',
    place: '-',
    teachers: ['Sanakavasa'],
    successors: ['Dhrtaka'],
    disciples: [''],
    image: '/images/avatar.png',
  },
  {
    id: 5,
    name_en: 'Dhrtaka',
    name_es: 'Dhrtaka',
    name_de: 'Dhrtaka',
    name_fr: 'Dhrtaka',
    name_vi: 'Đề-Đa-Ca',
    name_ru: 'Dhrtaka',
    name_zh: 'Dhrtaka',
    name_ja: 'Dhrtaka',
    name_ko: 'Dhrtaka',
    name_ar: 'Dhrtaka',
    birth_death_time: '-',
    sect: '-',
    country: 'India',
    place: '-',
    teachers: ['Upagupta'],
    successors: ['Miccaka'],
    disciples: [''],
    image: '/images/avatar.png',
  },
{
    id: 6,
    name_en: 'Miccaka',
    name_es: 'Miccaka',
    name_de: 'Miccaka',
    name_fr: 'Miccaka',
    name_vi: 'Di-Dá-Ca',
    name_ru: 'Miccaka',
    name_zh: 'Miccaka',
    name_ja: 'Miccaka',
    name_ko: 'Miccaka',
    name_ar: 'Miccaka',
    birth_death_time: '-',
    sect: '-',
    country: 'India',
    place: '-',
    teachers: ['Dhrtaka'],
    successors: ['Vasumitra'],
    disciples: [''],
    image: '/images/avatar.png',
  },
{
    id: 7,
    name_en: 'Vasumitra',
    name_es: 'Vasumitra',
    name_de: 'Vasumitra',
    name_fr: 'Vasumitra',
    name_vi: 'Bà-Tu-Mật',
    name_ru: 'Vasumitra',
    name_zh: 'Vasumitra',
    name_ja: 'Vasumitra',
    name_ko: 'Vasumitra',
    name_ar: 'Vasumitra',
    birth_death_time: '-',
    sect: '-',
    country: 'India',
    place: '-',
    teachers: ['Miccaka'],
    successors: ['Buddhanandi'],
    disciples: [''],
    image: '/images/avatar.png',
  },
  {
    id: 8,
    name_en: 'Buddhanandi',
    name_es: 'Buddhanandi',
    name_de: 'Buddhanandi',
    name_fr: 'Buddhanandi',
    name_vi: 'Phật-Đà-Nan-Đề',
    name_ru: 'Buddhanandi',
    name_zh: 'Buddhanandi',
    name_ja: 'Buddhanandi',
    name_ko: 'Buddhanandi',
    name_ar: 'Buddhanandi',
    birth_death_time: '-',
    sect: '-',
    country: 'India',
    place: '-',
    teachers: ['Vasumitra'],
    successors: ['Buddhamitra'],
    disciples: [''],
    image: '/images/avatar.png',
  },
  {
    id: 9,
    name_en: 'Buddhamitra',
    name_es: 'Buddhamitra',
    name_de: 'Buddhamitra',
    name_fr: 'Buddhamitra',
    name_vi: 'Phục-Đà-Mật-Đa',
    name_ru: 'Buddhamitra',
    name_zh: 'Buddhamitra',
    name_ja: 'Buddhamitra',
    name_ko: 'Buddhamitra',
    name_ar: 'Buddhamitra',
    birth_death_time: '-',
    sect: '-',
    country: 'India',
    place: ' mountain',
    teachers: ['Buddhanandi'],
    successors: ['Parsvika'],
    disciples: [''],
    image: '/images/avatar.png',
  },
  {
    id: 10,
    name_en: 'Parsvika',
    name_es: 'Parsvika',
    name_de: 'Parsvika',
    name_fr: 'Parsvika',
    name_vi: 'Hiếp-Tôn-Giả',
    name_ru: 'Parsvika',
    name_zh: 'Parsvika',
    name_ja: 'Parsvika',
    name_ko: 'Parsvika',
    name_ar: 'Parsvika',
    birth_death_time: '-',
    sect: '-',
    country: 'India',
    place: '-',
    teachers: ['Buddhamitra'],
    successors: ['Punyayasas'],
    disciples: [''],
    image: '/images/avatar.png',
  },
  {
    id: 11,
    name_en: 'Punyayasas',
    name_es: 'Punyayasas',
    name_de: 'Punyayasas',
    name_fr: 'Punyayasas',
    name_vi: 'Phú-Na-Dạ-Xa',
    name_ru: 'Punyayasas',
    name_zh: 'Punyayasas',
    name_ja: 'Punyayasas',
    name_ko: 'Punyayasas',
    name_ar: 'Punyayasas',
    birth_death_time: '-',
    sect: '-',
    country: 'India',
    place: '-',
    teachers: ['Parsvika'],
    successors: ['Asvaghosha'],
    disciples: [''],
    image: '/images/avatar.png',
  },
  {
    id: 12,
    name_en: 'Asvaghosha',
    name_es: 'Asvaghosha',
    name_de: 'Asvaghosha',
    name_fr: 'Asvaghosha',
    name_vi: 'Mã-Minh',
    name_ru: 'Asvaghosha',
    name_zh: 'Asvaghosha',
    name_ja: 'Asvaghosha',
    name_ko: 'Asvaghosha',
    name_ar: 'Asvaghosha',
    birth_death_time: '-',
    sect: '-',
    country: 'India',
    place: '-',
    teachers: ['Punyayasas'],
    successors: ['Kapimala'],
    disciples: [''],
    image: '/images/avatar.png',
  },
  {
    id: 13,
    name_en: 'Kapimala',
    name_es: 'Kapimala',
    name_de: 'Kapimala',
    name_fr: 'Kapimala',
    name_vi: 'Ca-Tỳ-Ma-La',
    name_ru: 'Kapimala',
    name_zh: 'Kapimala',
    name_ja: 'Kapimala',
    name_ko: 'Kapimala',
    name_ar: 'Kapimala',
    birth_death_time: '-',
    sect: '-',
    country: 'India',
    place: '-',
    teachers: ['Asvaghosha'],
    successors: ['Nagarjuna'],
    disciples: [''],
    image: '/images/avatar.png',
  },
  {
    id: 14,
    name_en: 'Nagarjuna',
    name_es: 'Nagarjuna',
    name_de: 'Nagarjuna',
    name_fr: 'Nagarjuna',
    name_vi: 'Long-Thọ',
    name_ru: 'Nagarjuna',
    name_zh: 'Nagarjuna',
    name_ja: 'Nagarjuna',
    name_ko: 'Nagarjuna',
    name_ar: 'Nagarjuna',
    birth_death_time: '-',
    sect: '-',
    country: 'India',
    place: '-',
    teachers: ['Kapimala'],
    successors: ['Kanadeva'],
    disciples: [''],
    image: '/images/avatar.png',
  },
  {
    id: 15,
    name_en: 'Kanadeva',
    name_es: 'Kanadeva',
    name_de: 'Kanadeva',
    name_fr: 'Kanadeva',
    name_vi: 'Ca-Na-Đề-Bà',
    name_ru: 'Kanadeva',
    name_zh: 'Kanadeva',
    name_ja: 'Kanadeva',
    name_ko: 'Kanadeva',
    name_ar: 'Kanadeva',
    birth_death_time: '-',
    sect: '-',
    country: 'India',
    place: '-',
    teachers: ['Nagarjuna'],
    successors: ['Rahulata'],
    disciples: [''],
    image: '/images/avatar.png',
  },
{
    id: 16,
    name_en: 'Rahulata',
    name_es: 'Rahulata',
    name_de: 'Rahulata',
    name_fr: 'Rahulata',
    name_vi: 'La-Hầu-La-Đa',
    name_ru: 'Rahulata',
    name_zh: 'Rahulata',
    name_ja: 'Rahulata',
    name_ko: 'Rahulata',
    name_ar: 'Rahulata',
    birth_death_time: '-',
    sect: '-',
    country: 'India',
    place: '-',
    teachers: ['Kanadeva'],
    successors: ['Sanghanandi'],
    disciples: [],
    dimage: '/images/avatar.png'
  },
  {
    id: 17,
    name_en: 'Sanghanandi',
    name_es: 'Sanghanandi',
    name_de: 'Sanghanandi',
    name_fr: 'Sanghanandi',
    name_vi: 'Tăng Già Nan Đề',
    name_ru: 'Sanghanandi',
    name_zh: 'Sanghanandi',
    name_ja: 'Sanghanandi',
    name_ko: 'Sanghanandi',
    name_ar: 'Sanghanandi',
    birth_death_time: '-',
    sect: '-',
    country: 'India',
    place: '-',
    teachers: ['Rahulata'],
    successors: ['Gayasata'],
    disciples: [],
    image: '/images/avatar.png'
  },
  {
    id: 18,
    name_en: 'Gayasata',
    name_es: 'Gayasata',
    name_de: 'Gayasata',
    name_fr: 'Gayasata',
    name_vi: 'Già Da Xá Đa',
    name_ru: 'Gayasata',
    name_zh: 'Gayasata',
    name_ja: 'Gayasata',
    name_ko: 'Gayasata',
    name_ar: 'Gayasata',
    birth_death_time: '-',
    sect: '-',
    country: 'India',
    place: '-',
    teachers: ['Sanghanandi'],
    successors: ['Kumarata'],
    disciples: [],
    image: '/images/avatar.png',
  },
  {
    id: 19,
    name_en: 'Kumarata',
    name_es: 'Kumarata',
    name_de: 'Kumarata',
    name_fr: 'Kumarata',
    name_vi: 'Cưu-Ma-La-Đa',
    name_ru: 'Kumarata',
    name_zh: 'Kumarata',
    name_ja: 'Kumarata',
    name_ko: 'Kumarata',
    name_ar: 'Kumarata',
    birth_death_time: '-',
    sect: '-',
    country: 'India',
    place: '-',
    teachers: ['Gayasata'],
    successors: ['Jayata'],
    disciples: [''],
    image: '/images/avatar.png',
  },
  {
    id: 20,
    name_en: 'Jayata',
    name_es: 'Jayata',
    name_de: 'Jayata',
    name_fr: 'Jayata',
    name_vi: 'Xà Dạ Đa',
    name_ru: 'Jayata',
    name_zh: 'Jayata',
    name_ja: 'Jayata',
    name_ko: 'Jayata',
    name_ar: 'Jayata',
    birth_death_time: '-',
    sect: '-',
    country: 'India',
    place: '-',
    teachers: ['Kumarata'],
    successors: ['Vasubandhu'],
    disciples: [''],
    image: '/images/avatar.png',
  },
{
    id: 21,
    name_en: 'Vasubandhu',
    name_es: 'Vasubandhu',
    name_de: 'Vasubandhu',
    name_fr: 'Vasubandhu',
    name_vi: 'Bà-Tu-Bàn-Đầu',
    name_ru: 'Vasubandhu',
    name_zh: 'Vasubandhu',
    name_ja: 'Vasubandhu',
    name_ko: 'Vasubandhu',
    name_ar: 'Vasubandhu',
    birth_death_time: '-',
    sect: '-',
    country: 'India',
    place: '-',
    teachers: ['Jayata'],
    successors: ['Manorhita'],
    disciples: [''],
    image: '/images/avatar.png',
  },
{
    id: 22,
    name_en: 'Manorhita',
    name_es: 'Manorhita',
    name_de: 'Manorhita',
    name_fr: 'Manorhita',
    name_vi: 'Ma-Noa-La',
    name_ru: 'Manorhita',
    name_zh: 'Manorhita',
    name_ja: 'Manorhita',
    name_ko: 'Manorhita',
    name_ar: 'Manorhita',
    birth_death_time: '-',
    sect: '-',
    country: 'India',
    place: '-',
    teachers: ['Vasubandhu'],
    successors: ['Haklena'],
    disciples: [''],
    image: '/images/avatar.png',
  },
  {
    id: 23,
    name_en: 'Haklena',
    name_es: 'Aryasimha',
    name_de: 'Aryasimha',
    name_fr: 'Aryasimha',
    name_vi: 'Hạc-Lặc-Na',
    name_ru: 'Aryasimha',
    name_zh: 'Aryasimha',
    name_ja: 'Aryasimha',
    name_ko: 'Aryasimha',
    name_ar: 'Aryasimha',
    birth_death_time: '-',
    sect: '-',
    country: 'India',
    place: '-',
    teachers: ['Manorhita'],
    successors: ['Aryasimha'],
    disciples: [''],
    image: '/images/avatar.png',
  },
  {
    id: 24,
    name_en: 'Aryasimha',
    name_es: 'Aryasimha',
    name_de: 'Aryasimha',
    name_fr: 'Aryasimha',
    name_vi: 'Sư-Tử',
    name_ru: 'Aryasimha',
    name_zh: 'Aryasimha',
    name_ja: 'Aryasimha',
    name_ko: 'Aryasimha',
    name_ar: 'Aryasimha',
    birth_death_time: '-',
    sect: '-',
    country: 'India',
    place: '-',
    teachers: ['Haklena'],
    successors: ['Basiasita'],
    disciples: [''],
    image: '/images/avatar.png',
  },
  {
    id: 25,
    name_en: 'Basiasita',
    name_es: 'Basiasita',
    name_de: 'Basiasita',
    name_fr: 'Basiasita',
    name_vi: 'Bà-Xá-Tư-Đa',
    name_ru: 'Basiasita',
    name_zh: 'Basiasita',
    name_ja: 'Basiasita',
    name_ko: 'Basiasita',
    name_ar: 'Basiasita',
    birth_death_time: '-',
    sect: '-',
    country: 'India',
    place: '-',
    teachers: ['Aryasimha'],
    successors: ['Punyamitra'],
    disciples: [''],
    image: '/images/avatar.png',
  },
  {
    id: 26,
    name_en: 'Punyamitra',
    name_es: 'Punyamitra',
    name_de: 'Punyamitra',
    name_fr: 'Punyamitra',
    name_vi: 'Bất-Như-Mật-Đa',
    name_ru: 'Punyamitra',
    name_zh: 'Punyamitra',
    name_ja: 'Punyamitra',
    name_ko: 'Punyamitra',
    name_ar: 'Punyamitra',
    birth_death_time: '-',
    sect: '-',
    country: 'India',
    place: '-',
    teachers: ['Basiasita'],
    successors: ['Prajnatara'],
    disciples: [''],
    image: '/images/avatar.png',
  },
  {
    id: 27,
    name_en: 'Prajnatara',
    name_es: 'Prajnatara',
    name_de: 'Prajnatara',
    name_fr: 'Prajnatara',
    name_vi: 'Bát-Nhã-Đa-La',
    name_ru: 'Prajnatara',
    name_zh: 'Prajnatara',
    name_ja: 'Prajnatara',
    name_ko: 'Prajnatara',
    name_ar: 'Prajnatara',
    birth_death_time: '-',
    sect: '-',
    country: 'India',
    place: '-',
    teachers: ['Punyamitra'],
    successors: ['Bodhidharma'],
    disciples: [''],
    image: '/images/avatar.png',
  },
  {
    id: 28,
    name_en: 'Bodhidharma',
    name_es: 'Bodhidharma',
    name_de: 'Bodhidharma',
    name_fr: 'Bodhidharma',
    name_vi: 'Bồ-Đề-Đạt-Ma',
    name_ru: 'Bodhidharma',
    name_zh: '達磨 - Damo',
    name_ja: 'だるま - Daruma',
    name_ko: '달마 - Dalma',
    name_ar: 'Bodhidharma',
    birth_death_time: '-',
    sect: '-',
    country: 'India',
    place: 'Shaolin Temple, Songshan mountain, Dengfeng, Zhengzhou, Henan, China',
    teachers: ['Prajnatara'],
    successors: ['Dazu Huike'],
    disciples: ['Dazu Huike'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/BodhidharmaYoshitoshi1887.jpg/232px-BodhidharmaYoshitoshi1887.jpg',
  },
]
export default InMasterDb;
