const InMasterDb = [
  {
    id: '1',
    hasContent: true,
    name_en: 'Mahakasyapa',
    name_es: 'Mahakasyapa',
    name_de: 'Mahakasyapa',
    name_fr: 'Mahakasyapa',
    name_vi: 'Ma-Ha-Ca-Diếp (Ẩm Quang)',
    name_ru: 'Mahakasyapa',
    name_zh: '摩訶迦葉',
    name_ja: 'Makakashō',
    name_ko: '마하가섭',
    name_ar: 'Mahakasyapa',
    birth_death_time: ['', ''],
    sect: ['-'],
    country: 'India',
    place: '-',
    teachers: ['Shakyamuni Buddha'],
    successors: ['Ananda'],
    disciples: ['Ananda'],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '2',
    hasContent: true,
    name_en: 'Ananda',
    name_es: 'Ananda',
    name_de: 'Ananda',
    name_fr: 'Ananda',
    name_vi: 'A-Nan (Khánh Hỷ)',
    name_ru: 'Ananda',
    name_zh: '阿難陀',
    name_ja: 'Ananda',
    name_ko: '아난다',
    name_ar: 'Ananda',
    birth_death_time: ['', ''],
    sect: ['Linji'],
    country: 'India',
    place: '-',
    teachers: ['Mahakasyapa'],
    successors: ['Sanakavasa'],
    disciples: ['Sanakavasa'],
    image: '/images/avatar.png',
    reference: ['',],

  },
  {
    id: '3',
    hasContent: true,
    name_en: 'Sanakavasa',
    name_es: 'Sanakavasa',
    name_de: 'Sanakavasa',
    name_fr: 'Sanakavasa',
    name_vi: 'Thương-Na-Hòa-Tu (Tự Nhiên Phục)',
    name_ru: 'Sanakavasa',
    name_zh: '商那和修',
    name_ja: 'Shōnawashu',
    name_ko: '상나화수',
    name_ar: 'Sanakavasa',
    birth_death_time: ['', ''],
    sect: ['-'],
    country: 'India',
    place: '-',
    teachers: ['Ananda'],
    successors: ['Upagupta'],
    disciples: ['Upagupta'],
    image: '/images/avatar.png',
    reference: ['',],

  },
  {
    id: '4',
    hasContent: true,
    name_en: 'Upagupta',
    name_es: 'Upagupta',
    name_de: 'Upagupta',
    name_fr: 'Upagupta',
    name_vi: 'Ưu-Ba-Cúc-Đa',
    name_ru: 'Upagupta',
    name_zh: '優婆掬多',
    name_ja: 'Ubakikuta',
    name_ko: '우바국다',
    name_ar: 'Upagupta',
    birth_death_time: ['', ''],
    sect: ['-'],
    country: 'India',
    place: '-',
    teachers: ['Sanakavasa'],
    successors: ['Dhrtaka'],
    disciples: ['Dhrtaka'],
    image: '/images/avatar.png',
    reference: ['',],

  },
  {
    id: '5',
    hasContent: true,
    name_en: 'Dhrtaka',
    name_es: 'Dhrtaka',
    name_de: 'Dhrtaka',
    name_fr: 'Dhrtaka',
    name_vi: 'Đề-Đa-Ca',
    name_ru: 'Dhrtaka',
    name_zh: '提多迦',
    name_ja: 'Daitaka',
    name_ko: '제다가',
    name_ar: 'Dhrtaka',
    birth_death_time: ['', ''],
    sect: ['-'],
    country: 'India',
    place: '-',
    teachers: ['Upagupta'],
    successors: ['Miccaka'],
    disciples: ['Miccaka'],
    image: '/images/avatar.png',
    reference: ['',],

  },
{
    id: '6',
    hasContent: true,
    name_en: 'Miccaka',
    name_es: 'Miccaka',
    name_de: 'Miccaka',
    name_fr: 'Miccaka',
    name_vi: 'Di-Dá-Ca',
    name_ru: 'Miccaka',
    name_zh: '彌遮迦',
    name_ja: 'Mishaka',
    name_ko: '미차가',
    name_ar: 'Miccaka',
    birth_death_time: ['', ''],
    sect: ['-'],
    country: 'India',
    place: '-',
    teachers: ['Dhrtaka'],
    successors: ['Vasumitra'],
    disciples: ['Vasumitra'],
    image: '/images/avatar.png',
    reference: ['',],

  },
{
    id: '7',
    hasContent: true,
    name_en: 'Vasumitra',
    name_es: 'Vasumitra',
    name_de: 'Vasumitra',
    name_fr: 'Vasumitra',
    name_vi: 'Bà-Tu-Mật',
    name_ru: 'Vasumitra',
    name_zh: '婆須密 (婆須密多)',
    name_ja: 'Bashumitsu (Bashumitta)',
    name_ko: '바수밀다',
    name_ar: 'Vasumitra',
    birth_death_time: ['', ''],
    sect: ['-'],
    country: 'India',
    place: '-',
    teachers: ['Miccaka'],
    successors: ['Buddhanandi'],
    disciples: ['Buddhanandi'],
    image: '/images/avatar.png',
    reference: ['',],

  },
  {
    id: '8',
    hasContent: true,
    name_en: 'Buddhanandi',
    name_es: 'Buddhanandi',
    name_de: 'Buddhanandi',
    name_fr: 'Buddhanandi',
    name_vi: 'Phật-Đà-Nan-Đề',
    name_ru: 'Buddhanandi',
    name_zh: '浮陀難提',
    name_ja: 'Buddanandai',
    name_ko: '불타난제',
    name_ar: 'Buddhanandi',
    birth_death_time: ['', ''],
    sect: ['-'],
    country: 'India',
    place: '-',
    teachers: ['Vasumitra'],
    successors: ['Buddhamitra'],
    disciples: ['Buddhamitra'],
    image: '/images/avatar.png',
    reference: ['',],

  },
  {
    id: '9',
    hasContent: true,
    name_en: 'Buddhamitra',
    name_es: 'Buddhamitra',
    name_de: 'Buddhamitra',
    name_fr: 'Buddhamitra',
    name_vi: 'Phục-Đà-Mật-Đa',
    name_ru: 'Buddhamitra',
    name_zh: '浮陀密多',
    name_ja: 'Buddamitta',
    name_ko: '복태밀다',
    name_ar: 'Buddhamitra',
    birth_death_time: ['', ''],
    sect: ['-'],
    country: 'India',
    place: ' mountain',
    teachers: ['Buddhanandi'],
    successors: ['Parsvika'],
    disciples: ['Parsvika'],
    image: '/images/avatar.png',
    reference: ['',],

  },
  {
    id: '10',
    hasContent: true,
    name_en: 'Parsvika',
    name_es: 'Parsvika',
    name_de: 'Parsvika',
    name_fr: 'Parsvika',
    name_vi: 'Ba-Lật-Thấp-Phược / Bà-Lật-Thấp-Bà (Hiếp-Tôn-Giả)',
    name_ru: 'Parsvika',
    name_zh: '波栗濕縛 / 婆栗濕婆 (脅尊者)',
    name_ja: 'Barishiba (Kyōsonja)',
    name_ko: '파률습박 (협존자)',
    name_ar: 'Parsvika',
    birth_death_time: ['', ''],
    sect: ['-'],
    country: 'India',
    place: '-',
    teachers: ['Buddhamitra'],
    successors: ['Punyayasas'],
    disciples: ['Punyayasas'],
    image: '/images/avatar.png',
    reference: ['',],

  },
  {
    id: '11',
    hasContent: true,
    name_en: 'Punyayasas',
    name_es: 'Punyayasas',
    name_de: 'Punyayasas',
    name_fr: 'Punyayasas',
    name_vi: 'Phú-Na-Dạ-Xa',
    name_ru: 'Punyayasas',
    name_zh: '富那夜奢',
    name_ja: 'Funayasha',
    name_ko: '부나야사',
    name_ar: 'Punyayasas',
    birth_death_time: ['', ''],
    sect: ['-'],
    country: 'India',
    place: '-',
    teachers: ['Parsvika'],
    successors: ['Asvaghosha'],
    disciples: ['Asvaghosha'],
    image: '/images/avatar.png',
    reference: ['',],

  },
  {
    id: '12',
    name_en: 'Asvaghosha',
    name_es: 'Asvaghosha',
    name_de: 'Asvaghosha',
    name_fr: 'Asvaghosha',
    name_vi: 'A-Na-Bồ-Đề (Mã-Minh)',
    name_ru: 'Asvaghosha',
    name_zh: '阿那菩提 (馬鳴)',
    name_ja: 'Anabotei (Memyō)',
    name_ko: '아슈바고샤 (마명)',
    name_ar: 'Asvaghosha',
    birth_death_time: ['', ''],
    sect: ['-'],
    country: 'India',
    place: '-',
    teachers: ['Punyayasas'],
    successors: ['Kapimala'],
    disciples: ['Kapimala'],
    image: '/images/avatar.png',
    reference: ['',],

  },
  {
    id: '13',
    name_en: 'Kapimala',
    name_es: 'Kapimala',
    name_de: 'Kapimala',
    name_fr: 'Kapimala',
    name_vi: 'Ca-Tỳ-Ma-La',
    name_ru: 'Kapimala',
    name_zh: '迦毘摩羅',
    name_ja: 'Kabimora (Kabimara)',
    name_ko: '가비마라',
    name_ar: 'Kapimala',
    birth_death_time: ['', ''],
    sect: ['-'],
    country: 'India',
    place: '-',
    teachers: ['Asvaghosha'],
    successors: ['Nagarjuna'],
    disciples: ['Nagarjuna'],
    image: '/images/avatar.png',
    reference: ['',],

  },
  {
    id: '14',
    name_en: 'Nagarjuna',
    name_es: 'Nagarjuna',
    name_de: 'Nagarjuna',
    name_fr: 'Nagarjuna',
    name_vi: 'Long-Thọ',
    name_ru: 'Nagarjuna',
    name_zh: '那伽閼剌樹那 (龍樹)',
    name_ja: 'Na-Già-Át-Lạt-Thụ-Na (Long-Thọ)',
    name_ko: '나가알랄수나 (용수)',
    name_ar: 'Nagarjuna',
    birth_death_time: ['', ''],
    sect: ['-'],
    country: 'India',
    place: '-',
    teachers: ['Kapimala'],
    successors: ['Kanadeva'],
    disciples: ['Kanadeva'],
    image: '/images/avatar.png',
    reference: ['',],

  },
  {
    id: '15',
    name_en: 'Kanadeva',
    name_es: 'Kanadeva',
    name_de: 'Kanadeva',
    name_fr: 'Kanadeva',
    name_vi: 'Ca-Na-Đề-Bà',
    name_ru: 'Kanadeva',
    name_zh: '迦那提婆',
    name_ja: 'Kanadaiba',
    name_ko: '가나제바',
    name_ar: 'Kanadeva',
    birth_death_time: ['', ''],
    sect: ['-'],
    country: 'India',
    place: '-',
    teachers: ['Nagarjuna'],
    successors: ['Rahulata'],
    disciples: ['Rahulata'],
    image: '/images/avatar.png',
    reference: ['',],

  },
{
    id: '16',
  name_en: 'Rahulata',
    name_es: 'Rahulata',
    name_de: 'Rahulata',
    name_fr: 'Rahulata',
    name_vi: 'La-Hầu-La-Đa',
    name_ru: 'Rahulata',
    name_zh: '羅睺羅多',
    name_ja: 'Ragorata',
    name_ko: '라후라다',
    name_ar: 'Rahulata',
    birth_death_time: ['', ''],
  sect: ['-'],
    country: 'India',
    place: '-',
    teachers: ['Kanadeva'],
    successors: ['Sanghanandi'],
    disciples: ['Sanghanandi'],
    image: '/images/avatar.png',
    reference: ['',],

  },
  {
    id: '17',
    name_en: 'Sanghanandi',
    name_es: 'Sanghanandi',
    name_de: 'Sanghanandi',
    name_fr: 'Sanghanandi',
    name_vi: 'Tăng Già Nan Đề',
    name_ru: 'Sanghanandi',
    name_zh: '僧伽難提',
    name_ja: 'Sōgyanandai',
    name_ko: '승가난제',
    name_ar: 'Sanghanandi',
    birth_death_time: ['', ''],
    sect: ['-'],
    country: 'India',
    place: '-',
    teachers: ['Rahulata'],
    successors: ['Gayasata'],
    disciples: ['Gayasata'],
    image: '/images/avatar.png',
    reference: ['',],

  },
  {
    id: '18',
    name_en: 'Gayasata',
    name_es: 'Gayasata',
    name_de: 'Gayasata',
    name_fr: 'Gayasata',
    name_vi: 'Già Da Xá Đa',
    name_ru: 'Gayasata',
    name_zh: '僧伽舍多',
    name_ja: 'Sōgyayasha',
    name_ko: '가야사다',
    name_ar: 'Gayasata',
    birth_death_time: ['', ''],
    sect: ['-'],
    country: 'India',
    place: '-',
    teachers: ['Sanghanandi'],
    successors: ['Kumarata'],
    disciples: ['Kumarata'],
    image: '/images/avatar.png',
    reference: ['',],

  },
  {
    id: '19',
    name_en: 'Kumarata',
    name_es: 'Kumarata',
    name_de: 'Kumarata',
    name_fr: 'Kumarata',
    name_vi: 'Cưu-Ma-La-Đa',
    name_ru: 'Kumarata',
    name_zh: '鳩摩羅多',
    name_ja: 'Kumorata (Kumarata',
    name_ko: '구마라다',
    name_ar: 'Kumarata',
    birth_death_time: ['', ''],
    sect: ['-'],
    country: 'India',
    place: '-',
    teachers: ['Gayasata'],
    successors: ['Jayata'],
    disciples: ['Jayata'],
    image: '/images/avatar.png',
    reference: ['',],

  },
  {
    id: '20',
    name_en: 'Jayata',
    name_es: 'Jayata',
    name_de: 'Jayata',
    name_fr: 'Jayata',
    name_vi: 'Xà Dạ Đa',
    name_ru: 'Jayata',
    name_zh: '闍夜多',
    name_ja: 'Shayata',
    name_ko: '사야다',
    name_ar: 'Jayata',
    birth_death_time: ['', ''],
    sect: ['-'],
    country: 'India',
    place: '-',
    teachers: ['Kumarata'],
    successors: ['Vasubandhu'],
    disciples: ['Vasubandhu'],
    image: '/images/avatar.png',
    reference: ['',],

  },
{
    id: '21',
  name_en: 'Vasubandhu',
    name_es: 'Vasubandhu',
    name_de: 'Vasubandhu',
    name_fr: 'Vasubandhu',
    name_vi: 'Bà-Tu-Bàn-Đầu (Thế-Thân)',
    name_ru: 'Vasubandhu',
    name_zh: '婆修盤頭 (世親)',
    name_ja: 'Bashubanzu (Sejin)',
    name_ko: '바수반두 (세친) ',
    name_ar: 'Vasubandhu',
    birth_death_time: ['', ''],
    sect: ['-'],
    country: 'India',
    place: '-',
    teachers: ['Jayata'],
    successors: ['Manorhita'],
    disciples: ['Manorhita'],
    image: '/images/avatar.png',
    reference: ['',],

  },
{
    id: '22',
    name_en: 'Manorhita',
    name_es: 'Manorhita',
    name_de: 'Manorhita',
    name_fr: 'Manorhita',
    name_vi: 'Ma-Noa-La',
    name_ru: 'Manorhita',
    name_zh: '摩拏羅',
    name_ja: 'Manura',
    name_ko: '마나라',
    name_ar: 'Manorhita',
    birth_death_time: ['', ''],
    sect: ['-'],
    country: 'India',
    place: '-',
    teachers: ['Vasubandhu'],
    successors: ['Haklena'],
    disciples: ['Haklena'],
    image: '/images/avatar.png',
    reference: ['',],

  },
  {
    id: '23',
    name_en: 'Haklenayaśas',
    name_es: 'Haklenayaśas',
    name_de: 'Haklenayaśas',
    name_fr: 'Haklenayaśas',
    name_vi: 'Hạc-Lặc-Na',
    name_ru: 'Haklenayaśas',
    name_zh: '鶴勒那 (鶴勒那夜奢) ',
    name_ja: 'Kakurokuna (Kakurokunayasha)',
    name_ko: '학륵나',
    name_ar: 'Haklenayaśas',
    birth_death_time: ['', ''],
    sect: ['-'],
    country: 'India',
    place: '-',
    teachers: ['Manorhita'],
    successors: ['Aryasimha'],
    disciples: ['Aryasimha'],
    image: '/images/avatar.png',
    reference: ['',],

  },
  {
    id: '24',
    name_en: 'Simhabodhi / Aryasimha',
    name_es: 'Simhabodhi',
    name_de: 'Simhabodhi',
    name_fr: 'Simhabodhi',
    name_vi: 'Sư Tử Bồ Đề / Sư Tử Trí',
    name_ru: 'Simhabodhi',
    name_zh: '師子菩提',
    name_ja: 'Shishibodai',
    name_ko: '사자',
    name_ar: 'Simhabodhi',
    birth_death_time: ['', ''],
    sect: ['-'],
    country: 'India',
    place: '-',
    teachers: ['Haklena'],
    successors: ['Basiasita'],
    disciples: ['Basiasita', 'Đạt Ma Đạt',],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '25.1',

    name_en: 'Vasiasita / Basiasita',
    name_es: 'Basiasita',
    name_de: 'Basiasita',
    name_fr: 'Basiasita',
    name_vi: 'Bà-Xá-Tư-Đa',
    name_ru: 'Basiasita',
    name_zh: '婆舍斯多',
    name_ja: 'Bashashita',
    name_ko: '바사사다',
    name_ar: 'Basiasita',
    birth_death_time: ['', ''],
    sect: ['-'],
    country: 'India',
    place: '-',
    teachers: ['Aryasimha/Simhabodhi'],
    successors: ['Punyamitra'],
    disciples: ['Punyamitra'],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '25.2',
    name_en: 'Dharmadha',
    name_es: 'Dharmadha',
    name_de: 'Dharmadha',
    name_fr: 'Dharmadha',
    name_vi: 'Đạt Ma Đạt',
    name_ru: 'Dharmadha',
    name_zh: 'Dharmadha',
    name_ja: 'Dharmadha',
    name_ko: 'Dharmadha',
    name_ar: 'Dharmadha',
    birth_death_time: ['', ''],
    sect: ['-'],
    country: 'India',
    place: '-',
    teachers: ['Aryasimha'],
    successors: [''],
    disciples: ['Nhân Đà La', 'Cù La Kỵ Lợi Bà'],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '26.1',
    name_en: 'Punyamitra',
    name_es: 'Punyamitra',
    name_de: 'Punyamitra',
    name_fr: 'Punyamitra',
    name_vi: 'Bất-Như-Mật-Đa',
    name_ru: 'Punyamitra',
    name_zh: '不如密多',
    name_ja: 'Funyomitta',
    name_ko: '불여밀다',
    name_ar: 'Punyamitra',
    birth_death_time: ['', ''],
    sect: ['-'],
    country: 'India',
    place: '-',
    teachers: ['Basiasita'],
    successors: ['Prajnatara'],
    disciples: ['Prajnatara'],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '26.2',
    name_en: 'Nhân Đà La',
    name_es: 'Nhân Đà La',
    name_de: 'Nhân Đà La',
    name_fr: 'Nhân Đà La',
    name_vi: 'Nhân Đà La',
    name_ru: 'Nhân Đà La',
    name_zh: 'Nhân Đà La',
    name_ja: 'Nhân Đà La',
    name_ko: 'Nhân Đà La',
    name_ar: 'Nhân Đà La',
    birth_death_time: ['', ''],
    sect: ['-'],
    country: 'India',
    place: '-',
    teachers: ['Đạt Ma Đạt'],
    successors: [''],
    disciples: ['Đạt Ma Thi Lợi Đế', 'Na Già Nan Đề', 'Phú/Phá Lâu Cầu Đa La', 'Ba La Bà Đề'],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '26.3',
    name_en: 'Cù La Kỵ Lợi Bà',
    name_es: 'Cù La Kỵ Lợi Bà',
    name_de: 'Cù La Kỵ Lợi Bà',
    name_fr: 'Cù La Kỵ Lợi Bà',
    name_vi: 'Cù La Kỵ Lợi Bà',
    name_ru: 'Cù La Kỵ Lợi Bà',
    name_zh: 'Cù La Kỵ Lợi Bà',
    name_ja: 'Cù La Kỵ Lợi Bà',
    name_ko: 'Cù La Kỵ Lợi Bà',
    name_ar: 'Cù La Kỵ Lợi Bà',
    birth_death_time: ['', ''],
    sect: ['-'],
    country: 'India',
    place: '-',
    teachers: ['Đạt Ma Đạt'],
    successors: [''],
    disciples: ['Bà/Ba La Bạt Ma', 'Tăng Già La Xoa'],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '27.1',
    name_en: 'Prajnatara',
    name_es: 'Prajnatara',
    name_de: 'Prajnatara',
    name_fr: 'Prajnatara',
    name_vi: 'Bát-Nhã-Đa-La',
    name_ru: 'Prajnatara',
    name_zh: '般若多羅',
    name_ja: 'Hannyatara',
    name_ko: '반야다라',
    name_ar: 'Prajnatara',
    birth_death_time: ['', ''],
    sect: ['-'],
    country: 'India',
    place: '-',
    teachers: ['Punyamitra'],
    successors: ['Bodhidharma'],
    disciples: ['Bodhidharma'],
    image: '/images/avatar.png',
    reference: ['',],
  },
{
    id: '27.2',

    name_en: 'Đạt Ma Thi Lợi Đế',
    name_es: 'Đạt Ma Thi Lợi Đế',
    name_de: 'Đạt Ma Thi Lợi Đế',
    name_fr: 'Đạt Ma Thi Lợi Đế',
    name_vi: 'Đạt Ma Thi Lợi Đế',
    name_ru: 'Đạt Ma Thi Lợi Đế',
    name_zh: 'Đạt Ma Thi Lợi Đế',
    name_ja: 'Đạt Ma Thi Lợi Đế',
    name_ko: 'Đạt Ma Thi Lợi Đế',
    name_ar: 'Đạt Ma Thi Lợi Đế',
    birth_death_time: ['', ''],
    sect: ['-'],
    country: 'India',
    place: '-',
    teachers: ['Nhân Đà La'],
    successors: [''],
    disciples: ['Ma Đế Lệ Bạt La / Ma Đế Lệ Phi La', 'A Lợi Bạt Mâu / Ha Lợi Bạt Mậu'],
    image: '/images/avatar.png',
    reference: ['',],
  },
{
    id: '27.3',

    name_en: 'Phá Lâu Cầu Đa La',
    name_es: 'Phá Lâu Cầu Đa La',
    name_de: 'Phá Lâu Cầu Đa La',
    name_fr: 'Phá Lâu Cầu Đa La',
    name_vi: 'Phá Lâu Cầu Đa La',
    name_ru: 'Phá Lâu Cầu Đa La',
    name_zh: 'Phá Lâu Cầu Đa La',
    name_ja: 'Phá Lâu Cầu Đa La',
    name_ko: 'Phá Lâu Cầu Đa La',
    name_ar: 'Phá Lâu Cầu Đa La',
    birth_death_time: ['', ''],
    sect: ['-'],
    country: 'India',
    place: '-',
    teachers: ['Nhân Đà La'],
    successors: [''],
    disciples: ['Hòa Tu Bàn Đầu', 'Đạt Ma Kha Đế', 'Chiên Đà La Đa Ba'],
    image: '/images/avatar.png',
    reference: ['',],
  },
{
    id: '27.4',

    name_en: 'Ba La Bạt Ma',
    name_es: 'Ba La Bạt Ma',
    name_de: 'Ba La Bạt Ma',
    name_fr: 'Ba La Bạt Ma',
    name_vi: 'Ba La Bạt Ma',
    name_ru: 'Ba La Bạt Ma',
    name_zh: 'Ba La Bạt Ma',
    name_ja: 'Ba La Bạt Ma',
    name_ko: 'Ba La Bạt Ma',
    name_ar: 'Ba La Bạt Ma',
    birth_death_time: ['', ''],
    sect: ['-'],
    country: 'India',
    place: '-',
    teachers: ['Cù La Kỵ Lợi Bà'],
    successors: [''],
    disciples: ['Lặc/Nặc La Đa La', 'Bàn Đầu Đa La', 'Bà Ba Bà La / Bà La Bà Đa'],
    image: '/images/avatar.png',
    reference: ['',],
  },
{
    id: '27.5',

    name_en: 'Tăng Già La Xoa',
    name_es: 'Tăng Già La Xoa',
    name_de: 'Tăng Già La Xoa',
    name_fr: 'Tăng Già La Xoa',
    name_vi: 'Tăng Già La Xoa',
    name_ru: 'Tăng Già La Xoa',
    name_zh: 'Tăng Già La Xoa',
    name_ja: 'Tăng Già La Xoa',
    name_ko: 'Tăng Già La Xoa',
    name_ar: 'Tăng Già La Xoa',
    birth_death_time: ['', ''],
    sect: ['-'],
    country: 'India',
    place: '-',
    teachers: ['Cù La Kỵ Lợi Bà'],
    successors: [''],
    disciples: ['Tì Xá Dã Đa La', 'Tì Lâu La Đa Ma', 'Tì Túc Xô Đa La / Tỳ-lật-sô-đa-la', 'Ưu Bà Chiên Đà / Ưu-ba-thiên-đà', 'Bà Nan Đề Đa /  Bà-nan-đề-la'],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '28',
    hasContent: true,
    name_en: 'Bodhidharma',
    name_es: 'Bodhidharma',
    name_de: 'Bodhidharma',
    name_fr: 'Bodhidharma',
    name_vi: 'Bồ-Đề-Đạt-Ma',
    name_ru: 'Bodhidharma',
    name_zh: '菩提達磨',
    name_ja: '達磨 だるま - Daruma / Bodaidaruma',
    name_ko: '달마 - 보리달마',
    name_ar: 'Bodhidharma',
    birth_death_time: ['', ''],
    sect: ['-'],
    country: 'India',
    place: 'Shaolin Temple, Songshan mountain, Dengfeng, Zhengzhou, Henan, China',
    teachers: ['Prajnatara'],
    successors: ['Dazu Huike'],
    disciples: ['Dazu Huike', 'Đạo Dục', 'Đạo Phó', 'Ni Tổng Trì', '6 Tôn giả đứng đầu 6 tông Hữu tướng, Vô tướng, Định tuệ, Giới hạnh, Vô đắc, Tịch tỉnh'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/BodhidharmaYoshitoshi1887.jpg/232px-BodhidharmaYoshitoshi1887.jpg',
    reference: ['',],
  },
  {
    id: '31.2',
    hasContent: true,
    name_en: 'Vinitaruci',
    name_es: 'Vinitaruci',
    name_de: 'Vinitaruci',
    name_fr: 'Vinitaruci',
    name_vi: 'Tì-ni-đa-lưu-chi (Diệt Hỉ)',
    name_ru: 'Vinitaruci',
    name_zh: '毘尼多流支',
    name_ja: 'Vinitaruci',
    name_ko: 'Vinitaruci',
    name_ar: 'Vinitaruci',
    birth_death_time: ['?', '594'],
    sect: ['-'],
    country: 'India',
    place: '-',
    teachers: ['Jianzhi Sengcan'],
    successors: ['Chúng Thiện Pháp Hiền'],
    disciples: ['Chúng Thiện Pháp Hiền'],
    image: '/',
    reference: ['Diệt Hỉ Thiền phái (滅喜禪派)'],
    youtubeId: [''],
  },
  {
    id: '34.1.7',
    name_en: 'Tây Ấn Quật Đa Tam Tạng',
    name_es: 'Tây Ấn Quật Đa Tam Tạng',
    name_de: 'Tây Ấn Quật Đa Tam Tạng',
    name_fr: 'Tây Ấn Quật Đa Tam Tạng',
    name_vi: 'Tây Ấn Quật Đa Tam Tạng',
    name_ru: 'Tây Ấn Quật Đa Tam Tạng',
    name_zh: '西域崛多三藏',
    name_ja: 'Tây Ấn Quật Đa Tam Tạng',
    name_ko: 'Tây Ấn Quật Đa Tam Tạng',
    name_ar: 'Tây Ấn Quật Đa Tam Tạng',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'India',
    place: '-',
    teachers: ['Dajian Huineng'],
    successors: ['-'],
    disciples: [],
    image: '/images/monocolor-unknown-zen-master.jpg',
    reference: [''],
  },
]
export default InMasterDb;
