const JpMasterDb = [
  {
    id: '36.3.9',
    name_en: '行表',
    name_es: '行表',
    name_de: '行表',
    name_fr: '行表',
    name_vi: 'Hành Biểu',
    name_ru: '行表',
    name_zh: '行表',
    name_ja: '行表',
    name_ko: '行表',
    name_ar: '行表',
    birth_death_time: ['722', '797'],
    records: '',
    sect: ['-'],
    country: 'Japan',
    place: '-',
    teachers: ['Dàoxuán (道璿)'],
    successors: [''],
    disciples: ['Tối Trừng (最澄)'],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '37.4.8.J',
    name_en: 'Tối Trừng',
    name_es: 'Tối Trừng',
    name_de: 'Tối Trừng',
    name_fr: 'Tối Trừng',
    name_vi: 'Tối Trừng',
    name_ru: 'Tối Trừng',
    name_zh: '最澄',
    name_ja: 'Tối Trừng',
    name_ko: 'Tối Trừng',
    name_ar: 'Tối Trừng',
    birth_death_time: ['767', '822'],
    records: '',
    sect: ['-'],
    country: 'Japan',
    place: '-',
    teachers: ['Hành Biểu (行表)'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '50.17.5',
    name_en: 'Duệ Sơn Giác A',
    name_es: 'Duệ Sơn Giác A',
    name_de: 'Duệ Sơn Giác A',
    name_fr: 'Duệ Sơn Giác A',
    name_vi: 'Duệ Sơn Giác A',
    name_ru: 'Duệ Sơn Giác A',
    name_zh: 'Duệ Sơn Giác A ',
    name_ja: 'Duệ Sơn Giác A',
    name_ko: 'Duệ Sơn Giác A',
    name_ar: 'Duệ Sơn Giác A',
    birth_death_time: ['', ''],
    records: '',
    sect: ['-'],
    country: 'Japan',
    place: '-',
    teachers: ['Shi Huiyuan'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '57.24.2.J',
    name_en: 'Kohō Kakumyō',
    name_es: 'Kohō Kakumyō',
    name_de: 'Kohō Kakumyō',
    name_fr: 'Kohō Kakumyō',
    name_vi: 'Cô Phong Giác Minh',
    name_ru: 'Kohō Kakumyō',
    name_zh: '孤峰覺明',
    name_ja: 'Kohō Kakumyō',
    name_ko: 'Kohō Kakumyō',
    name_ar: 'Kohō Kakumyō',
    birth_death_time: ['1271', '1361'],
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: 'Japan',
    place: '-',
    teachers: ['Zhongfeng Mingben'],
    successors: ['-'],
    disciples: [],
    image: '/',
    reference: ['https://vi.wikipedia.org/wiki/C%C3%B4_Phong_Gi%C3%A1c_Minh'],
  },
]
export default JpMasterDb;
