const JpMasterDb = [
  {
    id: '36.3.9',
    name_en: '行表',
    name_ja: '行表',
    name_zh: '行表',
    name_vi: 'Hành Biểu',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['722', '797'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇯🇵',
    place: '-',
    teachers: ['Dàoxuán (道璿)'],
    successors: [''],
    disciples: ['Tối Trừng (最澄)'],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '37.4.8',
    name_en: 'Tối Trừng',
    name_ja: 'Tối Trừng',
    name_zh: '最澄',
    name_vi: 'Tối Trừng',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['767', '822'],
    epoch: '',
    records: '',
    sect: [],
    country: '🇯🇵',
    place: '-',
    teachers: ['Hành Biểu (行表)'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: [''],
  },
  {
    id: '50.17.5',
    name_en: 'Duệ Sơn Giác A',
    name_ja: 'Duệ Sơn Giác A',
    name_zh: 'Duệ Sơn Giác A ',
    name_vi: 'Duệ Sơn Giác A',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: [],
    country: '🇯🇵',
    place: '-',
    teachers: ['Shi Huiyuan'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '57.24.2',
    name_en: 'Kohō Kakumyō',
    name_ja: 'Kohō Kakumyō',
    name_zh: '孤峰覺明',
    name_vi: 'Cô Phong Giác Minh',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1271', '1361'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: '🇯🇵',
    place: '-',
    teachers: ['Zhongfeng Mingben'],
    successors: ['-'],
    disciples: [],
    image: '/',
    reference: ['https://vi.wikipedia.org/wiki/C%C3%B4_Phong_Gi%C3%A1c_Minh', 'https://ja.wikipedia.org/wiki/%E5%AD%A4%E5%B3%B0%E8%A6%9A%E6%98%8E'],
  },
  {
    id: '57.24.4',
    name_en: 'Kosen Ingen',
    name_ja: 'Kosen Ingen',
    name_zh: '',
    name_vi: '',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['1295', '1374'],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi'],
    country: '🇯🇵',
    place: '-',
    teachers: ['Zhongfeng Mingben'],
    successors: ['-'],
    disciples: [],
    image: '/',
    reference: ['https://pl.wikipedia.org/wiki/Kosen_Ingen'],
  },
  {
    id: '71.38.1',
    hasContent: true,
    name_en: 'Bankei Yotaku',
    other_name_en: 'Bankei Yōtaku, Bankei kokushi',
    name_ja: 'Bankei Yōtaku',
    name_zh: '無明慧經',
    name_vi: 'Bàn Khuê Vĩnh Trác',
    other_name_vi: 'Bàn Khuê Quốc sư',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['', ''],
    epoch: '',
    records: '',
    sect: ['Linji', 'Yangqi', ''],
    country: '🇯🇵',
    place: '-',
    teachers: ['Bokuō Sogyū'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://vi.wikipedia.org/wiki/B%C3%A0n_Khu%C3%AA_V%C4%A9nh_Tr%C3%A1c', 'https://en.wikipedia.org/wiki/Bankei_Y%C5%8Dtaku'],
  }
]
export default JpMasterDb;
