const KoMasterDb = [
  {
    id: '37.4.15.K',
    name_en: 'Chŏlgam Toyun',
    name_es: 'Chŏlgam Toyun',
    name_de: 'Chŏlgam Toyun',
    name_fr: 'Chŏlgam Toyun',
    name_ru: 'Chŏlgam Toyun',
    name_ja: 'Chŏlgam Toyun',
    name_ko: '철감토윤',
    name_ar: 'Chŏlgam Toyun',
    name_zh: 'Chŏlgam Toyun',
    name_vi: 'Chŏlgam Toyun',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['797', '868'],
    epoch: '',
    records: '',
    sect: ['-'],
    country: 'Korea',
    place: '-',
    teachers: ['Nanquan Puyuan'],
    successors: ['Chinghyo Choljung'],
    disciples: ['Chinghyo Choljung'],
    image: '/',
    reference: ['https://pl.wikipedia.org/wiki/Ch%E2%80%99%C5%8Flgam_Toyun'],
  },
  {
    id: '38.5.12.K',
    name_en: 'Chinghyo Choljung',
    name_es: 'Chinghyo Choljung',
    name_de: 'Chinghyo Choljung',
    name_fr: 'Chinghyo Choljung',
    name_ru: 'Chinghyo Choljung',
    name_ja: 'Chinghyo Choljung',
    name_ko: '징효철중',
    name_ar: 'Chinghyo Choljung',
    name_zh: 'Chinghyo Choljung',
    name_vi: 'Chinghyo Choljung',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['826', '900'],
    epoch: '',
    records: '',
    sect: ['-'],
    country: 'Korea',
    place: '-',
    teachers: ['Chŏlgam Toyun'],
    successors: [''],
    disciples: [''],
    image: '/',
    reference: ['https://pl.wikipedia.org/wiki/Chinghyo_Ch%C5%8Fljung'],
  },
  {
    id: '40.7.10.K',
    hasContent: true,
    name_en: 'Longhua Lingzhao',
    other_name_en: 'Lingzhao Buna',
    name_es: 'Longhua Lingzhao',
    name_de: 'Longhua Lingzhao',
    name_fr: 'Longhua Lingzhao',
    name_ru: 'Longhua Lingzhao',
    name_ja: 'Longhua Lingzhao',
    name_ko: 'Longhua Lingzhao',
    name_ar: 'Longhua Lingzhao',
    name_zh: '龍華靈照',
    other_name_zh: '靈照布衲',
    name_vi: 'Long Hoa Linh Chiếu',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['870', '947'],
    epoch: '',
    records: '',
    sect: ['-'],
    country: 'Korea',
    place: '-',
    teachers: ['Xuefeng Yicun'],
    successors: [''],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://nigioikhatsi.net/thien/le-lay-chinh-minh.html', 'https://terebess.hu/zen/mesterek/Lamp5.pdf'],
  },
  {
    id: '40.7.11.K',
    name_en: 'Tongjin Kyŏngbo',
    name_es: 'Tongjin Kyŏngbo',
    name_de: 'Tongjin Kyŏngbo',
    name_fr: 'Tongjin Kyŏngbo',
    name_ru: 'Tongjin Kyŏngbo',
    name_ja: 'Tongjin Kyŏngbo',
    name_ko: 'Tongjin Kyŏngbo',
    name_ar: 'Tongjin Kyŏngbo',
    name_zh: 'Tongjin Kyŏngbo',
    name_vi: 'Tongjin Kyŏngbo',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['868', '948'],
    epoch: '',
    records: '...',
    sect: ['Caodong'],
    country: 'Korea',
    place: '-',
    teachers: ['Sushan Kuangren'],
    successors: ['-'],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['https://pl.wikipedia.org/wiki/Tongjin_Ky%C5%8Fngbo',],
  },
  {
    id: '41.8.1.K',
    name_en: 'Pŏpgyŏng Hyŏnhwi',
    name_es: 'Pŏpgyŏng Hyŏnhwi',
    name_de: 'Pŏpgyŏng Hyŏnhwi',
    name_fr: 'Pŏpgyŏng Hyŏnhwi',
    name_ru: 'Pŏpgyŏng Hyŏnhwi',
    name_ja: 'Pŏpgyŏng Hyŏnhwi',
    name_ko: 'Pŏpgyŏng Hyŏnhwi',
    name_ar: 'Pŏpgyŏng Hyŏnhwi',
    name_zh: 'Pŏpgyŏng Hyŏnhwi',
    name_vi: 'Pŏpgyŏng Hyŏnhwi',
    other_name_vi: '',
    nickname_vi: '',
    worship_tower: '',
    birth_death_time: ['875', '941'],
    epoch: '',
    records: '...',
    sect: ['-'],
    country: 'Korea',
    place: '-',
    teachers: ['Letan Kuangwu'],
    successors: ['-'],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['',],
  },
]
export default KoMasterDb;
