const KoMasterDb = [
  {
    id: '37.4.15.K',
    generation: '37',
    name_en: 'Chŏlgam Toyun',
    name_es: 'Chŏlgam Toyun',
    name_de: 'Chŏlgam Toyun',
    name_fr: 'Chŏlgam Toyun',
    name_vi: 'Chŏlgam Toyun',
    name_ru: 'Chŏlgam Toyun',
    name_zh: 'Chŏlgam Toyun',
    name_ja: 'Chŏlgam Toyun',
    name_ko: '철감토윤',
    name_ar: 'Chŏlgam Toyun',
    birth_death_time: ['797', '868'],
    records: '',
    sect: ['-'],
    country: 'Korea',
    place: '-',
    teachers: ['Nanquan Puyuan'],
    successors: ['Chinghyo Choljung'],
    disciples: ['Chinghyo Choljung'],
    image: '/',
    reference: ['https://pl.wikipedia.org/wiki/Ch%E2%80%99%C5%8Flgam_Toyun'],
  },
  {
    id: '38.5.12',
    generation: '38',
    name_en: 'Chinghyo Choljung',
    name_es: 'Chinghyo Choljung',
    name_de: 'Chinghyo Choljung',
    name_fr: 'Chinghyo Choljung',
    name_vi: 'Chinghyo Choljung',
    name_ru: 'Chinghyo Choljung',
    name_zh: 'Chinghyo Choljung',
    name_ja: 'Chinghyo Choljung',
    name_ko: '징효철중',
    name_ar: 'Chinghyo Choljung',
    birth_death_time: ['826', '900'],
    records: '',
    sect: ['-'],
    country: 'Korea',
    place: '-',
    teachers: ['Chŏlgam Toyun'],
    successors: [''],
    disciples: [''],
    image: '/',
    reference: ['https://pl.wikipedia.org/wiki/Chinghyo_Ch%C5%8Fljung'],
  },
  {
    id: '41.101.K',
    generation: '41',
    name_en: 'Pŏpgyŏng Hyŏnhwi',
    name_es: 'Pŏpgyŏng Hyŏnhwi',
    name_de: 'Pŏpgyŏng Hyŏnhwi',
    name_fr: 'Pŏpgyŏng Hyŏnhwi',
    name_vi: 'Pŏpgyŏng Hyŏnhwi',
    name_ru: 'Pŏpgyŏng Hyŏnhwi',
    name_zh: 'Pŏpgyŏng Hyŏnhwi',
    name_ja: 'Pŏpgyŏng Hyŏnhwi',
    name_ko: 'Pŏpgyŏng Hyŏnhwi',
    name_ar: 'Pŏpgyŏng Hyŏnhwi',
    birth_death_time: ['875', '941'],
    records: '...',
    sect: ['-'],
    country: 'Korea',
    place: '-',
    teachers: ['Letan Kuangwu'],
    successors: ['-'],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['',],
  },
]
export default KoMasterDb;
