const InMasterDb = [
  {
    id: '32.101.V',
    name_en: 'Chúng Thiện Pháp Hiền',
    name_es: 'Chúng Thiện Pháp Hiền',
    name_de: 'Chúng Thiện Pháp Hiền',
    name_fr: 'Chúng Thiện Pháp Hiền',
    name_vi: 'Chúng Thiện Pháp Hiền',
    name_ru: 'Chúng Thiện Pháp Hiền',
    name_zh: 'Chúng Thiện Pháp Hiền',
    name_ja: 'Chúng Thiện Pháp Hiền',
    name_ko: 'Chúng Thiện Pháp Hiền',
    name_ar: 'Chúng Thiện Pháp Hiền',
    birth_death_time: ['?', '626'],
    records: '...',
    sect: ['-'],
    country: 'Vietnam',
    place: '-',
    teachers: ['Vinitaruci'],
    successors: ['-'],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['',],
  },
  {
    id: '88.101.V',
    hasContent: true,
    name_en: 'Weili Juekai',
    name_es: 'Weili Juekai',
    name_de: 'Weili Juekai',
    name_fr: 'Weili Juekai',
    name_vi: 'Thích Duy Lực - Giác Khai',
    name_ru: 'Weili Juekai',
    name_zh: '釋惟力 覺開',
    name_ja: 'Weili Juekai',
    name_ko: 'Weili Juekai',
    name_ar: 'Weili Juekai',
    birth_death_time: ['1923', '2000'],
    records: '...',
    sect: ['-'],
    country: 'Vietnam',
    place: '-',
    teachers: ['Thích Hoằng Tu', 'Diệu Duyên'],
    successors: ['-'],
    disciples: [],
    image: '/images/avatar.png',
    reference: ['',],
  },

]
export default InMasterDb;
